/*** Autogenerated by WIDL 11.15 from xaccessibility.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __xaccessibility_h__
#define __xaccessibility_h__

/* Forward declarations */

#ifndef __IXAccessibilityImpl_FWD_DEFINED__
#define __IXAccessibilityImpl_FWD_DEFINED__
typedef interface IXAccessibilityImpl IXAccessibilityImpl;
#ifdef __cplusplus
interface IXAccessibilityImpl;
#endif /* __cplusplus */
#endif

#ifndef __IXAccessibilityImpl2_FWD_DEFINED__
#define __IXAccessibilityImpl2_FWD_DEFINED__
typedef interface IXAccessibilityImpl2 IXAccessibilityImpl2;
#ifdef __cplusplus
interface IXAccessibilityImpl2;
#endif /* __cplusplus */
#endif

#ifndef __XAccessibilityImpl_FWD_DEFINED__
#define __XAccessibilityImpl_FWD_DEFINED__
#ifdef __cplusplus
typedef class XAccessibilityImpl XAccessibilityImpl;
#else
typedef struct XAccessibilityImpl XAccessibilityImpl;
#endif /* defined __cplusplus */
#endif /* defined __XAccessibilityImpl_FWD_DEFINED__ */

/* Headers for imported files */

#include <unknwn.h>
#include <xgameruntimetypes.h>
#include <xspeechsynthesizer.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
enum class XClosedCaptionFontEdgeAttribute : UINT32
{                                                  
    Default,                                       
    NoEdgeAttribute,                               
    RaisedEdges,                                   
    DepressedEdges,                                
    UniformedEdges,                                
    DropShadowedEdges,                             
};                                                 
enum class XClosedCaptionFontStyle : UINT32
{                                          
    Default,                               
    MonospacedWithSerifs,                  
    ProportionalWithSerifs,                
    MonospacedWithoutSerifs,               
    ProportionalWithoutSerifs,             
    Casual,                                
    Cursive,                               
    SmallCapitals,                         
};                                         
enum class XHighContrastMode : UINT32
{                                    
    Off,                             
    Dark,                            
    Light,                           
    Other,                           
};                                   
enum class XSpeechToTextPositionHint : UINT32
{                                            
    BottomCenter,                            
    BottomLeft,                              
    BottomRight,                             
    MiddleRight,                             
    MiddleLeft,                              
    TopCenter,                               
    TopLeft,                                 
    TopRight,                                
};                                           
enum class XSpeechToTextType : UINT32
{                                    
    Voice,                           
    Text,                            
};                                   
#elif defined(__WINESRC__)
typedef enum XClosedCaptionFontEdgeAttribute {
    XClosedCaptionFontEdgeAttribute_Default = 0,
    XClosedCaptionFontEdgeAttribute_NoEdgeAttribute = 1,
    XClosedCaptionFontEdgeAttribute_RaisedEdges = 2,
    XClosedCaptionFontEdgeAttribute_DepressedEdges = 3,
    XClosedCaptionFontEdgeAttribute_UniformedEdges = 4,
    XClosedCaptionFontEdgeAttribute_DropShadowedEdges = 5
} XClosedCaptionFontEdgeAttribute;
typedef enum XClosedCaptionFontStyle {
    XClosedCaptionFontStyle_Default = 0,
    XClosedCaptionFontStyle_MonospacedWithSerifs = 1,
    XClosedCaptionFontStyle_ProportionalWithSerifs = 2,
    XClosedCaptionFontStyle_MonospacedWithoutSerifs = 3,
    XClosedCaptionFontStyle_ProportionalWithoutSerifs = 4,
    XClosedCaptionFontStyle_Casual = 5,
    XClosedCaptionFontStyle_Cursive = 6,
    XClosedCaptionFontStyle_SmallCapitals = 7
} XClosedCaptionFontStyle;
typedef enum XHighContrastMode {
    XHighContrastMode_Off = 0,
    XHighContrastMode_Dark = 1,
    XHighContrastMode_Light = 2,
    XHighContrastMode_Other = 3
} XHighContrastMode;
typedef enum XSpeechToTextPositionHint {
    XSpeechToTextPositionHint_BottomCenter = 0,
    XSpeechToTextPositionHint_BottomLeft = 1,
    XSpeechToTextPositionHint_BottomRight = 2,
    XSpeechToTextPositionHint_MiddleRight = 3,
    XSpeechToTextPositionHint_MiddleLeft = 4,
    XSpeechToTextPositionHint_TopCenter = 5,
    XSpeechToTextPositionHint_TopLeft = 6,
    XSpeechToTextPositionHint_TopRight = 7
} XSpeechToTextPositionHint;
typedef enum XSpeechToTextType {
    XSpeechToTextType_Voice = 0,
    XSpeechToTextType_Text = 1
} XSpeechToTextType;
#endif
typedef struct XClosedCaptionProperties XClosedCaptionProperties;
struct XClosedCaptionProperties {
    XColor BackgroundColor;
    XColor FontColor;
    XColor WindowColor;
    XClosedCaptionFontEdgeAttribute FontEdgeAttribute;
    XClosedCaptionFontStyle FontStyle;
    float FontScale;
    BOOLEAN Enabled;
};
#ifdef __WINESRC__
/*****************************************************************************
 * IXAccessibilityImpl interface
 */
#ifndef __IXAccessibilityImpl_INTERFACE_DEFINED__
#define __IXAccessibilityImpl_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXAccessibilityImpl, 0x3e241977, 0x6237, 0x41e9, 0x85,0x59, 0x10,0x2c,0x2d,0x99,0x83,0xf1);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("3e241977-6237-41e9-8559-102c2d9983f1")
IXAccessibilityImpl : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE XClosedCaptionGetProperties(
        XClosedCaptionProperties *props) = 0;

    virtual HRESULT STDMETHODCALLTYPE XClosedCaptionSetEnabled(
        BOOLEAN enabled) = 0;

    virtual HRESULT STDMETHODCALLTYPE XHighContrastGetMode(
        XHighContrastMode *mode) = 0;

    virtual HRESULT STDMETHODCALLTYPE XSpeechToTextSetPositionHint(
        XSpeechToTextPositionHint position) = 0;

    virtual HRESULT STDMETHODCALLTYPE XSpeechToTextSendString(
        const char *speakerName,
        const char *content,
        XSpeechToTextType type) = 0;

    virtual HRESULT STDMETHODCALLTYPE XSpeechSynthesizerEnumerateInstalledVoices(
        void *context,
        XSpeechSynthesizerInstalledVoicesCallback *callback) = 0;

    virtual HRESULT STDMETHODCALLTYPE XSpeechSynthesizerCreate(
        XSpeechSynthesizerHandle *speechSynthesizer) = 0;

    virtual HRESULT STDMETHODCALLTYPE XSpeechSynthesizerCloseHandle(
        XSpeechSynthesizerHandle speechSynthesizer) = 0;

    virtual HRESULT STDMETHODCALLTYPE XSpeechSynthesizerSetDefaultVoice(
        XSpeechSynthesizerHandle speechSynthesizer) = 0;

    virtual HRESULT STDMETHODCALLTYPE XSpeechSynthesizerSetCustomVoice(
        XSpeechSynthesizerHandle speechSynthesizer,
        const char *voiceId) = 0;

    virtual HRESULT STDMETHODCALLTYPE XSpeechSynthesizerCreateStreamFromText(
        XSpeechSynthesizerHandle speechSynthesizer,
        const char *text,
        XSpeechSynthesizerStreamHandle *speechSynthesisStream) = 0;

    virtual HRESULT STDMETHODCALLTYPE XSpeechSynthesizerCloseStreamHandle(
        XSpeechSynthesizerStreamHandle speechSynthesisStream) = 0;

    virtual HRESULT STDMETHODCALLTYPE XSpeechSynthesizerGetStreamDataSize(
        XSpeechSynthesizerStreamHandle speechSynthesisStream,
        SIZE_T *bufferSize) = 0;

    virtual HRESULT STDMETHODCALLTYPE XSpeechSynthesizerGetStreamData(
        XSpeechSynthesizerStreamHandle speechSynthesisStream,
        SIZE_T bufferSize,
        void *buffer,
        SIZE_T *bufferUsed) = 0;

    virtual HRESULT STDMETHODCALLTYPE XSpeechToTextBeginHypothesisString(
        const char *speakerName,
        const char *content,
        XSpeechToTextType type,
        UINT32 *hypothesisId) = 0;

    virtual HRESULT STDMETHODCALLTYPE XSpeechToTextUpdateHypothesisString(
        UINT32 hypothesisId,
        const char *content) = 0;

    virtual HRESULT STDMETHODCALLTYPE XSpeechToTextFinalizeHypothesisString(
        UINT32 hypothesisId,
        const char *content) = 0;

    virtual HRESULT STDMETHODCALLTYPE XSpeechToTextCancelHypothesisString(
        UINT32 hypothesisId) = 0;

    virtual HRESULT STDMETHODCALLTYPE XSpeechSynthesizerCreateStreamFromSsml(
        XSpeechSynthesizerHandle speechSynthesizer,
        const char *ssml,
        XSpeechSynthesizerStreamHandle *speechSynthesisStream) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXAccessibilityImpl, 0x3e241977, 0x6237, 0x41e9, 0x85,0x59, 0x10,0x2c,0x2d,0x99,0x83,0xf1)
#endif
#else
typedef struct IXAccessibilityImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXAccessibilityImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXAccessibilityImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXAccessibilityImpl *This);

    /*** IXAccessibilityImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XClosedCaptionGetProperties)(
        IXAccessibilityImpl *This,
        XClosedCaptionProperties *props);

    HRESULT (STDMETHODCALLTYPE *XClosedCaptionSetEnabled)(
        IXAccessibilityImpl *This,
        BOOLEAN enabled);

    HRESULT (STDMETHODCALLTYPE *XHighContrastGetMode)(
        IXAccessibilityImpl *This,
        XHighContrastMode *mode);

    HRESULT (STDMETHODCALLTYPE *XSpeechToTextSetPositionHint)(
        IXAccessibilityImpl *This,
        XSpeechToTextPositionHint position);

    HRESULT (STDMETHODCALLTYPE *XSpeechToTextSendString)(
        IXAccessibilityImpl *This,
        const char *speakerName,
        const char *content,
        XSpeechToTextType type);

    HRESULT (STDMETHODCALLTYPE *XSpeechSynthesizerEnumerateInstalledVoices)(
        IXAccessibilityImpl *This,
        void *context,
        XSpeechSynthesizerInstalledVoicesCallback *callback);

    HRESULT (STDMETHODCALLTYPE *XSpeechSynthesizerCreate)(
        IXAccessibilityImpl *This,
        XSpeechSynthesizerHandle *speechSynthesizer);

    HRESULT (STDMETHODCALLTYPE *XSpeechSynthesizerCloseHandle)(
        IXAccessibilityImpl *This,
        XSpeechSynthesizerHandle speechSynthesizer);

    HRESULT (STDMETHODCALLTYPE *XSpeechSynthesizerSetDefaultVoice)(
        IXAccessibilityImpl *This,
        XSpeechSynthesizerHandle speechSynthesizer);

    HRESULT (STDMETHODCALLTYPE *XSpeechSynthesizerSetCustomVoice)(
        IXAccessibilityImpl *This,
        XSpeechSynthesizerHandle speechSynthesizer,
        const char *voiceId);

    HRESULT (STDMETHODCALLTYPE *XSpeechSynthesizerCreateStreamFromText)(
        IXAccessibilityImpl *This,
        XSpeechSynthesizerHandle speechSynthesizer,
        const char *text,
        XSpeechSynthesizerStreamHandle *speechSynthesisStream);

    HRESULT (STDMETHODCALLTYPE *XSpeechSynthesizerCloseStreamHandle)(
        IXAccessibilityImpl *This,
        XSpeechSynthesizerStreamHandle speechSynthesisStream);

    HRESULT (STDMETHODCALLTYPE *XSpeechSynthesizerGetStreamDataSize)(
        IXAccessibilityImpl *This,
        XSpeechSynthesizerStreamHandle speechSynthesisStream,
        SIZE_T *bufferSize);

    HRESULT (STDMETHODCALLTYPE *XSpeechSynthesizerGetStreamData)(
        IXAccessibilityImpl *This,
        XSpeechSynthesizerStreamHandle speechSynthesisStream,
        SIZE_T bufferSize,
        void *buffer,
        SIZE_T *bufferUsed);

    HRESULT (STDMETHODCALLTYPE *XSpeechToTextBeginHypothesisString)(
        IXAccessibilityImpl *This,
        const char *speakerName,
        const char *content,
        XSpeechToTextType type,
        UINT32 *hypothesisId);

    HRESULT (STDMETHODCALLTYPE *XSpeechToTextUpdateHypothesisString)(
        IXAccessibilityImpl *This,
        UINT32 hypothesisId,
        const char *content);

    HRESULT (STDMETHODCALLTYPE *XSpeechToTextFinalizeHypothesisString)(
        IXAccessibilityImpl *This,
        UINT32 hypothesisId,
        const char *content);

    HRESULT (STDMETHODCALLTYPE *XSpeechToTextCancelHypothesisString)(
        IXAccessibilityImpl *This,
        UINT32 hypothesisId);

    HRESULT (STDMETHODCALLTYPE *XSpeechSynthesizerCreateStreamFromSsml)(
        IXAccessibilityImpl *This,
        XSpeechSynthesizerHandle speechSynthesizer,
        const char *ssml,
        XSpeechSynthesizerStreamHandle *speechSynthesisStream);

    END_INTERFACE
} IXAccessibilityImplVtbl;

interface IXAccessibilityImpl {
    CONST_VTBL IXAccessibilityImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXAccessibilityImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXAccessibilityImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXAccessibilityImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IXAccessibilityImpl methods ***/
#define IXAccessibilityImpl_XClosedCaptionGetProperties(This,props) (This)->lpVtbl->XClosedCaptionGetProperties(This,props)
#define IXAccessibilityImpl_XClosedCaptionSetEnabled(This,enabled) (This)->lpVtbl->XClosedCaptionSetEnabled(This,enabled)
#define IXAccessibilityImpl_XHighContrastGetMode(This,mode) (This)->lpVtbl->XHighContrastGetMode(This,mode)
#define IXAccessibilityImpl_XSpeechToTextSetPositionHint(This,position) (This)->lpVtbl->XSpeechToTextSetPositionHint(This,position)
#define IXAccessibilityImpl_XSpeechToTextSendString(This,speakerName,content,type) (This)->lpVtbl->XSpeechToTextSendString(This,speakerName,content,type)
#define IXAccessibilityImpl_XSpeechSynthesizerEnumerateInstalledVoices(This,context,callback) (This)->lpVtbl->XSpeechSynthesizerEnumerateInstalledVoices(This,context,callback)
#define IXAccessibilityImpl_XSpeechSynthesizerCreate(This,speechSynthesizer) (This)->lpVtbl->XSpeechSynthesizerCreate(This,speechSynthesizer)
#define IXAccessibilityImpl_XSpeechSynthesizerCloseHandle(This,speechSynthesizer) (This)->lpVtbl->XSpeechSynthesizerCloseHandle(This,speechSynthesizer)
#define IXAccessibilityImpl_XSpeechSynthesizerSetDefaultVoice(This,speechSynthesizer) (This)->lpVtbl->XSpeechSynthesizerSetDefaultVoice(This,speechSynthesizer)
#define IXAccessibilityImpl_XSpeechSynthesizerSetCustomVoice(This,speechSynthesizer,voiceId) (This)->lpVtbl->XSpeechSynthesizerSetCustomVoice(This,speechSynthesizer,voiceId)
#define IXAccessibilityImpl_XSpeechSynthesizerCreateStreamFromText(This,speechSynthesizer,text,speechSynthesisStream) (This)->lpVtbl->XSpeechSynthesizerCreateStreamFromText(This,speechSynthesizer,text,speechSynthesisStream)
#define IXAccessibilityImpl_XSpeechSynthesizerCloseStreamHandle(This,speechSynthesisStream) (This)->lpVtbl->XSpeechSynthesizerCloseStreamHandle(This,speechSynthesisStream)
#define IXAccessibilityImpl_XSpeechSynthesizerGetStreamDataSize(This,speechSynthesisStream,bufferSize) (This)->lpVtbl->XSpeechSynthesizerGetStreamDataSize(This,speechSynthesisStream,bufferSize)
#define IXAccessibilityImpl_XSpeechSynthesizerGetStreamData(This,speechSynthesisStream,bufferSize,buffer,bufferUsed) (This)->lpVtbl->XSpeechSynthesizerGetStreamData(This,speechSynthesisStream,bufferSize,buffer,bufferUsed)
#define IXAccessibilityImpl_XSpeechToTextBeginHypothesisString(This,speakerName,content,type,hypothesisId) (This)->lpVtbl->XSpeechToTextBeginHypothesisString(This,speakerName,content,type,hypothesisId)
#define IXAccessibilityImpl_XSpeechToTextUpdateHypothesisString(This,hypothesisId,content) (This)->lpVtbl->XSpeechToTextUpdateHypothesisString(This,hypothesisId,content)
#define IXAccessibilityImpl_XSpeechToTextFinalizeHypothesisString(This,hypothesisId,content) (This)->lpVtbl->XSpeechToTextFinalizeHypothesisString(This,hypothesisId,content)
#define IXAccessibilityImpl_XSpeechToTextCancelHypothesisString(This,hypothesisId) (This)->lpVtbl->XSpeechToTextCancelHypothesisString(This,hypothesisId)
#define IXAccessibilityImpl_XSpeechSynthesizerCreateStreamFromSsml(This,speechSynthesizer,ssml,speechSynthesisStream) (This)->lpVtbl->XSpeechSynthesizerCreateStreamFromSsml(This,speechSynthesizer,ssml,speechSynthesisStream)
#else
/*** IUnknown methods ***/
static inline HRESULT IXAccessibilityImpl_QueryInterface(IXAccessibilityImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXAccessibilityImpl_AddRef(IXAccessibilityImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXAccessibilityImpl_Release(IXAccessibilityImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IXAccessibilityImpl methods ***/
static inline HRESULT IXAccessibilityImpl_XClosedCaptionGetProperties(IXAccessibilityImpl* This,XClosedCaptionProperties *props) {
    return This->lpVtbl->XClosedCaptionGetProperties(This,props);
}
static inline HRESULT IXAccessibilityImpl_XClosedCaptionSetEnabled(IXAccessibilityImpl* This,BOOLEAN enabled) {
    return This->lpVtbl->XClosedCaptionSetEnabled(This,enabled);
}
static inline HRESULT IXAccessibilityImpl_XHighContrastGetMode(IXAccessibilityImpl* This,XHighContrastMode *mode) {
    return This->lpVtbl->XHighContrastGetMode(This,mode);
}
static inline HRESULT IXAccessibilityImpl_XSpeechToTextSetPositionHint(IXAccessibilityImpl* This,XSpeechToTextPositionHint position) {
    return This->lpVtbl->XSpeechToTextSetPositionHint(This,position);
}
static inline HRESULT IXAccessibilityImpl_XSpeechToTextSendString(IXAccessibilityImpl* This,const char *speakerName,const char *content,XSpeechToTextType type) {
    return This->lpVtbl->XSpeechToTextSendString(This,speakerName,content,type);
}
static inline HRESULT IXAccessibilityImpl_XSpeechSynthesizerEnumerateInstalledVoices(IXAccessibilityImpl* This,void *context,XSpeechSynthesizerInstalledVoicesCallback *callback) {
    return This->lpVtbl->XSpeechSynthesizerEnumerateInstalledVoices(This,context,callback);
}
static inline HRESULT IXAccessibilityImpl_XSpeechSynthesizerCreate(IXAccessibilityImpl* This,XSpeechSynthesizerHandle *speechSynthesizer) {
    return This->lpVtbl->XSpeechSynthesizerCreate(This,speechSynthesizer);
}
static inline HRESULT IXAccessibilityImpl_XSpeechSynthesizerCloseHandle(IXAccessibilityImpl* This,XSpeechSynthesizerHandle speechSynthesizer) {
    return This->lpVtbl->XSpeechSynthesizerCloseHandle(This,speechSynthesizer);
}
static inline HRESULT IXAccessibilityImpl_XSpeechSynthesizerSetDefaultVoice(IXAccessibilityImpl* This,XSpeechSynthesizerHandle speechSynthesizer) {
    return This->lpVtbl->XSpeechSynthesizerSetDefaultVoice(This,speechSynthesizer);
}
static inline HRESULT IXAccessibilityImpl_XSpeechSynthesizerSetCustomVoice(IXAccessibilityImpl* This,XSpeechSynthesizerHandle speechSynthesizer,const char *voiceId) {
    return This->lpVtbl->XSpeechSynthesizerSetCustomVoice(This,speechSynthesizer,voiceId);
}
static inline HRESULT IXAccessibilityImpl_XSpeechSynthesizerCreateStreamFromText(IXAccessibilityImpl* This,XSpeechSynthesizerHandle speechSynthesizer,const char *text,XSpeechSynthesizerStreamHandle *speechSynthesisStream) {
    return This->lpVtbl->XSpeechSynthesizerCreateStreamFromText(This,speechSynthesizer,text,speechSynthesisStream);
}
static inline HRESULT IXAccessibilityImpl_XSpeechSynthesizerCloseStreamHandle(IXAccessibilityImpl* This,XSpeechSynthesizerStreamHandle speechSynthesisStream) {
    return This->lpVtbl->XSpeechSynthesizerCloseStreamHandle(This,speechSynthesisStream);
}
static inline HRESULT IXAccessibilityImpl_XSpeechSynthesizerGetStreamDataSize(IXAccessibilityImpl* This,XSpeechSynthesizerStreamHandle speechSynthesisStream,SIZE_T *bufferSize) {
    return This->lpVtbl->XSpeechSynthesizerGetStreamDataSize(This,speechSynthesisStream,bufferSize);
}
static inline HRESULT IXAccessibilityImpl_XSpeechSynthesizerGetStreamData(IXAccessibilityImpl* This,XSpeechSynthesizerStreamHandle speechSynthesisStream,SIZE_T bufferSize,void *buffer,SIZE_T *bufferUsed) {
    return This->lpVtbl->XSpeechSynthesizerGetStreamData(This,speechSynthesisStream,bufferSize,buffer,bufferUsed);
}
static inline HRESULT IXAccessibilityImpl_XSpeechToTextBeginHypothesisString(IXAccessibilityImpl* This,const char *speakerName,const char *content,XSpeechToTextType type,UINT32 *hypothesisId) {
    return This->lpVtbl->XSpeechToTextBeginHypothesisString(This,speakerName,content,type,hypothesisId);
}
static inline HRESULT IXAccessibilityImpl_XSpeechToTextUpdateHypothesisString(IXAccessibilityImpl* This,UINT32 hypothesisId,const char *content) {
    return This->lpVtbl->XSpeechToTextUpdateHypothesisString(This,hypothesisId,content);
}
static inline HRESULT IXAccessibilityImpl_XSpeechToTextFinalizeHypothesisString(IXAccessibilityImpl* This,UINT32 hypothesisId,const char *content) {
    return This->lpVtbl->XSpeechToTextFinalizeHypothesisString(This,hypothesisId,content);
}
static inline HRESULT IXAccessibilityImpl_XSpeechToTextCancelHypothesisString(IXAccessibilityImpl* This,UINT32 hypothesisId) {
    return This->lpVtbl->XSpeechToTextCancelHypothesisString(This,hypothesisId);
}
static inline HRESULT IXAccessibilityImpl_XSpeechSynthesizerCreateStreamFromSsml(IXAccessibilityImpl* This,XSpeechSynthesizerHandle speechSynthesizer,const char *ssml,XSpeechSynthesizerStreamHandle *speechSynthesisStream) {
    return This->lpVtbl->XSpeechSynthesizerCreateStreamFromSsml(This,speechSynthesizer,ssml,speechSynthesisStream);
}
#endif
#endif

#endif


#endif  /* __IXAccessibilityImpl_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IXAccessibilityImpl2 interface
 */
#ifndef __IXAccessibilityImpl2_INTERFACE_DEFINED__
#define __IXAccessibilityImpl2_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXAccessibilityImpl2, 0xd722b373, 0x8c4d, 0x4692, 0x9e,0x51, 0xd6,0xad,0x9b,0x37,0xaa,0x7d);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("d722b373-8c4d-4692-9e51-d6ad9b37aa7d")
IXAccessibilityImpl2 : public IXAccessibilityImpl
{
};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXAccessibilityImpl2, 0xd722b373, 0x8c4d, 0x4692, 0x9e,0x51, 0xd6,0xad,0x9b,0x37,0xaa,0x7d)
#endif
#else
typedef struct IXAccessibilityImpl2Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXAccessibilityImpl2 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXAccessibilityImpl2 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXAccessibilityImpl2 *This);

    /*** IXAccessibilityImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XClosedCaptionGetProperties)(
        IXAccessibilityImpl2 *This,
        XClosedCaptionProperties *props);

    HRESULT (STDMETHODCALLTYPE *XClosedCaptionSetEnabled)(
        IXAccessibilityImpl2 *This,
        BOOLEAN enabled);

    HRESULT (STDMETHODCALLTYPE *XHighContrastGetMode)(
        IXAccessibilityImpl2 *This,
        XHighContrastMode *mode);

    HRESULT (STDMETHODCALLTYPE *XSpeechToTextSetPositionHint)(
        IXAccessibilityImpl2 *This,
        XSpeechToTextPositionHint position);

    HRESULT (STDMETHODCALLTYPE *XSpeechToTextSendString)(
        IXAccessibilityImpl2 *This,
        const char *speakerName,
        const char *content,
        XSpeechToTextType type);

    HRESULT (STDMETHODCALLTYPE *XSpeechSynthesizerEnumerateInstalledVoices)(
        IXAccessibilityImpl2 *This,
        void *context,
        XSpeechSynthesizerInstalledVoicesCallback *callback);

    HRESULT (STDMETHODCALLTYPE *XSpeechSynthesizerCreate)(
        IXAccessibilityImpl2 *This,
        XSpeechSynthesizerHandle *speechSynthesizer);

    HRESULT (STDMETHODCALLTYPE *XSpeechSynthesizerCloseHandle)(
        IXAccessibilityImpl2 *This,
        XSpeechSynthesizerHandle speechSynthesizer);

    HRESULT (STDMETHODCALLTYPE *XSpeechSynthesizerSetDefaultVoice)(
        IXAccessibilityImpl2 *This,
        XSpeechSynthesizerHandle speechSynthesizer);

    HRESULT (STDMETHODCALLTYPE *XSpeechSynthesizerSetCustomVoice)(
        IXAccessibilityImpl2 *This,
        XSpeechSynthesizerHandle speechSynthesizer,
        const char *voiceId);

    HRESULT (STDMETHODCALLTYPE *XSpeechSynthesizerCreateStreamFromText)(
        IXAccessibilityImpl2 *This,
        XSpeechSynthesizerHandle speechSynthesizer,
        const char *text,
        XSpeechSynthesizerStreamHandle *speechSynthesisStream);

    HRESULT (STDMETHODCALLTYPE *XSpeechSynthesizerCloseStreamHandle)(
        IXAccessibilityImpl2 *This,
        XSpeechSynthesizerStreamHandle speechSynthesisStream);

    HRESULT (STDMETHODCALLTYPE *XSpeechSynthesizerGetStreamDataSize)(
        IXAccessibilityImpl2 *This,
        XSpeechSynthesizerStreamHandle speechSynthesisStream,
        SIZE_T *bufferSize);

    HRESULT (STDMETHODCALLTYPE *XSpeechSynthesizerGetStreamData)(
        IXAccessibilityImpl2 *This,
        XSpeechSynthesizerStreamHandle speechSynthesisStream,
        SIZE_T bufferSize,
        void *buffer,
        SIZE_T *bufferUsed);

    HRESULT (STDMETHODCALLTYPE *XSpeechToTextBeginHypothesisString)(
        IXAccessibilityImpl2 *This,
        const char *speakerName,
        const char *content,
        XSpeechToTextType type,
        UINT32 *hypothesisId);

    HRESULT (STDMETHODCALLTYPE *XSpeechToTextUpdateHypothesisString)(
        IXAccessibilityImpl2 *This,
        UINT32 hypothesisId,
        const char *content);

    HRESULT (STDMETHODCALLTYPE *XSpeechToTextFinalizeHypothesisString)(
        IXAccessibilityImpl2 *This,
        UINT32 hypothesisId,
        const char *content);

    HRESULT (STDMETHODCALLTYPE *XSpeechToTextCancelHypothesisString)(
        IXAccessibilityImpl2 *This,
        UINT32 hypothesisId);

    HRESULT (STDMETHODCALLTYPE *XSpeechSynthesizerCreateStreamFromSsml)(
        IXAccessibilityImpl2 *This,
        XSpeechSynthesizerHandle speechSynthesizer,
        const char *ssml,
        XSpeechSynthesizerStreamHandle *speechSynthesisStream);

    END_INTERFACE
} IXAccessibilityImpl2Vtbl;

interface IXAccessibilityImpl2 {
    CONST_VTBL IXAccessibilityImpl2Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXAccessibilityImpl2_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXAccessibilityImpl2_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXAccessibilityImpl2_Release(This) (This)->lpVtbl->Release(This)
/*** IXAccessibilityImpl methods ***/
#define IXAccessibilityImpl2_XClosedCaptionGetProperties(This,props) (This)->lpVtbl->XClosedCaptionGetProperties(This,props)
#define IXAccessibilityImpl2_XClosedCaptionSetEnabled(This,enabled) (This)->lpVtbl->XClosedCaptionSetEnabled(This,enabled)
#define IXAccessibilityImpl2_XHighContrastGetMode(This,mode) (This)->lpVtbl->XHighContrastGetMode(This,mode)
#define IXAccessibilityImpl2_XSpeechToTextSetPositionHint(This,position) (This)->lpVtbl->XSpeechToTextSetPositionHint(This,position)
#define IXAccessibilityImpl2_XSpeechToTextSendString(This,speakerName,content,type) (This)->lpVtbl->XSpeechToTextSendString(This,speakerName,content,type)
#define IXAccessibilityImpl2_XSpeechSynthesizerEnumerateInstalledVoices(This,context,callback) (This)->lpVtbl->XSpeechSynthesizerEnumerateInstalledVoices(This,context,callback)
#define IXAccessibilityImpl2_XSpeechSynthesizerCreate(This,speechSynthesizer) (This)->lpVtbl->XSpeechSynthesizerCreate(This,speechSynthesizer)
#define IXAccessibilityImpl2_XSpeechSynthesizerCloseHandle(This,speechSynthesizer) (This)->lpVtbl->XSpeechSynthesizerCloseHandle(This,speechSynthesizer)
#define IXAccessibilityImpl2_XSpeechSynthesizerSetDefaultVoice(This,speechSynthesizer) (This)->lpVtbl->XSpeechSynthesizerSetDefaultVoice(This,speechSynthesizer)
#define IXAccessibilityImpl2_XSpeechSynthesizerSetCustomVoice(This,speechSynthesizer,voiceId) (This)->lpVtbl->XSpeechSynthesizerSetCustomVoice(This,speechSynthesizer,voiceId)
#define IXAccessibilityImpl2_XSpeechSynthesizerCreateStreamFromText(This,speechSynthesizer,text,speechSynthesisStream) (This)->lpVtbl->XSpeechSynthesizerCreateStreamFromText(This,speechSynthesizer,text,speechSynthesisStream)
#define IXAccessibilityImpl2_XSpeechSynthesizerCloseStreamHandle(This,speechSynthesisStream) (This)->lpVtbl->XSpeechSynthesizerCloseStreamHandle(This,speechSynthesisStream)
#define IXAccessibilityImpl2_XSpeechSynthesizerGetStreamDataSize(This,speechSynthesisStream,bufferSize) (This)->lpVtbl->XSpeechSynthesizerGetStreamDataSize(This,speechSynthesisStream,bufferSize)
#define IXAccessibilityImpl2_XSpeechSynthesizerGetStreamData(This,speechSynthesisStream,bufferSize,buffer,bufferUsed) (This)->lpVtbl->XSpeechSynthesizerGetStreamData(This,speechSynthesisStream,bufferSize,buffer,bufferUsed)
#define IXAccessibilityImpl2_XSpeechToTextBeginHypothesisString(This,speakerName,content,type,hypothesisId) (This)->lpVtbl->XSpeechToTextBeginHypothesisString(This,speakerName,content,type,hypothesisId)
#define IXAccessibilityImpl2_XSpeechToTextUpdateHypothesisString(This,hypothesisId,content) (This)->lpVtbl->XSpeechToTextUpdateHypothesisString(This,hypothesisId,content)
#define IXAccessibilityImpl2_XSpeechToTextFinalizeHypothesisString(This,hypothesisId,content) (This)->lpVtbl->XSpeechToTextFinalizeHypothesisString(This,hypothesisId,content)
#define IXAccessibilityImpl2_XSpeechToTextCancelHypothesisString(This,hypothesisId) (This)->lpVtbl->XSpeechToTextCancelHypothesisString(This,hypothesisId)
#define IXAccessibilityImpl2_XSpeechSynthesizerCreateStreamFromSsml(This,speechSynthesizer,ssml,speechSynthesisStream) (This)->lpVtbl->XSpeechSynthesizerCreateStreamFromSsml(This,speechSynthesizer,ssml,speechSynthesisStream)
#else
/*** IUnknown methods ***/
static inline HRESULT IXAccessibilityImpl2_QueryInterface(IXAccessibilityImpl2* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXAccessibilityImpl2_AddRef(IXAccessibilityImpl2* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXAccessibilityImpl2_Release(IXAccessibilityImpl2* This) {
    return This->lpVtbl->Release(This);
}
/*** IXAccessibilityImpl methods ***/
static inline HRESULT IXAccessibilityImpl2_XClosedCaptionGetProperties(IXAccessibilityImpl2* This,XClosedCaptionProperties *props) {
    return This->lpVtbl->XClosedCaptionGetProperties(This,props);
}
static inline HRESULT IXAccessibilityImpl2_XClosedCaptionSetEnabled(IXAccessibilityImpl2* This,BOOLEAN enabled) {
    return This->lpVtbl->XClosedCaptionSetEnabled(This,enabled);
}
static inline HRESULT IXAccessibilityImpl2_XHighContrastGetMode(IXAccessibilityImpl2* This,XHighContrastMode *mode) {
    return This->lpVtbl->XHighContrastGetMode(This,mode);
}
static inline HRESULT IXAccessibilityImpl2_XSpeechToTextSetPositionHint(IXAccessibilityImpl2* This,XSpeechToTextPositionHint position) {
    return This->lpVtbl->XSpeechToTextSetPositionHint(This,position);
}
static inline HRESULT IXAccessibilityImpl2_XSpeechToTextSendString(IXAccessibilityImpl2* This,const char *speakerName,const char *content,XSpeechToTextType type) {
    return This->lpVtbl->XSpeechToTextSendString(This,speakerName,content,type);
}
static inline HRESULT IXAccessibilityImpl2_XSpeechSynthesizerEnumerateInstalledVoices(IXAccessibilityImpl2* This,void *context,XSpeechSynthesizerInstalledVoicesCallback *callback) {
    return This->lpVtbl->XSpeechSynthesizerEnumerateInstalledVoices(This,context,callback);
}
static inline HRESULT IXAccessibilityImpl2_XSpeechSynthesizerCreate(IXAccessibilityImpl2* This,XSpeechSynthesizerHandle *speechSynthesizer) {
    return This->lpVtbl->XSpeechSynthesizerCreate(This,speechSynthesizer);
}
static inline HRESULT IXAccessibilityImpl2_XSpeechSynthesizerCloseHandle(IXAccessibilityImpl2* This,XSpeechSynthesizerHandle speechSynthesizer) {
    return This->lpVtbl->XSpeechSynthesizerCloseHandle(This,speechSynthesizer);
}
static inline HRESULT IXAccessibilityImpl2_XSpeechSynthesizerSetDefaultVoice(IXAccessibilityImpl2* This,XSpeechSynthesizerHandle speechSynthesizer) {
    return This->lpVtbl->XSpeechSynthesizerSetDefaultVoice(This,speechSynthesizer);
}
static inline HRESULT IXAccessibilityImpl2_XSpeechSynthesizerSetCustomVoice(IXAccessibilityImpl2* This,XSpeechSynthesizerHandle speechSynthesizer,const char *voiceId) {
    return This->lpVtbl->XSpeechSynthesizerSetCustomVoice(This,speechSynthesizer,voiceId);
}
static inline HRESULT IXAccessibilityImpl2_XSpeechSynthesizerCreateStreamFromText(IXAccessibilityImpl2* This,XSpeechSynthesizerHandle speechSynthesizer,const char *text,XSpeechSynthesizerStreamHandle *speechSynthesisStream) {
    return This->lpVtbl->XSpeechSynthesizerCreateStreamFromText(This,speechSynthesizer,text,speechSynthesisStream);
}
static inline HRESULT IXAccessibilityImpl2_XSpeechSynthesizerCloseStreamHandle(IXAccessibilityImpl2* This,XSpeechSynthesizerStreamHandle speechSynthesisStream) {
    return This->lpVtbl->XSpeechSynthesizerCloseStreamHandle(This,speechSynthesisStream);
}
static inline HRESULT IXAccessibilityImpl2_XSpeechSynthesizerGetStreamDataSize(IXAccessibilityImpl2* This,XSpeechSynthesizerStreamHandle speechSynthesisStream,SIZE_T *bufferSize) {
    return This->lpVtbl->XSpeechSynthesizerGetStreamDataSize(This,speechSynthesisStream,bufferSize);
}
static inline HRESULT IXAccessibilityImpl2_XSpeechSynthesizerGetStreamData(IXAccessibilityImpl2* This,XSpeechSynthesizerStreamHandle speechSynthesisStream,SIZE_T bufferSize,void *buffer,SIZE_T *bufferUsed) {
    return This->lpVtbl->XSpeechSynthesizerGetStreamData(This,speechSynthesisStream,bufferSize,buffer,bufferUsed);
}
static inline HRESULT IXAccessibilityImpl2_XSpeechToTextBeginHypothesisString(IXAccessibilityImpl2* This,const char *speakerName,const char *content,XSpeechToTextType type,UINT32 *hypothesisId) {
    return This->lpVtbl->XSpeechToTextBeginHypothesisString(This,speakerName,content,type,hypothesisId);
}
static inline HRESULT IXAccessibilityImpl2_XSpeechToTextUpdateHypothesisString(IXAccessibilityImpl2* This,UINT32 hypothesisId,const char *content) {
    return This->lpVtbl->XSpeechToTextUpdateHypothesisString(This,hypothesisId,content);
}
static inline HRESULT IXAccessibilityImpl2_XSpeechToTextFinalizeHypothesisString(IXAccessibilityImpl2* This,UINT32 hypothesisId,const char *content) {
    return This->lpVtbl->XSpeechToTextFinalizeHypothesisString(This,hypothesisId,content);
}
static inline HRESULT IXAccessibilityImpl2_XSpeechToTextCancelHypothesisString(IXAccessibilityImpl2* This,UINT32 hypothesisId) {
    return This->lpVtbl->XSpeechToTextCancelHypothesisString(This,hypothesisId);
}
static inline HRESULT IXAccessibilityImpl2_XSpeechSynthesizerCreateStreamFromSsml(IXAccessibilityImpl2* This,XSpeechSynthesizerHandle speechSynthesizer,const char *ssml,XSpeechSynthesizerStreamHandle *speechSynthesisStream) {
    return This->lpVtbl->XSpeechSynthesizerCreateStreamFromSsml(This,speechSynthesizer,ssml,speechSynthesisStream);
}
#endif
#endif

#endif


#endif  /* __IXAccessibilityImpl2_INTERFACE_DEFINED__ */

/*****************************************************************************
 * XAccessibilityImpl coclass
 */

DEFINE_GUID(CLSID_XAccessibilityImpl, 0x3e241977, 0x6237, 0x41e9, 0x85,0x59, 0x10,0x2c,0x2d,0x99,0x83,0xf1);

#ifdef __cplusplus
class DECLSPEC_UUID("3e241977-6237-41e9-8559-102c2d9983f1") XAccessibilityImpl;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(XAccessibilityImpl, 0x3e241977, 0x6237, 0x41e9, 0x85,0x59, 0x10,0x2c,0x2d,0x99,0x83,0xf1)
#endif
#endif

#endif
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __xaccessibility_h__ */
