/*** Autogenerated by WIDL 11.15 from xappcapture.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __xappcapture_h__
#define __xappcapture_h__

/* Forward declarations */

#ifndef __IXAppCaptureMetadataImpl_FWD_DEFINED__
#define __IXAppCaptureMetadataImpl_FWD_DEFINED__
typedef interface IXAppCaptureMetadataImpl IXAppCaptureMetadataImpl;
#ifdef __cplusplus
interface IXAppCaptureMetadataImpl;
#endif /* __cplusplus */
#endif

#ifndef __IXAppCaptureImpl_FWD_DEFINED__
#define __IXAppCaptureImpl_FWD_DEFINED__
typedef interface IXAppCaptureImpl IXAppCaptureImpl;
#ifdef __cplusplus
interface IXAppCaptureImpl;
#endif /* __cplusplus */
#endif

#ifndef __IXAppCaptureImpl2_FWD_DEFINED__
#define __IXAppCaptureImpl2_FWD_DEFINED__
typedef interface IXAppCaptureImpl2 IXAppCaptureImpl2;
#ifdef __cplusplus
interface IXAppCaptureImpl2;
#endif /* __cplusplus */
#endif

#ifndef __IXAppCaptureImpl3_FWD_DEFINED__
#define __IXAppCaptureImpl3_FWD_DEFINED__
typedef interface IXAppCaptureImpl3 IXAppCaptureImpl3;
#ifdef __cplusplus
interface IXAppCaptureImpl3;
#endif /* __cplusplus */
#endif

#ifndef __IXAppCaptureImpl4_FWD_DEFINED__
#define __IXAppCaptureImpl4_FWD_DEFINED__
typedef interface IXAppCaptureImpl4 IXAppCaptureImpl4;
#ifdef __cplusplus
interface IXAppCaptureImpl4;
#endif /* __cplusplus */
#endif

#ifndef __XAppCaptureMetadataImpl_FWD_DEFINED__
#define __XAppCaptureMetadataImpl_FWD_DEFINED__
#ifdef __cplusplus
typedef class XAppCaptureMetadataImpl XAppCaptureMetadataImpl;
#else
typedef struct XAppCaptureMetadataImpl XAppCaptureMetadataImpl;
#endif /* defined __cplusplus */
#endif /* defined __XAppCaptureMetadataImpl_FWD_DEFINED__ */

#ifndef __XAppCaptureImpl_FWD_DEFINED__
#define __XAppCaptureImpl_FWD_DEFINED__
#ifdef __cplusplus
typedef class XAppCaptureImpl XAppCaptureImpl;
#else
typedef struct XAppCaptureImpl XAppCaptureImpl;
#endif /* defined __cplusplus */
#endif /* defined __XAppCaptureImpl_FWD_DEFINED__ */

/* Headers for imported files */

#include <unknwn.h>
#include <xuser.h>

#ifdef __cplusplus
extern "C" {
#endif

#if 0
typedef UINT64 time_t;
#endif
#ifdef __cplusplus
enum class XAppCaptureMetadataPriority : UINT8
{                                             
    Informational,                            
    Important,                                
};                                            
enum class XAppCaptureScreenshotFormatFlag : UINT16
{                                                  
    SDR = 1,                                       
    HDR,                                           
};                                                 
enum class XAppCaptureVideoColorFormat : UINT8
{                                             
    SDR,                                      
    HDR,                                      
};                                            
enum class XAppCaptureVideoEncoding : UINT8
{                                          
    H264,                                  
    HEVC,                                  
};                                         
#elif defined(__WINESRC__)
typedef enum XAppCaptureMetadataPriority {
    XAppCaptureMetadataPriority_Informational = 0,
    XAppCaptureMetadataPriority_Important = 1
} XAppCaptureMetadataPriority;
typedef enum XAppCaptureScreenshotFormatFlag {
    XAppCaptureScreenshotFormatFlag_SDR = 1,
    XAppCaptureScreenshotFormatFlag_HDR = 2
} XAppCaptureScreenshotFormatFlag;
typedef enum XAppCaptureVideoColorFormat {
    XAppCaptureVideoColorFormat_SDR = 0,
    XAppCaptureVideoColorFormat_HDR = 1
} XAppCaptureVideoColorFormat;
typedef enum XAppCaptureVideoEncoding {
    XAppCaptureVideoEncoding_H264 = 0,
    XAppCaptureVideoEncoding_HEVC = 1
} XAppCaptureVideoEncoding;
#endif
typedef struct XAppCaptureLocalStream *XAppCaptureLocalStreamHandle;
typedef struct XAppCaptureScreenshotStream *XAppCaptureScreenshotStreamHandle;
typedef struct XAppBroadcastStatus XAppBroadcastStatus;
typedef struct XAppCaptureDiagnosticScreenshotResult XAppCaptureDiagnosticScreenshotResult;
typedef struct XAppCaptureLocalResult XAppCaptureLocalResult;
typedef struct XAppCaptureRecordClipResult XAppCaptureRecordClipResult;
typedef struct XAppCaptureScreenshotFile XAppCaptureScreenshotFile;
typedef struct XAppCaptureScreenshotStream XAppCaptureScreenshotStream;
typedef struct XAppCaptureTakeScreenshotResult XAppCaptureTakeScreenshotResult;
typedef struct XAppCaptureUserRecordingResult XAppCaptureUserRecordingResult;
typedef struct XAppCaptureVideoCaptureSettings XAppCaptureVideoCaptureSettings;
typedef void __stdcall  XAppBroadcastMonitorCallback(void *context);
typedef void __stdcall  XAppCaptureMetadataPurgedCallback(void *context);
struct XAppBroadcastStatus {
    BOOLEAN canStartBroadcast;
    BOOLEAN isAnyAppBroadcasting;
    BOOLEAN isCaptureResourceUnavailable;
    BOOLEAN isGameStreamInProgress;
    BOOLEAN isGpuConstrained;
    BOOLEAN isAppInactive;
    BOOLEAN isBlockedForApp;
    BOOLEAN isDisabledByUser;
    BOOLEAN isDisabledBySystem;
};
struct XAppCaptureScreenshotFile {
    char path[260];
    SIZE_T fileSize;
    UINT32 width;
    UINT32 height;
};
struct XAppCaptureDiagnosticScreenshotResult {
    SIZE_T fileCount;
    XAppCaptureScreenshotFile files[10];
};
struct XAppCaptureLocalResult {
    XAppCaptureLocalStreamHandle clipHandle;
    SIZE_T fileSizeInBytes;
    SYSTEMTIME clipStartTimestamp;
    UINT64 durationInMilliseconds;
    UINT32 width;
    UINT32 height;
    XAppCaptureVideoEncoding encoding;
    XAppCaptureVideoColorFormat colorFormat;
};
struct XAppCaptureRecordClipResult {
    char path[260];
    SIZE_T fileSize;
    time_t startTime;
    UINT32 durationInMs;
    UINT32 width;
    UINT32 height;
    XAppCaptureVideoEncoding encoding;
};
struct XAppCaptureScreenshotStream {
};
struct XAppCaptureTakeScreenshotResult {
    char localId[250];
    XAppCaptureScreenshotFormatFlag availableScreenshotFormats;
};
struct XAppCaptureUserRecordingResult {
    SIZE_T fileSizeInBytes;
    SYSTEMTIME clipStartTimestamp;
    UINT64 durationInMilliseconds;
    UINT32 width;
    UINT32 height;
    XAppCaptureVideoEncoding encoding;
    XAppCaptureVideoColorFormat colorFormat;
};
struct XAppCaptureVideoCaptureSettings {
    UINT32 width;
    UINT32 height;
    UINT64 maxRecordTimespanDurationInMs;
    XAppCaptureVideoEncoding encoding;
    XAppCaptureVideoColorFormat colorFormat;
    BOOLEAN isCaptureByGamesAllowed;
};
#ifdef __WINESRC__
/*****************************************************************************
 * IXAppCaptureMetadataImpl interface
 */
#ifndef __IXAppCaptureMetadataImpl_INTERFACE_DEFINED__
#define __IXAppCaptureMetadataImpl_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXAppCaptureMetadataImpl, 0x186d5592, 0xa72d, 0x45fb, 0x95,0x60, 0x11,0xae,0xd0,0xe6,0x64,0x7a);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("186d5592-a72d-45fb-9560-11aed0e6647a")
IXAppCaptureMetadataImpl : public IUnknown
{
    virtual BOOLEAN STDMETHODCALLTYPE XAppBroadcastIsAppBroadcasting(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppBroadcastShowUI(
        XUserHandle requestingUser) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppBroadcastGetStatus(
        XUserHandle requestingUser,
        XAppBroadcastStatus *appBroadcastStatus) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppBroadcastRegisterIsAppBroadcastingChanged(
        XTaskQueueHandle queue,
        void *context,
        XAppBroadcastMonitorCallback *appBroadcastMonitorCallback,
        XTaskQueueRegistrationToken *token) = 0;

    virtual BOOLEAN STDMETHODCALLTYPE XAppBroadcastUnregisterIsAppBroadcastingChanged(
        XTaskQueueRegistrationToken token,
        BOOLEAN wait) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppCaptureMetadataAddStringEvent(
        const char *name,
        const char *value,
        XAppCaptureMetadataPriority priority) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppCaptureMetadataAddInt32Event(
        const char *name,
        INT32 value,
        XAppCaptureMetadataPriority priority) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppCaptureMetadataAddDoubleEvent(
        const char *name,
        double value,
        XAppCaptureMetadataPriority priority) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppCaptureMetadataStartStringState(
        const char *name,
        const char *value,
        XAppCaptureMetadataPriority priority) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppCaptureMetadataStartInt32State(
        const char *name,
        INT32 value,
        XAppCaptureMetadataPriority priority) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppCaptureMetadataStartDoubleState(
        const char *name,
        double value,
        XAppCaptureMetadataPriority priority) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppCaptureMetadataStopState(
        const char *name) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppCaptureMetadataStopAllStates(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppCaptureMetadataRemainingStorageBytesAvailable(
        UINT64 *value) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppCaptureRegisterMetadataPurged(
        XTaskQueueHandle queue,
        void *context,
        XAppCaptureMetadataPurgedCallback *callback,
        XTaskQueueRegistrationToken *token) = 0;

    virtual BOOLEAN STDMETHODCALLTYPE XAppCaptureUnRegisterMetadataPurged(
        XTaskQueueRegistrationToken token,
        BOOLEAN wait) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXAppCaptureMetadataImpl, 0x186d5592, 0xa72d, 0x45fb, 0x95,0x60, 0x11,0xae,0xd0,0xe6,0x64,0x7a)
#endif
#else
typedef struct IXAppCaptureMetadataImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXAppCaptureMetadataImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXAppCaptureMetadataImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXAppCaptureMetadataImpl *This);

    /*** IXAppCaptureMetadataImpl methods ***/
    BOOLEAN (STDMETHODCALLTYPE *XAppBroadcastIsAppBroadcasting)(
        IXAppCaptureMetadataImpl *This);

    HRESULT (STDMETHODCALLTYPE *XAppBroadcastShowUI)(
        IXAppCaptureMetadataImpl *This,
        XUserHandle requestingUser);

    HRESULT (STDMETHODCALLTYPE *XAppBroadcastGetStatus)(
        IXAppCaptureMetadataImpl *This,
        XUserHandle requestingUser,
        XAppBroadcastStatus *appBroadcastStatus);

    HRESULT (STDMETHODCALLTYPE *XAppBroadcastRegisterIsAppBroadcastingChanged)(
        IXAppCaptureMetadataImpl *This,
        XTaskQueueHandle queue,
        void *context,
        XAppBroadcastMonitorCallback *appBroadcastMonitorCallback,
        XTaskQueueRegistrationToken *token);

    BOOLEAN (STDMETHODCALLTYPE *XAppBroadcastUnregisterIsAppBroadcastingChanged)(
        IXAppCaptureMetadataImpl *This,
        XTaskQueueRegistrationToken token,
        BOOLEAN wait);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureMetadataAddStringEvent)(
        IXAppCaptureMetadataImpl *This,
        const char *name,
        const char *value,
        XAppCaptureMetadataPriority priority);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureMetadataAddInt32Event)(
        IXAppCaptureMetadataImpl *This,
        const char *name,
        INT32 value,
        XAppCaptureMetadataPriority priority);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureMetadataAddDoubleEvent)(
        IXAppCaptureMetadataImpl *This,
        const char *name,
        double value,
        XAppCaptureMetadataPriority priority);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureMetadataStartStringState)(
        IXAppCaptureMetadataImpl *This,
        const char *name,
        const char *value,
        XAppCaptureMetadataPriority priority);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureMetadataStartInt32State)(
        IXAppCaptureMetadataImpl *This,
        const char *name,
        INT32 value,
        XAppCaptureMetadataPriority priority);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureMetadataStartDoubleState)(
        IXAppCaptureMetadataImpl *This,
        const char *name,
        double value,
        XAppCaptureMetadataPriority priority);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureMetadataStopState)(
        IXAppCaptureMetadataImpl *This,
        const char *name);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureMetadataStopAllStates)(
        IXAppCaptureMetadataImpl *This);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureMetadataRemainingStorageBytesAvailable)(
        IXAppCaptureMetadataImpl *This,
        UINT64 *value);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureRegisterMetadataPurged)(
        IXAppCaptureMetadataImpl *This,
        XTaskQueueHandle queue,
        void *context,
        XAppCaptureMetadataPurgedCallback *callback,
        XTaskQueueRegistrationToken *token);

    BOOLEAN (STDMETHODCALLTYPE *XAppCaptureUnRegisterMetadataPurged)(
        IXAppCaptureMetadataImpl *This,
        XTaskQueueRegistrationToken token,
        BOOLEAN wait);

    END_INTERFACE
} IXAppCaptureMetadataImplVtbl;

interface IXAppCaptureMetadataImpl {
    CONST_VTBL IXAppCaptureMetadataImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXAppCaptureMetadataImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXAppCaptureMetadataImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXAppCaptureMetadataImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IXAppCaptureMetadataImpl methods ***/
#define IXAppCaptureMetadataImpl_XAppBroadcastIsAppBroadcasting(This) (This)->lpVtbl->XAppBroadcastIsAppBroadcasting(This)
#define IXAppCaptureMetadataImpl_XAppBroadcastShowUI(This,requestingUser) (This)->lpVtbl->XAppBroadcastShowUI(This,requestingUser)
#define IXAppCaptureMetadataImpl_XAppBroadcastGetStatus(This,requestingUser,appBroadcastStatus) (This)->lpVtbl->XAppBroadcastGetStatus(This,requestingUser,appBroadcastStatus)
#define IXAppCaptureMetadataImpl_XAppBroadcastRegisterIsAppBroadcastingChanged(This,queue,context,appBroadcastMonitorCallback,token) (This)->lpVtbl->XAppBroadcastRegisterIsAppBroadcastingChanged(This,queue,context,appBroadcastMonitorCallback,token)
#define IXAppCaptureMetadataImpl_XAppBroadcastUnregisterIsAppBroadcastingChanged(This,token,wait) (This)->lpVtbl->XAppBroadcastUnregisterIsAppBroadcastingChanged(This,token,wait)
#define IXAppCaptureMetadataImpl_XAppCaptureMetadataAddStringEvent(This,name,value,priority) (This)->lpVtbl->XAppCaptureMetadataAddStringEvent(This,name,value,priority)
#define IXAppCaptureMetadataImpl_XAppCaptureMetadataAddInt32Event(This,name,value,priority) (This)->lpVtbl->XAppCaptureMetadataAddInt32Event(This,name,value,priority)
#define IXAppCaptureMetadataImpl_XAppCaptureMetadataAddDoubleEvent(This,name,value,priority) (This)->lpVtbl->XAppCaptureMetadataAddDoubleEvent(This,name,value,priority)
#define IXAppCaptureMetadataImpl_XAppCaptureMetadataStartStringState(This,name,value,priority) (This)->lpVtbl->XAppCaptureMetadataStartStringState(This,name,value,priority)
#define IXAppCaptureMetadataImpl_XAppCaptureMetadataStartInt32State(This,name,value,priority) (This)->lpVtbl->XAppCaptureMetadataStartInt32State(This,name,value,priority)
#define IXAppCaptureMetadataImpl_XAppCaptureMetadataStartDoubleState(This,name,value,priority) (This)->lpVtbl->XAppCaptureMetadataStartDoubleState(This,name,value,priority)
#define IXAppCaptureMetadataImpl_XAppCaptureMetadataStopState(This,name) (This)->lpVtbl->XAppCaptureMetadataStopState(This,name)
#define IXAppCaptureMetadataImpl_XAppCaptureMetadataStopAllStates(This) (This)->lpVtbl->XAppCaptureMetadataStopAllStates(This)
#define IXAppCaptureMetadataImpl_XAppCaptureMetadataRemainingStorageBytesAvailable(This,value) (This)->lpVtbl->XAppCaptureMetadataRemainingStorageBytesAvailable(This,value)
#define IXAppCaptureMetadataImpl_XAppCaptureRegisterMetadataPurged(This,queue,context,callback,token) (This)->lpVtbl->XAppCaptureRegisterMetadataPurged(This,queue,context,callback,token)
#define IXAppCaptureMetadataImpl_XAppCaptureUnRegisterMetadataPurged(This,token,wait) (This)->lpVtbl->XAppCaptureUnRegisterMetadataPurged(This,token,wait)
#else
/*** IUnknown methods ***/
static inline HRESULT IXAppCaptureMetadataImpl_QueryInterface(IXAppCaptureMetadataImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXAppCaptureMetadataImpl_AddRef(IXAppCaptureMetadataImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXAppCaptureMetadataImpl_Release(IXAppCaptureMetadataImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IXAppCaptureMetadataImpl methods ***/
static inline BOOLEAN IXAppCaptureMetadataImpl_XAppBroadcastIsAppBroadcasting(IXAppCaptureMetadataImpl* This) {
    return This->lpVtbl->XAppBroadcastIsAppBroadcasting(This);
}
static inline HRESULT IXAppCaptureMetadataImpl_XAppBroadcastShowUI(IXAppCaptureMetadataImpl* This,XUserHandle requestingUser) {
    return This->lpVtbl->XAppBroadcastShowUI(This,requestingUser);
}
static inline HRESULT IXAppCaptureMetadataImpl_XAppBroadcastGetStatus(IXAppCaptureMetadataImpl* This,XUserHandle requestingUser,XAppBroadcastStatus *appBroadcastStatus) {
    return This->lpVtbl->XAppBroadcastGetStatus(This,requestingUser,appBroadcastStatus);
}
static inline HRESULT IXAppCaptureMetadataImpl_XAppBroadcastRegisterIsAppBroadcastingChanged(IXAppCaptureMetadataImpl* This,XTaskQueueHandle queue,void *context,XAppBroadcastMonitorCallback *appBroadcastMonitorCallback,XTaskQueueRegistrationToken *token) {
    return This->lpVtbl->XAppBroadcastRegisterIsAppBroadcastingChanged(This,queue,context,appBroadcastMonitorCallback,token);
}
static inline BOOLEAN IXAppCaptureMetadataImpl_XAppBroadcastUnregisterIsAppBroadcastingChanged(IXAppCaptureMetadataImpl* This,XTaskQueueRegistrationToken token,BOOLEAN wait) {
    return This->lpVtbl->XAppBroadcastUnregisterIsAppBroadcastingChanged(This,token,wait);
}
static inline HRESULT IXAppCaptureMetadataImpl_XAppCaptureMetadataAddStringEvent(IXAppCaptureMetadataImpl* This,const char *name,const char *value,XAppCaptureMetadataPriority priority) {
    return This->lpVtbl->XAppCaptureMetadataAddStringEvent(This,name,value,priority);
}
static inline HRESULT IXAppCaptureMetadataImpl_XAppCaptureMetadataAddInt32Event(IXAppCaptureMetadataImpl* This,const char *name,INT32 value,XAppCaptureMetadataPriority priority) {
    return This->lpVtbl->XAppCaptureMetadataAddInt32Event(This,name,value,priority);
}
static inline HRESULT IXAppCaptureMetadataImpl_XAppCaptureMetadataAddDoubleEvent(IXAppCaptureMetadataImpl* This,const char *name,double value,XAppCaptureMetadataPriority priority) {
    return This->lpVtbl->XAppCaptureMetadataAddDoubleEvent(This,name,value,priority);
}
static inline HRESULT IXAppCaptureMetadataImpl_XAppCaptureMetadataStartStringState(IXAppCaptureMetadataImpl* This,const char *name,const char *value,XAppCaptureMetadataPriority priority) {
    return This->lpVtbl->XAppCaptureMetadataStartStringState(This,name,value,priority);
}
static inline HRESULT IXAppCaptureMetadataImpl_XAppCaptureMetadataStartInt32State(IXAppCaptureMetadataImpl* This,const char *name,INT32 value,XAppCaptureMetadataPriority priority) {
    return This->lpVtbl->XAppCaptureMetadataStartInt32State(This,name,value,priority);
}
static inline HRESULT IXAppCaptureMetadataImpl_XAppCaptureMetadataStartDoubleState(IXAppCaptureMetadataImpl* This,const char *name,double value,XAppCaptureMetadataPriority priority) {
    return This->lpVtbl->XAppCaptureMetadataStartDoubleState(This,name,value,priority);
}
static inline HRESULT IXAppCaptureMetadataImpl_XAppCaptureMetadataStopState(IXAppCaptureMetadataImpl* This,const char *name) {
    return This->lpVtbl->XAppCaptureMetadataStopState(This,name);
}
static inline HRESULT IXAppCaptureMetadataImpl_XAppCaptureMetadataStopAllStates(IXAppCaptureMetadataImpl* This) {
    return This->lpVtbl->XAppCaptureMetadataStopAllStates(This);
}
static inline HRESULT IXAppCaptureMetadataImpl_XAppCaptureMetadataRemainingStorageBytesAvailable(IXAppCaptureMetadataImpl* This,UINT64 *value) {
    return This->lpVtbl->XAppCaptureMetadataRemainingStorageBytesAvailable(This,value);
}
static inline HRESULT IXAppCaptureMetadataImpl_XAppCaptureRegisterMetadataPurged(IXAppCaptureMetadataImpl* This,XTaskQueueHandle queue,void *context,XAppCaptureMetadataPurgedCallback *callback,XTaskQueueRegistrationToken *token) {
    return This->lpVtbl->XAppCaptureRegisterMetadataPurged(This,queue,context,callback,token);
}
static inline BOOLEAN IXAppCaptureMetadataImpl_XAppCaptureUnRegisterMetadataPurged(IXAppCaptureMetadataImpl* This,XTaskQueueRegistrationToken token,BOOLEAN wait) {
    return This->lpVtbl->XAppCaptureUnRegisterMetadataPurged(This,token,wait);
}
#endif
#endif

#endif


#endif  /* __IXAppCaptureMetadataImpl_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IXAppCaptureImpl interface
 */
#ifndef __IXAppCaptureImpl_INTERFACE_DEFINED__
#define __IXAppCaptureImpl_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXAppCaptureImpl, 0xa4f1aee2, 0x4bf1, 0x4485, 0xb0,0x08, 0xa7,0xc2,0x6d,0x52,0xac,0x27);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("a4f1aee2-4bf1-4485-b008-a7c26d52ac27")
IXAppCaptureImpl : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE XAppCaptureTakeDiagnosticScreenshot(
        BOOLEAN gamescreenOnly,
        XAppCaptureScreenshotFormatFlag captureFlags,
        const char *filenamePrefix,
        XAppCaptureDiagnosticScreenshotResult *result) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppCaptureRecordDiagnosticClip(
        time_t startTime,
        UINT32 durationInMs,
        const char *filenamePrefix,
        XAppCaptureRecordClipResult *result) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppCaptureTakeScreenshot(
        XUserHandle requestingUser,
        XAppCaptureTakeScreenshotResult *result) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppCaptureOpenScreenshotStream(
        const char *localId,
        XAppCaptureScreenshotFormatFlag screenshotFormat,
        XAppCaptureScreenshotStreamHandle *handle,
        UINT64 *totalBytes) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppCaptureReadScreenshotStream(
        XAppCaptureScreenshotStreamHandle handle,
        UINT64 startPosition,
        UINT32 bytesToRead,
        UINT8 *buffer,
        UINT32 *bytesWritten) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppCaptureCloseScreenshotStream(
        XAppCaptureScreenshotStreamHandle handle) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppCaptureEnableRecord(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppCaptureDisableRecord(
        ) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXAppCaptureImpl, 0xa4f1aee2, 0x4bf1, 0x4485, 0xb0,0x08, 0xa7,0xc2,0x6d,0x52,0xac,0x27)
#endif
#else
typedef struct IXAppCaptureImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXAppCaptureImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXAppCaptureImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXAppCaptureImpl *This);

    /*** IXAppCaptureImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XAppCaptureTakeDiagnosticScreenshot)(
        IXAppCaptureImpl *This,
        BOOLEAN gamescreenOnly,
        XAppCaptureScreenshotFormatFlag captureFlags,
        const char *filenamePrefix,
        XAppCaptureDiagnosticScreenshotResult *result);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureRecordDiagnosticClip)(
        IXAppCaptureImpl *This,
        time_t startTime,
        UINT32 durationInMs,
        const char *filenamePrefix,
        XAppCaptureRecordClipResult *result);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureTakeScreenshot)(
        IXAppCaptureImpl *This,
        XUserHandle requestingUser,
        XAppCaptureTakeScreenshotResult *result);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureOpenScreenshotStream)(
        IXAppCaptureImpl *This,
        const char *localId,
        XAppCaptureScreenshotFormatFlag screenshotFormat,
        XAppCaptureScreenshotStreamHandle *handle,
        UINT64 *totalBytes);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureReadScreenshotStream)(
        IXAppCaptureImpl *This,
        XAppCaptureScreenshotStreamHandle handle,
        UINT64 startPosition,
        UINT32 bytesToRead,
        UINT8 *buffer,
        UINT32 *bytesWritten);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureCloseScreenshotStream)(
        IXAppCaptureImpl *This,
        XAppCaptureScreenshotStreamHandle handle);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureEnableRecord)(
        IXAppCaptureImpl *This);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureDisableRecord)(
        IXAppCaptureImpl *This);

    END_INTERFACE
} IXAppCaptureImplVtbl;

interface IXAppCaptureImpl {
    CONST_VTBL IXAppCaptureImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXAppCaptureImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXAppCaptureImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXAppCaptureImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IXAppCaptureImpl methods ***/
#define IXAppCaptureImpl_XAppCaptureTakeDiagnosticScreenshot(This,gamescreenOnly,captureFlags,filenamePrefix,result) (This)->lpVtbl->XAppCaptureTakeDiagnosticScreenshot(This,gamescreenOnly,captureFlags,filenamePrefix,result)
#define IXAppCaptureImpl_XAppCaptureRecordDiagnosticClip(This,startTime,durationInMs,filenamePrefix,result) (This)->lpVtbl->XAppCaptureRecordDiagnosticClip(This,startTime,durationInMs,filenamePrefix,result)
#define IXAppCaptureImpl_XAppCaptureTakeScreenshot(This,requestingUser,result) (This)->lpVtbl->XAppCaptureTakeScreenshot(This,requestingUser,result)
#define IXAppCaptureImpl_XAppCaptureOpenScreenshotStream(This,localId,screenshotFormat,handle,totalBytes) (This)->lpVtbl->XAppCaptureOpenScreenshotStream(This,localId,screenshotFormat,handle,totalBytes)
#define IXAppCaptureImpl_XAppCaptureReadScreenshotStream(This,handle,startPosition,bytesToRead,buffer,bytesWritten) (This)->lpVtbl->XAppCaptureReadScreenshotStream(This,handle,startPosition,bytesToRead,buffer,bytesWritten)
#define IXAppCaptureImpl_XAppCaptureCloseScreenshotStream(This,handle) (This)->lpVtbl->XAppCaptureCloseScreenshotStream(This,handle)
#define IXAppCaptureImpl_XAppCaptureEnableRecord(This) (This)->lpVtbl->XAppCaptureEnableRecord(This)
#define IXAppCaptureImpl_XAppCaptureDisableRecord(This) (This)->lpVtbl->XAppCaptureDisableRecord(This)
#else
/*** IUnknown methods ***/
static inline HRESULT IXAppCaptureImpl_QueryInterface(IXAppCaptureImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXAppCaptureImpl_AddRef(IXAppCaptureImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXAppCaptureImpl_Release(IXAppCaptureImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IXAppCaptureImpl methods ***/
static inline HRESULT IXAppCaptureImpl_XAppCaptureTakeDiagnosticScreenshot(IXAppCaptureImpl* This,BOOLEAN gamescreenOnly,XAppCaptureScreenshotFormatFlag captureFlags,const char *filenamePrefix,XAppCaptureDiagnosticScreenshotResult *result) {
    return This->lpVtbl->XAppCaptureTakeDiagnosticScreenshot(This,gamescreenOnly,captureFlags,filenamePrefix,result);
}
static inline HRESULT IXAppCaptureImpl_XAppCaptureRecordDiagnosticClip(IXAppCaptureImpl* This,time_t startTime,UINT32 durationInMs,const char *filenamePrefix,XAppCaptureRecordClipResult *result) {
    return This->lpVtbl->XAppCaptureRecordDiagnosticClip(This,startTime,durationInMs,filenamePrefix,result);
}
static inline HRESULT IXAppCaptureImpl_XAppCaptureTakeScreenshot(IXAppCaptureImpl* This,XUserHandle requestingUser,XAppCaptureTakeScreenshotResult *result) {
    return This->lpVtbl->XAppCaptureTakeScreenshot(This,requestingUser,result);
}
static inline HRESULT IXAppCaptureImpl_XAppCaptureOpenScreenshotStream(IXAppCaptureImpl* This,const char *localId,XAppCaptureScreenshotFormatFlag screenshotFormat,XAppCaptureScreenshotStreamHandle *handle,UINT64 *totalBytes) {
    return This->lpVtbl->XAppCaptureOpenScreenshotStream(This,localId,screenshotFormat,handle,totalBytes);
}
static inline HRESULT IXAppCaptureImpl_XAppCaptureReadScreenshotStream(IXAppCaptureImpl* This,XAppCaptureScreenshotStreamHandle handle,UINT64 startPosition,UINT32 bytesToRead,UINT8 *buffer,UINT32 *bytesWritten) {
    return This->lpVtbl->XAppCaptureReadScreenshotStream(This,handle,startPosition,bytesToRead,buffer,bytesWritten);
}
static inline HRESULT IXAppCaptureImpl_XAppCaptureCloseScreenshotStream(IXAppCaptureImpl* This,XAppCaptureScreenshotStreamHandle handle) {
    return This->lpVtbl->XAppCaptureCloseScreenshotStream(This,handle);
}
static inline HRESULT IXAppCaptureImpl_XAppCaptureEnableRecord(IXAppCaptureImpl* This) {
    return This->lpVtbl->XAppCaptureEnableRecord(This);
}
static inline HRESULT IXAppCaptureImpl_XAppCaptureDisableRecord(IXAppCaptureImpl* This) {
    return This->lpVtbl->XAppCaptureDisableRecord(This);
}
#endif
#endif

#endif


#endif  /* __IXAppCaptureImpl_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IXAppCaptureImpl2 interface
 */
#ifndef __IXAppCaptureImpl2_INTERFACE_DEFINED__
#define __IXAppCaptureImpl2_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXAppCaptureImpl2, 0x3a949778, 0x772e, 0x4799, 0xbd,0xea, 0x0a,0x66,0x39,0xe9,0x6b,0xaa);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("3a949778-772e-4799-bdea-0a6639e96baa")
IXAppCaptureImpl2 : public IXAppCaptureImpl
{
    virtual HRESULT STDMETHODCALLTYPE XAppCaptureGetVideoCaptureSettings(
        XAppCaptureVideoCaptureSettings *userCaptureSettings) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppCaptureRecordTimespan(
        const SYSTEMTIME *startTimestamp,
        UINT64 durationInMilliseconds,
        XAppCaptureLocalResult *result) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppCaptureReadLocalStream(
        XAppCaptureLocalStreamHandle handle,
        SIZE_T startPosition,
        UINT32 bytesToRead,
        UINT8 *buffer,
        UINT32 *bytesWritten) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppCaptureCloseLocalStream(
        XAppCaptureLocalStreamHandle handle) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXAppCaptureImpl2, 0x3a949778, 0x772e, 0x4799, 0xbd,0xea, 0x0a,0x66,0x39,0xe9,0x6b,0xaa)
#endif
#else
typedef struct IXAppCaptureImpl2Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXAppCaptureImpl2 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXAppCaptureImpl2 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXAppCaptureImpl2 *This);

    /*** IXAppCaptureImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XAppCaptureTakeDiagnosticScreenshot)(
        IXAppCaptureImpl2 *This,
        BOOLEAN gamescreenOnly,
        XAppCaptureScreenshotFormatFlag captureFlags,
        const char *filenamePrefix,
        XAppCaptureDiagnosticScreenshotResult *result);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureRecordDiagnosticClip)(
        IXAppCaptureImpl2 *This,
        time_t startTime,
        UINT32 durationInMs,
        const char *filenamePrefix,
        XAppCaptureRecordClipResult *result);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureTakeScreenshot)(
        IXAppCaptureImpl2 *This,
        XUserHandle requestingUser,
        XAppCaptureTakeScreenshotResult *result);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureOpenScreenshotStream)(
        IXAppCaptureImpl2 *This,
        const char *localId,
        XAppCaptureScreenshotFormatFlag screenshotFormat,
        XAppCaptureScreenshotStreamHandle *handle,
        UINT64 *totalBytes);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureReadScreenshotStream)(
        IXAppCaptureImpl2 *This,
        XAppCaptureScreenshotStreamHandle handle,
        UINT64 startPosition,
        UINT32 bytesToRead,
        UINT8 *buffer,
        UINT32 *bytesWritten);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureCloseScreenshotStream)(
        IXAppCaptureImpl2 *This,
        XAppCaptureScreenshotStreamHandle handle);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureEnableRecord)(
        IXAppCaptureImpl2 *This);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureDisableRecord)(
        IXAppCaptureImpl2 *This);

    /*** IXAppCaptureImpl2 methods ***/
    HRESULT (STDMETHODCALLTYPE *XAppCaptureGetVideoCaptureSettings)(
        IXAppCaptureImpl2 *This,
        XAppCaptureVideoCaptureSettings *userCaptureSettings);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureRecordTimespan)(
        IXAppCaptureImpl2 *This,
        const SYSTEMTIME *startTimestamp,
        UINT64 durationInMilliseconds,
        XAppCaptureLocalResult *result);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureReadLocalStream)(
        IXAppCaptureImpl2 *This,
        XAppCaptureLocalStreamHandle handle,
        SIZE_T startPosition,
        UINT32 bytesToRead,
        UINT8 *buffer,
        UINT32 *bytesWritten);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureCloseLocalStream)(
        IXAppCaptureImpl2 *This,
        XAppCaptureLocalStreamHandle handle);

    END_INTERFACE
} IXAppCaptureImpl2Vtbl;

interface IXAppCaptureImpl2 {
    CONST_VTBL IXAppCaptureImpl2Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXAppCaptureImpl2_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXAppCaptureImpl2_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXAppCaptureImpl2_Release(This) (This)->lpVtbl->Release(This)
/*** IXAppCaptureImpl methods ***/
#define IXAppCaptureImpl2_XAppCaptureTakeDiagnosticScreenshot(This,gamescreenOnly,captureFlags,filenamePrefix,result) (This)->lpVtbl->XAppCaptureTakeDiagnosticScreenshot(This,gamescreenOnly,captureFlags,filenamePrefix,result)
#define IXAppCaptureImpl2_XAppCaptureRecordDiagnosticClip(This,startTime,durationInMs,filenamePrefix,result) (This)->lpVtbl->XAppCaptureRecordDiagnosticClip(This,startTime,durationInMs,filenamePrefix,result)
#define IXAppCaptureImpl2_XAppCaptureTakeScreenshot(This,requestingUser,result) (This)->lpVtbl->XAppCaptureTakeScreenshot(This,requestingUser,result)
#define IXAppCaptureImpl2_XAppCaptureOpenScreenshotStream(This,localId,screenshotFormat,handle,totalBytes) (This)->lpVtbl->XAppCaptureOpenScreenshotStream(This,localId,screenshotFormat,handle,totalBytes)
#define IXAppCaptureImpl2_XAppCaptureReadScreenshotStream(This,handle,startPosition,bytesToRead,buffer,bytesWritten) (This)->lpVtbl->XAppCaptureReadScreenshotStream(This,handle,startPosition,bytesToRead,buffer,bytesWritten)
#define IXAppCaptureImpl2_XAppCaptureCloseScreenshotStream(This,handle) (This)->lpVtbl->XAppCaptureCloseScreenshotStream(This,handle)
#define IXAppCaptureImpl2_XAppCaptureEnableRecord(This) (This)->lpVtbl->XAppCaptureEnableRecord(This)
#define IXAppCaptureImpl2_XAppCaptureDisableRecord(This) (This)->lpVtbl->XAppCaptureDisableRecord(This)
/*** IXAppCaptureImpl2 methods ***/
#define IXAppCaptureImpl2_XAppCaptureGetVideoCaptureSettings(This,userCaptureSettings) (This)->lpVtbl->XAppCaptureGetVideoCaptureSettings(This,userCaptureSettings)
#define IXAppCaptureImpl2_XAppCaptureRecordTimespan(This,startTimestamp,durationInMilliseconds,result) (This)->lpVtbl->XAppCaptureRecordTimespan(This,startTimestamp,durationInMilliseconds,result)
#define IXAppCaptureImpl2_XAppCaptureReadLocalStream(This,handle,startPosition,bytesToRead,buffer,bytesWritten) (This)->lpVtbl->XAppCaptureReadLocalStream(This,handle,startPosition,bytesToRead,buffer,bytesWritten)
#define IXAppCaptureImpl2_XAppCaptureCloseLocalStream(This,handle) (This)->lpVtbl->XAppCaptureCloseLocalStream(This,handle)
#else
/*** IUnknown methods ***/
static inline HRESULT IXAppCaptureImpl2_QueryInterface(IXAppCaptureImpl2* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXAppCaptureImpl2_AddRef(IXAppCaptureImpl2* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXAppCaptureImpl2_Release(IXAppCaptureImpl2* This) {
    return This->lpVtbl->Release(This);
}
/*** IXAppCaptureImpl methods ***/
static inline HRESULT IXAppCaptureImpl2_XAppCaptureTakeDiagnosticScreenshot(IXAppCaptureImpl2* This,BOOLEAN gamescreenOnly,XAppCaptureScreenshotFormatFlag captureFlags,const char *filenamePrefix,XAppCaptureDiagnosticScreenshotResult *result) {
    return This->lpVtbl->XAppCaptureTakeDiagnosticScreenshot(This,gamescreenOnly,captureFlags,filenamePrefix,result);
}
static inline HRESULT IXAppCaptureImpl2_XAppCaptureRecordDiagnosticClip(IXAppCaptureImpl2* This,time_t startTime,UINT32 durationInMs,const char *filenamePrefix,XAppCaptureRecordClipResult *result) {
    return This->lpVtbl->XAppCaptureRecordDiagnosticClip(This,startTime,durationInMs,filenamePrefix,result);
}
static inline HRESULT IXAppCaptureImpl2_XAppCaptureTakeScreenshot(IXAppCaptureImpl2* This,XUserHandle requestingUser,XAppCaptureTakeScreenshotResult *result) {
    return This->lpVtbl->XAppCaptureTakeScreenshot(This,requestingUser,result);
}
static inline HRESULT IXAppCaptureImpl2_XAppCaptureOpenScreenshotStream(IXAppCaptureImpl2* This,const char *localId,XAppCaptureScreenshotFormatFlag screenshotFormat,XAppCaptureScreenshotStreamHandle *handle,UINT64 *totalBytes) {
    return This->lpVtbl->XAppCaptureOpenScreenshotStream(This,localId,screenshotFormat,handle,totalBytes);
}
static inline HRESULT IXAppCaptureImpl2_XAppCaptureReadScreenshotStream(IXAppCaptureImpl2* This,XAppCaptureScreenshotStreamHandle handle,UINT64 startPosition,UINT32 bytesToRead,UINT8 *buffer,UINT32 *bytesWritten) {
    return This->lpVtbl->XAppCaptureReadScreenshotStream(This,handle,startPosition,bytesToRead,buffer,bytesWritten);
}
static inline HRESULT IXAppCaptureImpl2_XAppCaptureCloseScreenshotStream(IXAppCaptureImpl2* This,XAppCaptureScreenshotStreamHandle handle) {
    return This->lpVtbl->XAppCaptureCloseScreenshotStream(This,handle);
}
static inline HRESULT IXAppCaptureImpl2_XAppCaptureEnableRecord(IXAppCaptureImpl2* This) {
    return This->lpVtbl->XAppCaptureEnableRecord(This);
}
static inline HRESULT IXAppCaptureImpl2_XAppCaptureDisableRecord(IXAppCaptureImpl2* This) {
    return This->lpVtbl->XAppCaptureDisableRecord(This);
}
/*** IXAppCaptureImpl2 methods ***/
static inline HRESULT IXAppCaptureImpl2_XAppCaptureGetVideoCaptureSettings(IXAppCaptureImpl2* This,XAppCaptureVideoCaptureSettings *userCaptureSettings) {
    return This->lpVtbl->XAppCaptureGetVideoCaptureSettings(This,userCaptureSettings);
}
static inline HRESULT IXAppCaptureImpl2_XAppCaptureRecordTimespan(IXAppCaptureImpl2* This,const SYSTEMTIME *startTimestamp,UINT64 durationInMilliseconds,XAppCaptureLocalResult *result) {
    return This->lpVtbl->XAppCaptureRecordTimespan(This,startTimestamp,durationInMilliseconds,result);
}
static inline HRESULT IXAppCaptureImpl2_XAppCaptureReadLocalStream(IXAppCaptureImpl2* This,XAppCaptureLocalStreamHandle handle,SIZE_T startPosition,UINT32 bytesToRead,UINT8 *buffer,UINT32 *bytesWritten) {
    return This->lpVtbl->XAppCaptureReadLocalStream(This,handle,startPosition,bytesToRead,buffer,bytesWritten);
}
static inline HRESULT IXAppCaptureImpl2_XAppCaptureCloseLocalStream(IXAppCaptureImpl2* This,XAppCaptureLocalStreamHandle handle) {
    return This->lpVtbl->XAppCaptureCloseLocalStream(This,handle);
}
#endif
#endif

#endif


#endif  /* __IXAppCaptureImpl2_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IXAppCaptureImpl3 interface
 */
#ifndef __IXAppCaptureImpl3_INTERFACE_DEFINED__
#define __IXAppCaptureImpl3_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXAppCaptureImpl3, 0x2bbca60a, 0x619c, 0x4fe1, 0x81,0x2e, 0xfb,0x5c,0x1d,0xbd,0xcf,0x51);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("2bbca60a-619c-4fe1-812e-fb5c1dbdcf51")
IXAppCaptureImpl3 : public IXAppCaptureImpl2
{
    virtual HRESULT STDMETHODCALLTYPE XAppCaptureStartUserRecord(
        XUserHandle requestingUser,
        UINT32 localIdBufferLength,
        char *localIdBuffer) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAppCaptureStopUserRecord(
        const char *localId,
        XAppCaptureUserRecordingResult *result) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXAppCaptureImpl3, 0x2bbca60a, 0x619c, 0x4fe1, 0x81,0x2e, 0xfb,0x5c,0x1d,0xbd,0xcf,0x51)
#endif
#else
typedef struct IXAppCaptureImpl3Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXAppCaptureImpl3 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXAppCaptureImpl3 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXAppCaptureImpl3 *This);

    /*** IXAppCaptureImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XAppCaptureTakeDiagnosticScreenshot)(
        IXAppCaptureImpl3 *This,
        BOOLEAN gamescreenOnly,
        XAppCaptureScreenshotFormatFlag captureFlags,
        const char *filenamePrefix,
        XAppCaptureDiagnosticScreenshotResult *result);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureRecordDiagnosticClip)(
        IXAppCaptureImpl3 *This,
        time_t startTime,
        UINT32 durationInMs,
        const char *filenamePrefix,
        XAppCaptureRecordClipResult *result);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureTakeScreenshot)(
        IXAppCaptureImpl3 *This,
        XUserHandle requestingUser,
        XAppCaptureTakeScreenshotResult *result);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureOpenScreenshotStream)(
        IXAppCaptureImpl3 *This,
        const char *localId,
        XAppCaptureScreenshotFormatFlag screenshotFormat,
        XAppCaptureScreenshotStreamHandle *handle,
        UINT64 *totalBytes);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureReadScreenshotStream)(
        IXAppCaptureImpl3 *This,
        XAppCaptureScreenshotStreamHandle handle,
        UINT64 startPosition,
        UINT32 bytesToRead,
        UINT8 *buffer,
        UINT32 *bytesWritten);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureCloseScreenshotStream)(
        IXAppCaptureImpl3 *This,
        XAppCaptureScreenshotStreamHandle handle);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureEnableRecord)(
        IXAppCaptureImpl3 *This);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureDisableRecord)(
        IXAppCaptureImpl3 *This);

    /*** IXAppCaptureImpl2 methods ***/
    HRESULT (STDMETHODCALLTYPE *XAppCaptureGetVideoCaptureSettings)(
        IXAppCaptureImpl3 *This,
        XAppCaptureVideoCaptureSettings *userCaptureSettings);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureRecordTimespan)(
        IXAppCaptureImpl3 *This,
        const SYSTEMTIME *startTimestamp,
        UINT64 durationInMilliseconds,
        XAppCaptureLocalResult *result);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureReadLocalStream)(
        IXAppCaptureImpl3 *This,
        XAppCaptureLocalStreamHandle handle,
        SIZE_T startPosition,
        UINT32 bytesToRead,
        UINT8 *buffer,
        UINT32 *bytesWritten);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureCloseLocalStream)(
        IXAppCaptureImpl3 *This,
        XAppCaptureLocalStreamHandle handle);

    /*** IXAppCaptureImpl3 methods ***/
    HRESULT (STDMETHODCALLTYPE *XAppCaptureStartUserRecord)(
        IXAppCaptureImpl3 *This,
        XUserHandle requestingUser,
        UINT32 localIdBufferLength,
        char *localIdBuffer);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureStopUserRecord)(
        IXAppCaptureImpl3 *This,
        const char *localId,
        XAppCaptureUserRecordingResult *result);

    END_INTERFACE
} IXAppCaptureImpl3Vtbl;

interface IXAppCaptureImpl3 {
    CONST_VTBL IXAppCaptureImpl3Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXAppCaptureImpl3_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXAppCaptureImpl3_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXAppCaptureImpl3_Release(This) (This)->lpVtbl->Release(This)
/*** IXAppCaptureImpl methods ***/
#define IXAppCaptureImpl3_XAppCaptureTakeDiagnosticScreenshot(This,gamescreenOnly,captureFlags,filenamePrefix,result) (This)->lpVtbl->XAppCaptureTakeDiagnosticScreenshot(This,gamescreenOnly,captureFlags,filenamePrefix,result)
#define IXAppCaptureImpl3_XAppCaptureRecordDiagnosticClip(This,startTime,durationInMs,filenamePrefix,result) (This)->lpVtbl->XAppCaptureRecordDiagnosticClip(This,startTime,durationInMs,filenamePrefix,result)
#define IXAppCaptureImpl3_XAppCaptureTakeScreenshot(This,requestingUser,result) (This)->lpVtbl->XAppCaptureTakeScreenshot(This,requestingUser,result)
#define IXAppCaptureImpl3_XAppCaptureOpenScreenshotStream(This,localId,screenshotFormat,handle,totalBytes) (This)->lpVtbl->XAppCaptureOpenScreenshotStream(This,localId,screenshotFormat,handle,totalBytes)
#define IXAppCaptureImpl3_XAppCaptureReadScreenshotStream(This,handle,startPosition,bytesToRead,buffer,bytesWritten) (This)->lpVtbl->XAppCaptureReadScreenshotStream(This,handle,startPosition,bytesToRead,buffer,bytesWritten)
#define IXAppCaptureImpl3_XAppCaptureCloseScreenshotStream(This,handle) (This)->lpVtbl->XAppCaptureCloseScreenshotStream(This,handle)
#define IXAppCaptureImpl3_XAppCaptureEnableRecord(This) (This)->lpVtbl->XAppCaptureEnableRecord(This)
#define IXAppCaptureImpl3_XAppCaptureDisableRecord(This) (This)->lpVtbl->XAppCaptureDisableRecord(This)
/*** IXAppCaptureImpl2 methods ***/
#define IXAppCaptureImpl3_XAppCaptureGetVideoCaptureSettings(This,userCaptureSettings) (This)->lpVtbl->XAppCaptureGetVideoCaptureSettings(This,userCaptureSettings)
#define IXAppCaptureImpl3_XAppCaptureRecordTimespan(This,startTimestamp,durationInMilliseconds,result) (This)->lpVtbl->XAppCaptureRecordTimespan(This,startTimestamp,durationInMilliseconds,result)
#define IXAppCaptureImpl3_XAppCaptureReadLocalStream(This,handle,startPosition,bytesToRead,buffer,bytesWritten) (This)->lpVtbl->XAppCaptureReadLocalStream(This,handle,startPosition,bytesToRead,buffer,bytesWritten)
#define IXAppCaptureImpl3_XAppCaptureCloseLocalStream(This,handle) (This)->lpVtbl->XAppCaptureCloseLocalStream(This,handle)
/*** IXAppCaptureImpl3 methods ***/
#define IXAppCaptureImpl3_XAppCaptureStartUserRecord(This,requestingUser,localIdBufferLength,localIdBuffer) (This)->lpVtbl->XAppCaptureStartUserRecord(This,requestingUser,localIdBufferLength,localIdBuffer)
#define IXAppCaptureImpl3_XAppCaptureStopUserRecord(This,localId,result) (This)->lpVtbl->XAppCaptureStopUserRecord(This,localId,result)
#else
/*** IUnknown methods ***/
static inline HRESULT IXAppCaptureImpl3_QueryInterface(IXAppCaptureImpl3* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXAppCaptureImpl3_AddRef(IXAppCaptureImpl3* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXAppCaptureImpl3_Release(IXAppCaptureImpl3* This) {
    return This->lpVtbl->Release(This);
}
/*** IXAppCaptureImpl methods ***/
static inline HRESULT IXAppCaptureImpl3_XAppCaptureTakeDiagnosticScreenshot(IXAppCaptureImpl3* This,BOOLEAN gamescreenOnly,XAppCaptureScreenshotFormatFlag captureFlags,const char *filenamePrefix,XAppCaptureDiagnosticScreenshotResult *result) {
    return This->lpVtbl->XAppCaptureTakeDiagnosticScreenshot(This,gamescreenOnly,captureFlags,filenamePrefix,result);
}
static inline HRESULT IXAppCaptureImpl3_XAppCaptureRecordDiagnosticClip(IXAppCaptureImpl3* This,time_t startTime,UINT32 durationInMs,const char *filenamePrefix,XAppCaptureRecordClipResult *result) {
    return This->lpVtbl->XAppCaptureRecordDiagnosticClip(This,startTime,durationInMs,filenamePrefix,result);
}
static inline HRESULT IXAppCaptureImpl3_XAppCaptureTakeScreenshot(IXAppCaptureImpl3* This,XUserHandle requestingUser,XAppCaptureTakeScreenshotResult *result) {
    return This->lpVtbl->XAppCaptureTakeScreenshot(This,requestingUser,result);
}
static inline HRESULT IXAppCaptureImpl3_XAppCaptureOpenScreenshotStream(IXAppCaptureImpl3* This,const char *localId,XAppCaptureScreenshotFormatFlag screenshotFormat,XAppCaptureScreenshotStreamHandle *handle,UINT64 *totalBytes) {
    return This->lpVtbl->XAppCaptureOpenScreenshotStream(This,localId,screenshotFormat,handle,totalBytes);
}
static inline HRESULT IXAppCaptureImpl3_XAppCaptureReadScreenshotStream(IXAppCaptureImpl3* This,XAppCaptureScreenshotStreamHandle handle,UINT64 startPosition,UINT32 bytesToRead,UINT8 *buffer,UINT32 *bytesWritten) {
    return This->lpVtbl->XAppCaptureReadScreenshotStream(This,handle,startPosition,bytesToRead,buffer,bytesWritten);
}
static inline HRESULT IXAppCaptureImpl3_XAppCaptureCloseScreenshotStream(IXAppCaptureImpl3* This,XAppCaptureScreenshotStreamHandle handle) {
    return This->lpVtbl->XAppCaptureCloseScreenshotStream(This,handle);
}
static inline HRESULT IXAppCaptureImpl3_XAppCaptureEnableRecord(IXAppCaptureImpl3* This) {
    return This->lpVtbl->XAppCaptureEnableRecord(This);
}
static inline HRESULT IXAppCaptureImpl3_XAppCaptureDisableRecord(IXAppCaptureImpl3* This) {
    return This->lpVtbl->XAppCaptureDisableRecord(This);
}
/*** IXAppCaptureImpl2 methods ***/
static inline HRESULT IXAppCaptureImpl3_XAppCaptureGetVideoCaptureSettings(IXAppCaptureImpl3* This,XAppCaptureVideoCaptureSettings *userCaptureSettings) {
    return This->lpVtbl->XAppCaptureGetVideoCaptureSettings(This,userCaptureSettings);
}
static inline HRESULT IXAppCaptureImpl3_XAppCaptureRecordTimespan(IXAppCaptureImpl3* This,const SYSTEMTIME *startTimestamp,UINT64 durationInMilliseconds,XAppCaptureLocalResult *result) {
    return This->lpVtbl->XAppCaptureRecordTimespan(This,startTimestamp,durationInMilliseconds,result);
}
static inline HRESULT IXAppCaptureImpl3_XAppCaptureReadLocalStream(IXAppCaptureImpl3* This,XAppCaptureLocalStreamHandle handle,SIZE_T startPosition,UINT32 bytesToRead,UINT8 *buffer,UINT32 *bytesWritten) {
    return This->lpVtbl->XAppCaptureReadLocalStream(This,handle,startPosition,bytesToRead,buffer,bytesWritten);
}
static inline HRESULT IXAppCaptureImpl3_XAppCaptureCloseLocalStream(IXAppCaptureImpl3* This,XAppCaptureLocalStreamHandle handle) {
    return This->lpVtbl->XAppCaptureCloseLocalStream(This,handle);
}
/*** IXAppCaptureImpl3 methods ***/
static inline HRESULT IXAppCaptureImpl3_XAppCaptureStartUserRecord(IXAppCaptureImpl3* This,XUserHandle requestingUser,UINT32 localIdBufferLength,char *localIdBuffer) {
    return This->lpVtbl->XAppCaptureStartUserRecord(This,requestingUser,localIdBufferLength,localIdBuffer);
}
static inline HRESULT IXAppCaptureImpl3_XAppCaptureStopUserRecord(IXAppCaptureImpl3* This,const char *localId,XAppCaptureUserRecordingResult *result) {
    return This->lpVtbl->XAppCaptureStopUserRecord(This,localId,result);
}
#endif
#endif

#endif


#endif  /* __IXAppCaptureImpl3_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IXAppCaptureImpl4 interface
 */
#ifndef __IXAppCaptureImpl4_INTERFACE_DEFINED__
#define __IXAppCaptureImpl4_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXAppCaptureImpl4, 0x22e672d7, 0xb4e3, 0x406c, 0xbd,0x50, 0x8f,0x0d,0x25,0x23,0x6f,0x9e);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("22e672d7-b4e3-406c-bd50-8f0d25236f9e")
IXAppCaptureImpl4 : public IXAppCaptureImpl3
{
    virtual HRESULT STDMETHODCALLTYPE XAppCaptureCancelUserRecord(
        const char *localId) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXAppCaptureImpl4, 0x22e672d7, 0xb4e3, 0x406c, 0xbd,0x50, 0x8f,0x0d,0x25,0x23,0x6f,0x9e)
#endif
#else
typedef struct IXAppCaptureImpl4Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXAppCaptureImpl4 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXAppCaptureImpl4 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXAppCaptureImpl4 *This);

    /*** IXAppCaptureImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XAppCaptureTakeDiagnosticScreenshot)(
        IXAppCaptureImpl4 *This,
        BOOLEAN gamescreenOnly,
        XAppCaptureScreenshotFormatFlag captureFlags,
        const char *filenamePrefix,
        XAppCaptureDiagnosticScreenshotResult *result);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureRecordDiagnosticClip)(
        IXAppCaptureImpl4 *This,
        time_t startTime,
        UINT32 durationInMs,
        const char *filenamePrefix,
        XAppCaptureRecordClipResult *result);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureTakeScreenshot)(
        IXAppCaptureImpl4 *This,
        XUserHandle requestingUser,
        XAppCaptureTakeScreenshotResult *result);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureOpenScreenshotStream)(
        IXAppCaptureImpl4 *This,
        const char *localId,
        XAppCaptureScreenshotFormatFlag screenshotFormat,
        XAppCaptureScreenshotStreamHandle *handle,
        UINT64 *totalBytes);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureReadScreenshotStream)(
        IXAppCaptureImpl4 *This,
        XAppCaptureScreenshotStreamHandle handle,
        UINT64 startPosition,
        UINT32 bytesToRead,
        UINT8 *buffer,
        UINT32 *bytesWritten);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureCloseScreenshotStream)(
        IXAppCaptureImpl4 *This,
        XAppCaptureScreenshotStreamHandle handle);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureEnableRecord)(
        IXAppCaptureImpl4 *This);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureDisableRecord)(
        IXAppCaptureImpl4 *This);

    /*** IXAppCaptureImpl2 methods ***/
    HRESULT (STDMETHODCALLTYPE *XAppCaptureGetVideoCaptureSettings)(
        IXAppCaptureImpl4 *This,
        XAppCaptureVideoCaptureSettings *userCaptureSettings);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureRecordTimespan)(
        IXAppCaptureImpl4 *This,
        const SYSTEMTIME *startTimestamp,
        UINT64 durationInMilliseconds,
        XAppCaptureLocalResult *result);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureReadLocalStream)(
        IXAppCaptureImpl4 *This,
        XAppCaptureLocalStreamHandle handle,
        SIZE_T startPosition,
        UINT32 bytesToRead,
        UINT8 *buffer,
        UINT32 *bytesWritten);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureCloseLocalStream)(
        IXAppCaptureImpl4 *This,
        XAppCaptureLocalStreamHandle handle);

    /*** IXAppCaptureImpl3 methods ***/
    HRESULT (STDMETHODCALLTYPE *XAppCaptureStartUserRecord)(
        IXAppCaptureImpl4 *This,
        XUserHandle requestingUser,
        UINT32 localIdBufferLength,
        char *localIdBuffer);

    HRESULT (STDMETHODCALLTYPE *XAppCaptureStopUserRecord)(
        IXAppCaptureImpl4 *This,
        const char *localId,
        XAppCaptureUserRecordingResult *result);

    /*** IXAppCaptureImpl4 methods ***/
    HRESULT (STDMETHODCALLTYPE *XAppCaptureCancelUserRecord)(
        IXAppCaptureImpl4 *This,
        const char *localId);

    END_INTERFACE
} IXAppCaptureImpl4Vtbl;

interface IXAppCaptureImpl4 {
    CONST_VTBL IXAppCaptureImpl4Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXAppCaptureImpl4_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXAppCaptureImpl4_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXAppCaptureImpl4_Release(This) (This)->lpVtbl->Release(This)
/*** IXAppCaptureImpl methods ***/
#define IXAppCaptureImpl4_XAppCaptureTakeDiagnosticScreenshot(This,gamescreenOnly,captureFlags,filenamePrefix,result) (This)->lpVtbl->XAppCaptureTakeDiagnosticScreenshot(This,gamescreenOnly,captureFlags,filenamePrefix,result)
#define IXAppCaptureImpl4_XAppCaptureRecordDiagnosticClip(This,startTime,durationInMs,filenamePrefix,result) (This)->lpVtbl->XAppCaptureRecordDiagnosticClip(This,startTime,durationInMs,filenamePrefix,result)
#define IXAppCaptureImpl4_XAppCaptureTakeScreenshot(This,requestingUser,result) (This)->lpVtbl->XAppCaptureTakeScreenshot(This,requestingUser,result)
#define IXAppCaptureImpl4_XAppCaptureOpenScreenshotStream(This,localId,screenshotFormat,handle,totalBytes) (This)->lpVtbl->XAppCaptureOpenScreenshotStream(This,localId,screenshotFormat,handle,totalBytes)
#define IXAppCaptureImpl4_XAppCaptureReadScreenshotStream(This,handle,startPosition,bytesToRead,buffer,bytesWritten) (This)->lpVtbl->XAppCaptureReadScreenshotStream(This,handle,startPosition,bytesToRead,buffer,bytesWritten)
#define IXAppCaptureImpl4_XAppCaptureCloseScreenshotStream(This,handle) (This)->lpVtbl->XAppCaptureCloseScreenshotStream(This,handle)
#define IXAppCaptureImpl4_XAppCaptureEnableRecord(This) (This)->lpVtbl->XAppCaptureEnableRecord(This)
#define IXAppCaptureImpl4_XAppCaptureDisableRecord(This) (This)->lpVtbl->XAppCaptureDisableRecord(This)
/*** IXAppCaptureImpl2 methods ***/
#define IXAppCaptureImpl4_XAppCaptureGetVideoCaptureSettings(This,userCaptureSettings) (This)->lpVtbl->XAppCaptureGetVideoCaptureSettings(This,userCaptureSettings)
#define IXAppCaptureImpl4_XAppCaptureRecordTimespan(This,startTimestamp,durationInMilliseconds,result) (This)->lpVtbl->XAppCaptureRecordTimespan(This,startTimestamp,durationInMilliseconds,result)
#define IXAppCaptureImpl4_XAppCaptureReadLocalStream(This,handle,startPosition,bytesToRead,buffer,bytesWritten) (This)->lpVtbl->XAppCaptureReadLocalStream(This,handle,startPosition,bytesToRead,buffer,bytesWritten)
#define IXAppCaptureImpl4_XAppCaptureCloseLocalStream(This,handle) (This)->lpVtbl->XAppCaptureCloseLocalStream(This,handle)
/*** IXAppCaptureImpl3 methods ***/
#define IXAppCaptureImpl4_XAppCaptureStartUserRecord(This,requestingUser,localIdBufferLength,localIdBuffer) (This)->lpVtbl->XAppCaptureStartUserRecord(This,requestingUser,localIdBufferLength,localIdBuffer)
#define IXAppCaptureImpl4_XAppCaptureStopUserRecord(This,localId,result) (This)->lpVtbl->XAppCaptureStopUserRecord(This,localId,result)
/*** IXAppCaptureImpl4 methods ***/
#define IXAppCaptureImpl4_XAppCaptureCancelUserRecord(This,localId) (This)->lpVtbl->XAppCaptureCancelUserRecord(This,localId)
#else
/*** IUnknown methods ***/
static inline HRESULT IXAppCaptureImpl4_QueryInterface(IXAppCaptureImpl4* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXAppCaptureImpl4_AddRef(IXAppCaptureImpl4* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXAppCaptureImpl4_Release(IXAppCaptureImpl4* This) {
    return This->lpVtbl->Release(This);
}
/*** IXAppCaptureImpl methods ***/
static inline HRESULT IXAppCaptureImpl4_XAppCaptureTakeDiagnosticScreenshot(IXAppCaptureImpl4* This,BOOLEAN gamescreenOnly,XAppCaptureScreenshotFormatFlag captureFlags,const char *filenamePrefix,XAppCaptureDiagnosticScreenshotResult *result) {
    return This->lpVtbl->XAppCaptureTakeDiagnosticScreenshot(This,gamescreenOnly,captureFlags,filenamePrefix,result);
}
static inline HRESULT IXAppCaptureImpl4_XAppCaptureRecordDiagnosticClip(IXAppCaptureImpl4* This,time_t startTime,UINT32 durationInMs,const char *filenamePrefix,XAppCaptureRecordClipResult *result) {
    return This->lpVtbl->XAppCaptureRecordDiagnosticClip(This,startTime,durationInMs,filenamePrefix,result);
}
static inline HRESULT IXAppCaptureImpl4_XAppCaptureTakeScreenshot(IXAppCaptureImpl4* This,XUserHandle requestingUser,XAppCaptureTakeScreenshotResult *result) {
    return This->lpVtbl->XAppCaptureTakeScreenshot(This,requestingUser,result);
}
static inline HRESULT IXAppCaptureImpl4_XAppCaptureOpenScreenshotStream(IXAppCaptureImpl4* This,const char *localId,XAppCaptureScreenshotFormatFlag screenshotFormat,XAppCaptureScreenshotStreamHandle *handle,UINT64 *totalBytes) {
    return This->lpVtbl->XAppCaptureOpenScreenshotStream(This,localId,screenshotFormat,handle,totalBytes);
}
static inline HRESULT IXAppCaptureImpl4_XAppCaptureReadScreenshotStream(IXAppCaptureImpl4* This,XAppCaptureScreenshotStreamHandle handle,UINT64 startPosition,UINT32 bytesToRead,UINT8 *buffer,UINT32 *bytesWritten) {
    return This->lpVtbl->XAppCaptureReadScreenshotStream(This,handle,startPosition,bytesToRead,buffer,bytesWritten);
}
static inline HRESULT IXAppCaptureImpl4_XAppCaptureCloseScreenshotStream(IXAppCaptureImpl4* This,XAppCaptureScreenshotStreamHandle handle) {
    return This->lpVtbl->XAppCaptureCloseScreenshotStream(This,handle);
}
static inline HRESULT IXAppCaptureImpl4_XAppCaptureEnableRecord(IXAppCaptureImpl4* This) {
    return This->lpVtbl->XAppCaptureEnableRecord(This);
}
static inline HRESULT IXAppCaptureImpl4_XAppCaptureDisableRecord(IXAppCaptureImpl4* This) {
    return This->lpVtbl->XAppCaptureDisableRecord(This);
}
/*** IXAppCaptureImpl2 methods ***/
static inline HRESULT IXAppCaptureImpl4_XAppCaptureGetVideoCaptureSettings(IXAppCaptureImpl4* This,XAppCaptureVideoCaptureSettings *userCaptureSettings) {
    return This->lpVtbl->XAppCaptureGetVideoCaptureSettings(This,userCaptureSettings);
}
static inline HRESULT IXAppCaptureImpl4_XAppCaptureRecordTimespan(IXAppCaptureImpl4* This,const SYSTEMTIME *startTimestamp,UINT64 durationInMilliseconds,XAppCaptureLocalResult *result) {
    return This->lpVtbl->XAppCaptureRecordTimespan(This,startTimestamp,durationInMilliseconds,result);
}
static inline HRESULT IXAppCaptureImpl4_XAppCaptureReadLocalStream(IXAppCaptureImpl4* This,XAppCaptureLocalStreamHandle handle,SIZE_T startPosition,UINT32 bytesToRead,UINT8 *buffer,UINT32 *bytesWritten) {
    return This->lpVtbl->XAppCaptureReadLocalStream(This,handle,startPosition,bytesToRead,buffer,bytesWritten);
}
static inline HRESULT IXAppCaptureImpl4_XAppCaptureCloseLocalStream(IXAppCaptureImpl4* This,XAppCaptureLocalStreamHandle handle) {
    return This->lpVtbl->XAppCaptureCloseLocalStream(This,handle);
}
/*** IXAppCaptureImpl3 methods ***/
static inline HRESULT IXAppCaptureImpl4_XAppCaptureStartUserRecord(IXAppCaptureImpl4* This,XUserHandle requestingUser,UINT32 localIdBufferLength,char *localIdBuffer) {
    return This->lpVtbl->XAppCaptureStartUserRecord(This,requestingUser,localIdBufferLength,localIdBuffer);
}
static inline HRESULT IXAppCaptureImpl4_XAppCaptureStopUserRecord(IXAppCaptureImpl4* This,const char *localId,XAppCaptureUserRecordingResult *result) {
    return This->lpVtbl->XAppCaptureStopUserRecord(This,localId,result);
}
/*** IXAppCaptureImpl4 methods ***/
static inline HRESULT IXAppCaptureImpl4_XAppCaptureCancelUserRecord(IXAppCaptureImpl4* This,const char *localId) {
    return This->lpVtbl->XAppCaptureCancelUserRecord(This,localId);
}
#endif
#endif

#endif


#endif  /* __IXAppCaptureImpl4_INTERFACE_DEFINED__ */

/*****************************************************************************
 * XAppCaptureMetadataImpl coclass
 */

DEFINE_GUID(CLSID_XAppCaptureMetadataImpl, 0x186d5592, 0xa72d, 0x45fb, 0x95,0x60, 0x11,0xae,0xd0,0xe6,0x64,0x7a);

#ifdef __cplusplus
class DECLSPEC_UUID("186d5592-a72d-45fb-9560-11aed0e6647a") XAppCaptureMetadataImpl;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(XAppCaptureMetadataImpl, 0x186d5592, 0xa72d, 0x45fb, 0x95,0x60, 0x11,0xae,0xd0,0xe6,0x64,0x7a)
#endif
#endif

/*****************************************************************************
 * XAppCaptureImpl coclass
 */

DEFINE_GUID(CLSID_XAppCaptureImpl, 0xa4f1aee2, 0x4bf1, 0x4485, 0xb0,0x08, 0xa7,0xc2,0x6d,0x52,0xac,0x27);

#ifdef __cplusplus
class DECLSPEC_UUID("a4f1aee2-4bf1-4485-b008-a7c26d52ac27") XAppCaptureImpl;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(XAppCaptureImpl, 0xa4f1aee2, 0x4bf1, 0x4485, 0xb0,0x08, 0xa7,0xc2,0x6d,0x52,0xac,0x27)
#endif
#endif

#endif
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __xappcapture_h__ */
