/*** Autogenerated by WIDL 11.15 from xasyncprovider.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __xasyncprovider_h__
#define __xasyncprovider_h__

/* Forward declarations */

#ifndef __IXThreadingImpl_FWD_DEFINED__
#define __IXThreadingImpl_FWD_DEFINED__
typedef interface IXThreadingImpl IXThreadingImpl;
#ifdef __cplusplus
interface IXThreadingImpl;
#endif /* __cplusplus */
#endif

#ifndef __XThreadingImpl_FWD_DEFINED__
#define __XThreadingImpl_FWD_DEFINED__
#ifdef __cplusplus
typedef class XThreadingImpl XThreadingImpl;
#else
typedef struct XThreadingImpl XThreadingImpl;
#endif /* defined __cplusplus */
#endif /* defined __XThreadingImpl_FWD_DEFINED__ */

/* Headers for imported files */

#include <unknwn.h>
#include <xasync.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
enum class XAsyncOp : UINT32
{                           
    Begin,                  
    DoWork,                 
    GetResult,              
    Cancel,                 
    Cleanup,                
};                          
#elif defined(__WINESRC__)
typedef enum XAsyncOp {
    XAsyncOp_Begin = 0,
    XAsyncOp_DoWork = 1,
    XAsyncOp_GetResult = 2,
    XAsyncOp_Cancel = 3,
    XAsyncOp_Cleanup = 4
} XAsyncOp;
#endif
typedef struct XAsyncProviderData XAsyncProviderData;
typedef HRESULT __stdcall  XAsyncProvider(XAsyncOp op,const XAsyncProviderData *data);
struct XAsyncProviderData {
    XAsyncBlock *async;
    SIZE_T bufferSize;
    void *buffer;
    void *context;
};
#ifdef __WINESRC__
/*****************************************************************************
 * IXThreadingImpl interface
 */
#ifndef __IXThreadingImpl_INTERFACE_DEFINED__
#define __IXThreadingImpl_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXThreadingImpl, 0x073b7dcb, 0x1fcf, 0x4030, 0x94,0xbe, 0xe3,0xc9,0xeb,0x62,0x34,0x28);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("073b7dcb-1fcf-4030-94be-e3c9eb623428")
IXThreadingImpl : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE XAsyncGetStatus(
        XAsyncBlock *asyncBlock,
        BOOLEAN wait) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAsyncGetResultSize(
        XAsyncBlock *asyncBlock,
        SIZE_T *bufferSize) = 0;

    virtual void STDMETHODCALLTYPE XAsyncCancel(
        XAsyncBlock *asyncBlock) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAsyncRun(
        XAsyncBlock *asyncBlock,
        XAsyncWork *work) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAsyncBegin(
        XAsyncBlock *asyncBlock,
        void *context,
        const void *identity,
        const char *identityName,
        XAsyncProvider *provider) = 0;

    virtual HRESULT STDMETHODCALLTYPE __PADDING__(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAsyncSchedule(
        XAsyncBlock *asyncBlock,
        UINT32 delayInMs) = 0;

    virtual void STDMETHODCALLTYPE XAsyncComplete(
        XAsyncBlock *asyncBlock,
        HRESULT result,
        SIZE_T requiredBufferSize) = 0;

    virtual HRESULT STDMETHODCALLTYPE XAsyncGetResult(
        XAsyncBlock *asyncBlock,
        const void *identity,
        SIZE_T bufferSize,
        void *buffer,
        SIZE_T *bufferUsed) = 0;

    virtual HRESULT STDMETHODCALLTYPE XTaskQueueCreate(
        XTaskQueueDispatchMode workDispatchMode,
        XTaskQueueDispatchMode completionDispatchMode,
        XTaskQueueHandle *queue) = 0;

    virtual HRESULT STDMETHODCALLTYPE XTaskQueueCreateComposite(
        XTaskQueuePortHandle workPort,
        XTaskQueuePortHandle completionPort,
        XTaskQueueHandle *queue) = 0;

    virtual HRESULT STDMETHODCALLTYPE XTaskQueueGetPort(
        XTaskQueueHandle queue,
        XTaskQueuePort port,
        XTaskQueuePortHandle *portHandle) = 0;

    virtual HRESULT STDMETHODCALLTYPE XTaskQueueDuplicateHandle(
        XTaskQueueHandle queueHandle,
        XTaskQueueHandle *duplicatedHandle) = 0;

    virtual BOOLEAN STDMETHODCALLTYPE XTaskQueueDispatch(
        XTaskQueueHandle queue,
        XTaskQueuePort port,
        UINT32 timeoutInMs) = 0;

    virtual void STDMETHODCALLTYPE XTaskQueueCloseHandle(
        XTaskQueueHandle queue) = 0;

    virtual HRESULT STDMETHODCALLTYPE XTaskQueueSubmitCallback(
        XTaskQueueHandle queue,
        XTaskQueuePort port,
        void *callbackContext,
        XTaskQueueCallback *callback) = 0;

    virtual HRESULT STDMETHODCALLTYPE XTaskQueueSubmitDelayedCallback(
        XTaskQueueHandle queue,
        XTaskQueuePort port,
        UINT32 delayMs,
        void *callbackContext,
        XTaskQueueCallback *callback) = 0;

    virtual HRESULT STDMETHODCALLTYPE XTaskQueueRegisterWaiter(
        XTaskQueueHandle queue,
        XTaskQueuePort port,
        HANDLE waitHandle,
        void *callbackContext,
        XTaskQueueCallback *callback,
        XTaskQueueRegistrationToken *token) = 0;

    virtual void STDMETHODCALLTYPE XTaskQueueUnregisterWaiter(
        XTaskQueueHandle queue,
        XTaskQueueRegistrationToken token) = 0;

    virtual HRESULT STDMETHODCALLTYPE XTaskQueueTerminate(
        XTaskQueueHandle queue,
        BOOLEAN wait,
        void *callbackContext,
        XTaskQueueTerminatedCallback *callback) = 0;

    virtual HRESULT STDMETHODCALLTYPE XTaskQueueRegisterMonitor(
        XTaskQueueHandle queue,
        void *callbackContext,
        XTaskQueueMonitorCallback *callback,
        XTaskQueueRegistrationToken *token) = 0;

    virtual void STDMETHODCALLTYPE XTaskQueueUnregisterMonitor(
        XTaskQueueHandle queue,
        XTaskQueueRegistrationToken token) = 0;

    virtual BOOLEAN STDMETHODCALLTYPE XTaskQueueGetCurrentProcessTaskQueue(
        XTaskQueueHandle *queue) = 0;

    virtual void STDMETHODCALLTYPE XTaskQueueSetCurrentProcessTaskQueue(
        XTaskQueueHandle queue) = 0;

    virtual HRESULT STDMETHODCALLTYPE XThreadSetTimeSensitive(
        BOOLEAN isTimeSensitiveThread) = 0;

    virtual HRESULT STDMETHODCALLTYPE __PADDING_2__(
        ) = 0;

    virtual void STDMETHODCALLTYPE XThreadAssertNotTimeSensitive(
        ) = 0;

    virtual BOOLEAN STDMETHODCALLTYPE XThreadIsTimeSensitive(
        ) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXThreadingImpl, 0x073b7dcb, 0x1fcf, 0x4030, 0x94,0xbe, 0xe3,0xc9,0xeb,0x62,0x34,0x28)
#endif
#else
typedef struct IXThreadingImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXThreadingImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXThreadingImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXThreadingImpl *This);

    /*** IXThreadingImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XAsyncGetStatus)(
        IXThreadingImpl *This,
        XAsyncBlock *asyncBlock,
        BOOLEAN wait);

    HRESULT (STDMETHODCALLTYPE *XAsyncGetResultSize)(
        IXThreadingImpl *This,
        XAsyncBlock *asyncBlock,
        SIZE_T *bufferSize);

    void (STDMETHODCALLTYPE *XAsyncCancel)(
        IXThreadingImpl *This,
        XAsyncBlock *asyncBlock);

    HRESULT (STDMETHODCALLTYPE *XAsyncRun)(
        IXThreadingImpl *This,
        XAsyncBlock *asyncBlock,
        XAsyncWork *work);

    HRESULT (STDMETHODCALLTYPE *XAsyncBegin)(
        IXThreadingImpl *This,
        XAsyncBlock *asyncBlock,
        void *context,
        const void *identity,
        const char *identityName,
        XAsyncProvider *provider);

    HRESULT (STDMETHODCALLTYPE *__PADDING__)(
        IXThreadingImpl *This);

    HRESULT (STDMETHODCALLTYPE *XAsyncSchedule)(
        IXThreadingImpl *This,
        XAsyncBlock *asyncBlock,
        UINT32 delayInMs);

    void (STDMETHODCALLTYPE *XAsyncComplete)(
        IXThreadingImpl *This,
        XAsyncBlock *asyncBlock,
        HRESULT result,
        SIZE_T requiredBufferSize);

    HRESULT (STDMETHODCALLTYPE *XAsyncGetResult)(
        IXThreadingImpl *This,
        XAsyncBlock *asyncBlock,
        const void *identity,
        SIZE_T bufferSize,
        void *buffer,
        SIZE_T *bufferUsed);

    HRESULT (STDMETHODCALLTYPE *XTaskQueueCreate)(
        IXThreadingImpl *This,
        XTaskQueueDispatchMode workDispatchMode,
        XTaskQueueDispatchMode completionDispatchMode,
        XTaskQueueHandle *queue);

    HRESULT (STDMETHODCALLTYPE *XTaskQueueCreateComposite)(
        IXThreadingImpl *This,
        XTaskQueuePortHandle workPort,
        XTaskQueuePortHandle completionPort,
        XTaskQueueHandle *queue);

    HRESULT (STDMETHODCALLTYPE *XTaskQueueGetPort)(
        IXThreadingImpl *This,
        XTaskQueueHandle queue,
        XTaskQueuePort port,
        XTaskQueuePortHandle *portHandle);

    HRESULT (STDMETHODCALLTYPE *XTaskQueueDuplicateHandle)(
        IXThreadingImpl *This,
        XTaskQueueHandle queueHandle,
        XTaskQueueHandle *duplicatedHandle);

    BOOLEAN (STDMETHODCALLTYPE *XTaskQueueDispatch)(
        IXThreadingImpl *This,
        XTaskQueueHandle queue,
        XTaskQueuePort port,
        UINT32 timeoutInMs);

    void (STDMETHODCALLTYPE *XTaskQueueCloseHandle)(
        IXThreadingImpl *This,
        XTaskQueueHandle queue);

    HRESULT (STDMETHODCALLTYPE *XTaskQueueSubmitCallback)(
        IXThreadingImpl *This,
        XTaskQueueHandle queue,
        XTaskQueuePort port,
        void *callbackContext,
        XTaskQueueCallback *callback);

    HRESULT (STDMETHODCALLTYPE *XTaskQueueSubmitDelayedCallback)(
        IXThreadingImpl *This,
        XTaskQueueHandle queue,
        XTaskQueuePort port,
        UINT32 delayMs,
        void *callbackContext,
        XTaskQueueCallback *callback);

    HRESULT (STDMETHODCALLTYPE *XTaskQueueRegisterWaiter)(
        IXThreadingImpl *This,
        XTaskQueueHandle queue,
        XTaskQueuePort port,
        HANDLE waitHandle,
        void *callbackContext,
        XTaskQueueCallback *callback,
        XTaskQueueRegistrationToken *token);

    void (STDMETHODCALLTYPE *XTaskQueueUnregisterWaiter)(
        IXThreadingImpl *This,
        XTaskQueueHandle queue,
        XTaskQueueRegistrationToken token);

    HRESULT (STDMETHODCALLTYPE *XTaskQueueTerminate)(
        IXThreadingImpl *This,
        XTaskQueueHandle queue,
        BOOLEAN wait,
        void *callbackContext,
        XTaskQueueTerminatedCallback *callback);

    HRESULT (STDMETHODCALLTYPE *XTaskQueueRegisterMonitor)(
        IXThreadingImpl *This,
        XTaskQueueHandle queue,
        void *callbackContext,
        XTaskQueueMonitorCallback *callback,
        XTaskQueueRegistrationToken *token);

    void (STDMETHODCALLTYPE *XTaskQueueUnregisterMonitor)(
        IXThreadingImpl *This,
        XTaskQueueHandle queue,
        XTaskQueueRegistrationToken token);

    BOOLEAN (STDMETHODCALLTYPE *XTaskQueueGetCurrentProcessTaskQueue)(
        IXThreadingImpl *This,
        XTaskQueueHandle *queue);

    void (STDMETHODCALLTYPE *XTaskQueueSetCurrentProcessTaskQueue)(
        IXThreadingImpl *This,
        XTaskQueueHandle queue);

    HRESULT (STDMETHODCALLTYPE *XThreadSetTimeSensitive)(
        IXThreadingImpl *This,
        BOOLEAN isTimeSensitiveThread);

    HRESULT (STDMETHODCALLTYPE *__PADDING_2__)(
        IXThreadingImpl *This);

    void (STDMETHODCALLTYPE *XThreadAssertNotTimeSensitive)(
        IXThreadingImpl *This);

    BOOLEAN (STDMETHODCALLTYPE *XThreadIsTimeSensitive)(
        IXThreadingImpl *This);

    END_INTERFACE
} IXThreadingImplVtbl;

interface IXThreadingImpl {
    CONST_VTBL IXThreadingImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXThreadingImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXThreadingImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXThreadingImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IXThreadingImpl methods ***/
#define IXThreadingImpl_XAsyncGetStatus(This,asyncBlock,wait) (This)->lpVtbl->XAsyncGetStatus(This,asyncBlock,wait)
#define IXThreadingImpl_XAsyncGetResultSize(This,asyncBlock,bufferSize) (This)->lpVtbl->XAsyncGetResultSize(This,asyncBlock,bufferSize)
#define IXThreadingImpl_XAsyncCancel(This,asyncBlock) (This)->lpVtbl->XAsyncCancel(This,asyncBlock)
#define IXThreadingImpl_XAsyncRun(This,asyncBlock,work) (This)->lpVtbl->XAsyncRun(This,asyncBlock,work)
#define IXThreadingImpl_XAsyncBegin(This,asyncBlock,context,identity,identityName,provider) (This)->lpVtbl->XAsyncBegin(This,asyncBlock,context,identity,identityName,provider)
#define IXThreadingImpl___PADDING__(This) (This)->lpVtbl->__PADDING__(This)
#define IXThreadingImpl_XAsyncSchedule(This,asyncBlock,delayInMs) (This)->lpVtbl->XAsyncSchedule(This,asyncBlock,delayInMs)
#define IXThreadingImpl_XAsyncComplete(This,asyncBlock,result,requiredBufferSize) (This)->lpVtbl->XAsyncComplete(This,asyncBlock,result,requiredBufferSize)
#define IXThreadingImpl_XAsyncGetResult(This,asyncBlock,identity,bufferSize,buffer,bufferUsed) (This)->lpVtbl->XAsyncGetResult(This,asyncBlock,identity,bufferSize,buffer,bufferUsed)
#define IXThreadingImpl_XTaskQueueCreate(This,workDispatchMode,completionDispatchMode,queue) (This)->lpVtbl->XTaskQueueCreate(This,workDispatchMode,completionDispatchMode,queue)
#define IXThreadingImpl_XTaskQueueCreateComposite(This,workPort,completionPort,queue) (This)->lpVtbl->XTaskQueueCreateComposite(This,workPort,completionPort,queue)
#define IXThreadingImpl_XTaskQueueGetPort(This,queue,port,portHandle) (This)->lpVtbl->XTaskQueueGetPort(This,queue,port,portHandle)
#define IXThreadingImpl_XTaskQueueDuplicateHandle(This,queueHandle,duplicatedHandle) (This)->lpVtbl->XTaskQueueDuplicateHandle(This,queueHandle,duplicatedHandle)
#define IXThreadingImpl_XTaskQueueDispatch(This,queue,port,timeoutInMs) (This)->lpVtbl->XTaskQueueDispatch(This,queue,port,timeoutInMs)
#define IXThreadingImpl_XTaskQueueCloseHandle(This,queue) (This)->lpVtbl->XTaskQueueCloseHandle(This,queue)
#define IXThreadingImpl_XTaskQueueSubmitCallback(This,queue,port,callbackContext,callback) (This)->lpVtbl->XTaskQueueSubmitCallback(This,queue,port,callbackContext,callback)
#define IXThreadingImpl_XTaskQueueSubmitDelayedCallback(This,queue,port,delayMs,callbackContext,callback) (This)->lpVtbl->XTaskQueueSubmitDelayedCallback(This,queue,port,delayMs,callbackContext,callback)
#define IXThreadingImpl_XTaskQueueRegisterWaiter(This,queue,port,waitHandle,callbackContext,callback,token) (This)->lpVtbl->XTaskQueueRegisterWaiter(This,queue,port,waitHandle,callbackContext,callback,token)
#define IXThreadingImpl_XTaskQueueUnregisterWaiter(This,queue,token) (This)->lpVtbl->XTaskQueueUnregisterWaiter(This,queue,token)
#define IXThreadingImpl_XTaskQueueTerminate(This,queue,wait,callbackContext,callback) (This)->lpVtbl->XTaskQueueTerminate(This,queue,wait,callbackContext,callback)
#define IXThreadingImpl_XTaskQueueRegisterMonitor(This,queue,callbackContext,callback,token) (This)->lpVtbl->XTaskQueueRegisterMonitor(This,queue,callbackContext,callback,token)
#define IXThreadingImpl_XTaskQueueUnregisterMonitor(This,queue,token) (This)->lpVtbl->XTaskQueueUnregisterMonitor(This,queue,token)
#define IXThreadingImpl_XTaskQueueGetCurrentProcessTaskQueue(This,queue) (This)->lpVtbl->XTaskQueueGetCurrentProcessTaskQueue(This,queue)
#define IXThreadingImpl_XTaskQueueSetCurrentProcessTaskQueue(This,queue) (This)->lpVtbl->XTaskQueueSetCurrentProcessTaskQueue(This,queue)
#define IXThreadingImpl_XThreadSetTimeSensitive(This,isTimeSensitiveThread) (This)->lpVtbl->XThreadSetTimeSensitive(This,isTimeSensitiveThread)
#define IXThreadingImpl___PADDING_2__(This) (This)->lpVtbl->__PADDING_2__(This)
#define IXThreadingImpl_XThreadAssertNotTimeSensitive(This) (This)->lpVtbl->XThreadAssertNotTimeSensitive(This)
#define IXThreadingImpl_XThreadIsTimeSensitive(This) (This)->lpVtbl->XThreadIsTimeSensitive(This)
#else
/*** IUnknown methods ***/
static inline HRESULT IXThreadingImpl_QueryInterface(IXThreadingImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXThreadingImpl_AddRef(IXThreadingImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXThreadingImpl_Release(IXThreadingImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IXThreadingImpl methods ***/
static inline HRESULT IXThreadingImpl_XAsyncGetStatus(IXThreadingImpl* This,XAsyncBlock *asyncBlock,BOOLEAN wait) {
    return This->lpVtbl->XAsyncGetStatus(This,asyncBlock,wait);
}
static inline HRESULT IXThreadingImpl_XAsyncGetResultSize(IXThreadingImpl* This,XAsyncBlock *asyncBlock,SIZE_T *bufferSize) {
    return This->lpVtbl->XAsyncGetResultSize(This,asyncBlock,bufferSize);
}
static inline void IXThreadingImpl_XAsyncCancel(IXThreadingImpl* This,XAsyncBlock *asyncBlock) {
    This->lpVtbl->XAsyncCancel(This,asyncBlock);
}
static inline HRESULT IXThreadingImpl_XAsyncRun(IXThreadingImpl* This,XAsyncBlock *asyncBlock,XAsyncWork *work) {
    return This->lpVtbl->XAsyncRun(This,asyncBlock,work);
}
static inline HRESULT IXThreadingImpl_XAsyncBegin(IXThreadingImpl* This,XAsyncBlock *asyncBlock,void *context,const void *identity,const char *identityName,XAsyncProvider *provider) {
    return This->lpVtbl->XAsyncBegin(This,asyncBlock,context,identity,identityName,provider);
}
static inline HRESULT IXThreadingImpl___PADDING__(IXThreadingImpl* This) {
    return This->lpVtbl->__PADDING__(This);
}
static inline HRESULT IXThreadingImpl_XAsyncSchedule(IXThreadingImpl* This,XAsyncBlock *asyncBlock,UINT32 delayInMs) {
    return This->lpVtbl->XAsyncSchedule(This,asyncBlock,delayInMs);
}
static inline void IXThreadingImpl_XAsyncComplete(IXThreadingImpl* This,XAsyncBlock *asyncBlock,HRESULT result,SIZE_T requiredBufferSize) {
    This->lpVtbl->XAsyncComplete(This,asyncBlock,result,requiredBufferSize);
}
static inline HRESULT IXThreadingImpl_XAsyncGetResult(IXThreadingImpl* This,XAsyncBlock *asyncBlock,const void *identity,SIZE_T bufferSize,void *buffer,SIZE_T *bufferUsed) {
    return This->lpVtbl->XAsyncGetResult(This,asyncBlock,identity,bufferSize,buffer,bufferUsed);
}
static inline HRESULT IXThreadingImpl_XTaskQueueCreate(IXThreadingImpl* This,XTaskQueueDispatchMode workDispatchMode,XTaskQueueDispatchMode completionDispatchMode,XTaskQueueHandle *queue) {
    return This->lpVtbl->XTaskQueueCreate(This,workDispatchMode,completionDispatchMode,queue);
}
static inline HRESULT IXThreadingImpl_XTaskQueueCreateComposite(IXThreadingImpl* This,XTaskQueuePortHandle workPort,XTaskQueuePortHandle completionPort,XTaskQueueHandle *queue) {
    return This->lpVtbl->XTaskQueueCreateComposite(This,workPort,completionPort,queue);
}
static inline HRESULT IXThreadingImpl_XTaskQueueGetPort(IXThreadingImpl* This,XTaskQueueHandle queue,XTaskQueuePort port,XTaskQueuePortHandle *portHandle) {
    return This->lpVtbl->XTaskQueueGetPort(This,queue,port,portHandle);
}
static inline HRESULT IXThreadingImpl_XTaskQueueDuplicateHandle(IXThreadingImpl* This,XTaskQueueHandle queueHandle,XTaskQueueHandle *duplicatedHandle) {
    return This->lpVtbl->XTaskQueueDuplicateHandle(This,queueHandle,duplicatedHandle);
}
static inline BOOLEAN IXThreadingImpl_XTaskQueueDispatch(IXThreadingImpl* This,XTaskQueueHandle queue,XTaskQueuePort port,UINT32 timeoutInMs) {
    return This->lpVtbl->XTaskQueueDispatch(This,queue,port,timeoutInMs);
}
static inline void IXThreadingImpl_XTaskQueueCloseHandle(IXThreadingImpl* This,XTaskQueueHandle queue) {
    This->lpVtbl->XTaskQueueCloseHandle(This,queue);
}
static inline HRESULT IXThreadingImpl_XTaskQueueSubmitCallback(IXThreadingImpl* This,XTaskQueueHandle queue,XTaskQueuePort port,void *callbackContext,XTaskQueueCallback *callback) {
    return This->lpVtbl->XTaskQueueSubmitCallback(This,queue,port,callbackContext,callback);
}
static inline HRESULT IXThreadingImpl_XTaskQueueSubmitDelayedCallback(IXThreadingImpl* This,XTaskQueueHandle queue,XTaskQueuePort port,UINT32 delayMs,void *callbackContext,XTaskQueueCallback *callback) {
    return This->lpVtbl->XTaskQueueSubmitDelayedCallback(This,queue,port,delayMs,callbackContext,callback);
}
static inline HRESULT IXThreadingImpl_XTaskQueueRegisterWaiter(IXThreadingImpl* This,XTaskQueueHandle queue,XTaskQueuePort port,HANDLE waitHandle,void *callbackContext,XTaskQueueCallback *callback,XTaskQueueRegistrationToken *token) {
    return This->lpVtbl->XTaskQueueRegisterWaiter(This,queue,port,waitHandle,callbackContext,callback,token);
}
static inline void IXThreadingImpl_XTaskQueueUnregisterWaiter(IXThreadingImpl* This,XTaskQueueHandle queue,XTaskQueueRegistrationToken token) {
    This->lpVtbl->XTaskQueueUnregisterWaiter(This,queue,token);
}
static inline HRESULT IXThreadingImpl_XTaskQueueTerminate(IXThreadingImpl* This,XTaskQueueHandle queue,BOOLEAN wait,void *callbackContext,XTaskQueueTerminatedCallback *callback) {
    return This->lpVtbl->XTaskQueueTerminate(This,queue,wait,callbackContext,callback);
}
static inline HRESULT IXThreadingImpl_XTaskQueueRegisterMonitor(IXThreadingImpl* This,XTaskQueueHandle queue,void *callbackContext,XTaskQueueMonitorCallback *callback,XTaskQueueRegistrationToken *token) {
    return This->lpVtbl->XTaskQueueRegisterMonitor(This,queue,callbackContext,callback,token);
}
static inline void IXThreadingImpl_XTaskQueueUnregisterMonitor(IXThreadingImpl* This,XTaskQueueHandle queue,XTaskQueueRegistrationToken token) {
    This->lpVtbl->XTaskQueueUnregisterMonitor(This,queue,token);
}
static inline BOOLEAN IXThreadingImpl_XTaskQueueGetCurrentProcessTaskQueue(IXThreadingImpl* This,XTaskQueueHandle *queue) {
    return This->lpVtbl->XTaskQueueGetCurrentProcessTaskQueue(This,queue);
}
static inline void IXThreadingImpl_XTaskQueueSetCurrentProcessTaskQueue(IXThreadingImpl* This,XTaskQueueHandle queue) {
    This->lpVtbl->XTaskQueueSetCurrentProcessTaskQueue(This,queue);
}
static inline HRESULT IXThreadingImpl_XThreadSetTimeSensitive(IXThreadingImpl* This,BOOLEAN isTimeSensitiveThread) {
    return This->lpVtbl->XThreadSetTimeSensitive(This,isTimeSensitiveThread);
}
static inline HRESULT IXThreadingImpl___PADDING_2__(IXThreadingImpl* This) {
    return This->lpVtbl->__PADDING_2__(This);
}
static inline void IXThreadingImpl_XThreadAssertNotTimeSensitive(IXThreadingImpl* This) {
    This->lpVtbl->XThreadAssertNotTimeSensitive(This);
}
static inline BOOLEAN IXThreadingImpl_XThreadIsTimeSensitive(IXThreadingImpl* This) {
    return This->lpVtbl->XThreadIsTimeSensitive(This);
}
#endif
#endif

#endif


#endif  /* __IXThreadingImpl_INTERFACE_DEFINED__ */

/*****************************************************************************
 * XThreadingImpl coclass
 */

DEFINE_GUID(CLSID_XThreadingImpl, 0x073b7dcb, 0x1fcf, 0x4030, 0x94,0xbe, 0xe3,0xc9,0xeb,0x62,0x34,0x28);

#ifdef __cplusplus
class DECLSPEC_UUID("073b7dcb-1fcf-4030-94be-e3c9eb623428") XThreadingImpl;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(XThreadingImpl, 0x073b7dcb, 0x1fcf, 0x4030, 0x94,0xbe, 0xe3,0xc9,0xeb,0x62,0x34,0x28)
#endif
#endif

#endif
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __xasyncprovider_h__ */
