/*** Autogenerated by WIDL 11.15 from xdisplay.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __xdisplay_h__
#define __xdisplay_h__

/* Forward declarations */

#ifndef __IXDisplayImpl_FWD_DEFINED__
#define __IXDisplayImpl_FWD_DEFINED__
typedef interface IXDisplayImpl IXDisplayImpl;
#ifdef __cplusplus
interface IXDisplayImpl;
#endif /* __cplusplus */
#endif

#ifndef __IXLauncherImpl_FWD_DEFINED__
#define __IXLauncherImpl_FWD_DEFINED__
typedef interface IXLauncherImpl IXLauncherImpl;
#ifdef __cplusplus
interface IXLauncherImpl;
#endif /* __cplusplus */
#endif

#ifndef __XDisplayImpl_FWD_DEFINED__
#define __XDisplayImpl_FWD_DEFINED__
#ifdef __cplusplus
typedef class XDisplayImpl XDisplayImpl;
#else
typedef struct XDisplayImpl XDisplayImpl;
#endif /* defined __cplusplus */
#endif /* defined __XDisplayImpl_FWD_DEFINED__ */

#ifndef __XLauncherImpl_FWD_DEFINED__
#define __XLauncherImpl_FWD_DEFINED__
#ifdef __cplusplus
typedef class XLauncherImpl XLauncherImpl;
#else
typedef struct XLauncherImpl XLauncherImpl;
#endif /* defined __cplusplus */
#endif /* defined __XLauncherImpl_FWD_DEFINED__ */

/* Headers for imported files */

#include <unknwn.h>
#include <xuser.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
enum class XDisplayHdrModePreference : UINT32
{                                            
    PreferHdr,                               
    PreferRefreshRate,                       
};                                           
enum class XDisplayHdrModeResult : UINT32
{                                        
    Unknown,                             
    Enabled,                             
    Disabled,                            
};                                       
#elif defined(__WINESRC__)
typedef enum XDisplayHdrModePreference {
    XDisplayHdrModePreference_PreferHdr = 0,
    XDisplayHdrModePreference_PreferRefreshRate = 1
} XDisplayHdrModePreference;
typedef enum XDisplayHdrModeResult {
    XDisplayHdrModeResult_Unknown = 0,
    XDisplayHdrModeResult_Enabled = 1,
    XDisplayHdrModeResult_Disabled = 2
} XDisplayHdrModeResult;
#endif
typedef struct XDisplayTimeoutDeferral *XDisplayTimeoutDeferralHandle;
typedef struct XDisplayHdrModeInfo XDisplayHdrModeInfo;
struct XDisplayHdrModeInfo {
    float minToneMapLuminance;
    float maxToneMapLuminance;
    float maxFullFrameToneMapLuminance;
};
#ifdef __WINESRC__
/*****************************************************************************
 * IXDisplayImpl interface
 */
#ifndef __IXDisplayImpl_INTERFACE_DEFINED__
#define __IXDisplayImpl_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXDisplayImpl, 0x35f07670, 0x706e, 0x4bfb, 0x94,0x76, 0x09,0x07,0x98,0xc5,0xeb,0xf3);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("35f07670-706e-4bfb-9476-090798c5ebf3")
IXDisplayImpl : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE __PADDING__(
        ) = 0;

    virtual XDisplayHdrModeResult STDMETHODCALLTYPE XDisplayTryEnableHdrMode(
        XDisplayHdrModePreference displayModePreference,
        XDisplayHdrModeInfo *displayHdrModeInfo) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXDisplayImpl, 0x35f07670, 0x706e, 0x4bfb, 0x94,0x76, 0x09,0x07,0x98,0xc5,0xeb,0xf3)
#endif
#else
typedef struct IXDisplayImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXDisplayImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXDisplayImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXDisplayImpl *This);

    /*** IXDisplayImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *__PADDING__)(
        IXDisplayImpl *This);

    XDisplayHdrModeResult (STDMETHODCALLTYPE *XDisplayTryEnableHdrMode)(
        IXDisplayImpl *This,
        XDisplayHdrModePreference displayModePreference,
        XDisplayHdrModeInfo *displayHdrModeInfo);

    END_INTERFACE
} IXDisplayImplVtbl;

interface IXDisplayImpl {
    CONST_VTBL IXDisplayImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXDisplayImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXDisplayImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXDisplayImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IXDisplayImpl methods ***/
#define IXDisplayImpl___PADDING__(This) (This)->lpVtbl->__PADDING__(This)
#define IXDisplayImpl_XDisplayTryEnableHdrMode(This,displayModePreference,displayHdrModeInfo) (This)->lpVtbl->XDisplayTryEnableHdrMode(This,displayModePreference,displayHdrModeInfo)
#else
/*** IUnknown methods ***/
static inline HRESULT IXDisplayImpl_QueryInterface(IXDisplayImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXDisplayImpl_AddRef(IXDisplayImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXDisplayImpl_Release(IXDisplayImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IXDisplayImpl methods ***/
static inline HRESULT IXDisplayImpl___PADDING__(IXDisplayImpl* This) {
    return This->lpVtbl->__PADDING__(This);
}
static inline XDisplayHdrModeResult IXDisplayImpl_XDisplayTryEnableHdrMode(IXDisplayImpl* This,XDisplayHdrModePreference displayModePreference,XDisplayHdrModeInfo *displayHdrModeInfo) {
    return This->lpVtbl->XDisplayTryEnableHdrMode(This,displayModePreference,displayHdrModeInfo);
}
#endif
#endif

#endif


#endif  /* __IXDisplayImpl_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IXLauncherImpl interface
 */
#ifndef __IXLauncherImpl_INTERFACE_DEFINED__
#define __IXLauncherImpl_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXLauncherImpl, 0x1b339674, 0x328d, 0x4283, 0xa2,0x00, 0x31,0x71,0xf1,0x8d,0x36,0x39);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("1b339674-328d-4283-a200-3171f18d3639")
IXLauncherImpl : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE XLaunchUri(
        XUserHandle user,
        const char *uri) = 0;

    virtual HRESULT STDMETHODCALLTYPE XDisplayAcquireTimeoutDeferral(
        XDisplayTimeoutDeferralHandle *handle) = 0;

    virtual void STDMETHODCALLTYPE XDisplayCloseTimeoutDeferralHandle(
        XDisplayTimeoutDeferralHandle handle) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXLauncherImpl, 0x1b339674, 0x328d, 0x4283, 0xa2,0x00, 0x31,0x71,0xf1,0x8d,0x36,0x39)
#endif
#else
typedef struct IXLauncherImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXLauncherImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXLauncherImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXLauncherImpl *This);

    /*** IXLauncherImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XLaunchUri)(
        IXLauncherImpl *This,
        XUserHandle user,
        const char *uri);

    HRESULT (STDMETHODCALLTYPE *XDisplayAcquireTimeoutDeferral)(
        IXLauncherImpl *This,
        XDisplayTimeoutDeferralHandle *handle);

    void (STDMETHODCALLTYPE *XDisplayCloseTimeoutDeferralHandle)(
        IXLauncherImpl *This,
        XDisplayTimeoutDeferralHandle handle);

    END_INTERFACE
} IXLauncherImplVtbl;

interface IXLauncherImpl {
    CONST_VTBL IXLauncherImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXLauncherImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXLauncherImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXLauncherImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IXLauncherImpl methods ***/
#define IXLauncherImpl_XLaunchUri(This,user,uri) (This)->lpVtbl->XLaunchUri(This,user,uri)
#define IXLauncherImpl_XDisplayAcquireTimeoutDeferral(This,handle) (This)->lpVtbl->XDisplayAcquireTimeoutDeferral(This,handle)
#define IXLauncherImpl_XDisplayCloseTimeoutDeferralHandle(This,handle) (This)->lpVtbl->XDisplayCloseTimeoutDeferralHandle(This,handle)
#else
/*** IUnknown methods ***/
static inline HRESULT IXLauncherImpl_QueryInterface(IXLauncherImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXLauncherImpl_AddRef(IXLauncherImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXLauncherImpl_Release(IXLauncherImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IXLauncherImpl methods ***/
static inline HRESULT IXLauncherImpl_XLaunchUri(IXLauncherImpl* This,XUserHandle user,const char *uri) {
    return This->lpVtbl->XLaunchUri(This,user,uri);
}
static inline HRESULT IXLauncherImpl_XDisplayAcquireTimeoutDeferral(IXLauncherImpl* This,XDisplayTimeoutDeferralHandle *handle) {
    return This->lpVtbl->XDisplayAcquireTimeoutDeferral(This,handle);
}
static inline void IXLauncherImpl_XDisplayCloseTimeoutDeferralHandle(IXLauncherImpl* This,XDisplayTimeoutDeferralHandle handle) {
    This->lpVtbl->XDisplayCloseTimeoutDeferralHandle(This,handle);
}
#endif
#endif

#endif


#endif  /* __IXLauncherImpl_INTERFACE_DEFINED__ */

/*****************************************************************************
 * XDisplayImpl coclass
 */

DEFINE_GUID(CLSID_XDisplayImpl, 0x03f0fe74, 0xfdd9, 0x4e5c, 0xb6,0x30, 0xf9,0x33,0x9c,0x47,0xac,0xc5);

#ifdef __cplusplus
class DECLSPEC_UUID("03f0fe74-fdd9-4e5c-b630-f9339c47acc5") XDisplayImpl;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(XDisplayImpl, 0x03f0fe74, 0xfdd9, 0x4e5c, 0xb6,0x30, 0xf9,0x33,0x9c,0x47,0xac,0xc5)
#endif
#endif

/*****************************************************************************
 * XLauncherImpl coclass
 */

DEFINE_GUID(CLSID_XLauncherImpl, 0x1b339674, 0x328d, 0x4283, 0xa2,0x00, 0x31,0x71,0xf1,0x8d,0x36,0x39);

#ifdef __cplusplus
class DECLSPEC_UUID("1b339674-328d-4283-a200-3171f18d3639") XLauncherImpl;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(XLauncherImpl, 0x1b339674, 0x328d, 0x4283, 0xa2,0x00, 0x31,0x71,0xf1,0x8d,0x36,0x39)
#endif
#endif

#endif
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __xdisplay_h__ */
