/*** Autogenerated by WIDL 11.15 from xerror.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __xerror_h__
#define __xerror_h__

/* Forward declarations */

#ifndef __IXErrorImpl_FWD_DEFINED__
#define __IXErrorImpl_FWD_DEFINED__
typedef interface IXErrorImpl IXErrorImpl;
#ifdef __cplusplus
interface IXErrorImpl;
#endif /* __cplusplus */
#endif

#ifndef __XErrorImpl_FWD_DEFINED__
#define __XErrorImpl_FWD_DEFINED__
#ifdef __cplusplus
typedef class XErrorImpl XErrorImpl;
#else
typedef struct XErrorImpl XErrorImpl;
#endif /* defined __cplusplus */
#endif /* defined __XErrorImpl_FWD_DEFINED__ */

/* Headers for imported files */

#include <unknwn.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
enum class XErrorOptions : UINT32   
{                                   
    None                     = 0x00,
    OutputDebugStringOnError = 0x01,
    DebugBreakOnError        = 0x02,
    FailFastOnError          = 0x04,
};                                  
#elif defined(__WINESRC__)
typedef enum XErrorOptions {
    XErrorOptions_None = 0x0,
    XErrorOptions_OutputDebugStringOnError = 0x1,
    XErrorOptions_DebugBreakOnError = 0x2,
    XErrorOptions_FailFastOnError = 0x4
} XErrorOptions;
#endif
typedef void __stdcall  XErrorCallback(HRESULT hr,const char *msg,void *context);
#ifdef __WINESRC__
/*****************************************************************************
 * IXErrorImpl interface
 */
#ifndef __IXErrorImpl_INTERFACE_DEFINED__
#define __IXErrorImpl_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXErrorImpl, 0x8ca467f7, 0x22e8, 0x4096, 0x84,0x56, 0xbb,0x8a,0xa1,0x3f,0x79,0xd8);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("8ca467f7-22e8-4096-8456-bb8aa13f79d8")
IXErrorImpl : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE __PADDING__(
        ) = 0;

    virtual void STDMETHODCALLTYPE XErrorSetCallback(
        XErrorCallback *callback,
        void *context) = 0;

    virtual void STDMETHODCALLTYPE XErrorSetOptions(
        XErrorOptions optionsDebuggerPresent,
        XErrorOptions optionsDebuggerNotPresent) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXErrorImpl, 0x8ca467f7, 0x22e8, 0x4096, 0x84,0x56, 0xbb,0x8a,0xa1,0x3f,0x79,0xd8)
#endif
#else
typedef struct IXErrorImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXErrorImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXErrorImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXErrorImpl *This);

    /*** IXErrorImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *__PADDING__)(
        IXErrorImpl *This);

    void (STDMETHODCALLTYPE *XErrorSetCallback)(
        IXErrorImpl *This,
        XErrorCallback *callback,
        void *context);

    void (STDMETHODCALLTYPE *XErrorSetOptions)(
        IXErrorImpl *This,
        XErrorOptions optionsDebuggerPresent,
        XErrorOptions optionsDebuggerNotPresent);

    END_INTERFACE
} IXErrorImplVtbl;

interface IXErrorImpl {
    CONST_VTBL IXErrorImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXErrorImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXErrorImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXErrorImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IXErrorImpl methods ***/
#define IXErrorImpl___PADDING__(This) (This)->lpVtbl->__PADDING__(This)
#define IXErrorImpl_XErrorSetCallback(This,callback,context) (This)->lpVtbl->XErrorSetCallback(This,callback,context)
#define IXErrorImpl_XErrorSetOptions(This,optionsDebuggerPresent,optionsDebuggerNotPresent) (This)->lpVtbl->XErrorSetOptions(This,optionsDebuggerPresent,optionsDebuggerNotPresent)
#else
/*** IUnknown methods ***/
static inline HRESULT IXErrorImpl_QueryInterface(IXErrorImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXErrorImpl_AddRef(IXErrorImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXErrorImpl_Release(IXErrorImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IXErrorImpl methods ***/
static inline HRESULT IXErrorImpl___PADDING__(IXErrorImpl* This) {
    return This->lpVtbl->__PADDING__(This);
}
static inline void IXErrorImpl_XErrorSetCallback(IXErrorImpl* This,XErrorCallback *callback,void *context) {
    This->lpVtbl->XErrorSetCallback(This,callback,context);
}
static inline void IXErrorImpl_XErrorSetOptions(IXErrorImpl* This,XErrorOptions optionsDebuggerPresent,XErrorOptions optionsDebuggerNotPresent) {
    This->lpVtbl->XErrorSetOptions(This,optionsDebuggerPresent,optionsDebuggerNotPresent);
}
#endif
#endif

#endif


#endif  /* __IXErrorImpl_INTERFACE_DEFINED__ */

/*****************************************************************************
 * XErrorImpl coclass
 */

DEFINE_GUID(CLSID_XErrorImpl, 0x8ca467f7, 0x22e8, 0x4096, 0x84,0x56, 0xbb,0x8a,0xa1,0x3f,0x79,0xd8);

#ifdef __cplusplus
class DECLSPEC_UUID("8ca467f7-22e8-4096-8456-bb8aa13f79d8") XErrorImpl;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(XErrorImpl, 0x8ca467f7, 0x22e8, 0x4096, 0x84,0x56, 0xbb,0x8a,0xa1,0x3f,0x79,0xd8)
#endif
#endif

#endif
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __xerror_h__ */
