/*** Autogenerated by WIDL 11.15 from xgameruntimefeature.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __xgameruntimefeature_h__
#define __xgameruntimefeature_h__

/* Forward declarations */

#ifndef __IXGameRuntimeFeatureImpl_FWD_DEFINED__
#define __IXGameRuntimeFeatureImpl_FWD_DEFINED__
typedef interface IXGameRuntimeFeatureImpl IXGameRuntimeFeatureImpl;
#ifdef __cplusplus
interface IXGameRuntimeFeatureImpl;
#endif /* __cplusplus */
#endif

#ifndef __XGameRuntimeFeatureImpl_FWD_DEFINED__
#define __XGameRuntimeFeatureImpl_FWD_DEFINED__
#ifdef __cplusplus
typedef class XGameRuntimeFeatureImpl XGameRuntimeFeatureImpl;
#else
typedef struct XGameRuntimeFeatureImpl XGameRuntimeFeatureImpl;
#endif /* defined __cplusplus */
#endif /* defined __XGameRuntimeFeatureImpl_FWD_DEFINED__ */

/* Headers for imported files */

#include <unknwn.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
enum class XGameRuntimeFeature : UINT32
{                                      
    XAccessibility,                    
    XAppCapture,                       
    XAsync,                            
    XAsyncProvider,                    
    XDisplay,                          
    XGame,                             
    XGameInvite,                       
    XGameSave,                         
    XGameUI,                           
    XLauncher,                         
    XNetworking,                       
    XPackage,                          
    XPersistentLocalStorage,           
    XSpeechSynthesizer,                
    XStore,                            
    XSystem,                           
    XTaskQueue,                        
    XThread,                           
    XUser,                             
    XError,                            
    XGameEvent,                        
    XGameStreaming,                    
};                                     
#elif defined(__WINESRC__)
typedef enum XGameRuntimeFeature {
    XGameRuntimeFeature_XAccessibility = 0,
    XGameRuntimeFeature_XAppCapture = 1,
    XGameRuntimeFeature_XAsync = 2,
    XGameRuntimeFeature_XAsyncProvider = 3,
    XGameRuntimeFeature_XDisplay = 4,
    XGameRuntimeFeature_XGame = 5,
    XGameRuntimeFeature_XGameInvite = 6,
    XGameRuntimeFeature_XGameSave = 7,
    XGameRuntimeFeature_XGameUI = 8,
    XGameRuntimeFeature_XLauncher = 9,
    XGameRuntimeFeature_XNetworking = 10,
    XGameRuntimeFeature_XPackage = 11,
    XGameRuntimeFeature_XPersistentLocalStorage = 12,
    XGameRuntimeFeature_XSpeechSynthesizer = 13,
    XGameRuntimeFeature_XStore = 14,
    XGameRuntimeFeature_XSystem = 15,
    XGameRuntimeFeature_XTaskQueue = 16,
    XGameRuntimeFeature_XThread = 17,
    XGameRuntimeFeature_XUser = 18,
    XGameRuntimeFeature_XError = 19,
    XGameRuntimeFeature_XGameEvent = 20,
    XGameRuntimeFeature_XGameStreaming = 21
} XGameRuntimeFeature;
/*****************************************************************************
 * IXGameRuntimeFeatureImpl interface
 */
#ifndef __IXGameRuntimeFeatureImpl_INTERFACE_DEFINED__
#define __IXGameRuntimeFeatureImpl_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXGameRuntimeFeatureImpl, 0x8836fe87, 0xedb9, 0x4fe3, 0x8d,0xad, 0x05,0xf0,0xd2,0xcd,0x5b,0x40);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("8836fe87-edb9-4fe3-8dad-05f0d2cd5b40")
IXGameRuntimeFeatureImpl : public IUnknown
{
    virtual BOOLEAN STDMETHODCALLTYPE XGameRuntimeIsFeatureAvailable(
        XGameRuntimeFeature feature) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXGameRuntimeFeatureImpl, 0x8836fe87, 0xedb9, 0x4fe3, 0x8d,0xad, 0x05,0xf0,0xd2,0xcd,0x5b,0x40)
#endif
#else
typedef struct IXGameRuntimeFeatureImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXGameRuntimeFeatureImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXGameRuntimeFeatureImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXGameRuntimeFeatureImpl *This);

    /*** IXGameRuntimeFeatureImpl methods ***/
    BOOLEAN (STDMETHODCALLTYPE *XGameRuntimeIsFeatureAvailable)(
        IXGameRuntimeFeatureImpl *This,
        XGameRuntimeFeature feature);

    END_INTERFACE
} IXGameRuntimeFeatureImplVtbl;

interface IXGameRuntimeFeatureImpl {
    CONST_VTBL IXGameRuntimeFeatureImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXGameRuntimeFeatureImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXGameRuntimeFeatureImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXGameRuntimeFeatureImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IXGameRuntimeFeatureImpl methods ***/
#define IXGameRuntimeFeatureImpl_XGameRuntimeIsFeatureAvailable(This,feature) (This)->lpVtbl->XGameRuntimeIsFeatureAvailable(This,feature)
#else
/*** IUnknown methods ***/
static inline HRESULT IXGameRuntimeFeatureImpl_QueryInterface(IXGameRuntimeFeatureImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXGameRuntimeFeatureImpl_AddRef(IXGameRuntimeFeatureImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXGameRuntimeFeatureImpl_Release(IXGameRuntimeFeatureImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IXGameRuntimeFeatureImpl methods ***/
static inline BOOLEAN IXGameRuntimeFeatureImpl_XGameRuntimeIsFeatureAvailable(IXGameRuntimeFeatureImpl* This,XGameRuntimeFeature feature) {
    return This->lpVtbl->XGameRuntimeIsFeatureAvailable(This,feature);
}
#endif
#endif

#endif


#endif  /* __IXGameRuntimeFeatureImpl_INTERFACE_DEFINED__ */

/*****************************************************************************
 * XGameRuntimeFeatureImpl coclass
 */

DEFINE_GUID(CLSID_XGameRuntimeFeatureImpl, 0x8836fe87, 0xedb9, 0x4fe3, 0x8d,0xad, 0x05,0xf0,0xd2,0xcd,0x5b,0x40);

#ifdef __cplusplus
class DECLSPEC_UUID("8836fe87-edb9-4fe3-8dad-05f0d2cd5b40") XGameRuntimeFeatureImpl;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(XGameRuntimeFeatureImpl, 0x8836fe87, 0xedb9, 0x4fe3, 0x8d,0xad, 0x05,0xf0,0xd2,0xcd,0x5b,0x40)
#endif
#endif

#endif
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __xgameruntimefeature_h__ */
