/*** Autogenerated by WIDL 11.15 from xgameactivation.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __xgameactivation_h__
#define __xgameactivation_h__

/* Forward declarations */

#ifndef __IXGameActivationImpl_FWD_DEFINED__
#define __IXGameActivationImpl_FWD_DEFINED__
typedef interface IXGameActivationImpl IXGameActivationImpl;
#ifdef __cplusplus
interface IXGameActivationImpl;
#endif /* __cplusplus */
#endif

#ifndef __XGameActivationImpl_FWD_DEFINED__
#define __XGameActivationImpl_FWD_DEFINED__
#ifdef __cplusplus
typedef class XGameActivationImpl XGameActivationImpl;
#else
typedef struct XGameActivationImpl XGameActivationImpl;
#endif /* defined __cplusplus */
#endif /* defined __XGameActivationImpl_FWD_DEFINED__ */

/* Headers for imported files */

#include <unknwn.h>
#include <xtaskqueue.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
enum class XGameActivationType : UINT32
{                                      
    Protocol,                          
    File,                              
    PendingGameInvite,                 
    AcceptedGameInvite,                
};                                     
#elif defined(__WINESRC__)
typedef enum XGameActivationType {
    XGameActivationType_Protocol = 0,
    XGameActivationType_File = 1,
    XGameActivationType_PendingGameInvite = 2,
    XGameActivationType_AcceptedGameInvite = 3
} XGameActivationType;
#endif
typedef struct XGameActivationInfo XGameActivationInfo;
typedef void __stdcall  XGameActivationCallback(void *context,const XGameActivationInfo *activationInfo);
struct XGameActivationInfo {
    XGameActivationType type;
    __C89_NAMELESS union {
        const char *protocolUri;
        const char *file;
        const char *inviteUri;
    } __C89_NAMELESSUNIONNAME;
};
#ifdef __WINESRC__
/*****************************************************************************
 * IXGameActivationImpl interface
 */
#ifndef __IXGameActivationImpl_INTERFACE_DEFINED__
#define __IXGameActivationImpl_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXGameActivationImpl, 0x2e4f76fe, 0x0fc7, 0x461e, 0xab,0x4d, 0xa4,0x49,0x94,0x34,0xc3,0xcf);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("2e4f76fe-0fc7-461e-ab4d-a4499434c3cf")
IXGameActivationImpl : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE XGameActivationRegisterForEvent(
        XTaskQueueHandle queue,
        void *context,
        XGameActivationCallback *callback,
        XTaskQueueRegistrationToken *token) = 0;

    virtual BOOLEAN STDMETHODCALLTYPE XGameActivationUnregisterForEvent(
        XTaskQueueRegistrationToken token,
        BOOLEAN wait) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameActivationAcceptPendingInvite(
        const char *inviteUri) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXGameActivationImpl, 0x2e4f76fe, 0x0fc7, 0x461e, 0xab,0x4d, 0xa4,0x49,0x94,0x34,0xc3,0xcf)
#endif
#else
typedef struct IXGameActivationImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXGameActivationImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXGameActivationImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXGameActivationImpl *This);

    /*** IXGameActivationImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XGameActivationRegisterForEvent)(
        IXGameActivationImpl *This,
        XTaskQueueHandle queue,
        void *context,
        XGameActivationCallback *callback,
        XTaskQueueRegistrationToken *token);

    BOOLEAN (STDMETHODCALLTYPE *XGameActivationUnregisterForEvent)(
        IXGameActivationImpl *This,
        XTaskQueueRegistrationToken token,
        BOOLEAN wait);

    HRESULT (STDMETHODCALLTYPE *XGameActivationAcceptPendingInvite)(
        IXGameActivationImpl *This,
        const char *inviteUri);

    END_INTERFACE
} IXGameActivationImplVtbl;

interface IXGameActivationImpl {
    CONST_VTBL IXGameActivationImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXGameActivationImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXGameActivationImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXGameActivationImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IXGameActivationImpl methods ***/
#define IXGameActivationImpl_XGameActivationRegisterForEvent(This,queue,context,callback,token) (This)->lpVtbl->XGameActivationRegisterForEvent(This,queue,context,callback,token)
#define IXGameActivationImpl_XGameActivationUnregisterForEvent(This,token,wait) (This)->lpVtbl->XGameActivationUnregisterForEvent(This,token,wait)
#define IXGameActivationImpl_XGameActivationAcceptPendingInvite(This,inviteUri) (This)->lpVtbl->XGameActivationAcceptPendingInvite(This,inviteUri)
#else
/*** IUnknown methods ***/
static inline HRESULT IXGameActivationImpl_QueryInterface(IXGameActivationImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXGameActivationImpl_AddRef(IXGameActivationImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXGameActivationImpl_Release(IXGameActivationImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IXGameActivationImpl methods ***/
static inline HRESULT IXGameActivationImpl_XGameActivationRegisterForEvent(IXGameActivationImpl* This,XTaskQueueHandle queue,void *context,XGameActivationCallback *callback,XTaskQueueRegistrationToken *token) {
    return This->lpVtbl->XGameActivationRegisterForEvent(This,queue,context,callback,token);
}
static inline BOOLEAN IXGameActivationImpl_XGameActivationUnregisterForEvent(IXGameActivationImpl* This,XTaskQueueRegistrationToken token,BOOLEAN wait) {
    return This->lpVtbl->XGameActivationUnregisterForEvent(This,token,wait);
}
static inline HRESULT IXGameActivationImpl_XGameActivationAcceptPendingInvite(IXGameActivationImpl* This,const char *inviteUri) {
    return This->lpVtbl->XGameActivationAcceptPendingInvite(This,inviteUri);
}
#endif
#endif

#endif


#endif  /* __IXGameActivationImpl_INTERFACE_DEFINED__ */

/*****************************************************************************
 * XGameActivationImpl coclass
 */

DEFINE_GUID(CLSID_XGameActivationImpl, 0x7f0fe8b8, 0xe075, 0x49ab, 0x9a,0xa7, 0xa1,0xe0,0x65,0x48,0x9a,0x9e);

#ifdef __cplusplus
class DECLSPEC_UUID("7f0fe8b8-e075-49ab-9aa7-a1e065489a9e") XGameActivationImpl;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(XGameActivationImpl, 0x7f0fe8b8, 0xe075, 0x49ab, 0x9a,0xa7, 0xa1,0xe0,0x65,0x48,0x9a,0x9e)
#endif
#endif

#endif
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __xgameactivation_h__ */
