/*** Autogenerated by WIDL 11.15 from xgameevent.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __xgameevent_h__
#define __xgameevent_h__

/* Forward declarations */

#ifndef __IXGameEventImpl_FWD_DEFINED__
#define __IXGameEventImpl_FWD_DEFINED__
typedef interface IXGameEventImpl IXGameEventImpl;
#ifdef __cplusplus
interface IXGameEventImpl;
#endif /* __cplusplus */
#endif

#ifndef __XGameEventImpl_FWD_DEFINED__
#define __XGameEventImpl_FWD_DEFINED__
#ifdef __cplusplus
typedef class XGameEventImpl XGameEventImpl;
#else
typedef struct XGameEventImpl XGameEventImpl;
#endif /* defined __cplusplus */
#endif /* defined __XGameEventImpl_FWD_DEFINED__ */

/* Headers for imported files */

#include <unknwn.h>
#include <xuser.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __WINESRC__
/*****************************************************************************
 * IXGameEventImpl interface
 */
#ifndef __IXGameEventImpl_INTERFACE_DEFINED__
#define __IXGameEventImpl_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXGameEventImpl, 0xbbfbdcc7, 0xbfe7, 0x409b, 0xa5,0xca, 0xed,0xf0,0x54,0x96,0x0b,0x4d);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("bbfbdcc7-bfe7-409b-a5ca-edf054960b4d")
IXGameEventImpl : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE XGameEventWrite(
        XUserHandle user,
        const char *serviceConfigId,
        const char *playSessionId,
        const char *eventName,
        const char *dimensionsJson,
        const char *measurementsJson) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXGameEventImpl, 0xbbfbdcc7, 0xbfe7, 0x409b, 0xa5,0xca, 0xed,0xf0,0x54,0x96,0x0b,0x4d)
#endif
#else
typedef struct IXGameEventImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXGameEventImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXGameEventImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXGameEventImpl *This);

    /*** IXGameEventImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XGameEventWrite)(
        IXGameEventImpl *This,
        XUserHandle user,
        const char *serviceConfigId,
        const char *playSessionId,
        const char *eventName,
        const char *dimensionsJson,
        const char *measurementsJson);

    END_INTERFACE
} IXGameEventImplVtbl;

interface IXGameEventImpl {
    CONST_VTBL IXGameEventImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXGameEventImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXGameEventImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXGameEventImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IXGameEventImpl methods ***/
#define IXGameEventImpl_XGameEventWrite(This,user,serviceConfigId,playSessionId,eventName,dimensionsJson,measurementsJson) (This)->lpVtbl->XGameEventWrite(This,user,serviceConfigId,playSessionId,eventName,dimensionsJson,measurementsJson)
#else
/*** IUnknown methods ***/
static inline HRESULT IXGameEventImpl_QueryInterface(IXGameEventImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXGameEventImpl_AddRef(IXGameEventImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXGameEventImpl_Release(IXGameEventImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IXGameEventImpl methods ***/
static inline HRESULT IXGameEventImpl_XGameEventWrite(IXGameEventImpl* This,XUserHandle user,const char *serviceConfigId,const char *playSessionId,const char *eventName,const char *dimensionsJson,const char *measurementsJson) {
    return This->lpVtbl->XGameEventWrite(This,user,serviceConfigId,playSessionId,eventName,dimensionsJson,measurementsJson);
}
#endif
#endif

#endif


#endif  /* __IXGameEventImpl_INTERFACE_DEFINED__ */

/*****************************************************************************
 * XGameEventImpl coclass
 */

DEFINE_GUID(CLSID_XGameEventImpl, 0xbbfbdcc7, 0xbfe7, 0x409b, 0xa5,0xca, 0xed,0xf0,0x54,0x96,0x0b,0x4d);

#ifdef __cplusplus
class DECLSPEC_UUID("bbfbdcc7-bfe7-409b-a5ca-edf054960b4d") XGameEventImpl;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(XGameEventImpl, 0xbbfbdcc7, 0xbfe7, 0x409b, 0xa5,0xca, 0xed,0xf0,0x54,0x96,0x0b,0x4d)
#endif
#endif

#endif
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __xgameevent_h__ */
