/*** Autogenerated by WIDL 11.15 from xgameprotocol.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __xgameprotocol_h__
#define __xgameprotocol_h__

/* Forward declarations */

#ifndef __IXGameProtocolImpl_FWD_DEFINED__
#define __IXGameProtocolImpl_FWD_DEFINED__
typedef interface IXGameProtocolImpl IXGameProtocolImpl;
#ifdef __cplusplus
interface IXGameProtocolImpl;
#endif /* __cplusplus */
#endif

#ifndef __XGameProtocolImpl_FWD_DEFINED__
#define __XGameProtocolImpl_FWD_DEFINED__
#ifdef __cplusplus
typedef class XGameProtocolImpl XGameProtocolImpl;
#else
typedef struct XGameProtocolImpl XGameProtocolImpl;
#endif /* defined __cplusplus */
#endif /* defined __XGameProtocolImpl_FWD_DEFINED__ */

/* Headers for imported files */

#include <unknwn.h>
#include <xtaskqueue.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef void __stdcall  XGameProtocolActivationCallback(void *context,const char *protocolUri);
#ifdef __WINESRC__
/*****************************************************************************
 * IXGameProtocolImpl interface
 */
#ifndef __IXGameProtocolImpl_INTERFACE_DEFINED__
#define __IXGameProtocolImpl_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXGameProtocolImpl, 0x026b010c, 0x06c3, 0x4cdd, 0xbb,0xcb, 0x43,0xf2,0x29,0xdb,0x1c,0xff);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("026b010c-06c3-4cdd-bbcb-43f229db1cff")
IXGameProtocolImpl : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE XGameProtocolRegisterForActivation(
        XTaskQueueHandle queue,
        void *context,
        XGameProtocolActivationCallback *callback,
        XTaskQueueRegistrationToken *token) = 0;

    virtual BOOLEAN STDMETHODCALLTYPE XGameProtocolUnregisterForActivation(
        XTaskQueueRegistrationToken token,
        BOOLEAN wait) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXGameProtocolImpl, 0x026b010c, 0x06c3, 0x4cdd, 0xbb,0xcb, 0x43,0xf2,0x29,0xdb,0x1c,0xff)
#endif
#else
typedef struct IXGameProtocolImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXGameProtocolImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXGameProtocolImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXGameProtocolImpl *This);

    /*** IXGameProtocolImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XGameProtocolRegisterForActivation)(
        IXGameProtocolImpl *This,
        XTaskQueueHandle queue,
        void *context,
        XGameProtocolActivationCallback *callback,
        XTaskQueueRegistrationToken *token);

    BOOLEAN (STDMETHODCALLTYPE *XGameProtocolUnregisterForActivation)(
        IXGameProtocolImpl *This,
        XTaskQueueRegistrationToken token,
        BOOLEAN wait);

    END_INTERFACE
} IXGameProtocolImplVtbl;

interface IXGameProtocolImpl {
    CONST_VTBL IXGameProtocolImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXGameProtocolImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXGameProtocolImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXGameProtocolImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IXGameProtocolImpl methods ***/
#define IXGameProtocolImpl_XGameProtocolRegisterForActivation(This,queue,context,callback,token) (This)->lpVtbl->XGameProtocolRegisterForActivation(This,queue,context,callback,token)
#define IXGameProtocolImpl_XGameProtocolUnregisterForActivation(This,token,wait) (This)->lpVtbl->XGameProtocolUnregisterForActivation(This,token,wait)
#else
/*** IUnknown methods ***/
static inline HRESULT IXGameProtocolImpl_QueryInterface(IXGameProtocolImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXGameProtocolImpl_AddRef(IXGameProtocolImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXGameProtocolImpl_Release(IXGameProtocolImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IXGameProtocolImpl methods ***/
static inline HRESULT IXGameProtocolImpl_XGameProtocolRegisterForActivation(IXGameProtocolImpl* This,XTaskQueueHandle queue,void *context,XGameProtocolActivationCallback *callback,XTaskQueueRegistrationToken *token) {
    return This->lpVtbl->XGameProtocolRegisterForActivation(This,queue,context,callback,token);
}
static inline BOOLEAN IXGameProtocolImpl_XGameProtocolUnregisterForActivation(IXGameProtocolImpl* This,XTaskQueueRegistrationToken token,BOOLEAN wait) {
    return This->lpVtbl->XGameProtocolUnregisterForActivation(This,token,wait);
}
#endif
#endif

#endif


#endif  /* __IXGameProtocolImpl_INTERFACE_DEFINED__ */

/*****************************************************************************
 * XGameProtocolImpl coclass
 */

DEFINE_GUID(CLSID_XGameProtocolImpl, 0x95fd18d2, 0x74dd, 0x4d7c, 0xaa,0x1b, 0x0b,0x51,0x82,0x76,0x65,0xd6);

#ifdef __cplusplus
class DECLSPEC_UUID("95fd18d2-74dd-4d7c-aa1b-0b51827665d6") XGameProtocolImpl;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(XGameProtocolImpl, 0x95fd18d2, 0x74dd, 0x4d7c, 0xaa,0x1b, 0x0b,0x51,0x82,0x76,0x65,0xd6)
#endif
#endif

#endif
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __xgameprotocol_h__ */
