@ stub -private DllCanUnloadNow()
@ stdcall -private DllGetActivationFactory(ptr ptr)
@ stdcall -private InitializeApiImpl(long long)
@ stdcall -private InitializeApiImplEx(long long long)
@ stdcall -private InitializeApiImplEx2(long long long ptr)
@ stdcall -private QueryApiImpl(ptr ptr ptr)
@ stdcall -private UninitializeApiImpl()
@ stub -private XErrorReport(long str)

# Flat GDK C Exports
@ stdcall XGameRuntimeInitialize()
@ stdcall XGameRuntimeInitializeWithOptions(ptr)
@ stdcall XGameRuntimeUninitialize()
@ stdcall XGameRuntimeIsFeatureAvailable(long)
@ stdcall XGameGetXboxTitleId(ptr)

# XUser Management
@ stdcall XUserAddAsync(long ptr)
@ stdcall XUserAddResult(ptr ptr)
@ stdcall XUserAddByIdWithUiAsync(long ptr)
@ stdcall XUserAddByIdWithUiResult(ptr ptr)
@ stdcall XUserCloseHandle(ptr)
@ stdcall XUserDuplicateHandle(ptr ptr)
@ stdcall XUserCompare(ptr ptr ptr)
@ stdcall XUserGetId(ptr ptr)
@ stdcall XUserGetLocalId(ptr ptr)
@ stdcall XUserGetState(ptr ptr)
@ stdcall XUserGetIsGuest(ptr ptr)
@ stdcall XUserGetAgeGroup(ptr ptr)
@ stdcall XUserGetGamertag(ptr long long ptr ptr)
@ stdcall XUserGetGamerPictureAsync(ptr long ptr)
@ stdcall XUserGetGamerPictureResultSize(ptr ptr)
@ stdcall XUserGetGamerPictureResult(ptr long ptr ptr)
@ stdcall XUserGetTokenAndSignatureAsync(ptr long str str long ptr long ptr ptr)
@ stdcall XUserGetTokenAndSignatureResultSize(ptr ptr)
@ stdcall XUserGetTokenAndSignatureResult(ptr long ptr ptr ptr)
@ stdcall XUserGetTokenAndSignatureUtf16Async(ptr long ptr ptr long ptr long ptr ptr)
@ stdcall XUserGetTokenAndSignatureUtf16ResultSize(ptr ptr)
@ stdcall XUserGetTokenAndSignatureUtf16Result(ptr long ptr ptr ptr)
@ stdcall XUserCheckPrivilege(ptr long long ptr ptr)
@ stdcall XUserResolvePrivilegeWithUiAsync(ptr long long ptr)
@ stdcall XUserResolvePrivilegeWithUiResult(ptr)
@ stdcall XUserRegisterForChangeEvent(ptr ptr ptr ptr)
@ stdcall XUserUnregisterForChangeEvent(ptr long)
@ stdcall XUserFindUserById(int64 ptr)
@ stdcall XUserFindUserByLocalId(int64 ptr)
@ stdcall XUserGetMaxUsers()
@ stdcall XUserIsStoreUser(ptr ptr)
@ stdcall XUserGetSignOutDeferral(ptr)
@ stdcall XUserCloseSignOutDeferralHandle(ptr)

# XTaskQueue & XAsync
@ stdcall XTaskQueueCreate(long long ptr)
@ stdcall XTaskQueueCreateComposite(ptr ptr ptr)
@ stdcall XTaskQueueDispatch(ptr long long)
@ stdcall XTaskQueueCloseHandle(ptr)
@ stdcall XTaskQueueDuplicateHandle(ptr ptr)
@ stdcall XTaskQueueGetCurrentProcessTaskQueue(ptr)
@ stdcall XTaskQueueSetCurrentProcessTaskQueue(ptr)
@ stdcall XTaskQueueGetPort(ptr long ptr)
@ stdcall XTaskQueueRegisterMonitor(ptr ptr ptr ptr)
@ stdcall XTaskQueueUnregisterMonitor(ptr int64)
@ stdcall XTaskQueueRegisterWaiter(ptr long ptr ptr ptr ptr)
@ stdcall XTaskQueueUnregisterWaiter(ptr ptr)
@ stdcall XTaskQueueSubmitCallback(ptr long ptr ptr)
@ stdcall XTaskQueueSubmitDelayedCallback(ptr long long ptr ptr)
@ stdcall XTaskQueueTerminate(ptr long ptr ptr)
@ stdcall XAsyncGetStatus(ptr long)
@ stdcall XAsyncGetResult(ptr ptr long ptr ptr)
@ stdcall XAsyncGetResultSize(ptr ptr)
@ stdcall XAsyncCancel(ptr)
@ stdcall XAsyncRun(ptr ptr)

# XPersistentLocalStorage
@ stdcall XPersistentLocalStorageGetPath(long ptr ptr)
@ stdcall XPersistentLocalStorageGetPathSize(ptr)
@ stdcall XPersistentLocalStorageGetSpaceInfo(ptr ptr)
@ stdcall XPersistentLocalStoragePromptUserForSpaceAsync(int64 ptr)
@ stdcall XPersistentLocalStoragePromptUserForSpaceResult(ptr)

# XPackage
@ stdcall XPackageIsPackagedProcess()
@ stdcall XPackageGetCurrentProcessPackageIdentifier(long ptr)
@ stdcall XPackageGetMountPath(ptr long ptr)
@ stdcall XPackageGetMountPathSize(ptr ptr)
@ stdcall XPackageCreateInstallationMonitor(str long ptr long ptr ptr)
@ stdcall XPackageCloseInstallationMonitorHandle(ptr)
@ stdcall XPackageCloseMountHandle(ptr)
@ stdcall XPackageGetInstallationProgress(ptr ptr)
@ stdcall XPackageUpdateInstallationMonitor(ptr)
@ stdcall XPackageGetUserLocale(long ptr)

# XGameSave
@ stdcall XGameSaveInitializeProvider(ptr str long ptr)
@ stdcall XGameSaveInitializeProviderAsync(ptr str long ptr)
@ stdcall XGameSaveInitializeProviderResult(ptr ptr)
@ stdcall XGameSaveCloseProvider(ptr)
@ stdcall XGameSaveCreateUpdate(ptr str ptr)
@ stdcall XGameSaveCloseUpdate(ptr)
@ stdcall XGameSaveSubmitUpdate(ptr)
@ stdcall XGameSaveSubmitUpdateAsync(ptr ptr)
@ stdcall XGameSaveSubmitUpdateResult(ptr)
@ stdcall XGameSaveDeleteContainer(ptr str)
@ stdcall XGameSaveDeleteContainerAsync(ptr str ptr)
@ stdcall XGameSaveDeleteContainerResult(ptr)
@ stdcall XGameSaveReadBlobData(ptr str str long ptr ptr)
@ stdcall XGameSaveReadBlobDataAsync(ptr str str long ptr ptr)
@ stdcall XGameSaveReadBlobDataResult(ptr ptr)
@ stdcall XGameSaveGetContainerInfo(ptr str ptr)
@ stdcall XGameSaveGetRemainingQuota(ptr ptr)
@ stdcall XGameSaveGetRemainingQuotaAsync(ptr ptr)
@ stdcall XGameSaveGetRemainingQuotaResult(ptr ptr)
@ stdcall XGameSaveFilesGetFolderWithUiAsync(ptr str str long ptr)
@ stdcall XGameSaveFilesGetFolderWithUiResult(ptr long ptr)

# XStore
@ stdcall XStoreCreateContext(ptr ptr)
@ stdcall XStoreCloseContextHandle(ptr)
@ stdcall XStoreCloseLicenseHandle(ptr)
@ stdcall XStoreCloseProductsQueryHandle(ptr)
@ stdcall XStoreQueryGameLicenseAsync(ptr ptr)
@ stdcall XStoreQueryGameLicenseResult(ptr ptr)
@ stdcall XStoreIsLicenseValid(ptr)
@ stdcall XStoreQueryAssociatedProductsAsync(ptr long long ptr)
@ stdcall XStoreQueryAssociatedProductsResult(ptr ptr)
@ stdcall XStoreQueryEntitledProductsAsync(ptr long long ptr)
@ stdcall XStoreQueryEntitledProductsResult(ptr ptr)
@ stdcall XStoreQueryProductsAsync(ptr long ptr long ptr long ptr)
@ stdcall XStoreQueryProductsResult(ptr ptr)
@ stdcall XStoreProductsQueryNextPageAsync(ptr ptr)
@ stdcall XStoreProductsQueryNextPageResult(ptr ptr)
@ stdcall XStoreProductsQueryHasMorePages(ptr)
@ stdcall XStoreEnumerateProductsQuery(ptr ptr ptr)
@ stdcall XStoreAcquireLicenseForPackageAsync(ptr str ptr)
@ stdcall XStoreAcquireLicenseForPackageResult(ptr ptr)
@ stdcall XStoreAcquireLicenseForDurablesAsync(ptr str ptr)
@ stdcall XStoreAcquireLicenseForDurablesResult(ptr ptr)
@ stdcall XStoreCanAcquireLicenseForPackageAsync(ptr str ptr)
@ stdcall XStoreCanAcquireLicenseForPackageResult(ptr ptr)
@ stdcall XStoreCanAcquireLicenseForStoreIdAsync(ptr str ptr)
@ stdcall XStoreCanAcquireLicenseForStoreIdResult(ptr ptr)
@ stdcall XStoreShowPurchaseUIAsync(ptr str str str ptr)
@ stdcall XStoreShowPurchaseUIResult(ptr)
@ stdcall XStoreShowProductPageUIAsync(ptr str ptr)
@ stdcall XStoreShowProductPageUIResult(ptr)
@ stdcall XStoreShowRateAndReviewUIAsync(ptr ptr)
@ stdcall XStoreShowRateAndReviewUIResult(ptr)
@ stdcall XStoreShowRedeemTokenUIAsync(ptr str ptr long long ptr)
@ stdcall XStoreShowRedeemTokenUIResult(ptr)
@ stdcall XStoreGetUserCollectionsIdAsync(ptr str str ptr)
@ stdcall XStoreGetUserCollectionsIdResultSize(ptr ptr)
@ stdcall XStoreGetUserCollectionsIdResult(ptr long ptr)
@ stdcall XStoreGetUserPurchaseIdAsync(ptr str str ptr)
@ stdcall XStoreGetUserPurchaseIdResultSize(ptr ptr)
@ stdcall XStoreGetUserPurchaseIdResult(ptr long ptr)
@ stdcall XStoreQueryLicenseTokenAsync(ptr ptr long str ptr)
@ stdcall XStoreQueryLicenseTokenResultSize(ptr ptr)
@ stdcall XStoreQueryLicenseTokenResult(ptr long ptr)
