/*** Autogenerated by WIDL 11.15 from xgamestreaming.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __xgamestreaming_h__
#define __xgamestreaming_h__

/* Forward declarations */

#ifndef __IXGameStreamingImpl_FWD_DEFINED__
#define __IXGameStreamingImpl_FWD_DEFINED__
typedef interface IXGameStreamingImpl IXGameStreamingImpl;
#ifdef __cplusplus
interface IXGameStreamingImpl;
#endif /* __cplusplus */
#endif

#ifndef __IXGameStreamingImpl2_FWD_DEFINED__
#define __IXGameStreamingImpl2_FWD_DEFINED__
typedef interface IXGameStreamingImpl2 IXGameStreamingImpl2;
#ifdef __cplusplus
interface IXGameStreamingImpl2;
#endif /* __cplusplus */
#endif

#ifndef __IXGameStreamingImpl3_FWD_DEFINED__
#define __IXGameStreamingImpl3_FWD_DEFINED__
typedef interface IXGameStreamingImpl3 IXGameStreamingImpl3;
#ifdef __cplusplus
interface IXGameStreamingImpl3;
#endif /* __cplusplus */
#endif

#ifndef __XGameStreamingImpl_FWD_DEFINED__
#define __XGameStreamingImpl_FWD_DEFINED__
#ifdef __cplusplus
typedef class XGameStreamingImpl XGameStreamingImpl;
#else
typedef struct XGameStreamingImpl XGameStreamingImpl;
#endif /* defined __cplusplus */
#endif /* defined __XGameStreamingImpl_FWD_DEFINED__ */

/* Headers for imported files */

#include <unknwn.h>
#include <xgameruntimetypes.h>
#include <xtaskqueue.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
enum class XGameStreamingClientProperty : UINT32
{                                               
    None,                                       
    StreamPhysicalDimensions,                   
    TouchInputEnabled,                          
    TouchBundleVersion,                         
    IPAddress,                                  
    SessionId,                                  
    DisplayDetails,                             
};                                              
enum class XGameStreamingConnectionState : UINT32
{                                                
    Disconnected,                                
    Connected,                                   
};                                               
enum class XGameStreamingGamepadPhysicality : UINT64
{                                                   
    None                     = 0x0000000000000000,  
    DPadUpPhysical           = 0x0000000000000001,  
    DPadDownPhysical         = 0x0000000000000002,  
    DPadLeftPhysical         = 0x0000000000000004,  
    DPadRightPhysical        = 0x0000000000000008,  
    MenuPhysical             = 0x0000000000000010,  
    ViewPhysical             = 0x0000000000000020,  
    LeftThumbstickPhysical   = 0x0000000000000040,  
    RightThumbstickPhysical  = 0x0000000000000080,  
    LeftShoulderPhysical     = 0x0000000000000100,  
    RightShoulderPhysical    = 0x0000000000000200,  
    APhysical                = 0x0000000000001000,  
    BPhysical                = 0x0000000000002000,  
    XPhysical                = 0x0000000000004000,  
    YPhysical                = 0x0000000000008000,  
    LeftTriggerPhysical      = 0x0000000000010000,  
    RightTriggerPhysical     = 0x0000000000020000,  
    LeftThumbstickXPhysical  = 0x0000000000040000,  
    LeftThumbstickYPhysical  = 0x0000000000080000,  
    RightThumbstickXPhysical = 0x0000000000100000,  
    RightThumbstickYPhysical = 0x0000000000200000,  
    ButtonsPhysical          = 0x000000000000F3FF,  
    AnalogsPhysical          = 0x00000000003F0000,  
    AllPhysical              = 0x00000000003FF3FF,  
    DPadUpVirtual            = 0x0000000100000000,  
    DPadDownVirtual          = 0x0000000200000000,  
    DPadLeftVirtual          = 0x0000000400000000,  
    DPadRightVirtual         = 0x0000000800000000,  
    MenuVirtual              = 0x0000001000000000,  
    ViewVirtual              = 0x0000002000000000,  
    LeftThumbstickVirtual    = 0x0000004000000000,  
    RightThumbstickVirtual   = 0x0000008000000000,  
    LeftShoulderVirtual      = 0x0000010000000000,  
    RightShoulderVirtual     = 0x0000020000000000,  
    AVirtual                 = 0x0000100000000000,  
    BVirtual                 = 0x0000200000000000,  
    XVirtual                 = 0x0000400000000000,  
    YVirtual                 = 0x0000800000000000,  
    LeftTriggerVirtual       = 0x0001000000000000,  
    RightTriggerVirtual      = 0x0002000000000000,  
    LeftThumbstickXVirtual   = 0x0004000000000000,  
    LeftThumbstickYVirtual   = 0x0008000000000000,  
    RightThumbstickXVirtual  = 0x0010000000000000,  
    RightThumbstickYVirtual  = 0x0020000000000000,  
    ButtonsVirtual           = 0x0000F3FF00000000,  
    AnalogsVirtual           = 0x003F000000000000,  
    AllVirtual               = 0x003FF3FF00000000,  
};                                                  
enum class XGameStreamingTouchControlsStateOperationKind : UINT32
{                                                                
    Replace,                                                     
};                                                               
enum class XGameStreamingTouchControlsStateValueKind : UINT32
{                                                            
    Boolean,                                                 
    Integer,                                                 
    Double,                                                  
    String,                                                  
};                                                           
enum class XGameStreamingVideoFlags : UINT32
{                                           
    None                      = 0x00,       
    SupportsCustomAspectRatio = 0x01,       
    SupportsPresentScaling    = 0x02,       
};                                          
#elif defined(__WINESRC__)
typedef enum XGameStreamingClientProperty {
    XGameStreamingClientProperty_None = 0,
    XGameStreamingClientProperty_StreamPhysicalDimensions = 1,
    XGameStreamingClientProperty_TouchInputEnabled = 2,
    XGameStreamingClientProperty_TouchBundleVersion = 3,
    XGameStreamingClientProperty_IPAddress = 4,
    XGameStreamingClientProperty_SessionId = 5,
    XGameStreamingClientProperty_DisplayDetails = 6
} XGameStreamingClientProperty;
typedef enum XGameStreamingConnectionState {
    XGameStreamingConnectionState_Disconnected = 0,
    XGameStreamingConnectionState_Connected = 1
} XGameStreamingConnectionState;
typedef UINT64 XGameStreamingGamepadPhysicality;
typedef enum XGameStreamingTouchControlsStateOperationKind {
    XGameStreamingTouchControlsStateOperationKind_Replace = 0
} XGameStreamingTouchControlsStateOperationKind;
typedef enum XGameStreamingTouchControlsStateValueKind {
    XGameStreamingTouchControlsStateValueKind_Boolean = 0,
    XGameStreamingTouchControlsStateValueKind_Integer = 1,
    XGameStreamingTouchControlsStateValueKind_Double = 2,
    XGameStreamingTouchControlsStateValueKind_String = 3
} XGameStreamingTouchControlsStateValueKind;
typedef enum XGameStreamingVideoFlags {
    XGameStreamingVideoFlags_None = 0x0,
    XGameStreamingVideoFlags_SupportsCustomAspectRatio = 0x1,
    XGameStreamingVideoFlags_SupportsPresentScaling = 0x2
} XGameStreamingVideoFlags;
#endif
typedef UINT64 XGameStreamingClientId;
typedef UINT64 D3D12XBOX_FRAME_PIPELINE_TOKEN;
typedef struct IGameInputReading IGameInputReading;
typedef struct XGameStreamingDisplayDetails XGameStreamingDisplayDetails;
typedef struct XGameStreamingTouchControlsStateOperation XGameStreamingTouchControlsStateOperation;
typedef struct XGameStreamingTouchControlsStateValue XGameStreamingTouchControlsStateValue;
typedef void __stdcall  XGameStreamingClientPropertiesChangedCallback(void *context,XGameStreamingClientId client,UINT32 updatedPropertiesCount,XGameStreamingClientProperty *updatedProperties);
typedef void __stdcall  XGameStreamingConnectionStateChangedCallback(void *context,XGameStreamingClientId client,XGameStreamingConnectionState state);
struct XGameStreamingDisplayDetails {
    UINT32 preferredWidth;
    UINT32 preferredHeight;
    RECT safeArea;
    UINT32 maxPixels;
    UINT32 maxWidth;
    UINT32 maxHeight;
    XGameStreamingVideoFlags flags;
};
struct XGameStreamingTouchControlsStateValue {
    XGameStreamingTouchControlsStateValueKind valueKind;
    __C89_NAMELESS union {
        BOOLEAN booleanValue;
        INT64 integerValue;
        double doubleValue;
        const char *stringValue;
    } __C89_NAMELESSUNIONNAME;
};
struct XGameStreamingTouchControlsStateOperation {
    XGameStreamingTouchControlsStateOperationKind operationKind;
    const char *path;
    XGameStreamingTouchControlsStateValue value;
};
#ifdef __WINESRC__
/*****************************************************************************
 * IXGameStreamingImpl interface
 */
#ifndef __IXGameStreamingImpl_INTERFACE_DEFINED__
#define __IXGameStreamingImpl_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXGameStreamingImpl, 0x8aff07f5, 0xa1bf, 0x4db8, 0x80,0xa5, 0x31,0xcc,0xa0,0xde,0x51,0xb7);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("8aff07f5-a1bf-4db8-80a5-31cca0de51b7")
IXGameStreamingImpl : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE XGameStreamingInitialize(
        ) = 0;

    virtual void STDMETHODCALLTYPE XGameStreamingUninitialize(
        ) = 0;

    virtual BOOLEAN STDMETHODCALLTYPE XGameStreamingIsStreaming(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameStreamingRegisterClientPropertiesChanged(
        XGameStreamingClientId client,
        XTaskQueueHandle queue,
        void *context,
        XGameStreamingClientPropertiesChangedCallback *callback,
        XTaskQueueRegistrationToken *token) = 0;

    virtual BOOLEAN STDMETHODCALLTYPE XGameStreamingUnregisterClientPropertiesChanged(
        XGameStreamingClientId client,
        XTaskQueueRegistrationToken token,
        BOOLEAN wait) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameStreamingGetStreamPhysicalDimensions(
        XGameStreamingClientId client,
        UINT32 *horizontalMm,
        UINT32 *verticalMm) = 0;

    virtual UINT32 STDMETHODCALLTYPE XGameStreamingGetClientCount(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameStreamingGetClients(
        UINT32 clientCount,
        XGameStreamingClientId clients[],
        UINT32 *clientsUsed) = 0;

    virtual XGameStreamingConnectionState STDMETHODCALLTYPE XGameStreamingGetConnectionState(
        XGameStreamingClientId client) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameStreamingRegisterConnectionStateChanged(
        XTaskQueueHandle queue,
        void *context,
        XGameStreamingConnectionStateChangedCallback *callback,
        XTaskQueueRegistrationToken *token) = 0;

    virtual BOOLEAN STDMETHODCALLTYPE XGameStreamingUnregisterConnectionStateChanged(
        XTaskQueueRegistrationToken token,
        BOOLEAN wait) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameStreamingGetStreamAddedLatency(
        XGameStreamingClientId client,
        UINT32 *averageInputLatencyUs,
        UINT32 *averageOutputLatencyUs,
        UINT32 *standardDeviationUs) = 0;

    virtual SIZE_T STDMETHODCALLTYPE XGameStreamingGetServerLocationNameSize(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameStreamingGetServerLocationName(
        SIZE_T serverLocationNameSize,
        char *serverLocationName) = 0;

    virtual void STDMETHODCALLTYPE XGameStreamingHideTouchControls(
        ) = 0;

    virtual void STDMETHODCALLTYPE XGameStreamingShowTouchControlLayout(
        const char *layout) = 0;

    virtual void STDMETHODCALLTYPE XGameStreamingHideTouchControlsOnClient(
        XGameStreamingClientId client) = 0;

    virtual void STDMETHODCALLTYPE XGameStreamingShowTouchControlLayoutOnClient(
        XGameStreamingClientId client,
        const char *layout) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameStreamingIsTouchInputEnabled(
        XGameStreamingClientId client,
        BOOLEAN *touchInputEnabled) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameStreamingGetLastFrameDisplayed(
        XGameStreamingClientId client,
        D3D12XBOX_FRAME_PIPELINE_TOKEN *framePipelineToken) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameStreamingGetAssociatedFrame(
        IGameInputReading *gamepadReading,
        D3D12XBOX_FRAME_PIPELINE_TOKEN *framePipelineToken) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameStreamingGetGamepadPhysicality(
        IGameInputReading *gamepadReading,
        XGameStreamingGamepadPhysicality *gamepadPhysicality) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameStreamingUpdateTouchControlsState(
        SIZE_T operationCount,
        const XGameStreamingTouchControlsStateOperation operations[]) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameStreamingUpdateTouchControlsStateOnClient(
        XGameStreamingClientId client,
        SIZE_T operationCount,
        const XGameStreamingTouchControlsStateOperation operations[]) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameStreamingShowTouchControlsWithStateUpdate(
        const char *layout,
        SIZE_T operationCount,
        const XGameStreamingTouchControlsStateOperation operations[]) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameStreamingShowTouchControlsWithStateUpdateOnClient(
        XGameStreamingClientId client,
        const char *layout,
        SIZE_T operationCount,
        const XGameStreamingTouchControlsStateOperation operations[]) = 0;

    virtual SIZE_T STDMETHODCALLTYPE XGameStreamingGetTouchBundleVersionNameSize(
        XGameStreamingClientId client) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameStreamingGetTouchBundleVersion(
        XGameStreamingClientId client,
        XVersion *version,
        SIZE_T versionNameSize,
        char *versionName) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameStreamingGetClientIPAddress(
        XGameStreamingClientId client,
        SIZE_T ipAddressSize,
        char *ipAddress) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXGameStreamingImpl, 0x8aff07f5, 0xa1bf, 0x4db8, 0x80,0xa5, 0x31,0xcc,0xa0,0xde,0x51,0xb7)
#endif
#else
typedef struct IXGameStreamingImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXGameStreamingImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXGameStreamingImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXGameStreamingImpl *This);

    /*** IXGameStreamingImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XGameStreamingInitialize)(
        IXGameStreamingImpl *This);

    void (STDMETHODCALLTYPE *XGameStreamingUninitialize)(
        IXGameStreamingImpl *This);

    BOOLEAN (STDMETHODCALLTYPE *XGameStreamingIsStreaming)(
        IXGameStreamingImpl *This);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingRegisterClientPropertiesChanged)(
        IXGameStreamingImpl *This,
        XGameStreamingClientId client,
        XTaskQueueHandle queue,
        void *context,
        XGameStreamingClientPropertiesChangedCallback *callback,
        XTaskQueueRegistrationToken *token);

    BOOLEAN (STDMETHODCALLTYPE *XGameStreamingUnregisterClientPropertiesChanged)(
        IXGameStreamingImpl *This,
        XGameStreamingClientId client,
        XTaskQueueRegistrationToken token,
        BOOLEAN wait);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetStreamPhysicalDimensions)(
        IXGameStreamingImpl *This,
        XGameStreamingClientId client,
        UINT32 *horizontalMm,
        UINT32 *verticalMm);

    UINT32 (STDMETHODCALLTYPE *XGameStreamingGetClientCount)(
        IXGameStreamingImpl *This);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetClients)(
        IXGameStreamingImpl *This,
        UINT32 clientCount,
        XGameStreamingClientId clients[],
        UINT32 *clientsUsed);

    XGameStreamingConnectionState (STDMETHODCALLTYPE *XGameStreamingGetConnectionState)(
        IXGameStreamingImpl *This,
        XGameStreamingClientId client);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingRegisterConnectionStateChanged)(
        IXGameStreamingImpl *This,
        XTaskQueueHandle queue,
        void *context,
        XGameStreamingConnectionStateChangedCallback *callback,
        XTaskQueueRegistrationToken *token);

    BOOLEAN (STDMETHODCALLTYPE *XGameStreamingUnregisterConnectionStateChanged)(
        IXGameStreamingImpl *This,
        XTaskQueueRegistrationToken token,
        BOOLEAN wait);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetStreamAddedLatency)(
        IXGameStreamingImpl *This,
        XGameStreamingClientId client,
        UINT32 *averageInputLatencyUs,
        UINT32 *averageOutputLatencyUs,
        UINT32 *standardDeviationUs);

    SIZE_T (STDMETHODCALLTYPE *XGameStreamingGetServerLocationNameSize)(
        IXGameStreamingImpl *This);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetServerLocationName)(
        IXGameStreamingImpl *This,
        SIZE_T serverLocationNameSize,
        char *serverLocationName);

    void (STDMETHODCALLTYPE *XGameStreamingHideTouchControls)(
        IXGameStreamingImpl *This);

    void (STDMETHODCALLTYPE *XGameStreamingShowTouchControlLayout)(
        IXGameStreamingImpl *This,
        const char *layout);

    void (STDMETHODCALLTYPE *XGameStreamingHideTouchControlsOnClient)(
        IXGameStreamingImpl *This,
        XGameStreamingClientId client);

    void (STDMETHODCALLTYPE *XGameStreamingShowTouchControlLayoutOnClient)(
        IXGameStreamingImpl *This,
        XGameStreamingClientId client,
        const char *layout);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingIsTouchInputEnabled)(
        IXGameStreamingImpl *This,
        XGameStreamingClientId client,
        BOOLEAN *touchInputEnabled);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetLastFrameDisplayed)(
        IXGameStreamingImpl *This,
        XGameStreamingClientId client,
        D3D12XBOX_FRAME_PIPELINE_TOKEN *framePipelineToken);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetAssociatedFrame)(
        IXGameStreamingImpl *This,
        IGameInputReading *gamepadReading,
        D3D12XBOX_FRAME_PIPELINE_TOKEN *framePipelineToken);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetGamepadPhysicality)(
        IXGameStreamingImpl *This,
        IGameInputReading *gamepadReading,
        XGameStreamingGamepadPhysicality *gamepadPhysicality);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingUpdateTouchControlsState)(
        IXGameStreamingImpl *This,
        SIZE_T operationCount,
        const XGameStreamingTouchControlsStateOperation operations[]);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingUpdateTouchControlsStateOnClient)(
        IXGameStreamingImpl *This,
        XGameStreamingClientId client,
        SIZE_T operationCount,
        const XGameStreamingTouchControlsStateOperation operations[]);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingShowTouchControlsWithStateUpdate)(
        IXGameStreamingImpl *This,
        const char *layout,
        SIZE_T operationCount,
        const XGameStreamingTouchControlsStateOperation operations[]);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingShowTouchControlsWithStateUpdateOnClient)(
        IXGameStreamingImpl *This,
        XGameStreamingClientId client,
        const char *layout,
        SIZE_T operationCount,
        const XGameStreamingTouchControlsStateOperation operations[]);

    SIZE_T (STDMETHODCALLTYPE *XGameStreamingGetTouchBundleVersionNameSize)(
        IXGameStreamingImpl *This,
        XGameStreamingClientId client);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetTouchBundleVersion)(
        IXGameStreamingImpl *This,
        XGameStreamingClientId client,
        XVersion *version,
        SIZE_T versionNameSize,
        char *versionName);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetClientIPAddress)(
        IXGameStreamingImpl *This,
        XGameStreamingClientId client,
        SIZE_T ipAddressSize,
        char *ipAddress);

    END_INTERFACE
} IXGameStreamingImplVtbl;

interface IXGameStreamingImpl {
    CONST_VTBL IXGameStreamingImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXGameStreamingImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXGameStreamingImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXGameStreamingImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IXGameStreamingImpl methods ***/
#define IXGameStreamingImpl_XGameStreamingInitialize(This) (This)->lpVtbl->XGameStreamingInitialize(This)
#define IXGameStreamingImpl_XGameStreamingUninitialize(This) (This)->lpVtbl->XGameStreamingUninitialize(This)
#define IXGameStreamingImpl_XGameStreamingIsStreaming(This) (This)->lpVtbl->XGameStreamingIsStreaming(This)
#define IXGameStreamingImpl_XGameStreamingRegisterClientPropertiesChanged(This,client,queue,context,callback,token) (This)->lpVtbl->XGameStreamingRegisterClientPropertiesChanged(This,client,queue,context,callback,token)
#define IXGameStreamingImpl_XGameStreamingUnregisterClientPropertiesChanged(This,client,token,wait) (This)->lpVtbl->XGameStreamingUnregisterClientPropertiesChanged(This,client,token,wait)
#define IXGameStreamingImpl_XGameStreamingGetStreamPhysicalDimensions(This,client,horizontalMm,verticalMm) (This)->lpVtbl->XGameStreamingGetStreamPhysicalDimensions(This,client,horizontalMm,verticalMm)
#define IXGameStreamingImpl_XGameStreamingGetClientCount(This) (This)->lpVtbl->XGameStreamingGetClientCount(This)
#define IXGameStreamingImpl_XGameStreamingGetClients(This,clientCount,clients,clientsUsed) (This)->lpVtbl->XGameStreamingGetClients(This,clientCount,clients,clientsUsed)
#define IXGameStreamingImpl_XGameStreamingGetConnectionState(This,client) (This)->lpVtbl->XGameStreamingGetConnectionState(This,client)
#define IXGameStreamingImpl_XGameStreamingRegisterConnectionStateChanged(This,queue,context,callback,token) (This)->lpVtbl->XGameStreamingRegisterConnectionStateChanged(This,queue,context,callback,token)
#define IXGameStreamingImpl_XGameStreamingUnregisterConnectionStateChanged(This,token,wait) (This)->lpVtbl->XGameStreamingUnregisterConnectionStateChanged(This,token,wait)
#define IXGameStreamingImpl_XGameStreamingGetStreamAddedLatency(This,client,averageInputLatencyUs,averageOutputLatencyUs,standardDeviationUs) (This)->lpVtbl->XGameStreamingGetStreamAddedLatency(This,client,averageInputLatencyUs,averageOutputLatencyUs,standardDeviationUs)
#define IXGameStreamingImpl_XGameStreamingGetServerLocationNameSize(This) (This)->lpVtbl->XGameStreamingGetServerLocationNameSize(This)
#define IXGameStreamingImpl_XGameStreamingGetServerLocationName(This,serverLocationNameSize,serverLocationName) (This)->lpVtbl->XGameStreamingGetServerLocationName(This,serverLocationNameSize,serverLocationName)
#define IXGameStreamingImpl_XGameStreamingHideTouchControls(This) (This)->lpVtbl->XGameStreamingHideTouchControls(This)
#define IXGameStreamingImpl_XGameStreamingShowTouchControlLayout(This,layout) (This)->lpVtbl->XGameStreamingShowTouchControlLayout(This,layout)
#define IXGameStreamingImpl_XGameStreamingHideTouchControlsOnClient(This,client) (This)->lpVtbl->XGameStreamingHideTouchControlsOnClient(This,client)
#define IXGameStreamingImpl_XGameStreamingShowTouchControlLayoutOnClient(This,client,layout) (This)->lpVtbl->XGameStreamingShowTouchControlLayoutOnClient(This,client,layout)
#define IXGameStreamingImpl_XGameStreamingIsTouchInputEnabled(This,client,touchInputEnabled) (This)->lpVtbl->XGameStreamingIsTouchInputEnabled(This,client,touchInputEnabled)
#define IXGameStreamingImpl_XGameStreamingGetLastFrameDisplayed(This,client,framePipelineToken) (This)->lpVtbl->XGameStreamingGetLastFrameDisplayed(This,client,framePipelineToken)
#define IXGameStreamingImpl_XGameStreamingGetAssociatedFrame(This,gamepadReading,framePipelineToken) (This)->lpVtbl->XGameStreamingGetAssociatedFrame(This,gamepadReading,framePipelineToken)
#define IXGameStreamingImpl_XGameStreamingGetGamepadPhysicality(This,gamepadReading,gamepadPhysicality) (This)->lpVtbl->XGameStreamingGetGamepadPhysicality(This,gamepadReading,gamepadPhysicality)
#define IXGameStreamingImpl_XGameStreamingUpdateTouchControlsState(This,operationCount,operations) (This)->lpVtbl->XGameStreamingUpdateTouchControlsState(This,operationCount,operations)
#define IXGameStreamingImpl_XGameStreamingUpdateTouchControlsStateOnClient(This,client,operationCount,operations) (This)->lpVtbl->XGameStreamingUpdateTouchControlsStateOnClient(This,client,operationCount,operations)
#define IXGameStreamingImpl_XGameStreamingShowTouchControlsWithStateUpdate(This,layout,operationCount,operations) (This)->lpVtbl->XGameStreamingShowTouchControlsWithStateUpdate(This,layout,operationCount,operations)
#define IXGameStreamingImpl_XGameStreamingShowTouchControlsWithStateUpdateOnClient(This,client,layout,operationCount,operations) (This)->lpVtbl->XGameStreamingShowTouchControlsWithStateUpdateOnClient(This,client,layout,operationCount,operations)
#define IXGameStreamingImpl_XGameStreamingGetTouchBundleVersionNameSize(This,client) (This)->lpVtbl->XGameStreamingGetTouchBundleVersionNameSize(This,client)
#define IXGameStreamingImpl_XGameStreamingGetTouchBundleVersion(This,client,version,versionNameSize,versionName) (This)->lpVtbl->XGameStreamingGetTouchBundleVersion(This,client,version,versionNameSize,versionName)
#define IXGameStreamingImpl_XGameStreamingGetClientIPAddress(This,client,ipAddressSize,ipAddress) (This)->lpVtbl->XGameStreamingGetClientIPAddress(This,client,ipAddressSize,ipAddress)
#else
/*** IUnknown methods ***/
static inline HRESULT IXGameStreamingImpl_QueryInterface(IXGameStreamingImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXGameStreamingImpl_AddRef(IXGameStreamingImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXGameStreamingImpl_Release(IXGameStreamingImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IXGameStreamingImpl methods ***/
static inline HRESULT IXGameStreamingImpl_XGameStreamingInitialize(IXGameStreamingImpl* This) {
    return This->lpVtbl->XGameStreamingInitialize(This);
}
static inline void IXGameStreamingImpl_XGameStreamingUninitialize(IXGameStreamingImpl* This) {
    This->lpVtbl->XGameStreamingUninitialize(This);
}
static inline BOOLEAN IXGameStreamingImpl_XGameStreamingIsStreaming(IXGameStreamingImpl* This) {
    return This->lpVtbl->XGameStreamingIsStreaming(This);
}
static inline HRESULT IXGameStreamingImpl_XGameStreamingRegisterClientPropertiesChanged(IXGameStreamingImpl* This,XGameStreamingClientId client,XTaskQueueHandle queue,void *context,XGameStreamingClientPropertiesChangedCallback *callback,XTaskQueueRegistrationToken *token) {
    return This->lpVtbl->XGameStreamingRegisterClientPropertiesChanged(This,client,queue,context,callback,token);
}
static inline BOOLEAN IXGameStreamingImpl_XGameStreamingUnregisterClientPropertiesChanged(IXGameStreamingImpl* This,XGameStreamingClientId client,XTaskQueueRegistrationToken token,BOOLEAN wait) {
    return This->lpVtbl->XGameStreamingUnregisterClientPropertiesChanged(This,client,token,wait);
}
static inline HRESULT IXGameStreamingImpl_XGameStreamingGetStreamPhysicalDimensions(IXGameStreamingImpl* This,XGameStreamingClientId client,UINT32 *horizontalMm,UINT32 *verticalMm) {
    return This->lpVtbl->XGameStreamingGetStreamPhysicalDimensions(This,client,horizontalMm,verticalMm);
}
static inline UINT32 IXGameStreamingImpl_XGameStreamingGetClientCount(IXGameStreamingImpl* This) {
    return This->lpVtbl->XGameStreamingGetClientCount(This);
}
static inline HRESULT IXGameStreamingImpl_XGameStreamingGetClients(IXGameStreamingImpl* This,UINT32 clientCount,XGameStreamingClientId clients[],UINT32 *clientsUsed) {
    return This->lpVtbl->XGameStreamingGetClients(This,clientCount,clients,clientsUsed);
}
static inline XGameStreamingConnectionState IXGameStreamingImpl_XGameStreamingGetConnectionState(IXGameStreamingImpl* This,XGameStreamingClientId client) {
    return This->lpVtbl->XGameStreamingGetConnectionState(This,client);
}
static inline HRESULT IXGameStreamingImpl_XGameStreamingRegisterConnectionStateChanged(IXGameStreamingImpl* This,XTaskQueueHandle queue,void *context,XGameStreamingConnectionStateChangedCallback *callback,XTaskQueueRegistrationToken *token) {
    return This->lpVtbl->XGameStreamingRegisterConnectionStateChanged(This,queue,context,callback,token);
}
static inline BOOLEAN IXGameStreamingImpl_XGameStreamingUnregisterConnectionStateChanged(IXGameStreamingImpl* This,XTaskQueueRegistrationToken token,BOOLEAN wait) {
    return This->lpVtbl->XGameStreamingUnregisterConnectionStateChanged(This,token,wait);
}
static inline HRESULT IXGameStreamingImpl_XGameStreamingGetStreamAddedLatency(IXGameStreamingImpl* This,XGameStreamingClientId client,UINT32 *averageInputLatencyUs,UINT32 *averageOutputLatencyUs,UINT32 *standardDeviationUs) {
    return This->lpVtbl->XGameStreamingGetStreamAddedLatency(This,client,averageInputLatencyUs,averageOutputLatencyUs,standardDeviationUs);
}
static inline SIZE_T IXGameStreamingImpl_XGameStreamingGetServerLocationNameSize(IXGameStreamingImpl* This) {
    return This->lpVtbl->XGameStreamingGetServerLocationNameSize(This);
}
static inline HRESULT IXGameStreamingImpl_XGameStreamingGetServerLocationName(IXGameStreamingImpl* This,SIZE_T serverLocationNameSize,char *serverLocationName) {
    return This->lpVtbl->XGameStreamingGetServerLocationName(This,serverLocationNameSize,serverLocationName);
}
static inline void IXGameStreamingImpl_XGameStreamingHideTouchControls(IXGameStreamingImpl* This) {
    This->lpVtbl->XGameStreamingHideTouchControls(This);
}
static inline void IXGameStreamingImpl_XGameStreamingShowTouchControlLayout(IXGameStreamingImpl* This,const char *layout) {
    This->lpVtbl->XGameStreamingShowTouchControlLayout(This,layout);
}
static inline void IXGameStreamingImpl_XGameStreamingHideTouchControlsOnClient(IXGameStreamingImpl* This,XGameStreamingClientId client) {
    This->lpVtbl->XGameStreamingHideTouchControlsOnClient(This,client);
}
static inline void IXGameStreamingImpl_XGameStreamingShowTouchControlLayoutOnClient(IXGameStreamingImpl* This,XGameStreamingClientId client,const char *layout) {
    This->lpVtbl->XGameStreamingShowTouchControlLayoutOnClient(This,client,layout);
}
static inline HRESULT IXGameStreamingImpl_XGameStreamingIsTouchInputEnabled(IXGameStreamingImpl* This,XGameStreamingClientId client,BOOLEAN *touchInputEnabled) {
    return This->lpVtbl->XGameStreamingIsTouchInputEnabled(This,client,touchInputEnabled);
}
static inline HRESULT IXGameStreamingImpl_XGameStreamingGetLastFrameDisplayed(IXGameStreamingImpl* This,XGameStreamingClientId client,D3D12XBOX_FRAME_PIPELINE_TOKEN *framePipelineToken) {
    return This->lpVtbl->XGameStreamingGetLastFrameDisplayed(This,client,framePipelineToken);
}
static inline HRESULT IXGameStreamingImpl_XGameStreamingGetAssociatedFrame(IXGameStreamingImpl* This,IGameInputReading *gamepadReading,D3D12XBOX_FRAME_PIPELINE_TOKEN *framePipelineToken) {
    return This->lpVtbl->XGameStreamingGetAssociatedFrame(This,gamepadReading,framePipelineToken);
}
static inline HRESULT IXGameStreamingImpl_XGameStreamingGetGamepadPhysicality(IXGameStreamingImpl* This,IGameInputReading *gamepadReading,XGameStreamingGamepadPhysicality *gamepadPhysicality) {
    return This->lpVtbl->XGameStreamingGetGamepadPhysicality(This,gamepadReading,gamepadPhysicality);
}
static inline HRESULT IXGameStreamingImpl_XGameStreamingUpdateTouchControlsState(IXGameStreamingImpl* This,SIZE_T operationCount,const XGameStreamingTouchControlsStateOperation operations[]) {
    return This->lpVtbl->XGameStreamingUpdateTouchControlsState(This,operationCount,operations);
}
static inline HRESULT IXGameStreamingImpl_XGameStreamingUpdateTouchControlsStateOnClient(IXGameStreamingImpl* This,XGameStreamingClientId client,SIZE_T operationCount,const XGameStreamingTouchControlsStateOperation operations[]) {
    return This->lpVtbl->XGameStreamingUpdateTouchControlsStateOnClient(This,client,operationCount,operations);
}
static inline HRESULT IXGameStreamingImpl_XGameStreamingShowTouchControlsWithStateUpdate(IXGameStreamingImpl* This,const char *layout,SIZE_T operationCount,const XGameStreamingTouchControlsStateOperation operations[]) {
    return This->lpVtbl->XGameStreamingShowTouchControlsWithStateUpdate(This,layout,operationCount,operations);
}
static inline HRESULT IXGameStreamingImpl_XGameStreamingShowTouchControlsWithStateUpdateOnClient(IXGameStreamingImpl* This,XGameStreamingClientId client,const char *layout,SIZE_T operationCount,const XGameStreamingTouchControlsStateOperation operations[]) {
    return This->lpVtbl->XGameStreamingShowTouchControlsWithStateUpdateOnClient(This,client,layout,operationCount,operations);
}
static inline SIZE_T IXGameStreamingImpl_XGameStreamingGetTouchBundleVersionNameSize(IXGameStreamingImpl* This,XGameStreamingClientId client) {
    return This->lpVtbl->XGameStreamingGetTouchBundleVersionNameSize(This,client);
}
static inline HRESULT IXGameStreamingImpl_XGameStreamingGetTouchBundleVersion(IXGameStreamingImpl* This,XGameStreamingClientId client,XVersion *version,SIZE_T versionNameSize,char *versionName) {
    return This->lpVtbl->XGameStreamingGetTouchBundleVersion(This,client,version,versionNameSize,versionName);
}
static inline HRESULT IXGameStreamingImpl_XGameStreamingGetClientIPAddress(IXGameStreamingImpl* This,XGameStreamingClientId client,SIZE_T ipAddressSize,char *ipAddress) {
    return This->lpVtbl->XGameStreamingGetClientIPAddress(This,client,ipAddressSize,ipAddress);
}
#endif
#endif

#endif


#endif  /* __IXGameStreamingImpl_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IXGameStreamingImpl2 interface
 */
#ifndef __IXGameStreamingImpl2_INTERFACE_DEFINED__
#define __IXGameStreamingImpl2_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXGameStreamingImpl2, 0x5f5e5169, 0x746c, 0x4001, 0xad,0x1c, 0xda,0x72,0x8d,0x01,0xc9,0xeb);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("5f5e5169-746c-4001-ad1c-da728d01c9eb")
IXGameStreamingImpl2 : public IXGameStreamingImpl
{
    virtual HRESULT STDMETHODCALLTYPE XGameStreamingGetSessionId(
        XGameStreamingClientId client,
        SIZE_T sessionIdSize,
        char *sessionId,
        SIZE_T *sessionIdUsed) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXGameStreamingImpl2, 0x5f5e5169, 0x746c, 0x4001, 0xad,0x1c, 0xda,0x72,0x8d,0x01,0xc9,0xeb)
#endif
#else
typedef struct IXGameStreamingImpl2Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXGameStreamingImpl2 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXGameStreamingImpl2 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXGameStreamingImpl2 *This);

    /*** IXGameStreamingImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XGameStreamingInitialize)(
        IXGameStreamingImpl2 *This);

    void (STDMETHODCALLTYPE *XGameStreamingUninitialize)(
        IXGameStreamingImpl2 *This);

    BOOLEAN (STDMETHODCALLTYPE *XGameStreamingIsStreaming)(
        IXGameStreamingImpl2 *This);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingRegisterClientPropertiesChanged)(
        IXGameStreamingImpl2 *This,
        XGameStreamingClientId client,
        XTaskQueueHandle queue,
        void *context,
        XGameStreamingClientPropertiesChangedCallback *callback,
        XTaskQueueRegistrationToken *token);

    BOOLEAN (STDMETHODCALLTYPE *XGameStreamingUnregisterClientPropertiesChanged)(
        IXGameStreamingImpl2 *This,
        XGameStreamingClientId client,
        XTaskQueueRegistrationToken token,
        BOOLEAN wait);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetStreamPhysicalDimensions)(
        IXGameStreamingImpl2 *This,
        XGameStreamingClientId client,
        UINT32 *horizontalMm,
        UINT32 *verticalMm);

    UINT32 (STDMETHODCALLTYPE *XGameStreamingGetClientCount)(
        IXGameStreamingImpl2 *This);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetClients)(
        IXGameStreamingImpl2 *This,
        UINT32 clientCount,
        XGameStreamingClientId clients[],
        UINT32 *clientsUsed);

    XGameStreamingConnectionState (STDMETHODCALLTYPE *XGameStreamingGetConnectionState)(
        IXGameStreamingImpl2 *This,
        XGameStreamingClientId client);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingRegisterConnectionStateChanged)(
        IXGameStreamingImpl2 *This,
        XTaskQueueHandle queue,
        void *context,
        XGameStreamingConnectionStateChangedCallback *callback,
        XTaskQueueRegistrationToken *token);

    BOOLEAN (STDMETHODCALLTYPE *XGameStreamingUnregisterConnectionStateChanged)(
        IXGameStreamingImpl2 *This,
        XTaskQueueRegistrationToken token,
        BOOLEAN wait);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetStreamAddedLatency)(
        IXGameStreamingImpl2 *This,
        XGameStreamingClientId client,
        UINT32 *averageInputLatencyUs,
        UINT32 *averageOutputLatencyUs,
        UINT32 *standardDeviationUs);

    SIZE_T (STDMETHODCALLTYPE *XGameStreamingGetServerLocationNameSize)(
        IXGameStreamingImpl2 *This);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetServerLocationName)(
        IXGameStreamingImpl2 *This,
        SIZE_T serverLocationNameSize,
        char *serverLocationName);

    void (STDMETHODCALLTYPE *XGameStreamingHideTouchControls)(
        IXGameStreamingImpl2 *This);

    void (STDMETHODCALLTYPE *XGameStreamingShowTouchControlLayout)(
        IXGameStreamingImpl2 *This,
        const char *layout);

    void (STDMETHODCALLTYPE *XGameStreamingHideTouchControlsOnClient)(
        IXGameStreamingImpl2 *This,
        XGameStreamingClientId client);

    void (STDMETHODCALLTYPE *XGameStreamingShowTouchControlLayoutOnClient)(
        IXGameStreamingImpl2 *This,
        XGameStreamingClientId client,
        const char *layout);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingIsTouchInputEnabled)(
        IXGameStreamingImpl2 *This,
        XGameStreamingClientId client,
        BOOLEAN *touchInputEnabled);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetLastFrameDisplayed)(
        IXGameStreamingImpl2 *This,
        XGameStreamingClientId client,
        D3D12XBOX_FRAME_PIPELINE_TOKEN *framePipelineToken);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetAssociatedFrame)(
        IXGameStreamingImpl2 *This,
        IGameInputReading *gamepadReading,
        D3D12XBOX_FRAME_PIPELINE_TOKEN *framePipelineToken);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetGamepadPhysicality)(
        IXGameStreamingImpl2 *This,
        IGameInputReading *gamepadReading,
        XGameStreamingGamepadPhysicality *gamepadPhysicality);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingUpdateTouchControlsState)(
        IXGameStreamingImpl2 *This,
        SIZE_T operationCount,
        const XGameStreamingTouchControlsStateOperation operations[]);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingUpdateTouchControlsStateOnClient)(
        IXGameStreamingImpl2 *This,
        XGameStreamingClientId client,
        SIZE_T operationCount,
        const XGameStreamingTouchControlsStateOperation operations[]);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingShowTouchControlsWithStateUpdate)(
        IXGameStreamingImpl2 *This,
        const char *layout,
        SIZE_T operationCount,
        const XGameStreamingTouchControlsStateOperation operations[]);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingShowTouchControlsWithStateUpdateOnClient)(
        IXGameStreamingImpl2 *This,
        XGameStreamingClientId client,
        const char *layout,
        SIZE_T operationCount,
        const XGameStreamingTouchControlsStateOperation operations[]);

    SIZE_T (STDMETHODCALLTYPE *XGameStreamingGetTouchBundleVersionNameSize)(
        IXGameStreamingImpl2 *This,
        XGameStreamingClientId client);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetTouchBundleVersion)(
        IXGameStreamingImpl2 *This,
        XGameStreamingClientId client,
        XVersion *version,
        SIZE_T versionNameSize,
        char *versionName);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetClientIPAddress)(
        IXGameStreamingImpl2 *This,
        XGameStreamingClientId client,
        SIZE_T ipAddressSize,
        char *ipAddress);

    /*** IXGameStreamingImpl2 methods ***/
    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetSessionId)(
        IXGameStreamingImpl2 *This,
        XGameStreamingClientId client,
        SIZE_T sessionIdSize,
        char *sessionId,
        SIZE_T *sessionIdUsed);

    END_INTERFACE
} IXGameStreamingImpl2Vtbl;

interface IXGameStreamingImpl2 {
    CONST_VTBL IXGameStreamingImpl2Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXGameStreamingImpl2_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXGameStreamingImpl2_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXGameStreamingImpl2_Release(This) (This)->lpVtbl->Release(This)
/*** IXGameStreamingImpl methods ***/
#define IXGameStreamingImpl2_XGameStreamingInitialize(This) (This)->lpVtbl->XGameStreamingInitialize(This)
#define IXGameStreamingImpl2_XGameStreamingUninitialize(This) (This)->lpVtbl->XGameStreamingUninitialize(This)
#define IXGameStreamingImpl2_XGameStreamingIsStreaming(This) (This)->lpVtbl->XGameStreamingIsStreaming(This)
#define IXGameStreamingImpl2_XGameStreamingRegisterClientPropertiesChanged(This,client,queue,context,callback,token) (This)->lpVtbl->XGameStreamingRegisterClientPropertiesChanged(This,client,queue,context,callback,token)
#define IXGameStreamingImpl2_XGameStreamingUnregisterClientPropertiesChanged(This,client,token,wait) (This)->lpVtbl->XGameStreamingUnregisterClientPropertiesChanged(This,client,token,wait)
#define IXGameStreamingImpl2_XGameStreamingGetStreamPhysicalDimensions(This,client,horizontalMm,verticalMm) (This)->lpVtbl->XGameStreamingGetStreamPhysicalDimensions(This,client,horizontalMm,verticalMm)
#define IXGameStreamingImpl2_XGameStreamingGetClientCount(This) (This)->lpVtbl->XGameStreamingGetClientCount(This)
#define IXGameStreamingImpl2_XGameStreamingGetClients(This,clientCount,clients,clientsUsed) (This)->lpVtbl->XGameStreamingGetClients(This,clientCount,clients,clientsUsed)
#define IXGameStreamingImpl2_XGameStreamingGetConnectionState(This,client) (This)->lpVtbl->XGameStreamingGetConnectionState(This,client)
#define IXGameStreamingImpl2_XGameStreamingRegisterConnectionStateChanged(This,queue,context,callback,token) (This)->lpVtbl->XGameStreamingRegisterConnectionStateChanged(This,queue,context,callback,token)
#define IXGameStreamingImpl2_XGameStreamingUnregisterConnectionStateChanged(This,token,wait) (This)->lpVtbl->XGameStreamingUnregisterConnectionStateChanged(This,token,wait)
#define IXGameStreamingImpl2_XGameStreamingGetStreamAddedLatency(This,client,averageInputLatencyUs,averageOutputLatencyUs,standardDeviationUs) (This)->lpVtbl->XGameStreamingGetStreamAddedLatency(This,client,averageInputLatencyUs,averageOutputLatencyUs,standardDeviationUs)
#define IXGameStreamingImpl2_XGameStreamingGetServerLocationNameSize(This) (This)->lpVtbl->XGameStreamingGetServerLocationNameSize(This)
#define IXGameStreamingImpl2_XGameStreamingGetServerLocationName(This,serverLocationNameSize,serverLocationName) (This)->lpVtbl->XGameStreamingGetServerLocationName(This,serverLocationNameSize,serverLocationName)
#define IXGameStreamingImpl2_XGameStreamingHideTouchControls(This) (This)->lpVtbl->XGameStreamingHideTouchControls(This)
#define IXGameStreamingImpl2_XGameStreamingShowTouchControlLayout(This,layout) (This)->lpVtbl->XGameStreamingShowTouchControlLayout(This,layout)
#define IXGameStreamingImpl2_XGameStreamingHideTouchControlsOnClient(This,client) (This)->lpVtbl->XGameStreamingHideTouchControlsOnClient(This,client)
#define IXGameStreamingImpl2_XGameStreamingShowTouchControlLayoutOnClient(This,client,layout) (This)->lpVtbl->XGameStreamingShowTouchControlLayoutOnClient(This,client,layout)
#define IXGameStreamingImpl2_XGameStreamingIsTouchInputEnabled(This,client,touchInputEnabled) (This)->lpVtbl->XGameStreamingIsTouchInputEnabled(This,client,touchInputEnabled)
#define IXGameStreamingImpl2_XGameStreamingGetLastFrameDisplayed(This,client,framePipelineToken) (This)->lpVtbl->XGameStreamingGetLastFrameDisplayed(This,client,framePipelineToken)
#define IXGameStreamingImpl2_XGameStreamingGetAssociatedFrame(This,gamepadReading,framePipelineToken) (This)->lpVtbl->XGameStreamingGetAssociatedFrame(This,gamepadReading,framePipelineToken)
#define IXGameStreamingImpl2_XGameStreamingGetGamepadPhysicality(This,gamepadReading,gamepadPhysicality) (This)->lpVtbl->XGameStreamingGetGamepadPhysicality(This,gamepadReading,gamepadPhysicality)
#define IXGameStreamingImpl2_XGameStreamingUpdateTouchControlsState(This,operationCount,operations) (This)->lpVtbl->XGameStreamingUpdateTouchControlsState(This,operationCount,operations)
#define IXGameStreamingImpl2_XGameStreamingUpdateTouchControlsStateOnClient(This,client,operationCount,operations) (This)->lpVtbl->XGameStreamingUpdateTouchControlsStateOnClient(This,client,operationCount,operations)
#define IXGameStreamingImpl2_XGameStreamingShowTouchControlsWithStateUpdate(This,layout,operationCount,operations) (This)->lpVtbl->XGameStreamingShowTouchControlsWithStateUpdate(This,layout,operationCount,operations)
#define IXGameStreamingImpl2_XGameStreamingShowTouchControlsWithStateUpdateOnClient(This,client,layout,operationCount,operations) (This)->lpVtbl->XGameStreamingShowTouchControlsWithStateUpdateOnClient(This,client,layout,operationCount,operations)
#define IXGameStreamingImpl2_XGameStreamingGetTouchBundleVersionNameSize(This,client) (This)->lpVtbl->XGameStreamingGetTouchBundleVersionNameSize(This,client)
#define IXGameStreamingImpl2_XGameStreamingGetTouchBundleVersion(This,client,version,versionNameSize,versionName) (This)->lpVtbl->XGameStreamingGetTouchBundleVersion(This,client,version,versionNameSize,versionName)
#define IXGameStreamingImpl2_XGameStreamingGetClientIPAddress(This,client,ipAddressSize,ipAddress) (This)->lpVtbl->XGameStreamingGetClientIPAddress(This,client,ipAddressSize,ipAddress)
/*** IXGameStreamingImpl2 methods ***/
#define IXGameStreamingImpl2_XGameStreamingGetSessionId(This,client,sessionIdSize,sessionId,sessionIdUsed) (This)->lpVtbl->XGameStreamingGetSessionId(This,client,sessionIdSize,sessionId,sessionIdUsed)
#else
/*** IUnknown methods ***/
static inline HRESULT IXGameStreamingImpl2_QueryInterface(IXGameStreamingImpl2* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXGameStreamingImpl2_AddRef(IXGameStreamingImpl2* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXGameStreamingImpl2_Release(IXGameStreamingImpl2* This) {
    return This->lpVtbl->Release(This);
}
/*** IXGameStreamingImpl methods ***/
static inline HRESULT IXGameStreamingImpl2_XGameStreamingInitialize(IXGameStreamingImpl2* This) {
    return This->lpVtbl->XGameStreamingInitialize(This);
}
static inline void IXGameStreamingImpl2_XGameStreamingUninitialize(IXGameStreamingImpl2* This) {
    This->lpVtbl->XGameStreamingUninitialize(This);
}
static inline BOOLEAN IXGameStreamingImpl2_XGameStreamingIsStreaming(IXGameStreamingImpl2* This) {
    return This->lpVtbl->XGameStreamingIsStreaming(This);
}
static inline HRESULT IXGameStreamingImpl2_XGameStreamingRegisterClientPropertiesChanged(IXGameStreamingImpl2* This,XGameStreamingClientId client,XTaskQueueHandle queue,void *context,XGameStreamingClientPropertiesChangedCallback *callback,XTaskQueueRegistrationToken *token) {
    return This->lpVtbl->XGameStreamingRegisterClientPropertiesChanged(This,client,queue,context,callback,token);
}
static inline BOOLEAN IXGameStreamingImpl2_XGameStreamingUnregisterClientPropertiesChanged(IXGameStreamingImpl2* This,XGameStreamingClientId client,XTaskQueueRegistrationToken token,BOOLEAN wait) {
    return This->lpVtbl->XGameStreamingUnregisterClientPropertiesChanged(This,client,token,wait);
}
static inline HRESULT IXGameStreamingImpl2_XGameStreamingGetStreamPhysicalDimensions(IXGameStreamingImpl2* This,XGameStreamingClientId client,UINT32 *horizontalMm,UINT32 *verticalMm) {
    return This->lpVtbl->XGameStreamingGetStreamPhysicalDimensions(This,client,horizontalMm,verticalMm);
}
static inline UINT32 IXGameStreamingImpl2_XGameStreamingGetClientCount(IXGameStreamingImpl2* This) {
    return This->lpVtbl->XGameStreamingGetClientCount(This);
}
static inline HRESULT IXGameStreamingImpl2_XGameStreamingGetClients(IXGameStreamingImpl2* This,UINT32 clientCount,XGameStreamingClientId clients[],UINT32 *clientsUsed) {
    return This->lpVtbl->XGameStreamingGetClients(This,clientCount,clients,clientsUsed);
}
static inline XGameStreamingConnectionState IXGameStreamingImpl2_XGameStreamingGetConnectionState(IXGameStreamingImpl2* This,XGameStreamingClientId client) {
    return This->lpVtbl->XGameStreamingGetConnectionState(This,client);
}
static inline HRESULT IXGameStreamingImpl2_XGameStreamingRegisterConnectionStateChanged(IXGameStreamingImpl2* This,XTaskQueueHandle queue,void *context,XGameStreamingConnectionStateChangedCallback *callback,XTaskQueueRegistrationToken *token) {
    return This->lpVtbl->XGameStreamingRegisterConnectionStateChanged(This,queue,context,callback,token);
}
static inline BOOLEAN IXGameStreamingImpl2_XGameStreamingUnregisterConnectionStateChanged(IXGameStreamingImpl2* This,XTaskQueueRegistrationToken token,BOOLEAN wait) {
    return This->lpVtbl->XGameStreamingUnregisterConnectionStateChanged(This,token,wait);
}
static inline HRESULT IXGameStreamingImpl2_XGameStreamingGetStreamAddedLatency(IXGameStreamingImpl2* This,XGameStreamingClientId client,UINT32 *averageInputLatencyUs,UINT32 *averageOutputLatencyUs,UINT32 *standardDeviationUs) {
    return This->lpVtbl->XGameStreamingGetStreamAddedLatency(This,client,averageInputLatencyUs,averageOutputLatencyUs,standardDeviationUs);
}
static inline SIZE_T IXGameStreamingImpl2_XGameStreamingGetServerLocationNameSize(IXGameStreamingImpl2* This) {
    return This->lpVtbl->XGameStreamingGetServerLocationNameSize(This);
}
static inline HRESULT IXGameStreamingImpl2_XGameStreamingGetServerLocationName(IXGameStreamingImpl2* This,SIZE_T serverLocationNameSize,char *serverLocationName) {
    return This->lpVtbl->XGameStreamingGetServerLocationName(This,serverLocationNameSize,serverLocationName);
}
static inline void IXGameStreamingImpl2_XGameStreamingHideTouchControls(IXGameStreamingImpl2* This) {
    This->lpVtbl->XGameStreamingHideTouchControls(This);
}
static inline void IXGameStreamingImpl2_XGameStreamingShowTouchControlLayout(IXGameStreamingImpl2* This,const char *layout) {
    This->lpVtbl->XGameStreamingShowTouchControlLayout(This,layout);
}
static inline void IXGameStreamingImpl2_XGameStreamingHideTouchControlsOnClient(IXGameStreamingImpl2* This,XGameStreamingClientId client) {
    This->lpVtbl->XGameStreamingHideTouchControlsOnClient(This,client);
}
static inline void IXGameStreamingImpl2_XGameStreamingShowTouchControlLayoutOnClient(IXGameStreamingImpl2* This,XGameStreamingClientId client,const char *layout) {
    This->lpVtbl->XGameStreamingShowTouchControlLayoutOnClient(This,client,layout);
}
static inline HRESULT IXGameStreamingImpl2_XGameStreamingIsTouchInputEnabled(IXGameStreamingImpl2* This,XGameStreamingClientId client,BOOLEAN *touchInputEnabled) {
    return This->lpVtbl->XGameStreamingIsTouchInputEnabled(This,client,touchInputEnabled);
}
static inline HRESULT IXGameStreamingImpl2_XGameStreamingGetLastFrameDisplayed(IXGameStreamingImpl2* This,XGameStreamingClientId client,D3D12XBOX_FRAME_PIPELINE_TOKEN *framePipelineToken) {
    return This->lpVtbl->XGameStreamingGetLastFrameDisplayed(This,client,framePipelineToken);
}
static inline HRESULT IXGameStreamingImpl2_XGameStreamingGetAssociatedFrame(IXGameStreamingImpl2* This,IGameInputReading *gamepadReading,D3D12XBOX_FRAME_PIPELINE_TOKEN *framePipelineToken) {
    return This->lpVtbl->XGameStreamingGetAssociatedFrame(This,gamepadReading,framePipelineToken);
}
static inline HRESULT IXGameStreamingImpl2_XGameStreamingGetGamepadPhysicality(IXGameStreamingImpl2* This,IGameInputReading *gamepadReading,XGameStreamingGamepadPhysicality *gamepadPhysicality) {
    return This->lpVtbl->XGameStreamingGetGamepadPhysicality(This,gamepadReading,gamepadPhysicality);
}
static inline HRESULT IXGameStreamingImpl2_XGameStreamingUpdateTouchControlsState(IXGameStreamingImpl2* This,SIZE_T operationCount,const XGameStreamingTouchControlsStateOperation operations[]) {
    return This->lpVtbl->XGameStreamingUpdateTouchControlsState(This,operationCount,operations);
}
static inline HRESULT IXGameStreamingImpl2_XGameStreamingUpdateTouchControlsStateOnClient(IXGameStreamingImpl2* This,XGameStreamingClientId client,SIZE_T operationCount,const XGameStreamingTouchControlsStateOperation operations[]) {
    return This->lpVtbl->XGameStreamingUpdateTouchControlsStateOnClient(This,client,operationCount,operations);
}
static inline HRESULT IXGameStreamingImpl2_XGameStreamingShowTouchControlsWithStateUpdate(IXGameStreamingImpl2* This,const char *layout,SIZE_T operationCount,const XGameStreamingTouchControlsStateOperation operations[]) {
    return This->lpVtbl->XGameStreamingShowTouchControlsWithStateUpdate(This,layout,operationCount,operations);
}
static inline HRESULT IXGameStreamingImpl2_XGameStreamingShowTouchControlsWithStateUpdateOnClient(IXGameStreamingImpl2* This,XGameStreamingClientId client,const char *layout,SIZE_T operationCount,const XGameStreamingTouchControlsStateOperation operations[]) {
    return This->lpVtbl->XGameStreamingShowTouchControlsWithStateUpdateOnClient(This,client,layout,operationCount,operations);
}
static inline SIZE_T IXGameStreamingImpl2_XGameStreamingGetTouchBundleVersionNameSize(IXGameStreamingImpl2* This,XGameStreamingClientId client) {
    return This->lpVtbl->XGameStreamingGetTouchBundleVersionNameSize(This,client);
}
static inline HRESULT IXGameStreamingImpl2_XGameStreamingGetTouchBundleVersion(IXGameStreamingImpl2* This,XGameStreamingClientId client,XVersion *version,SIZE_T versionNameSize,char *versionName) {
    return This->lpVtbl->XGameStreamingGetTouchBundleVersion(This,client,version,versionNameSize,versionName);
}
static inline HRESULT IXGameStreamingImpl2_XGameStreamingGetClientIPAddress(IXGameStreamingImpl2* This,XGameStreamingClientId client,SIZE_T ipAddressSize,char *ipAddress) {
    return This->lpVtbl->XGameStreamingGetClientIPAddress(This,client,ipAddressSize,ipAddress);
}
/*** IXGameStreamingImpl2 methods ***/
static inline HRESULT IXGameStreamingImpl2_XGameStreamingGetSessionId(IXGameStreamingImpl2* This,XGameStreamingClientId client,SIZE_T sessionIdSize,char *sessionId,SIZE_T *sessionIdUsed) {
    return This->lpVtbl->XGameStreamingGetSessionId(This,client,sessionIdSize,sessionId,sessionIdUsed);
}
#endif
#endif

#endif


#endif  /* __IXGameStreamingImpl2_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IXGameStreamingImpl3 interface
 */
#ifndef __IXGameStreamingImpl3_INTERFACE_DEFINED__
#define __IXGameStreamingImpl3_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXGameStreamingImpl3, 0x57786622, 0x6605, 0x46d0, 0xb9,0x17, 0x0f,0x22,0xbb,0xcd,0x9c,0x52);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("57786622-6605-46d0-b917-0f22bbcd9c52")
IXGameStreamingImpl3 : public IXGameStreamingImpl2
{
    virtual HRESULT STDMETHODCALLTYPE XGameStreamingGetDisplayDetails(
        XGameStreamingClientId client,
        UINT32 maxSupportedPixels,
        float widestSupportedAspectRatio,
        float tallestSupportedAspectRatio,
        XGameStreamingDisplayDetails *displayDetails) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameStreamingSetResolution(
        UINT32 width,
        UINT32 height) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXGameStreamingImpl3, 0x57786622, 0x6605, 0x46d0, 0xb9,0x17, 0x0f,0x22,0xbb,0xcd,0x9c,0x52)
#endif
#else
typedef struct IXGameStreamingImpl3Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXGameStreamingImpl3 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXGameStreamingImpl3 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXGameStreamingImpl3 *This);

    /*** IXGameStreamingImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XGameStreamingInitialize)(
        IXGameStreamingImpl3 *This);

    void (STDMETHODCALLTYPE *XGameStreamingUninitialize)(
        IXGameStreamingImpl3 *This);

    BOOLEAN (STDMETHODCALLTYPE *XGameStreamingIsStreaming)(
        IXGameStreamingImpl3 *This);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingRegisterClientPropertiesChanged)(
        IXGameStreamingImpl3 *This,
        XGameStreamingClientId client,
        XTaskQueueHandle queue,
        void *context,
        XGameStreamingClientPropertiesChangedCallback *callback,
        XTaskQueueRegistrationToken *token);

    BOOLEAN (STDMETHODCALLTYPE *XGameStreamingUnregisterClientPropertiesChanged)(
        IXGameStreamingImpl3 *This,
        XGameStreamingClientId client,
        XTaskQueueRegistrationToken token,
        BOOLEAN wait);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetStreamPhysicalDimensions)(
        IXGameStreamingImpl3 *This,
        XGameStreamingClientId client,
        UINT32 *horizontalMm,
        UINT32 *verticalMm);

    UINT32 (STDMETHODCALLTYPE *XGameStreamingGetClientCount)(
        IXGameStreamingImpl3 *This);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetClients)(
        IXGameStreamingImpl3 *This,
        UINT32 clientCount,
        XGameStreamingClientId clients[],
        UINT32 *clientsUsed);

    XGameStreamingConnectionState (STDMETHODCALLTYPE *XGameStreamingGetConnectionState)(
        IXGameStreamingImpl3 *This,
        XGameStreamingClientId client);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingRegisterConnectionStateChanged)(
        IXGameStreamingImpl3 *This,
        XTaskQueueHandle queue,
        void *context,
        XGameStreamingConnectionStateChangedCallback *callback,
        XTaskQueueRegistrationToken *token);

    BOOLEAN (STDMETHODCALLTYPE *XGameStreamingUnregisterConnectionStateChanged)(
        IXGameStreamingImpl3 *This,
        XTaskQueueRegistrationToken token,
        BOOLEAN wait);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetStreamAddedLatency)(
        IXGameStreamingImpl3 *This,
        XGameStreamingClientId client,
        UINT32 *averageInputLatencyUs,
        UINT32 *averageOutputLatencyUs,
        UINT32 *standardDeviationUs);

    SIZE_T (STDMETHODCALLTYPE *XGameStreamingGetServerLocationNameSize)(
        IXGameStreamingImpl3 *This);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetServerLocationName)(
        IXGameStreamingImpl3 *This,
        SIZE_T serverLocationNameSize,
        char *serverLocationName);

    void (STDMETHODCALLTYPE *XGameStreamingHideTouchControls)(
        IXGameStreamingImpl3 *This);

    void (STDMETHODCALLTYPE *XGameStreamingShowTouchControlLayout)(
        IXGameStreamingImpl3 *This,
        const char *layout);

    void (STDMETHODCALLTYPE *XGameStreamingHideTouchControlsOnClient)(
        IXGameStreamingImpl3 *This,
        XGameStreamingClientId client);

    void (STDMETHODCALLTYPE *XGameStreamingShowTouchControlLayoutOnClient)(
        IXGameStreamingImpl3 *This,
        XGameStreamingClientId client,
        const char *layout);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingIsTouchInputEnabled)(
        IXGameStreamingImpl3 *This,
        XGameStreamingClientId client,
        BOOLEAN *touchInputEnabled);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetLastFrameDisplayed)(
        IXGameStreamingImpl3 *This,
        XGameStreamingClientId client,
        D3D12XBOX_FRAME_PIPELINE_TOKEN *framePipelineToken);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetAssociatedFrame)(
        IXGameStreamingImpl3 *This,
        IGameInputReading *gamepadReading,
        D3D12XBOX_FRAME_PIPELINE_TOKEN *framePipelineToken);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetGamepadPhysicality)(
        IXGameStreamingImpl3 *This,
        IGameInputReading *gamepadReading,
        XGameStreamingGamepadPhysicality *gamepadPhysicality);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingUpdateTouchControlsState)(
        IXGameStreamingImpl3 *This,
        SIZE_T operationCount,
        const XGameStreamingTouchControlsStateOperation operations[]);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingUpdateTouchControlsStateOnClient)(
        IXGameStreamingImpl3 *This,
        XGameStreamingClientId client,
        SIZE_T operationCount,
        const XGameStreamingTouchControlsStateOperation operations[]);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingShowTouchControlsWithStateUpdate)(
        IXGameStreamingImpl3 *This,
        const char *layout,
        SIZE_T operationCount,
        const XGameStreamingTouchControlsStateOperation operations[]);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingShowTouchControlsWithStateUpdateOnClient)(
        IXGameStreamingImpl3 *This,
        XGameStreamingClientId client,
        const char *layout,
        SIZE_T operationCount,
        const XGameStreamingTouchControlsStateOperation operations[]);

    SIZE_T (STDMETHODCALLTYPE *XGameStreamingGetTouchBundleVersionNameSize)(
        IXGameStreamingImpl3 *This,
        XGameStreamingClientId client);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetTouchBundleVersion)(
        IXGameStreamingImpl3 *This,
        XGameStreamingClientId client,
        XVersion *version,
        SIZE_T versionNameSize,
        char *versionName);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetClientIPAddress)(
        IXGameStreamingImpl3 *This,
        XGameStreamingClientId client,
        SIZE_T ipAddressSize,
        char *ipAddress);

    /*** IXGameStreamingImpl2 methods ***/
    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetSessionId)(
        IXGameStreamingImpl3 *This,
        XGameStreamingClientId client,
        SIZE_T sessionIdSize,
        char *sessionId,
        SIZE_T *sessionIdUsed);

    /*** IXGameStreamingImpl3 methods ***/
    HRESULT (STDMETHODCALLTYPE *XGameStreamingGetDisplayDetails)(
        IXGameStreamingImpl3 *This,
        XGameStreamingClientId client,
        UINT32 maxSupportedPixels,
        float widestSupportedAspectRatio,
        float tallestSupportedAspectRatio,
        XGameStreamingDisplayDetails *displayDetails);

    HRESULT (STDMETHODCALLTYPE *XGameStreamingSetResolution)(
        IXGameStreamingImpl3 *This,
        UINT32 width,
        UINT32 height);

    END_INTERFACE
} IXGameStreamingImpl3Vtbl;

interface IXGameStreamingImpl3 {
    CONST_VTBL IXGameStreamingImpl3Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXGameStreamingImpl3_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXGameStreamingImpl3_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXGameStreamingImpl3_Release(This) (This)->lpVtbl->Release(This)
/*** IXGameStreamingImpl methods ***/
#define IXGameStreamingImpl3_XGameStreamingInitialize(This) (This)->lpVtbl->XGameStreamingInitialize(This)
#define IXGameStreamingImpl3_XGameStreamingUninitialize(This) (This)->lpVtbl->XGameStreamingUninitialize(This)
#define IXGameStreamingImpl3_XGameStreamingIsStreaming(This) (This)->lpVtbl->XGameStreamingIsStreaming(This)
#define IXGameStreamingImpl3_XGameStreamingRegisterClientPropertiesChanged(This,client,queue,context,callback,token) (This)->lpVtbl->XGameStreamingRegisterClientPropertiesChanged(This,client,queue,context,callback,token)
#define IXGameStreamingImpl3_XGameStreamingUnregisterClientPropertiesChanged(This,client,token,wait) (This)->lpVtbl->XGameStreamingUnregisterClientPropertiesChanged(This,client,token,wait)
#define IXGameStreamingImpl3_XGameStreamingGetStreamPhysicalDimensions(This,client,horizontalMm,verticalMm) (This)->lpVtbl->XGameStreamingGetStreamPhysicalDimensions(This,client,horizontalMm,verticalMm)
#define IXGameStreamingImpl3_XGameStreamingGetClientCount(This) (This)->lpVtbl->XGameStreamingGetClientCount(This)
#define IXGameStreamingImpl3_XGameStreamingGetClients(This,clientCount,clients,clientsUsed) (This)->lpVtbl->XGameStreamingGetClients(This,clientCount,clients,clientsUsed)
#define IXGameStreamingImpl3_XGameStreamingGetConnectionState(This,client) (This)->lpVtbl->XGameStreamingGetConnectionState(This,client)
#define IXGameStreamingImpl3_XGameStreamingRegisterConnectionStateChanged(This,queue,context,callback,token) (This)->lpVtbl->XGameStreamingRegisterConnectionStateChanged(This,queue,context,callback,token)
#define IXGameStreamingImpl3_XGameStreamingUnregisterConnectionStateChanged(This,token,wait) (This)->lpVtbl->XGameStreamingUnregisterConnectionStateChanged(This,token,wait)
#define IXGameStreamingImpl3_XGameStreamingGetStreamAddedLatency(This,client,averageInputLatencyUs,averageOutputLatencyUs,standardDeviationUs) (This)->lpVtbl->XGameStreamingGetStreamAddedLatency(This,client,averageInputLatencyUs,averageOutputLatencyUs,standardDeviationUs)
#define IXGameStreamingImpl3_XGameStreamingGetServerLocationNameSize(This) (This)->lpVtbl->XGameStreamingGetServerLocationNameSize(This)
#define IXGameStreamingImpl3_XGameStreamingGetServerLocationName(This,serverLocationNameSize,serverLocationName) (This)->lpVtbl->XGameStreamingGetServerLocationName(This,serverLocationNameSize,serverLocationName)
#define IXGameStreamingImpl3_XGameStreamingHideTouchControls(This) (This)->lpVtbl->XGameStreamingHideTouchControls(This)
#define IXGameStreamingImpl3_XGameStreamingShowTouchControlLayout(This,layout) (This)->lpVtbl->XGameStreamingShowTouchControlLayout(This,layout)
#define IXGameStreamingImpl3_XGameStreamingHideTouchControlsOnClient(This,client) (This)->lpVtbl->XGameStreamingHideTouchControlsOnClient(This,client)
#define IXGameStreamingImpl3_XGameStreamingShowTouchControlLayoutOnClient(This,client,layout) (This)->lpVtbl->XGameStreamingShowTouchControlLayoutOnClient(This,client,layout)
#define IXGameStreamingImpl3_XGameStreamingIsTouchInputEnabled(This,client,touchInputEnabled) (This)->lpVtbl->XGameStreamingIsTouchInputEnabled(This,client,touchInputEnabled)
#define IXGameStreamingImpl3_XGameStreamingGetLastFrameDisplayed(This,client,framePipelineToken) (This)->lpVtbl->XGameStreamingGetLastFrameDisplayed(This,client,framePipelineToken)
#define IXGameStreamingImpl3_XGameStreamingGetAssociatedFrame(This,gamepadReading,framePipelineToken) (This)->lpVtbl->XGameStreamingGetAssociatedFrame(This,gamepadReading,framePipelineToken)
#define IXGameStreamingImpl3_XGameStreamingGetGamepadPhysicality(This,gamepadReading,gamepadPhysicality) (This)->lpVtbl->XGameStreamingGetGamepadPhysicality(This,gamepadReading,gamepadPhysicality)
#define IXGameStreamingImpl3_XGameStreamingUpdateTouchControlsState(This,operationCount,operations) (This)->lpVtbl->XGameStreamingUpdateTouchControlsState(This,operationCount,operations)
#define IXGameStreamingImpl3_XGameStreamingUpdateTouchControlsStateOnClient(This,client,operationCount,operations) (This)->lpVtbl->XGameStreamingUpdateTouchControlsStateOnClient(This,client,operationCount,operations)
#define IXGameStreamingImpl3_XGameStreamingShowTouchControlsWithStateUpdate(This,layout,operationCount,operations) (This)->lpVtbl->XGameStreamingShowTouchControlsWithStateUpdate(This,layout,operationCount,operations)
#define IXGameStreamingImpl3_XGameStreamingShowTouchControlsWithStateUpdateOnClient(This,client,layout,operationCount,operations) (This)->lpVtbl->XGameStreamingShowTouchControlsWithStateUpdateOnClient(This,client,layout,operationCount,operations)
#define IXGameStreamingImpl3_XGameStreamingGetTouchBundleVersionNameSize(This,client) (This)->lpVtbl->XGameStreamingGetTouchBundleVersionNameSize(This,client)
#define IXGameStreamingImpl3_XGameStreamingGetTouchBundleVersion(This,client,version,versionNameSize,versionName) (This)->lpVtbl->XGameStreamingGetTouchBundleVersion(This,client,version,versionNameSize,versionName)
#define IXGameStreamingImpl3_XGameStreamingGetClientIPAddress(This,client,ipAddressSize,ipAddress) (This)->lpVtbl->XGameStreamingGetClientIPAddress(This,client,ipAddressSize,ipAddress)
/*** IXGameStreamingImpl2 methods ***/
#define IXGameStreamingImpl3_XGameStreamingGetSessionId(This,client,sessionIdSize,sessionId,sessionIdUsed) (This)->lpVtbl->XGameStreamingGetSessionId(This,client,sessionIdSize,sessionId,sessionIdUsed)
/*** IXGameStreamingImpl3 methods ***/
#define IXGameStreamingImpl3_XGameStreamingGetDisplayDetails(This,client,maxSupportedPixels,widestSupportedAspectRatio,tallestSupportedAspectRatio,displayDetails) (This)->lpVtbl->XGameStreamingGetDisplayDetails(This,client,maxSupportedPixels,widestSupportedAspectRatio,tallestSupportedAspectRatio,displayDetails)
#define IXGameStreamingImpl3_XGameStreamingSetResolution(This,width,height) (This)->lpVtbl->XGameStreamingSetResolution(This,width,height)
#else
/*** IUnknown methods ***/
static inline HRESULT IXGameStreamingImpl3_QueryInterface(IXGameStreamingImpl3* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXGameStreamingImpl3_AddRef(IXGameStreamingImpl3* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXGameStreamingImpl3_Release(IXGameStreamingImpl3* This) {
    return This->lpVtbl->Release(This);
}
/*** IXGameStreamingImpl methods ***/
static inline HRESULT IXGameStreamingImpl3_XGameStreamingInitialize(IXGameStreamingImpl3* This) {
    return This->lpVtbl->XGameStreamingInitialize(This);
}
static inline void IXGameStreamingImpl3_XGameStreamingUninitialize(IXGameStreamingImpl3* This) {
    This->lpVtbl->XGameStreamingUninitialize(This);
}
static inline BOOLEAN IXGameStreamingImpl3_XGameStreamingIsStreaming(IXGameStreamingImpl3* This) {
    return This->lpVtbl->XGameStreamingIsStreaming(This);
}
static inline HRESULT IXGameStreamingImpl3_XGameStreamingRegisterClientPropertiesChanged(IXGameStreamingImpl3* This,XGameStreamingClientId client,XTaskQueueHandle queue,void *context,XGameStreamingClientPropertiesChangedCallback *callback,XTaskQueueRegistrationToken *token) {
    return This->lpVtbl->XGameStreamingRegisterClientPropertiesChanged(This,client,queue,context,callback,token);
}
static inline BOOLEAN IXGameStreamingImpl3_XGameStreamingUnregisterClientPropertiesChanged(IXGameStreamingImpl3* This,XGameStreamingClientId client,XTaskQueueRegistrationToken token,BOOLEAN wait) {
    return This->lpVtbl->XGameStreamingUnregisterClientPropertiesChanged(This,client,token,wait);
}
static inline HRESULT IXGameStreamingImpl3_XGameStreamingGetStreamPhysicalDimensions(IXGameStreamingImpl3* This,XGameStreamingClientId client,UINT32 *horizontalMm,UINT32 *verticalMm) {
    return This->lpVtbl->XGameStreamingGetStreamPhysicalDimensions(This,client,horizontalMm,verticalMm);
}
static inline UINT32 IXGameStreamingImpl3_XGameStreamingGetClientCount(IXGameStreamingImpl3* This) {
    return This->lpVtbl->XGameStreamingGetClientCount(This);
}
static inline HRESULT IXGameStreamingImpl3_XGameStreamingGetClients(IXGameStreamingImpl3* This,UINT32 clientCount,XGameStreamingClientId clients[],UINT32 *clientsUsed) {
    return This->lpVtbl->XGameStreamingGetClients(This,clientCount,clients,clientsUsed);
}
static inline XGameStreamingConnectionState IXGameStreamingImpl3_XGameStreamingGetConnectionState(IXGameStreamingImpl3* This,XGameStreamingClientId client) {
    return This->lpVtbl->XGameStreamingGetConnectionState(This,client);
}
static inline HRESULT IXGameStreamingImpl3_XGameStreamingRegisterConnectionStateChanged(IXGameStreamingImpl3* This,XTaskQueueHandle queue,void *context,XGameStreamingConnectionStateChangedCallback *callback,XTaskQueueRegistrationToken *token) {
    return This->lpVtbl->XGameStreamingRegisterConnectionStateChanged(This,queue,context,callback,token);
}
static inline BOOLEAN IXGameStreamingImpl3_XGameStreamingUnregisterConnectionStateChanged(IXGameStreamingImpl3* This,XTaskQueueRegistrationToken token,BOOLEAN wait) {
    return This->lpVtbl->XGameStreamingUnregisterConnectionStateChanged(This,token,wait);
}
static inline HRESULT IXGameStreamingImpl3_XGameStreamingGetStreamAddedLatency(IXGameStreamingImpl3* This,XGameStreamingClientId client,UINT32 *averageInputLatencyUs,UINT32 *averageOutputLatencyUs,UINT32 *standardDeviationUs) {
    return This->lpVtbl->XGameStreamingGetStreamAddedLatency(This,client,averageInputLatencyUs,averageOutputLatencyUs,standardDeviationUs);
}
static inline SIZE_T IXGameStreamingImpl3_XGameStreamingGetServerLocationNameSize(IXGameStreamingImpl3* This) {
    return This->lpVtbl->XGameStreamingGetServerLocationNameSize(This);
}
static inline HRESULT IXGameStreamingImpl3_XGameStreamingGetServerLocationName(IXGameStreamingImpl3* This,SIZE_T serverLocationNameSize,char *serverLocationName) {
    return This->lpVtbl->XGameStreamingGetServerLocationName(This,serverLocationNameSize,serverLocationName);
}
static inline void IXGameStreamingImpl3_XGameStreamingHideTouchControls(IXGameStreamingImpl3* This) {
    This->lpVtbl->XGameStreamingHideTouchControls(This);
}
static inline void IXGameStreamingImpl3_XGameStreamingShowTouchControlLayout(IXGameStreamingImpl3* This,const char *layout) {
    This->lpVtbl->XGameStreamingShowTouchControlLayout(This,layout);
}
static inline void IXGameStreamingImpl3_XGameStreamingHideTouchControlsOnClient(IXGameStreamingImpl3* This,XGameStreamingClientId client) {
    This->lpVtbl->XGameStreamingHideTouchControlsOnClient(This,client);
}
static inline void IXGameStreamingImpl3_XGameStreamingShowTouchControlLayoutOnClient(IXGameStreamingImpl3* This,XGameStreamingClientId client,const char *layout) {
    This->lpVtbl->XGameStreamingShowTouchControlLayoutOnClient(This,client,layout);
}
static inline HRESULT IXGameStreamingImpl3_XGameStreamingIsTouchInputEnabled(IXGameStreamingImpl3* This,XGameStreamingClientId client,BOOLEAN *touchInputEnabled) {
    return This->lpVtbl->XGameStreamingIsTouchInputEnabled(This,client,touchInputEnabled);
}
static inline HRESULT IXGameStreamingImpl3_XGameStreamingGetLastFrameDisplayed(IXGameStreamingImpl3* This,XGameStreamingClientId client,D3D12XBOX_FRAME_PIPELINE_TOKEN *framePipelineToken) {
    return This->lpVtbl->XGameStreamingGetLastFrameDisplayed(This,client,framePipelineToken);
}
static inline HRESULT IXGameStreamingImpl3_XGameStreamingGetAssociatedFrame(IXGameStreamingImpl3* This,IGameInputReading *gamepadReading,D3D12XBOX_FRAME_PIPELINE_TOKEN *framePipelineToken) {
    return This->lpVtbl->XGameStreamingGetAssociatedFrame(This,gamepadReading,framePipelineToken);
}
static inline HRESULT IXGameStreamingImpl3_XGameStreamingGetGamepadPhysicality(IXGameStreamingImpl3* This,IGameInputReading *gamepadReading,XGameStreamingGamepadPhysicality *gamepadPhysicality) {
    return This->lpVtbl->XGameStreamingGetGamepadPhysicality(This,gamepadReading,gamepadPhysicality);
}
static inline HRESULT IXGameStreamingImpl3_XGameStreamingUpdateTouchControlsState(IXGameStreamingImpl3* This,SIZE_T operationCount,const XGameStreamingTouchControlsStateOperation operations[]) {
    return This->lpVtbl->XGameStreamingUpdateTouchControlsState(This,operationCount,operations);
}
static inline HRESULT IXGameStreamingImpl3_XGameStreamingUpdateTouchControlsStateOnClient(IXGameStreamingImpl3* This,XGameStreamingClientId client,SIZE_T operationCount,const XGameStreamingTouchControlsStateOperation operations[]) {
    return This->lpVtbl->XGameStreamingUpdateTouchControlsStateOnClient(This,client,operationCount,operations);
}
static inline HRESULT IXGameStreamingImpl3_XGameStreamingShowTouchControlsWithStateUpdate(IXGameStreamingImpl3* This,const char *layout,SIZE_T operationCount,const XGameStreamingTouchControlsStateOperation operations[]) {
    return This->lpVtbl->XGameStreamingShowTouchControlsWithStateUpdate(This,layout,operationCount,operations);
}
static inline HRESULT IXGameStreamingImpl3_XGameStreamingShowTouchControlsWithStateUpdateOnClient(IXGameStreamingImpl3* This,XGameStreamingClientId client,const char *layout,SIZE_T operationCount,const XGameStreamingTouchControlsStateOperation operations[]) {
    return This->lpVtbl->XGameStreamingShowTouchControlsWithStateUpdateOnClient(This,client,layout,operationCount,operations);
}
static inline SIZE_T IXGameStreamingImpl3_XGameStreamingGetTouchBundleVersionNameSize(IXGameStreamingImpl3* This,XGameStreamingClientId client) {
    return This->lpVtbl->XGameStreamingGetTouchBundleVersionNameSize(This,client);
}
static inline HRESULT IXGameStreamingImpl3_XGameStreamingGetTouchBundleVersion(IXGameStreamingImpl3* This,XGameStreamingClientId client,XVersion *version,SIZE_T versionNameSize,char *versionName) {
    return This->lpVtbl->XGameStreamingGetTouchBundleVersion(This,client,version,versionNameSize,versionName);
}
static inline HRESULT IXGameStreamingImpl3_XGameStreamingGetClientIPAddress(IXGameStreamingImpl3* This,XGameStreamingClientId client,SIZE_T ipAddressSize,char *ipAddress) {
    return This->lpVtbl->XGameStreamingGetClientIPAddress(This,client,ipAddressSize,ipAddress);
}
/*** IXGameStreamingImpl2 methods ***/
static inline HRESULT IXGameStreamingImpl3_XGameStreamingGetSessionId(IXGameStreamingImpl3* This,XGameStreamingClientId client,SIZE_T sessionIdSize,char *sessionId,SIZE_T *sessionIdUsed) {
    return This->lpVtbl->XGameStreamingGetSessionId(This,client,sessionIdSize,sessionId,sessionIdUsed);
}
/*** IXGameStreamingImpl3 methods ***/
static inline HRESULT IXGameStreamingImpl3_XGameStreamingGetDisplayDetails(IXGameStreamingImpl3* This,XGameStreamingClientId client,UINT32 maxSupportedPixels,float widestSupportedAspectRatio,float tallestSupportedAspectRatio,XGameStreamingDisplayDetails *displayDetails) {
    return This->lpVtbl->XGameStreamingGetDisplayDetails(This,client,maxSupportedPixels,widestSupportedAspectRatio,tallestSupportedAspectRatio,displayDetails);
}
static inline HRESULT IXGameStreamingImpl3_XGameStreamingSetResolution(IXGameStreamingImpl3* This,UINT32 width,UINT32 height) {
    return This->lpVtbl->XGameStreamingSetResolution(This,width,height);
}
#endif
#endif

#endif


#endif  /* __IXGameStreamingImpl3_INTERFACE_DEFINED__ */

/*****************************************************************************
 * XGameStreamingImpl coclass
 */

DEFINE_GUID(CLSID_XGameStreamingImpl, 0x0a2192aa, 0xb2d5, 0x4d58, 0x83,0xbe, 0x38,0x3b,0x6d,0x80,0x79,0x9e);

#ifdef __cplusplus
class DECLSPEC_UUID("0a2192aa-b2d5-4d58-83be-383b6d80799e") XGameStreamingImpl;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(XGameStreamingImpl, 0x0a2192aa, 0xb2d5, 0x4d58, 0x83,0xbe, 0x38,0x3b,0x6d,0x80,0x79,0x9e)
#endif
#endif

#endif
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __xgamestreaming_h__ */
