/*** Autogenerated by WIDL 11.15 from xgamesave.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __xgamesave_h__
#define __xgamesave_h__

/* Forward declarations */

#ifndef __IXGameSaveImpl_FWD_DEFINED__
#define __IXGameSaveImpl_FWD_DEFINED__
typedef interface IXGameSaveImpl IXGameSaveImpl;
#ifdef __cplusplus
interface IXGameSaveImpl;
#endif /* __cplusplus */
#endif

#ifndef __IXGameSaveImpl2_FWD_DEFINED__
#define __IXGameSaveImpl2_FWD_DEFINED__
typedef interface IXGameSaveImpl2 IXGameSaveImpl2;
#ifdef __cplusplus
interface IXGameSaveImpl2;
#endif /* __cplusplus */
#endif

#ifndef __IXGameSaveImpl3_FWD_DEFINED__
#define __IXGameSaveImpl3_FWD_DEFINED__
typedef interface IXGameSaveImpl3 IXGameSaveImpl3;
#ifdef __cplusplus
interface IXGameSaveImpl3;
#endif /* __cplusplus */
#endif

#ifndef __XGameSaveImpl_FWD_DEFINED__
#define __XGameSaveImpl_FWD_DEFINED__
#ifdef __cplusplus
typedef class XGameSaveImpl XGameSaveImpl;
#else
typedef struct XGameSaveImpl XGameSaveImpl;
#endif /* defined __cplusplus */
#endif /* defined __XGameSaveImpl_FWD_DEFINED__ */

/* Headers for imported files */

#include <unknwn.h>
#include <xasync.h>
#include <xuser.h>

#ifdef __cplusplus
extern "C" {
#endif

#if 0
typedef UINT64 time_t;
#endif
typedef struct XGameSaveContainer *XGameSaveContainerHandle;
typedef struct XGameSaveProvider *XGameSaveProviderHandle;
typedef struct XGameSaveUpdate *XGameSaveUpdateHandle;
typedef struct XGameSaveBlob XGameSaveBlob;
typedef struct XGameSaveBlobInfo XGameSaveBlobInfo;
typedef struct XGameSaveContainerInfo XGameSaveContainerInfo;
typedef BOOLEAN __stdcall  XGameSaveBlobInfoCallback(const XGameSaveBlobInfo *info,void *context);
typedef BOOLEAN __stdcall  XGameSaveContainerInfoCallback(const XGameSaveContainerInfo *info,void *context);
struct XGameSaveBlobInfo {
    const char *name;
    UINT32 size;
};
struct XGameSaveBlob {
    XGameSaveBlobInfo info;
    UINT8 *data;
};
struct XGameSaveContainerInfo {
    const char *name;
    const char *displayName;
    UINT32 blobCount;
    UINT64 totalSize;
    time_t lastModifiedTime;
    BOOLEAN needsSync;
};
#ifdef __WINESRC__
/*****************************************************************************
 * IXGameSaveImpl interface
 */
#ifndef __IXGameSaveImpl_INTERFACE_DEFINED__
#define __IXGameSaveImpl_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXGameSaveImpl, 0x704c3f58, 0xe629, 0x4cc2, 0xb1,0x97, 0x30,0x51,0x1b,0x99,0x6f,0xe2);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("704c3f58-e629-4cc2-b197-30511b996fe2")
IXGameSaveImpl : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE XGameSaveInitializeProvider(
        XUserHandle requestingUser,
        const char *configurationId,
        BOOLEAN syncOnDemand,
        XGameSaveProviderHandle *provider) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveInitializeProviderAsync(
        XUserHandle requestingUser,
        const char *configurationId,
        BOOLEAN syncOnDemand,
        XAsyncBlock *async) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveInitializeProviderResult(
        XAsyncBlock *async,
        XGameSaveProviderHandle *provider) = 0;

    virtual void STDMETHODCALLTYPE XGameSaveCloseProvider(
        XGameSaveProviderHandle provider) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveGetRemainingQuota(
        XGameSaveProviderHandle provider,
        INT64 *remainingQuota) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveGetRemainingQuotaAsync(
        XGameSaveProviderHandle provider,
        XAsyncBlock *async) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveGetRemainingQuotaResult(
        XAsyncBlock *async,
        INT64 *remainingQuota) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveDeleteContainer(
        XGameSaveProviderHandle provider,
        const char *containerName) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveDeleteContainerAsync(
        XGameSaveProviderHandle provider,
        const char *containerName,
        XAsyncBlock *async) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveDeleteContainerResult(
        XAsyncBlock *async) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveGetContainerInfo(
        XGameSaveProviderHandle provider,
        const char *containerName,
        void *context,
        XGameSaveContainerInfoCallback *callback) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveEnumerateContainerInfo(
        XGameSaveProviderHandle provider,
        void *context,
        XGameSaveContainerInfoCallback *callback) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveEnumerateContainerInfoByName(
        XGameSaveProviderHandle provider,
        const char *containerNamePrefix,
        void *context,
        XGameSaveContainerInfoCallback *callback) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveCreateContainer(
        XGameSaveProviderHandle provider,
        const char *containerName,
        XGameSaveContainerHandle *containerContext) = 0;

    virtual void STDMETHODCALLTYPE XGameSaveCloseContainer(
        XGameSaveContainerHandle context) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveEnumerateBlobInfo(
        XGameSaveContainerHandle container,
        void *context,
        XGameSaveBlobInfoCallback *callback) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveEnumerateBlobInfoByName(
        XGameSaveContainerHandle container,
        const char *blobNamePrefix,
        void *context,
        XGameSaveBlobInfoCallback *callback) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveReadBlobData(
        XGameSaveContainerHandle container,
        const char **blobNames,
        UINT32 *countOfBlobs,
        SIZE_T blobsSize,
        XGameSaveBlob *blobData) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveReadBlobDataAsync(
        XGameSaveContainerHandle container,
        const char **blobNames,
        UINT32 countOfBlobs,
        XAsyncBlock *async) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveReadBlobDataResult(
        XAsyncBlock *async,
        SIZE_T blobsSize,
        XGameSaveBlob *blobData,
        UINT32 *countOfBlobs) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveCreateUpdate(
        XGameSaveContainerHandle container,
        const char *containerDisplayName,
        XGameSaveUpdateHandle *updateContext) = 0;

    virtual void STDMETHODCALLTYPE XGameSaveCloseUpdate(
        XGameSaveUpdateHandle context) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveSubmitBlobWrite(
        XGameSaveUpdateHandle updateContext,
        const char *blobName,
        UINT8 *data,
        SIZE_T byteCount) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveSubmitBlobDelete(
        XGameSaveUpdateHandle updateContext,
        const char *blobName) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveSubmitUpdate(
        XGameSaveUpdateHandle updateContext) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveSubmitUpdateAsync(
        XGameSaveUpdateHandle updateContext,
        XAsyncBlock *async) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveSubmitUpdateResult(
        XAsyncBlock *async) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXGameSaveImpl, 0x704c3f58, 0xe629, 0x4cc2, 0xb1,0x97, 0x30,0x51,0x1b,0x99,0x6f,0xe2)
#endif
#else
typedef struct IXGameSaveImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXGameSaveImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXGameSaveImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXGameSaveImpl *This);

    /*** IXGameSaveImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XGameSaveInitializeProvider)(
        IXGameSaveImpl *This,
        XUserHandle requestingUser,
        const char *configurationId,
        BOOLEAN syncOnDemand,
        XGameSaveProviderHandle *provider);

    HRESULT (STDMETHODCALLTYPE *XGameSaveInitializeProviderAsync)(
        IXGameSaveImpl *This,
        XUserHandle requestingUser,
        const char *configurationId,
        BOOLEAN syncOnDemand,
        XAsyncBlock *async);

    HRESULT (STDMETHODCALLTYPE *XGameSaveInitializeProviderResult)(
        IXGameSaveImpl *This,
        XAsyncBlock *async,
        XGameSaveProviderHandle *provider);

    void (STDMETHODCALLTYPE *XGameSaveCloseProvider)(
        IXGameSaveImpl *This,
        XGameSaveProviderHandle provider);

    HRESULT (STDMETHODCALLTYPE *XGameSaveGetRemainingQuota)(
        IXGameSaveImpl *This,
        XGameSaveProviderHandle provider,
        INT64 *remainingQuota);

    HRESULT (STDMETHODCALLTYPE *XGameSaveGetRemainingQuotaAsync)(
        IXGameSaveImpl *This,
        XGameSaveProviderHandle provider,
        XAsyncBlock *async);

    HRESULT (STDMETHODCALLTYPE *XGameSaveGetRemainingQuotaResult)(
        IXGameSaveImpl *This,
        XAsyncBlock *async,
        INT64 *remainingQuota);

    HRESULT (STDMETHODCALLTYPE *XGameSaveDeleteContainer)(
        IXGameSaveImpl *This,
        XGameSaveProviderHandle provider,
        const char *containerName);

    HRESULT (STDMETHODCALLTYPE *XGameSaveDeleteContainerAsync)(
        IXGameSaveImpl *This,
        XGameSaveProviderHandle provider,
        const char *containerName,
        XAsyncBlock *async);

    HRESULT (STDMETHODCALLTYPE *XGameSaveDeleteContainerResult)(
        IXGameSaveImpl *This,
        XAsyncBlock *async);

    HRESULT (STDMETHODCALLTYPE *XGameSaveGetContainerInfo)(
        IXGameSaveImpl *This,
        XGameSaveProviderHandle provider,
        const char *containerName,
        void *context,
        XGameSaveContainerInfoCallback *callback);

    HRESULT (STDMETHODCALLTYPE *XGameSaveEnumerateContainerInfo)(
        IXGameSaveImpl *This,
        XGameSaveProviderHandle provider,
        void *context,
        XGameSaveContainerInfoCallback *callback);

    HRESULT (STDMETHODCALLTYPE *XGameSaveEnumerateContainerInfoByName)(
        IXGameSaveImpl *This,
        XGameSaveProviderHandle provider,
        const char *containerNamePrefix,
        void *context,
        XGameSaveContainerInfoCallback *callback);

    HRESULT (STDMETHODCALLTYPE *XGameSaveCreateContainer)(
        IXGameSaveImpl *This,
        XGameSaveProviderHandle provider,
        const char *containerName,
        XGameSaveContainerHandle *containerContext);

    void (STDMETHODCALLTYPE *XGameSaveCloseContainer)(
        IXGameSaveImpl *This,
        XGameSaveContainerHandle context);

    HRESULT (STDMETHODCALLTYPE *XGameSaveEnumerateBlobInfo)(
        IXGameSaveImpl *This,
        XGameSaveContainerHandle container,
        void *context,
        XGameSaveBlobInfoCallback *callback);

    HRESULT (STDMETHODCALLTYPE *XGameSaveEnumerateBlobInfoByName)(
        IXGameSaveImpl *This,
        XGameSaveContainerHandle container,
        const char *blobNamePrefix,
        void *context,
        XGameSaveBlobInfoCallback *callback);

    HRESULT (STDMETHODCALLTYPE *XGameSaveReadBlobData)(
        IXGameSaveImpl *This,
        XGameSaveContainerHandle container,
        const char **blobNames,
        UINT32 *countOfBlobs,
        SIZE_T blobsSize,
        XGameSaveBlob *blobData);

    HRESULT (STDMETHODCALLTYPE *XGameSaveReadBlobDataAsync)(
        IXGameSaveImpl *This,
        XGameSaveContainerHandle container,
        const char **blobNames,
        UINT32 countOfBlobs,
        XAsyncBlock *async);

    HRESULT (STDMETHODCALLTYPE *XGameSaveReadBlobDataResult)(
        IXGameSaveImpl *This,
        XAsyncBlock *async,
        SIZE_T blobsSize,
        XGameSaveBlob *blobData,
        UINT32 *countOfBlobs);

    HRESULT (STDMETHODCALLTYPE *XGameSaveCreateUpdate)(
        IXGameSaveImpl *This,
        XGameSaveContainerHandle container,
        const char *containerDisplayName,
        XGameSaveUpdateHandle *updateContext);

    void (STDMETHODCALLTYPE *XGameSaveCloseUpdate)(
        IXGameSaveImpl *This,
        XGameSaveUpdateHandle context);

    HRESULT (STDMETHODCALLTYPE *XGameSaveSubmitBlobWrite)(
        IXGameSaveImpl *This,
        XGameSaveUpdateHandle updateContext,
        const char *blobName,
        UINT8 *data,
        SIZE_T byteCount);

    HRESULT (STDMETHODCALLTYPE *XGameSaveSubmitBlobDelete)(
        IXGameSaveImpl *This,
        XGameSaveUpdateHandle updateContext,
        const char *blobName);

    HRESULT (STDMETHODCALLTYPE *XGameSaveSubmitUpdate)(
        IXGameSaveImpl *This,
        XGameSaveUpdateHandle updateContext);

    HRESULT (STDMETHODCALLTYPE *XGameSaveSubmitUpdateAsync)(
        IXGameSaveImpl *This,
        XGameSaveUpdateHandle updateContext,
        XAsyncBlock *async);

    HRESULT (STDMETHODCALLTYPE *XGameSaveSubmitUpdateResult)(
        IXGameSaveImpl *This,
        XAsyncBlock *async);

    END_INTERFACE
} IXGameSaveImplVtbl;

interface IXGameSaveImpl {
    CONST_VTBL IXGameSaveImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXGameSaveImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXGameSaveImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXGameSaveImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IXGameSaveImpl methods ***/
#define IXGameSaveImpl_XGameSaveInitializeProvider(This,requestingUser,configurationId,syncOnDemand,provider) (This)->lpVtbl->XGameSaveInitializeProvider(This,requestingUser,configurationId,syncOnDemand,provider)
#define IXGameSaveImpl_XGameSaveInitializeProviderAsync(This,requestingUser,configurationId,syncOnDemand,async) (This)->lpVtbl->XGameSaveInitializeProviderAsync(This,requestingUser,configurationId,syncOnDemand,async)
#define IXGameSaveImpl_XGameSaveInitializeProviderResult(This,async,provider) (This)->lpVtbl->XGameSaveInitializeProviderResult(This,async,provider)
#define IXGameSaveImpl_XGameSaveCloseProvider(This,provider) (This)->lpVtbl->XGameSaveCloseProvider(This,provider)
#define IXGameSaveImpl_XGameSaveGetRemainingQuota(This,provider,remainingQuota) (This)->lpVtbl->XGameSaveGetRemainingQuota(This,provider,remainingQuota)
#define IXGameSaveImpl_XGameSaveGetRemainingQuotaAsync(This,provider,async) (This)->lpVtbl->XGameSaveGetRemainingQuotaAsync(This,provider,async)
#define IXGameSaveImpl_XGameSaveGetRemainingQuotaResult(This,async,remainingQuota) (This)->lpVtbl->XGameSaveGetRemainingQuotaResult(This,async,remainingQuota)
#define IXGameSaveImpl_XGameSaveDeleteContainer(This,provider,containerName) (This)->lpVtbl->XGameSaveDeleteContainer(This,provider,containerName)
#define IXGameSaveImpl_XGameSaveDeleteContainerAsync(This,provider,containerName,async) (This)->lpVtbl->XGameSaveDeleteContainerAsync(This,provider,containerName,async)
#define IXGameSaveImpl_XGameSaveDeleteContainerResult(This,async) (This)->lpVtbl->XGameSaveDeleteContainerResult(This,async)
#define IXGameSaveImpl_XGameSaveGetContainerInfo(This,provider,containerName,context,callback) (This)->lpVtbl->XGameSaveGetContainerInfo(This,provider,containerName,context,callback)
#define IXGameSaveImpl_XGameSaveEnumerateContainerInfo(This,provider,context,callback) (This)->lpVtbl->XGameSaveEnumerateContainerInfo(This,provider,context,callback)
#define IXGameSaveImpl_XGameSaveEnumerateContainerInfoByName(This,provider,containerNamePrefix,context,callback) (This)->lpVtbl->XGameSaveEnumerateContainerInfoByName(This,provider,containerNamePrefix,context,callback)
#define IXGameSaveImpl_XGameSaveCreateContainer(This,provider,containerName,containerContext) (This)->lpVtbl->XGameSaveCreateContainer(This,provider,containerName,containerContext)
#define IXGameSaveImpl_XGameSaveCloseContainer(This,context) (This)->lpVtbl->XGameSaveCloseContainer(This,context)
#define IXGameSaveImpl_XGameSaveEnumerateBlobInfo(This,container,context,callback) (This)->lpVtbl->XGameSaveEnumerateBlobInfo(This,container,context,callback)
#define IXGameSaveImpl_XGameSaveEnumerateBlobInfoByName(This,container,blobNamePrefix,context,callback) (This)->lpVtbl->XGameSaveEnumerateBlobInfoByName(This,container,blobNamePrefix,context,callback)
#define IXGameSaveImpl_XGameSaveReadBlobData(This,container,blobNames,countOfBlobs,blobsSize,blobData) (This)->lpVtbl->XGameSaveReadBlobData(This,container,blobNames,countOfBlobs,blobsSize,blobData)
#define IXGameSaveImpl_XGameSaveReadBlobDataAsync(This,container,blobNames,countOfBlobs,async) (This)->lpVtbl->XGameSaveReadBlobDataAsync(This,container,blobNames,countOfBlobs,async)
#define IXGameSaveImpl_XGameSaveReadBlobDataResult(This,async,blobsSize,blobData,countOfBlobs) (This)->lpVtbl->XGameSaveReadBlobDataResult(This,async,blobsSize,blobData,countOfBlobs)
#define IXGameSaveImpl_XGameSaveCreateUpdate(This,container,containerDisplayName,updateContext) (This)->lpVtbl->XGameSaveCreateUpdate(This,container,containerDisplayName,updateContext)
#define IXGameSaveImpl_XGameSaveCloseUpdate(This,context) (This)->lpVtbl->XGameSaveCloseUpdate(This,context)
#define IXGameSaveImpl_XGameSaveSubmitBlobWrite(This,updateContext,blobName,data,byteCount) (This)->lpVtbl->XGameSaveSubmitBlobWrite(This,updateContext,blobName,data,byteCount)
#define IXGameSaveImpl_XGameSaveSubmitBlobDelete(This,updateContext,blobName) (This)->lpVtbl->XGameSaveSubmitBlobDelete(This,updateContext,blobName)
#define IXGameSaveImpl_XGameSaveSubmitUpdate(This,updateContext) (This)->lpVtbl->XGameSaveSubmitUpdate(This,updateContext)
#define IXGameSaveImpl_XGameSaveSubmitUpdateAsync(This,updateContext,async) (This)->lpVtbl->XGameSaveSubmitUpdateAsync(This,updateContext,async)
#define IXGameSaveImpl_XGameSaveSubmitUpdateResult(This,async) (This)->lpVtbl->XGameSaveSubmitUpdateResult(This,async)
#else
/*** IUnknown methods ***/
static inline HRESULT IXGameSaveImpl_QueryInterface(IXGameSaveImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXGameSaveImpl_AddRef(IXGameSaveImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXGameSaveImpl_Release(IXGameSaveImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IXGameSaveImpl methods ***/
static inline HRESULT IXGameSaveImpl_XGameSaveInitializeProvider(IXGameSaveImpl* This,XUserHandle requestingUser,const char *configurationId,BOOLEAN syncOnDemand,XGameSaveProviderHandle *provider) {
    return This->lpVtbl->XGameSaveInitializeProvider(This,requestingUser,configurationId,syncOnDemand,provider);
}
static inline HRESULT IXGameSaveImpl_XGameSaveInitializeProviderAsync(IXGameSaveImpl* This,XUserHandle requestingUser,const char *configurationId,BOOLEAN syncOnDemand,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveInitializeProviderAsync(This,requestingUser,configurationId,syncOnDemand,async);
}
static inline HRESULT IXGameSaveImpl_XGameSaveInitializeProviderResult(IXGameSaveImpl* This,XAsyncBlock *async,XGameSaveProviderHandle *provider) {
    return This->lpVtbl->XGameSaveInitializeProviderResult(This,async,provider);
}
static inline void IXGameSaveImpl_XGameSaveCloseProvider(IXGameSaveImpl* This,XGameSaveProviderHandle provider) {
    This->lpVtbl->XGameSaveCloseProvider(This,provider);
}
static inline HRESULT IXGameSaveImpl_XGameSaveGetRemainingQuota(IXGameSaveImpl* This,XGameSaveProviderHandle provider,INT64 *remainingQuota) {
    return This->lpVtbl->XGameSaveGetRemainingQuota(This,provider,remainingQuota);
}
static inline HRESULT IXGameSaveImpl_XGameSaveGetRemainingQuotaAsync(IXGameSaveImpl* This,XGameSaveProviderHandle provider,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveGetRemainingQuotaAsync(This,provider,async);
}
static inline HRESULT IXGameSaveImpl_XGameSaveGetRemainingQuotaResult(IXGameSaveImpl* This,XAsyncBlock *async,INT64 *remainingQuota) {
    return This->lpVtbl->XGameSaveGetRemainingQuotaResult(This,async,remainingQuota);
}
static inline HRESULT IXGameSaveImpl_XGameSaveDeleteContainer(IXGameSaveImpl* This,XGameSaveProviderHandle provider,const char *containerName) {
    return This->lpVtbl->XGameSaveDeleteContainer(This,provider,containerName);
}
static inline HRESULT IXGameSaveImpl_XGameSaveDeleteContainerAsync(IXGameSaveImpl* This,XGameSaveProviderHandle provider,const char *containerName,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveDeleteContainerAsync(This,provider,containerName,async);
}
static inline HRESULT IXGameSaveImpl_XGameSaveDeleteContainerResult(IXGameSaveImpl* This,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveDeleteContainerResult(This,async);
}
static inline HRESULT IXGameSaveImpl_XGameSaveGetContainerInfo(IXGameSaveImpl* This,XGameSaveProviderHandle provider,const char *containerName,void *context,XGameSaveContainerInfoCallback *callback) {
    return This->lpVtbl->XGameSaveGetContainerInfo(This,provider,containerName,context,callback);
}
static inline HRESULT IXGameSaveImpl_XGameSaveEnumerateContainerInfo(IXGameSaveImpl* This,XGameSaveProviderHandle provider,void *context,XGameSaveContainerInfoCallback *callback) {
    return This->lpVtbl->XGameSaveEnumerateContainerInfo(This,provider,context,callback);
}
static inline HRESULT IXGameSaveImpl_XGameSaveEnumerateContainerInfoByName(IXGameSaveImpl* This,XGameSaveProviderHandle provider,const char *containerNamePrefix,void *context,XGameSaveContainerInfoCallback *callback) {
    return This->lpVtbl->XGameSaveEnumerateContainerInfoByName(This,provider,containerNamePrefix,context,callback);
}
static inline HRESULT IXGameSaveImpl_XGameSaveCreateContainer(IXGameSaveImpl* This,XGameSaveProviderHandle provider,const char *containerName,XGameSaveContainerHandle *containerContext) {
    return This->lpVtbl->XGameSaveCreateContainer(This,provider,containerName,containerContext);
}
static inline void IXGameSaveImpl_XGameSaveCloseContainer(IXGameSaveImpl* This,XGameSaveContainerHandle context) {
    This->lpVtbl->XGameSaveCloseContainer(This,context);
}
static inline HRESULT IXGameSaveImpl_XGameSaveEnumerateBlobInfo(IXGameSaveImpl* This,XGameSaveContainerHandle container,void *context,XGameSaveBlobInfoCallback *callback) {
    return This->lpVtbl->XGameSaveEnumerateBlobInfo(This,container,context,callback);
}
static inline HRESULT IXGameSaveImpl_XGameSaveEnumerateBlobInfoByName(IXGameSaveImpl* This,XGameSaveContainerHandle container,const char *blobNamePrefix,void *context,XGameSaveBlobInfoCallback *callback) {
    return This->lpVtbl->XGameSaveEnumerateBlobInfoByName(This,container,blobNamePrefix,context,callback);
}
static inline HRESULT IXGameSaveImpl_XGameSaveReadBlobData(IXGameSaveImpl* This,XGameSaveContainerHandle container,const char **blobNames,UINT32 *countOfBlobs,SIZE_T blobsSize,XGameSaveBlob *blobData) {
    return This->lpVtbl->XGameSaveReadBlobData(This,container,blobNames,countOfBlobs,blobsSize,blobData);
}
static inline HRESULT IXGameSaveImpl_XGameSaveReadBlobDataAsync(IXGameSaveImpl* This,XGameSaveContainerHandle container,const char **blobNames,UINT32 countOfBlobs,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveReadBlobDataAsync(This,container,blobNames,countOfBlobs,async);
}
static inline HRESULT IXGameSaveImpl_XGameSaveReadBlobDataResult(IXGameSaveImpl* This,XAsyncBlock *async,SIZE_T blobsSize,XGameSaveBlob *blobData,UINT32 *countOfBlobs) {
    return This->lpVtbl->XGameSaveReadBlobDataResult(This,async,blobsSize,blobData,countOfBlobs);
}
static inline HRESULT IXGameSaveImpl_XGameSaveCreateUpdate(IXGameSaveImpl* This,XGameSaveContainerHandle container,const char *containerDisplayName,XGameSaveUpdateHandle *updateContext) {
    return This->lpVtbl->XGameSaveCreateUpdate(This,container,containerDisplayName,updateContext);
}
static inline void IXGameSaveImpl_XGameSaveCloseUpdate(IXGameSaveImpl* This,XGameSaveUpdateHandle context) {
    This->lpVtbl->XGameSaveCloseUpdate(This,context);
}
static inline HRESULT IXGameSaveImpl_XGameSaveSubmitBlobWrite(IXGameSaveImpl* This,XGameSaveUpdateHandle updateContext,const char *blobName,UINT8 *data,SIZE_T byteCount) {
    return This->lpVtbl->XGameSaveSubmitBlobWrite(This,updateContext,blobName,data,byteCount);
}
static inline HRESULT IXGameSaveImpl_XGameSaveSubmitBlobDelete(IXGameSaveImpl* This,XGameSaveUpdateHandle updateContext,const char *blobName) {
    return This->lpVtbl->XGameSaveSubmitBlobDelete(This,updateContext,blobName);
}
static inline HRESULT IXGameSaveImpl_XGameSaveSubmitUpdate(IXGameSaveImpl* This,XGameSaveUpdateHandle updateContext) {
    return This->lpVtbl->XGameSaveSubmitUpdate(This,updateContext);
}
static inline HRESULT IXGameSaveImpl_XGameSaveSubmitUpdateAsync(IXGameSaveImpl* This,XGameSaveUpdateHandle updateContext,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveSubmitUpdateAsync(This,updateContext,async);
}
static inline HRESULT IXGameSaveImpl_XGameSaveSubmitUpdateResult(IXGameSaveImpl* This,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveSubmitUpdateResult(This,async);
}
#endif
#endif

#endif


#endif  /* __IXGameSaveImpl_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IXGameSaveImpl2 interface
 */
#ifndef __IXGameSaveImpl2_INTERFACE_DEFINED__
#define __IXGameSaveImpl2_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXGameSaveImpl2, 0x704c3f58, 0xe629, 0x4cc2, 0xb1,0x97, 0x30,0x51,0x1b,0x99,0x6e,0xe2);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("704c3f58-e629-4cc2-b197-30511b996ee2")
IXGameSaveImpl2 : public IXGameSaveImpl
{
    virtual HRESULT STDMETHODCALLTYPE XGameSaveFilesGetFolderWithUiAsync(
        XUserHandle requestingUser,
        const char *configurationId,
        XAsyncBlock *async) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveFilesGetFolderWithUiResult(
        XAsyncBlock *async,
        SIZE_T folderSize,
        char *folderResult) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameSaveFilesGetRemainingQuota(
        XUserHandle userContext,
        const char *configurationId,
        INT64 *remainingQuota) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXGameSaveImpl2, 0x704c3f58, 0xe629, 0x4cc2, 0xb1,0x97, 0x30,0x51,0x1b,0x99,0x6e,0xe2)
#endif
#else
typedef struct IXGameSaveImpl2Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXGameSaveImpl2 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXGameSaveImpl2 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXGameSaveImpl2 *This);

    /*** IXGameSaveImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XGameSaveInitializeProvider)(
        IXGameSaveImpl2 *This,
        XUserHandle requestingUser,
        const char *configurationId,
        BOOLEAN syncOnDemand,
        XGameSaveProviderHandle *provider);

    HRESULT (STDMETHODCALLTYPE *XGameSaveInitializeProviderAsync)(
        IXGameSaveImpl2 *This,
        XUserHandle requestingUser,
        const char *configurationId,
        BOOLEAN syncOnDemand,
        XAsyncBlock *async);

    HRESULT (STDMETHODCALLTYPE *XGameSaveInitializeProviderResult)(
        IXGameSaveImpl2 *This,
        XAsyncBlock *async,
        XGameSaveProviderHandle *provider);

    void (STDMETHODCALLTYPE *XGameSaveCloseProvider)(
        IXGameSaveImpl2 *This,
        XGameSaveProviderHandle provider);

    HRESULT (STDMETHODCALLTYPE *XGameSaveGetRemainingQuota)(
        IXGameSaveImpl2 *This,
        XGameSaveProviderHandle provider,
        INT64 *remainingQuota);

    HRESULT (STDMETHODCALLTYPE *XGameSaveGetRemainingQuotaAsync)(
        IXGameSaveImpl2 *This,
        XGameSaveProviderHandle provider,
        XAsyncBlock *async);

    HRESULT (STDMETHODCALLTYPE *XGameSaveGetRemainingQuotaResult)(
        IXGameSaveImpl2 *This,
        XAsyncBlock *async,
        INT64 *remainingQuota);

    HRESULT (STDMETHODCALLTYPE *XGameSaveDeleteContainer)(
        IXGameSaveImpl2 *This,
        XGameSaveProviderHandle provider,
        const char *containerName);

    HRESULT (STDMETHODCALLTYPE *XGameSaveDeleteContainerAsync)(
        IXGameSaveImpl2 *This,
        XGameSaveProviderHandle provider,
        const char *containerName,
        XAsyncBlock *async);

    HRESULT (STDMETHODCALLTYPE *XGameSaveDeleteContainerResult)(
        IXGameSaveImpl2 *This,
        XAsyncBlock *async);

    HRESULT (STDMETHODCALLTYPE *XGameSaveGetContainerInfo)(
        IXGameSaveImpl2 *This,
        XGameSaveProviderHandle provider,
        const char *containerName,
        void *context,
        XGameSaveContainerInfoCallback *callback);

    HRESULT (STDMETHODCALLTYPE *XGameSaveEnumerateContainerInfo)(
        IXGameSaveImpl2 *This,
        XGameSaveProviderHandle provider,
        void *context,
        XGameSaveContainerInfoCallback *callback);

    HRESULT (STDMETHODCALLTYPE *XGameSaveEnumerateContainerInfoByName)(
        IXGameSaveImpl2 *This,
        XGameSaveProviderHandle provider,
        const char *containerNamePrefix,
        void *context,
        XGameSaveContainerInfoCallback *callback);

    HRESULT (STDMETHODCALLTYPE *XGameSaveCreateContainer)(
        IXGameSaveImpl2 *This,
        XGameSaveProviderHandle provider,
        const char *containerName,
        XGameSaveContainerHandle *containerContext);

    void (STDMETHODCALLTYPE *XGameSaveCloseContainer)(
        IXGameSaveImpl2 *This,
        XGameSaveContainerHandle context);

    HRESULT (STDMETHODCALLTYPE *XGameSaveEnumerateBlobInfo)(
        IXGameSaveImpl2 *This,
        XGameSaveContainerHandle container,
        void *context,
        XGameSaveBlobInfoCallback *callback);

    HRESULT (STDMETHODCALLTYPE *XGameSaveEnumerateBlobInfoByName)(
        IXGameSaveImpl2 *This,
        XGameSaveContainerHandle container,
        const char *blobNamePrefix,
        void *context,
        XGameSaveBlobInfoCallback *callback);

    HRESULT (STDMETHODCALLTYPE *XGameSaveReadBlobData)(
        IXGameSaveImpl2 *This,
        XGameSaveContainerHandle container,
        const char **blobNames,
        UINT32 *countOfBlobs,
        SIZE_T blobsSize,
        XGameSaveBlob *blobData);

    HRESULT (STDMETHODCALLTYPE *XGameSaveReadBlobDataAsync)(
        IXGameSaveImpl2 *This,
        XGameSaveContainerHandle container,
        const char **blobNames,
        UINT32 countOfBlobs,
        XAsyncBlock *async);

    HRESULT (STDMETHODCALLTYPE *XGameSaveReadBlobDataResult)(
        IXGameSaveImpl2 *This,
        XAsyncBlock *async,
        SIZE_T blobsSize,
        XGameSaveBlob *blobData,
        UINT32 *countOfBlobs);

    HRESULT (STDMETHODCALLTYPE *XGameSaveCreateUpdate)(
        IXGameSaveImpl2 *This,
        XGameSaveContainerHandle container,
        const char *containerDisplayName,
        XGameSaveUpdateHandle *updateContext);

    void (STDMETHODCALLTYPE *XGameSaveCloseUpdate)(
        IXGameSaveImpl2 *This,
        XGameSaveUpdateHandle context);

    HRESULT (STDMETHODCALLTYPE *XGameSaveSubmitBlobWrite)(
        IXGameSaveImpl2 *This,
        XGameSaveUpdateHandle updateContext,
        const char *blobName,
        UINT8 *data,
        SIZE_T byteCount);

    HRESULT (STDMETHODCALLTYPE *XGameSaveSubmitBlobDelete)(
        IXGameSaveImpl2 *This,
        XGameSaveUpdateHandle updateContext,
        const char *blobName);

    HRESULT (STDMETHODCALLTYPE *XGameSaveSubmitUpdate)(
        IXGameSaveImpl2 *This,
        XGameSaveUpdateHandle updateContext);

    HRESULT (STDMETHODCALLTYPE *XGameSaveSubmitUpdateAsync)(
        IXGameSaveImpl2 *This,
        XGameSaveUpdateHandle updateContext,
        XAsyncBlock *async);

    HRESULT (STDMETHODCALLTYPE *XGameSaveSubmitUpdateResult)(
        IXGameSaveImpl2 *This,
        XAsyncBlock *async);

    /*** IXGameSaveImpl2 methods ***/
    HRESULT (STDMETHODCALLTYPE *XGameSaveFilesGetFolderWithUiAsync)(
        IXGameSaveImpl2 *This,
        XUserHandle requestingUser,
        const char *configurationId,
        XAsyncBlock *async);

    HRESULT (STDMETHODCALLTYPE *XGameSaveFilesGetFolderWithUiResult)(
        IXGameSaveImpl2 *This,
        XAsyncBlock *async,
        SIZE_T folderSize,
        char *folderResult);

    HRESULT (STDMETHODCALLTYPE *XGameSaveFilesGetRemainingQuota)(
        IXGameSaveImpl2 *This,
        XUserHandle userContext,
        const char *configurationId,
        INT64 *remainingQuota);

    END_INTERFACE
} IXGameSaveImpl2Vtbl;

interface IXGameSaveImpl2 {
    CONST_VTBL IXGameSaveImpl2Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXGameSaveImpl2_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXGameSaveImpl2_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXGameSaveImpl2_Release(This) (This)->lpVtbl->Release(This)
/*** IXGameSaveImpl methods ***/
#define IXGameSaveImpl2_XGameSaveInitializeProvider(This,requestingUser,configurationId,syncOnDemand,provider) (This)->lpVtbl->XGameSaveInitializeProvider(This,requestingUser,configurationId,syncOnDemand,provider)
#define IXGameSaveImpl2_XGameSaveInitializeProviderAsync(This,requestingUser,configurationId,syncOnDemand,async) (This)->lpVtbl->XGameSaveInitializeProviderAsync(This,requestingUser,configurationId,syncOnDemand,async)
#define IXGameSaveImpl2_XGameSaveInitializeProviderResult(This,async,provider) (This)->lpVtbl->XGameSaveInitializeProviderResult(This,async,provider)
#define IXGameSaveImpl2_XGameSaveCloseProvider(This,provider) (This)->lpVtbl->XGameSaveCloseProvider(This,provider)
#define IXGameSaveImpl2_XGameSaveGetRemainingQuota(This,provider,remainingQuota) (This)->lpVtbl->XGameSaveGetRemainingQuota(This,provider,remainingQuota)
#define IXGameSaveImpl2_XGameSaveGetRemainingQuotaAsync(This,provider,async) (This)->lpVtbl->XGameSaveGetRemainingQuotaAsync(This,provider,async)
#define IXGameSaveImpl2_XGameSaveGetRemainingQuotaResult(This,async,remainingQuota) (This)->lpVtbl->XGameSaveGetRemainingQuotaResult(This,async,remainingQuota)
#define IXGameSaveImpl2_XGameSaveDeleteContainer(This,provider,containerName) (This)->lpVtbl->XGameSaveDeleteContainer(This,provider,containerName)
#define IXGameSaveImpl2_XGameSaveDeleteContainerAsync(This,provider,containerName,async) (This)->lpVtbl->XGameSaveDeleteContainerAsync(This,provider,containerName,async)
#define IXGameSaveImpl2_XGameSaveDeleteContainerResult(This,async) (This)->lpVtbl->XGameSaveDeleteContainerResult(This,async)
#define IXGameSaveImpl2_XGameSaveGetContainerInfo(This,provider,containerName,context,callback) (This)->lpVtbl->XGameSaveGetContainerInfo(This,provider,containerName,context,callback)
#define IXGameSaveImpl2_XGameSaveEnumerateContainerInfo(This,provider,context,callback) (This)->lpVtbl->XGameSaveEnumerateContainerInfo(This,provider,context,callback)
#define IXGameSaveImpl2_XGameSaveEnumerateContainerInfoByName(This,provider,containerNamePrefix,context,callback) (This)->lpVtbl->XGameSaveEnumerateContainerInfoByName(This,provider,containerNamePrefix,context,callback)
#define IXGameSaveImpl2_XGameSaveCreateContainer(This,provider,containerName,containerContext) (This)->lpVtbl->XGameSaveCreateContainer(This,provider,containerName,containerContext)
#define IXGameSaveImpl2_XGameSaveCloseContainer(This,context) (This)->lpVtbl->XGameSaveCloseContainer(This,context)
#define IXGameSaveImpl2_XGameSaveEnumerateBlobInfo(This,container,context,callback) (This)->lpVtbl->XGameSaveEnumerateBlobInfo(This,container,context,callback)
#define IXGameSaveImpl2_XGameSaveEnumerateBlobInfoByName(This,container,blobNamePrefix,context,callback) (This)->lpVtbl->XGameSaveEnumerateBlobInfoByName(This,container,blobNamePrefix,context,callback)
#define IXGameSaveImpl2_XGameSaveReadBlobData(This,container,blobNames,countOfBlobs,blobsSize,blobData) (This)->lpVtbl->XGameSaveReadBlobData(This,container,blobNames,countOfBlobs,blobsSize,blobData)
#define IXGameSaveImpl2_XGameSaveReadBlobDataAsync(This,container,blobNames,countOfBlobs,async) (This)->lpVtbl->XGameSaveReadBlobDataAsync(This,container,blobNames,countOfBlobs,async)
#define IXGameSaveImpl2_XGameSaveReadBlobDataResult(This,async,blobsSize,blobData,countOfBlobs) (This)->lpVtbl->XGameSaveReadBlobDataResult(This,async,blobsSize,blobData,countOfBlobs)
#define IXGameSaveImpl2_XGameSaveCreateUpdate(This,container,containerDisplayName,updateContext) (This)->lpVtbl->XGameSaveCreateUpdate(This,container,containerDisplayName,updateContext)
#define IXGameSaveImpl2_XGameSaveCloseUpdate(This,context) (This)->lpVtbl->XGameSaveCloseUpdate(This,context)
#define IXGameSaveImpl2_XGameSaveSubmitBlobWrite(This,updateContext,blobName,data,byteCount) (This)->lpVtbl->XGameSaveSubmitBlobWrite(This,updateContext,blobName,data,byteCount)
#define IXGameSaveImpl2_XGameSaveSubmitBlobDelete(This,updateContext,blobName) (This)->lpVtbl->XGameSaveSubmitBlobDelete(This,updateContext,blobName)
#define IXGameSaveImpl2_XGameSaveSubmitUpdate(This,updateContext) (This)->lpVtbl->XGameSaveSubmitUpdate(This,updateContext)
#define IXGameSaveImpl2_XGameSaveSubmitUpdateAsync(This,updateContext,async) (This)->lpVtbl->XGameSaveSubmitUpdateAsync(This,updateContext,async)
#define IXGameSaveImpl2_XGameSaveSubmitUpdateResult(This,async) (This)->lpVtbl->XGameSaveSubmitUpdateResult(This,async)
/*** IXGameSaveImpl2 methods ***/
#define IXGameSaveImpl2_XGameSaveFilesGetFolderWithUiAsync(This,requestingUser,configurationId,async) (This)->lpVtbl->XGameSaveFilesGetFolderWithUiAsync(This,requestingUser,configurationId,async)
#define IXGameSaveImpl2_XGameSaveFilesGetFolderWithUiResult(This,async,folderSize,folderResult) (This)->lpVtbl->XGameSaveFilesGetFolderWithUiResult(This,async,folderSize,folderResult)
#define IXGameSaveImpl2_XGameSaveFilesGetRemainingQuota(This,userContext,configurationId,remainingQuota) (This)->lpVtbl->XGameSaveFilesGetRemainingQuota(This,userContext,configurationId,remainingQuota)
#else
/*** IUnknown methods ***/
static inline HRESULT IXGameSaveImpl2_QueryInterface(IXGameSaveImpl2* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXGameSaveImpl2_AddRef(IXGameSaveImpl2* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXGameSaveImpl2_Release(IXGameSaveImpl2* This) {
    return This->lpVtbl->Release(This);
}
/*** IXGameSaveImpl methods ***/
static inline HRESULT IXGameSaveImpl2_XGameSaveInitializeProvider(IXGameSaveImpl2* This,XUserHandle requestingUser,const char *configurationId,BOOLEAN syncOnDemand,XGameSaveProviderHandle *provider) {
    return This->lpVtbl->XGameSaveInitializeProvider(This,requestingUser,configurationId,syncOnDemand,provider);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveInitializeProviderAsync(IXGameSaveImpl2* This,XUserHandle requestingUser,const char *configurationId,BOOLEAN syncOnDemand,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveInitializeProviderAsync(This,requestingUser,configurationId,syncOnDemand,async);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveInitializeProviderResult(IXGameSaveImpl2* This,XAsyncBlock *async,XGameSaveProviderHandle *provider) {
    return This->lpVtbl->XGameSaveInitializeProviderResult(This,async,provider);
}
static inline void IXGameSaveImpl2_XGameSaveCloseProvider(IXGameSaveImpl2* This,XGameSaveProviderHandle provider) {
    This->lpVtbl->XGameSaveCloseProvider(This,provider);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveGetRemainingQuota(IXGameSaveImpl2* This,XGameSaveProviderHandle provider,INT64 *remainingQuota) {
    return This->lpVtbl->XGameSaveGetRemainingQuota(This,provider,remainingQuota);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveGetRemainingQuotaAsync(IXGameSaveImpl2* This,XGameSaveProviderHandle provider,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveGetRemainingQuotaAsync(This,provider,async);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveGetRemainingQuotaResult(IXGameSaveImpl2* This,XAsyncBlock *async,INT64 *remainingQuota) {
    return This->lpVtbl->XGameSaveGetRemainingQuotaResult(This,async,remainingQuota);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveDeleteContainer(IXGameSaveImpl2* This,XGameSaveProviderHandle provider,const char *containerName) {
    return This->lpVtbl->XGameSaveDeleteContainer(This,provider,containerName);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveDeleteContainerAsync(IXGameSaveImpl2* This,XGameSaveProviderHandle provider,const char *containerName,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveDeleteContainerAsync(This,provider,containerName,async);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveDeleteContainerResult(IXGameSaveImpl2* This,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveDeleteContainerResult(This,async);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveGetContainerInfo(IXGameSaveImpl2* This,XGameSaveProviderHandle provider,const char *containerName,void *context,XGameSaveContainerInfoCallback *callback) {
    return This->lpVtbl->XGameSaveGetContainerInfo(This,provider,containerName,context,callback);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveEnumerateContainerInfo(IXGameSaveImpl2* This,XGameSaveProviderHandle provider,void *context,XGameSaveContainerInfoCallback *callback) {
    return This->lpVtbl->XGameSaveEnumerateContainerInfo(This,provider,context,callback);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveEnumerateContainerInfoByName(IXGameSaveImpl2* This,XGameSaveProviderHandle provider,const char *containerNamePrefix,void *context,XGameSaveContainerInfoCallback *callback) {
    return This->lpVtbl->XGameSaveEnumerateContainerInfoByName(This,provider,containerNamePrefix,context,callback);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveCreateContainer(IXGameSaveImpl2* This,XGameSaveProviderHandle provider,const char *containerName,XGameSaveContainerHandle *containerContext) {
    return This->lpVtbl->XGameSaveCreateContainer(This,provider,containerName,containerContext);
}
static inline void IXGameSaveImpl2_XGameSaveCloseContainer(IXGameSaveImpl2* This,XGameSaveContainerHandle context) {
    This->lpVtbl->XGameSaveCloseContainer(This,context);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveEnumerateBlobInfo(IXGameSaveImpl2* This,XGameSaveContainerHandle container,void *context,XGameSaveBlobInfoCallback *callback) {
    return This->lpVtbl->XGameSaveEnumerateBlobInfo(This,container,context,callback);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveEnumerateBlobInfoByName(IXGameSaveImpl2* This,XGameSaveContainerHandle container,const char *blobNamePrefix,void *context,XGameSaveBlobInfoCallback *callback) {
    return This->lpVtbl->XGameSaveEnumerateBlobInfoByName(This,container,blobNamePrefix,context,callback);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveReadBlobData(IXGameSaveImpl2* This,XGameSaveContainerHandle container,const char **blobNames,UINT32 *countOfBlobs,SIZE_T blobsSize,XGameSaveBlob *blobData) {
    return This->lpVtbl->XGameSaveReadBlobData(This,container,blobNames,countOfBlobs,blobsSize,blobData);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveReadBlobDataAsync(IXGameSaveImpl2* This,XGameSaveContainerHandle container,const char **blobNames,UINT32 countOfBlobs,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveReadBlobDataAsync(This,container,blobNames,countOfBlobs,async);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveReadBlobDataResult(IXGameSaveImpl2* This,XAsyncBlock *async,SIZE_T blobsSize,XGameSaveBlob *blobData,UINT32 *countOfBlobs) {
    return This->lpVtbl->XGameSaveReadBlobDataResult(This,async,blobsSize,blobData,countOfBlobs);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveCreateUpdate(IXGameSaveImpl2* This,XGameSaveContainerHandle container,const char *containerDisplayName,XGameSaveUpdateHandle *updateContext) {
    return This->lpVtbl->XGameSaveCreateUpdate(This,container,containerDisplayName,updateContext);
}
static inline void IXGameSaveImpl2_XGameSaveCloseUpdate(IXGameSaveImpl2* This,XGameSaveUpdateHandle context) {
    This->lpVtbl->XGameSaveCloseUpdate(This,context);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveSubmitBlobWrite(IXGameSaveImpl2* This,XGameSaveUpdateHandle updateContext,const char *blobName,UINT8 *data,SIZE_T byteCount) {
    return This->lpVtbl->XGameSaveSubmitBlobWrite(This,updateContext,blobName,data,byteCount);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveSubmitBlobDelete(IXGameSaveImpl2* This,XGameSaveUpdateHandle updateContext,const char *blobName) {
    return This->lpVtbl->XGameSaveSubmitBlobDelete(This,updateContext,blobName);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveSubmitUpdate(IXGameSaveImpl2* This,XGameSaveUpdateHandle updateContext) {
    return This->lpVtbl->XGameSaveSubmitUpdate(This,updateContext);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveSubmitUpdateAsync(IXGameSaveImpl2* This,XGameSaveUpdateHandle updateContext,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveSubmitUpdateAsync(This,updateContext,async);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveSubmitUpdateResult(IXGameSaveImpl2* This,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveSubmitUpdateResult(This,async);
}
/*** IXGameSaveImpl2 methods ***/
static inline HRESULT IXGameSaveImpl2_XGameSaveFilesGetFolderWithUiAsync(IXGameSaveImpl2* This,XUserHandle requestingUser,const char *configurationId,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveFilesGetFolderWithUiAsync(This,requestingUser,configurationId,async);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveFilesGetFolderWithUiResult(IXGameSaveImpl2* This,XAsyncBlock *async,SIZE_T folderSize,char *folderResult) {
    return This->lpVtbl->XGameSaveFilesGetFolderWithUiResult(This,async,folderSize,folderResult);
}
static inline HRESULT IXGameSaveImpl2_XGameSaveFilesGetRemainingQuota(IXGameSaveImpl2* This,XUserHandle userContext,const char *configurationId,INT64 *remainingQuota) {
    return This->lpVtbl->XGameSaveFilesGetRemainingQuota(This,userContext,configurationId,remainingQuota);
}
#endif
#endif

#endif


#endif  /* __IXGameSaveImpl2_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IXGameSaveImpl3 interface
 */
#ifndef __IXGameSaveImpl3_INTERFACE_DEFINED__
#define __IXGameSaveImpl3_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXGameSaveImpl3, 0x1bfff3af, 0xf14a, 0x40a3, 0x8e,0x35, 0x9a,0xda,0x90,0x65,0x93,0xf9);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("1bfff3af-f14a-40a3-8e35-9ada906593f9")
IXGameSaveImpl3 : public IXGameSaveImpl2
{
};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXGameSaveImpl3, 0x1bfff3af, 0xf14a, 0x40a3, 0x8e,0x35, 0x9a,0xda,0x90,0x65,0x93,0xf9)
#endif
#else
typedef struct IXGameSaveImpl3Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXGameSaveImpl3 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXGameSaveImpl3 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXGameSaveImpl3 *This);

    /*** IXGameSaveImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XGameSaveInitializeProvider)(
        IXGameSaveImpl3 *This,
        XUserHandle requestingUser,
        const char *configurationId,
        BOOLEAN syncOnDemand,
        XGameSaveProviderHandle *provider);

    HRESULT (STDMETHODCALLTYPE *XGameSaveInitializeProviderAsync)(
        IXGameSaveImpl3 *This,
        XUserHandle requestingUser,
        const char *configurationId,
        BOOLEAN syncOnDemand,
        XAsyncBlock *async);

    HRESULT (STDMETHODCALLTYPE *XGameSaveInitializeProviderResult)(
        IXGameSaveImpl3 *This,
        XAsyncBlock *async,
        XGameSaveProviderHandle *provider);

    void (STDMETHODCALLTYPE *XGameSaveCloseProvider)(
        IXGameSaveImpl3 *This,
        XGameSaveProviderHandle provider);

    HRESULT (STDMETHODCALLTYPE *XGameSaveGetRemainingQuota)(
        IXGameSaveImpl3 *This,
        XGameSaveProviderHandle provider,
        INT64 *remainingQuota);

    HRESULT (STDMETHODCALLTYPE *XGameSaveGetRemainingQuotaAsync)(
        IXGameSaveImpl3 *This,
        XGameSaveProviderHandle provider,
        XAsyncBlock *async);

    HRESULT (STDMETHODCALLTYPE *XGameSaveGetRemainingQuotaResult)(
        IXGameSaveImpl3 *This,
        XAsyncBlock *async,
        INT64 *remainingQuota);

    HRESULT (STDMETHODCALLTYPE *XGameSaveDeleteContainer)(
        IXGameSaveImpl3 *This,
        XGameSaveProviderHandle provider,
        const char *containerName);

    HRESULT (STDMETHODCALLTYPE *XGameSaveDeleteContainerAsync)(
        IXGameSaveImpl3 *This,
        XGameSaveProviderHandle provider,
        const char *containerName,
        XAsyncBlock *async);

    HRESULT (STDMETHODCALLTYPE *XGameSaveDeleteContainerResult)(
        IXGameSaveImpl3 *This,
        XAsyncBlock *async);

    HRESULT (STDMETHODCALLTYPE *XGameSaveGetContainerInfo)(
        IXGameSaveImpl3 *This,
        XGameSaveProviderHandle provider,
        const char *containerName,
        void *context,
        XGameSaveContainerInfoCallback *callback);

    HRESULT (STDMETHODCALLTYPE *XGameSaveEnumerateContainerInfo)(
        IXGameSaveImpl3 *This,
        XGameSaveProviderHandle provider,
        void *context,
        XGameSaveContainerInfoCallback *callback);

    HRESULT (STDMETHODCALLTYPE *XGameSaveEnumerateContainerInfoByName)(
        IXGameSaveImpl3 *This,
        XGameSaveProviderHandle provider,
        const char *containerNamePrefix,
        void *context,
        XGameSaveContainerInfoCallback *callback);

    HRESULT (STDMETHODCALLTYPE *XGameSaveCreateContainer)(
        IXGameSaveImpl3 *This,
        XGameSaveProviderHandle provider,
        const char *containerName,
        XGameSaveContainerHandle *containerContext);

    void (STDMETHODCALLTYPE *XGameSaveCloseContainer)(
        IXGameSaveImpl3 *This,
        XGameSaveContainerHandle context);

    HRESULT (STDMETHODCALLTYPE *XGameSaveEnumerateBlobInfo)(
        IXGameSaveImpl3 *This,
        XGameSaveContainerHandle container,
        void *context,
        XGameSaveBlobInfoCallback *callback);

    HRESULT (STDMETHODCALLTYPE *XGameSaveEnumerateBlobInfoByName)(
        IXGameSaveImpl3 *This,
        XGameSaveContainerHandle container,
        const char *blobNamePrefix,
        void *context,
        XGameSaveBlobInfoCallback *callback);

    HRESULT (STDMETHODCALLTYPE *XGameSaveReadBlobData)(
        IXGameSaveImpl3 *This,
        XGameSaveContainerHandle container,
        const char **blobNames,
        UINT32 *countOfBlobs,
        SIZE_T blobsSize,
        XGameSaveBlob *blobData);

    HRESULT (STDMETHODCALLTYPE *XGameSaveReadBlobDataAsync)(
        IXGameSaveImpl3 *This,
        XGameSaveContainerHandle container,
        const char **blobNames,
        UINT32 countOfBlobs,
        XAsyncBlock *async);

    HRESULT (STDMETHODCALLTYPE *XGameSaveReadBlobDataResult)(
        IXGameSaveImpl3 *This,
        XAsyncBlock *async,
        SIZE_T blobsSize,
        XGameSaveBlob *blobData,
        UINT32 *countOfBlobs);

    HRESULT (STDMETHODCALLTYPE *XGameSaveCreateUpdate)(
        IXGameSaveImpl3 *This,
        XGameSaveContainerHandle container,
        const char *containerDisplayName,
        XGameSaveUpdateHandle *updateContext);

    void (STDMETHODCALLTYPE *XGameSaveCloseUpdate)(
        IXGameSaveImpl3 *This,
        XGameSaveUpdateHandle context);

    HRESULT (STDMETHODCALLTYPE *XGameSaveSubmitBlobWrite)(
        IXGameSaveImpl3 *This,
        XGameSaveUpdateHandle updateContext,
        const char *blobName,
        UINT8 *data,
        SIZE_T byteCount);

    HRESULT (STDMETHODCALLTYPE *XGameSaveSubmitBlobDelete)(
        IXGameSaveImpl3 *This,
        XGameSaveUpdateHandle updateContext,
        const char *blobName);

    HRESULT (STDMETHODCALLTYPE *XGameSaveSubmitUpdate)(
        IXGameSaveImpl3 *This,
        XGameSaveUpdateHandle updateContext);

    HRESULT (STDMETHODCALLTYPE *XGameSaveSubmitUpdateAsync)(
        IXGameSaveImpl3 *This,
        XGameSaveUpdateHandle updateContext,
        XAsyncBlock *async);

    HRESULT (STDMETHODCALLTYPE *XGameSaveSubmitUpdateResult)(
        IXGameSaveImpl3 *This,
        XAsyncBlock *async);

    /*** IXGameSaveImpl2 methods ***/
    HRESULT (STDMETHODCALLTYPE *XGameSaveFilesGetFolderWithUiAsync)(
        IXGameSaveImpl3 *This,
        XUserHandle requestingUser,
        const char *configurationId,
        XAsyncBlock *async);

    HRESULT (STDMETHODCALLTYPE *XGameSaveFilesGetFolderWithUiResult)(
        IXGameSaveImpl3 *This,
        XAsyncBlock *async,
        SIZE_T folderSize,
        char *folderResult);

    HRESULT (STDMETHODCALLTYPE *XGameSaveFilesGetRemainingQuota)(
        IXGameSaveImpl3 *This,
        XUserHandle userContext,
        const char *configurationId,
        INT64 *remainingQuota);

    END_INTERFACE
} IXGameSaveImpl3Vtbl;

interface IXGameSaveImpl3 {
    CONST_VTBL IXGameSaveImpl3Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXGameSaveImpl3_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXGameSaveImpl3_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXGameSaveImpl3_Release(This) (This)->lpVtbl->Release(This)
/*** IXGameSaveImpl methods ***/
#define IXGameSaveImpl3_XGameSaveInitializeProvider(This,requestingUser,configurationId,syncOnDemand,provider) (This)->lpVtbl->XGameSaveInitializeProvider(This,requestingUser,configurationId,syncOnDemand,provider)
#define IXGameSaveImpl3_XGameSaveInitializeProviderAsync(This,requestingUser,configurationId,syncOnDemand,async) (This)->lpVtbl->XGameSaveInitializeProviderAsync(This,requestingUser,configurationId,syncOnDemand,async)
#define IXGameSaveImpl3_XGameSaveInitializeProviderResult(This,async,provider) (This)->lpVtbl->XGameSaveInitializeProviderResult(This,async,provider)
#define IXGameSaveImpl3_XGameSaveCloseProvider(This,provider) (This)->lpVtbl->XGameSaveCloseProvider(This,provider)
#define IXGameSaveImpl3_XGameSaveGetRemainingQuota(This,provider,remainingQuota) (This)->lpVtbl->XGameSaveGetRemainingQuota(This,provider,remainingQuota)
#define IXGameSaveImpl3_XGameSaveGetRemainingQuotaAsync(This,provider,async) (This)->lpVtbl->XGameSaveGetRemainingQuotaAsync(This,provider,async)
#define IXGameSaveImpl3_XGameSaveGetRemainingQuotaResult(This,async,remainingQuota) (This)->lpVtbl->XGameSaveGetRemainingQuotaResult(This,async,remainingQuota)
#define IXGameSaveImpl3_XGameSaveDeleteContainer(This,provider,containerName) (This)->lpVtbl->XGameSaveDeleteContainer(This,provider,containerName)
#define IXGameSaveImpl3_XGameSaveDeleteContainerAsync(This,provider,containerName,async) (This)->lpVtbl->XGameSaveDeleteContainerAsync(This,provider,containerName,async)
#define IXGameSaveImpl3_XGameSaveDeleteContainerResult(This,async) (This)->lpVtbl->XGameSaveDeleteContainerResult(This,async)
#define IXGameSaveImpl3_XGameSaveGetContainerInfo(This,provider,containerName,context,callback) (This)->lpVtbl->XGameSaveGetContainerInfo(This,provider,containerName,context,callback)
#define IXGameSaveImpl3_XGameSaveEnumerateContainerInfo(This,provider,context,callback) (This)->lpVtbl->XGameSaveEnumerateContainerInfo(This,provider,context,callback)
#define IXGameSaveImpl3_XGameSaveEnumerateContainerInfoByName(This,provider,containerNamePrefix,context,callback) (This)->lpVtbl->XGameSaveEnumerateContainerInfoByName(This,provider,containerNamePrefix,context,callback)
#define IXGameSaveImpl3_XGameSaveCreateContainer(This,provider,containerName,containerContext) (This)->lpVtbl->XGameSaveCreateContainer(This,provider,containerName,containerContext)
#define IXGameSaveImpl3_XGameSaveCloseContainer(This,context) (This)->lpVtbl->XGameSaveCloseContainer(This,context)
#define IXGameSaveImpl3_XGameSaveEnumerateBlobInfo(This,container,context,callback) (This)->lpVtbl->XGameSaveEnumerateBlobInfo(This,container,context,callback)
#define IXGameSaveImpl3_XGameSaveEnumerateBlobInfoByName(This,container,blobNamePrefix,context,callback) (This)->lpVtbl->XGameSaveEnumerateBlobInfoByName(This,container,blobNamePrefix,context,callback)
#define IXGameSaveImpl3_XGameSaveReadBlobData(This,container,blobNames,countOfBlobs,blobsSize,blobData) (This)->lpVtbl->XGameSaveReadBlobData(This,container,blobNames,countOfBlobs,blobsSize,blobData)
#define IXGameSaveImpl3_XGameSaveReadBlobDataAsync(This,container,blobNames,countOfBlobs,async) (This)->lpVtbl->XGameSaveReadBlobDataAsync(This,container,blobNames,countOfBlobs,async)
#define IXGameSaveImpl3_XGameSaveReadBlobDataResult(This,async,blobsSize,blobData,countOfBlobs) (This)->lpVtbl->XGameSaveReadBlobDataResult(This,async,blobsSize,blobData,countOfBlobs)
#define IXGameSaveImpl3_XGameSaveCreateUpdate(This,container,containerDisplayName,updateContext) (This)->lpVtbl->XGameSaveCreateUpdate(This,container,containerDisplayName,updateContext)
#define IXGameSaveImpl3_XGameSaveCloseUpdate(This,context) (This)->lpVtbl->XGameSaveCloseUpdate(This,context)
#define IXGameSaveImpl3_XGameSaveSubmitBlobWrite(This,updateContext,blobName,data,byteCount) (This)->lpVtbl->XGameSaveSubmitBlobWrite(This,updateContext,blobName,data,byteCount)
#define IXGameSaveImpl3_XGameSaveSubmitBlobDelete(This,updateContext,blobName) (This)->lpVtbl->XGameSaveSubmitBlobDelete(This,updateContext,blobName)
#define IXGameSaveImpl3_XGameSaveSubmitUpdate(This,updateContext) (This)->lpVtbl->XGameSaveSubmitUpdate(This,updateContext)
#define IXGameSaveImpl3_XGameSaveSubmitUpdateAsync(This,updateContext,async) (This)->lpVtbl->XGameSaveSubmitUpdateAsync(This,updateContext,async)
#define IXGameSaveImpl3_XGameSaveSubmitUpdateResult(This,async) (This)->lpVtbl->XGameSaveSubmitUpdateResult(This,async)
/*** IXGameSaveImpl2 methods ***/
#define IXGameSaveImpl3_XGameSaveFilesGetFolderWithUiAsync(This,requestingUser,configurationId,async) (This)->lpVtbl->XGameSaveFilesGetFolderWithUiAsync(This,requestingUser,configurationId,async)
#define IXGameSaveImpl3_XGameSaveFilesGetFolderWithUiResult(This,async,folderSize,folderResult) (This)->lpVtbl->XGameSaveFilesGetFolderWithUiResult(This,async,folderSize,folderResult)
#define IXGameSaveImpl3_XGameSaveFilesGetRemainingQuota(This,userContext,configurationId,remainingQuota) (This)->lpVtbl->XGameSaveFilesGetRemainingQuota(This,userContext,configurationId,remainingQuota)
#else
/*** IUnknown methods ***/
static inline HRESULT IXGameSaveImpl3_QueryInterface(IXGameSaveImpl3* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXGameSaveImpl3_AddRef(IXGameSaveImpl3* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXGameSaveImpl3_Release(IXGameSaveImpl3* This) {
    return This->lpVtbl->Release(This);
}
/*** IXGameSaveImpl methods ***/
static inline HRESULT IXGameSaveImpl3_XGameSaveInitializeProvider(IXGameSaveImpl3* This,XUserHandle requestingUser,const char *configurationId,BOOLEAN syncOnDemand,XGameSaveProviderHandle *provider) {
    return This->lpVtbl->XGameSaveInitializeProvider(This,requestingUser,configurationId,syncOnDemand,provider);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveInitializeProviderAsync(IXGameSaveImpl3* This,XUserHandle requestingUser,const char *configurationId,BOOLEAN syncOnDemand,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveInitializeProviderAsync(This,requestingUser,configurationId,syncOnDemand,async);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveInitializeProviderResult(IXGameSaveImpl3* This,XAsyncBlock *async,XGameSaveProviderHandle *provider) {
    return This->lpVtbl->XGameSaveInitializeProviderResult(This,async,provider);
}
static inline void IXGameSaveImpl3_XGameSaveCloseProvider(IXGameSaveImpl3* This,XGameSaveProviderHandle provider) {
    This->lpVtbl->XGameSaveCloseProvider(This,provider);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveGetRemainingQuota(IXGameSaveImpl3* This,XGameSaveProviderHandle provider,INT64 *remainingQuota) {
    return This->lpVtbl->XGameSaveGetRemainingQuota(This,provider,remainingQuota);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveGetRemainingQuotaAsync(IXGameSaveImpl3* This,XGameSaveProviderHandle provider,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveGetRemainingQuotaAsync(This,provider,async);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveGetRemainingQuotaResult(IXGameSaveImpl3* This,XAsyncBlock *async,INT64 *remainingQuota) {
    return This->lpVtbl->XGameSaveGetRemainingQuotaResult(This,async,remainingQuota);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveDeleteContainer(IXGameSaveImpl3* This,XGameSaveProviderHandle provider,const char *containerName) {
    return This->lpVtbl->XGameSaveDeleteContainer(This,provider,containerName);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveDeleteContainerAsync(IXGameSaveImpl3* This,XGameSaveProviderHandle provider,const char *containerName,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveDeleteContainerAsync(This,provider,containerName,async);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveDeleteContainerResult(IXGameSaveImpl3* This,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveDeleteContainerResult(This,async);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveGetContainerInfo(IXGameSaveImpl3* This,XGameSaveProviderHandle provider,const char *containerName,void *context,XGameSaveContainerInfoCallback *callback) {
    return This->lpVtbl->XGameSaveGetContainerInfo(This,provider,containerName,context,callback);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveEnumerateContainerInfo(IXGameSaveImpl3* This,XGameSaveProviderHandle provider,void *context,XGameSaveContainerInfoCallback *callback) {
    return This->lpVtbl->XGameSaveEnumerateContainerInfo(This,provider,context,callback);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveEnumerateContainerInfoByName(IXGameSaveImpl3* This,XGameSaveProviderHandle provider,const char *containerNamePrefix,void *context,XGameSaveContainerInfoCallback *callback) {
    return This->lpVtbl->XGameSaveEnumerateContainerInfoByName(This,provider,containerNamePrefix,context,callback);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveCreateContainer(IXGameSaveImpl3* This,XGameSaveProviderHandle provider,const char *containerName,XGameSaveContainerHandle *containerContext) {
    return This->lpVtbl->XGameSaveCreateContainer(This,provider,containerName,containerContext);
}
static inline void IXGameSaveImpl3_XGameSaveCloseContainer(IXGameSaveImpl3* This,XGameSaveContainerHandle context) {
    This->lpVtbl->XGameSaveCloseContainer(This,context);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveEnumerateBlobInfo(IXGameSaveImpl3* This,XGameSaveContainerHandle container,void *context,XGameSaveBlobInfoCallback *callback) {
    return This->lpVtbl->XGameSaveEnumerateBlobInfo(This,container,context,callback);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveEnumerateBlobInfoByName(IXGameSaveImpl3* This,XGameSaveContainerHandle container,const char *blobNamePrefix,void *context,XGameSaveBlobInfoCallback *callback) {
    return This->lpVtbl->XGameSaveEnumerateBlobInfoByName(This,container,blobNamePrefix,context,callback);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveReadBlobData(IXGameSaveImpl3* This,XGameSaveContainerHandle container,const char **blobNames,UINT32 *countOfBlobs,SIZE_T blobsSize,XGameSaveBlob *blobData) {
    return This->lpVtbl->XGameSaveReadBlobData(This,container,blobNames,countOfBlobs,blobsSize,blobData);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveReadBlobDataAsync(IXGameSaveImpl3* This,XGameSaveContainerHandle container,const char **blobNames,UINT32 countOfBlobs,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveReadBlobDataAsync(This,container,blobNames,countOfBlobs,async);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveReadBlobDataResult(IXGameSaveImpl3* This,XAsyncBlock *async,SIZE_T blobsSize,XGameSaveBlob *blobData,UINT32 *countOfBlobs) {
    return This->lpVtbl->XGameSaveReadBlobDataResult(This,async,blobsSize,blobData,countOfBlobs);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveCreateUpdate(IXGameSaveImpl3* This,XGameSaveContainerHandle container,const char *containerDisplayName,XGameSaveUpdateHandle *updateContext) {
    return This->lpVtbl->XGameSaveCreateUpdate(This,container,containerDisplayName,updateContext);
}
static inline void IXGameSaveImpl3_XGameSaveCloseUpdate(IXGameSaveImpl3* This,XGameSaveUpdateHandle context) {
    This->lpVtbl->XGameSaveCloseUpdate(This,context);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveSubmitBlobWrite(IXGameSaveImpl3* This,XGameSaveUpdateHandle updateContext,const char *blobName,UINT8 *data,SIZE_T byteCount) {
    return This->lpVtbl->XGameSaveSubmitBlobWrite(This,updateContext,blobName,data,byteCount);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveSubmitBlobDelete(IXGameSaveImpl3* This,XGameSaveUpdateHandle updateContext,const char *blobName) {
    return This->lpVtbl->XGameSaveSubmitBlobDelete(This,updateContext,blobName);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveSubmitUpdate(IXGameSaveImpl3* This,XGameSaveUpdateHandle updateContext) {
    return This->lpVtbl->XGameSaveSubmitUpdate(This,updateContext);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveSubmitUpdateAsync(IXGameSaveImpl3* This,XGameSaveUpdateHandle updateContext,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveSubmitUpdateAsync(This,updateContext,async);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveSubmitUpdateResult(IXGameSaveImpl3* This,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveSubmitUpdateResult(This,async);
}
/*** IXGameSaveImpl2 methods ***/
static inline HRESULT IXGameSaveImpl3_XGameSaveFilesGetFolderWithUiAsync(IXGameSaveImpl3* This,XUserHandle requestingUser,const char *configurationId,XAsyncBlock *async) {
    return This->lpVtbl->XGameSaveFilesGetFolderWithUiAsync(This,requestingUser,configurationId,async);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveFilesGetFolderWithUiResult(IXGameSaveImpl3* This,XAsyncBlock *async,SIZE_T folderSize,char *folderResult) {
    return This->lpVtbl->XGameSaveFilesGetFolderWithUiResult(This,async,folderSize,folderResult);
}
static inline HRESULT IXGameSaveImpl3_XGameSaveFilesGetRemainingQuota(IXGameSaveImpl3* This,XUserHandle userContext,const char *configurationId,INT64 *remainingQuota) {
    return This->lpVtbl->XGameSaveFilesGetRemainingQuota(This,userContext,configurationId,remainingQuota);
}
#endif
#endif

#endif


#endif  /* __IXGameSaveImpl3_INTERFACE_DEFINED__ */

/*****************************************************************************
 * XGameSaveImpl coclass
 */

DEFINE_GUID(CLSID_XGameSaveImpl, 0x704c3f58, 0xe629, 0x4cc2, 0xb1,0x97, 0x30,0x51,0x1b,0x99,0x6f,0xe2);

#ifdef __cplusplus
class DECLSPEC_UUID("704c3f58-e629-4cc2-b197-30511b996fe2") XGameSaveImpl;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(XGameSaveImpl, 0x704c3f58, 0xe629, 0x4cc2, 0xb1,0x97, 0x30,0x51,0x1b,0x99,0x6f,0xe2)
#endif
#endif

#endif
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __xgamesave_h__ */
