/*** Autogenerated by WIDL 11.15 from xgameinvite.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __xgameinvite_h__
#define __xgameinvite_h__

/* Forward declarations */

#ifndef __IXGameInviteImpl_FWD_DEFINED__
#define __IXGameInviteImpl_FWD_DEFINED__
typedef interface IXGameInviteImpl IXGameInviteImpl;
#ifdef __cplusplus
interface IXGameInviteImpl;
#endif /* __cplusplus */
#endif

#ifndef __IXGameInviteImpl2_FWD_DEFINED__
#define __IXGameInviteImpl2_FWD_DEFINED__
typedef interface IXGameInviteImpl2 IXGameInviteImpl2;
#ifdef __cplusplus
interface IXGameInviteImpl2;
#endif /* __cplusplus */
#endif

#ifndef __XGameInviteImpl_FWD_DEFINED__
#define __XGameInviteImpl_FWD_DEFINED__
#ifdef __cplusplus
typedef class XGameInviteImpl XGameInviteImpl;
#else
typedef struct XGameInviteImpl XGameInviteImpl;
#endif /* defined __cplusplus */
#endif /* defined __XGameInviteImpl_FWD_DEFINED__ */

/* Headers for imported files */

#include <unknwn.h>
#include <xtaskqueue.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef void __stdcall  XGameInviteEventCallback(void *context,const char *inviteUri);
#ifdef __WINESRC__
/*****************************************************************************
 * IXGameInviteImpl interface
 */
#ifndef __IXGameInviteImpl_INTERFACE_DEFINED__
#define __IXGameInviteImpl_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXGameInviteImpl, 0x0651aae2, 0x4012, 0x4077, 0xbf,0x84, 0x8b,0x90,0x97,0x09,0x0e,0x2c);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("0651aae2-4012-4077-bf84-8b9097090e2c")
IXGameInviteImpl : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE XGameInviteRegisterForEvent(
        XTaskQueueHandle queue,
        void *context,
        XGameInviteEventCallback *callback,
        XTaskQueueRegistrationToken *token) = 0;

    virtual BOOLEAN STDMETHODCALLTYPE XGameInviteUnregisterForEvent(
        XTaskQueueRegistrationToken token,
        BOOLEAN wait) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXGameInviteImpl, 0x0651aae2, 0x4012, 0x4077, 0xbf,0x84, 0x8b,0x90,0x97,0x09,0x0e,0x2c)
#endif
#else
typedef struct IXGameInviteImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXGameInviteImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXGameInviteImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXGameInviteImpl *This);

    /*** IXGameInviteImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XGameInviteRegisterForEvent)(
        IXGameInviteImpl *This,
        XTaskQueueHandle queue,
        void *context,
        XGameInviteEventCallback *callback,
        XTaskQueueRegistrationToken *token);

    BOOLEAN (STDMETHODCALLTYPE *XGameInviteUnregisterForEvent)(
        IXGameInviteImpl *This,
        XTaskQueueRegistrationToken token,
        BOOLEAN wait);

    END_INTERFACE
} IXGameInviteImplVtbl;

interface IXGameInviteImpl {
    CONST_VTBL IXGameInviteImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXGameInviteImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXGameInviteImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXGameInviteImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IXGameInviteImpl methods ***/
#define IXGameInviteImpl_XGameInviteRegisterForEvent(This,queue,context,callback,token) (This)->lpVtbl->XGameInviteRegisterForEvent(This,queue,context,callback,token)
#define IXGameInviteImpl_XGameInviteUnregisterForEvent(This,token,wait) (This)->lpVtbl->XGameInviteUnregisterForEvent(This,token,wait)
#else
/*** IUnknown methods ***/
static inline HRESULT IXGameInviteImpl_QueryInterface(IXGameInviteImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXGameInviteImpl_AddRef(IXGameInviteImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXGameInviteImpl_Release(IXGameInviteImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IXGameInviteImpl methods ***/
static inline HRESULT IXGameInviteImpl_XGameInviteRegisterForEvent(IXGameInviteImpl* This,XTaskQueueHandle queue,void *context,XGameInviteEventCallback *callback,XTaskQueueRegistrationToken *token) {
    return This->lpVtbl->XGameInviteRegisterForEvent(This,queue,context,callback,token);
}
static inline BOOLEAN IXGameInviteImpl_XGameInviteUnregisterForEvent(IXGameInviteImpl* This,XTaskQueueRegistrationToken token,BOOLEAN wait) {
    return This->lpVtbl->XGameInviteUnregisterForEvent(This,token,wait);
}
#endif
#endif

#endif


#endif  /* __IXGameInviteImpl_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IXGameInviteImpl2 interface
 */
#ifndef __IXGameInviteImpl2_INTERFACE_DEFINED__
#define __IXGameInviteImpl2_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXGameInviteImpl2, 0x014d1cc3, 0xbcfe, 0x41ff, 0xb2,0xf0, 0xe1,0xef,0x07,0x15,0x58,0x28);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("014d1cc3-bcfe-41ff-b2f0-e1ef07155828")
IXGameInviteImpl2 : public IXGameInviteImpl
{
    virtual HRESULT STDMETHODCALLTYPE XGameInviteRegisterForPendingEvent(
        XTaskQueueHandle queue,
        void *context,
        XGameInviteEventCallback *callback,
        XTaskQueueRegistrationToken *token) = 0;

    virtual BOOLEAN STDMETHODCALLTYPE XGameInviteUnregisterForPendingEvent(
        XTaskQueueRegistrationToken token,
        BOOLEAN wait) = 0;

    virtual HRESULT STDMETHODCALLTYPE XGameInviteAcceptPendingInvite(
        const char *inviteUri) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXGameInviteImpl2, 0x014d1cc3, 0xbcfe, 0x41ff, 0xb2,0xf0, 0xe1,0xef,0x07,0x15,0x58,0x28)
#endif
#else
typedef struct IXGameInviteImpl2Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXGameInviteImpl2 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXGameInviteImpl2 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXGameInviteImpl2 *This);

    /*** IXGameInviteImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XGameInviteRegisterForEvent)(
        IXGameInviteImpl2 *This,
        XTaskQueueHandle queue,
        void *context,
        XGameInviteEventCallback *callback,
        XTaskQueueRegistrationToken *token);

    BOOLEAN (STDMETHODCALLTYPE *XGameInviteUnregisterForEvent)(
        IXGameInviteImpl2 *This,
        XTaskQueueRegistrationToken token,
        BOOLEAN wait);

    /*** IXGameInviteImpl2 methods ***/
    HRESULT (STDMETHODCALLTYPE *XGameInviteRegisterForPendingEvent)(
        IXGameInviteImpl2 *This,
        XTaskQueueHandle queue,
        void *context,
        XGameInviteEventCallback *callback,
        XTaskQueueRegistrationToken *token);

    BOOLEAN (STDMETHODCALLTYPE *XGameInviteUnregisterForPendingEvent)(
        IXGameInviteImpl2 *This,
        XTaskQueueRegistrationToken token,
        BOOLEAN wait);

    HRESULT (STDMETHODCALLTYPE *XGameInviteAcceptPendingInvite)(
        IXGameInviteImpl2 *This,
        const char *inviteUri);

    END_INTERFACE
} IXGameInviteImpl2Vtbl;

interface IXGameInviteImpl2 {
    CONST_VTBL IXGameInviteImpl2Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXGameInviteImpl2_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXGameInviteImpl2_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXGameInviteImpl2_Release(This) (This)->lpVtbl->Release(This)
/*** IXGameInviteImpl methods ***/
#define IXGameInviteImpl2_XGameInviteRegisterForEvent(This,queue,context,callback,token) (This)->lpVtbl->XGameInviteRegisterForEvent(This,queue,context,callback,token)
#define IXGameInviteImpl2_XGameInviteUnregisterForEvent(This,token,wait) (This)->lpVtbl->XGameInviteUnregisterForEvent(This,token,wait)
/*** IXGameInviteImpl2 methods ***/
#define IXGameInviteImpl2_XGameInviteRegisterForPendingEvent(This,queue,context,callback,token) (This)->lpVtbl->XGameInviteRegisterForPendingEvent(This,queue,context,callback,token)
#define IXGameInviteImpl2_XGameInviteUnregisterForPendingEvent(This,token,wait) (This)->lpVtbl->XGameInviteUnregisterForPendingEvent(This,token,wait)
#define IXGameInviteImpl2_XGameInviteAcceptPendingInvite(This,inviteUri) (This)->lpVtbl->XGameInviteAcceptPendingInvite(This,inviteUri)
#else
/*** IUnknown methods ***/
static inline HRESULT IXGameInviteImpl2_QueryInterface(IXGameInviteImpl2* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXGameInviteImpl2_AddRef(IXGameInviteImpl2* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXGameInviteImpl2_Release(IXGameInviteImpl2* This) {
    return This->lpVtbl->Release(This);
}
/*** IXGameInviteImpl methods ***/
static inline HRESULT IXGameInviteImpl2_XGameInviteRegisterForEvent(IXGameInviteImpl2* This,XTaskQueueHandle queue,void *context,XGameInviteEventCallback *callback,XTaskQueueRegistrationToken *token) {
    return This->lpVtbl->XGameInviteRegisterForEvent(This,queue,context,callback,token);
}
static inline BOOLEAN IXGameInviteImpl2_XGameInviteUnregisterForEvent(IXGameInviteImpl2* This,XTaskQueueRegistrationToken token,BOOLEAN wait) {
    return This->lpVtbl->XGameInviteUnregisterForEvent(This,token,wait);
}
/*** IXGameInviteImpl2 methods ***/
static inline HRESULT IXGameInviteImpl2_XGameInviteRegisterForPendingEvent(IXGameInviteImpl2* This,XTaskQueueHandle queue,void *context,XGameInviteEventCallback *callback,XTaskQueueRegistrationToken *token) {
    return This->lpVtbl->XGameInviteRegisterForPendingEvent(This,queue,context,callback,token);
}
static inline BOOLEAN IXGameInviteImpl2_XGameInviteUnregisterForPendingEvent(IXGameInviteImpl2* This,XTaskQueueRegistrationToken token,BOOLEAN wait) {
    return This->lpVtbl->XGameInviteUnregisterForPendingEvent(This,token,wait);
}
static inline HRESULT IXGameInviteImpl2_XGameInviteAcceptPendingInvite(IXGameInviteImpl2* This,const char *inviteUri) {
    return This->lpVtbl->XGameInviteAcceptPendingInvite(This,inviteUri);
}
#endif
#endif

#endif


#endif  /* __IXGameInviteImpl2_INTERFACE_DEFINED__ */

/*****************************************************************************
 * XGameInviteImpl coclass
 */

DEFINE_GUID(CLSID_XGameInviteImpl, 0x0651aae2, 0x4012, 0x4077, 0xbf,0x84, 0x8b,0x90,0x97,0x09,0x0e,0x2c);

#ifdef __cplusplus
class DECLSPEC_UUID("0651aae2-4012-4077-bf84-8b9097090e2c") XGameInviteImpl;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(XGameInviteImpl, 0x0651aae2, 0x4012, 0x4077, 0xbf,0x84, 0x8b,0x90,0x97,0x09,0x0e,0x2c)
#endif
#endif

#endif
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __xgameinvite_h__ */
