/*** Autogenerated by WIDL 11.15 from xnetworking.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __xnetworking_h__
#define __xnetworking_h__

/* Forward declarations */

#ifndef __IXNetworkingImpl_FWD_DEFINED__
#define __IXNetworkingImpl_FWD_DEFINED__
typedef interface IXNetworkingImpl IXNetworkingImpl;
#ifdef __cplusplus
interface IXNetworkingImpl;
#endif /* __cplusplus */
#endif

#ifndef __IXNetworkingImpl2_FWD_DEFINED__
#define __IXNetworkingImpl2_FWD_DEFINED__
typedef interface IXNetworkingImpl2 IXNetworkingImpl2;
#ifdef __cplusplus
interface IXNetworkingImpl2;
#endif /* __cplusplus */
#endif

#ifndef __XNetworkingImpl_FWD_DEFINED__
#define __XNetworkingImpl_FWD_DEFINED__
#ifdef __cplusplus
typedef class XNetworkingImpl XNetworkingImpl;
#else
typedef struct XNetworkingImpl XNetworkingImpl;
#endif /* defined __cplusplus */
#endif /* defined __XNetworkingImpl_FWD_DEFINED__ */

/* Headers for imported files */

#include <unknwn.h>
#include <xasync.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
enum class XNetworkingConfigurationSetting : UINT32
{                                                  
    MaxTitleTcpQueuedReceiveBufferSize,            
    MaxSystemTcpQueuedReceiveBufferSize,           
    MaxToolsTcpQueuedReceiveBufferSize,            
};                                                 
enum class XNetworkingConnectivityCostHint : UINT32
{                                                  
    Unknown                                        
    Unrestricted                                   
    Fixed                                          
    Varialbe                                       
};                                                 
enum class XNetworkingConnectivityLevelHint : UINT32
{                                                   
    Unknown                                         
    None                                            
    LocalAccess                                     
    InternetAccess                                  
    ConstrainedInternetAccess                       
};                                                  
enum class XNetworkingStatisticsType : UINT32
{                                            
    TitleTcpQueuedReceivedBufferUsage        
    SystemTcpQueuedReceivedBufferUsage       
    ToolsTcpQueuedReceivedBufferUsage        
};                                           
enum class XNetworkingThumbprintType : UINT32
{                                            
    Leaf                                     
    Issuer                                   
    Root                                     
};                                           
#elif defined(__WINESRC__)
typedef enum XNetworkingConfigurationSetting {
    XNetworkingConfigurationSetting_MaxTitleTcpQueuedReceiveBufferSize = 0,
    XNetworkingConfigurationSetting_MaxSystemTcpQueuedReceiveBufferSize = 1,
    XNetworkingConfigurationSetting_MaxToolsTcpQueuedReceiveBufferSize = 2
} XNetworkingConfigurationSetting;
typedef enum XNetworkingConnectivityCostHint {
    XNetworkingConnectivityCostHint_Unknown = 0,
    XNetworkingConnectivityCostHint_Unrestricted = 1,
    XNetworkingConnectivityCostHint_Fixed = 2,
    XNetworkingConnectivityCostHint_Varialbe = 3
} XNetworkingConnectivityCostHint;
typedef enum XNetworkingConnectivityLevelHint {
    XNetworkingConnectivityLevelHint_Unknown = 0,
    XNetworkingConnectivityLevelHint_None = 1,
    XNetworkingConnectivityLevelHint_LocalAccess = 2,
    XNetworkingConnectivityLevelHint_InternetAccess = 3,
    XNetworkingConnectivityLevelHint_ConstrainedInternetAccess = 4
} XNetworkingConnectivityLevelHint;
typedef enum XNetworkingStatisticsType {
    XNetworkingStatisticsType_TitleTcpQueuedReceivedBufferUsage = 0,
    XNetworkingStatisticsType_SystemTcpQueuedReceivedBufferUsage = 1,
    XNetworkingStatisticsType_ToolsTcpQueuedReceivedBufferUsage = 2
} XNetworkingStatisticsType;
typedef enum XNetworkingThumbprintType {
    XNetworkingThumbprintType_Leaf = 0,
    XNetworkingThumbprintType_Issuer = 1,
    XNetworkingThumbprintType_Root = 2
} XNetworkingThumbprintType;
#endif
typedef struct XNetworkingConnectivityHint XNetworkingConnectivityHint;
typedef struct XNetworkingSecurityInformation XNetworkingSecurityInformation;
typedef struct XNetworkingTcpQueuedReceivedBufferUsageStatistics XNetworkingTcpQueuedReceivedBufferUsageStatistics;
typedef struct XNetworkingThumbprint XNetworkingThumbprint;
typedef union XNetworkingStatisticsBuffer XNetworkingStatisticsBuffer;
typedef void __stdcall  XNetworkingConnectivityHintChangedCallback(void *context,const XNetworkingConnectivityHint *connectivityHint);
typedef void __stdcall  XNetworkingPreferredLocalUdpMultiplayerPortChangedCallback(void *context,UINT64 preferredLocalUdpMultiplayerPort);
struct XNetworkingConnectivityHint {
    XNetworkingConnectivityLevelHint connectivityLevel;
    XNetworkingConnectivityCostHint connectivityCost;
    UINT32 ianaInterfaceType;
    BOOLEAN networkInitialized;
    BOOLEAN approachingDataLimit;
    BOOLEAN overDataLimit;
    BOOLEAN roaming;
};
struct XNetworkingSecurityInformation {
    UINT32 enabledHttpSecurityProtocolFlags;
    SIZE_T thumbprintCount;
    XNetworkingThumbprint *thumbprints;
};
struct XNetworkingTcpQueuedReceivedBufferUsageStatistics {
    UINT64 numBytesCurrentlyQueued;
    UINT64 peakNumBytesEverQueued;
    UINT64 totalNumBytesQueued;
    UINT64 numBytesDroppedForExceedingConfiguredMax;
    UINT64 numBytesDroppedDueToAnyFailure;
};
struct XNetworkingThumbprint {
    XNetworkingThumbprintType thumbprintType;
    SIZE_T thumbprintBufferByteCount;
    UINT8 *thumbprintBuffer;
};
union XNetworkingStatisticsBuffer {
    XNetworkingTcpQueuedReceivedBufferUsageStatistics tcpQueuedReceiveBufferUsage;
};
#ifdef __WINESRC__
/*****************************************************************************
 * IXNetworkingImpl interface
 */
#ifndef __IXNetworkingImpl_INTERFACE_DEFINED__
#define __IXNetworkingImpl_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXNetworkingImpl, 0x37e56907, 0x2f10, 0x41e8, 0xb7,0x2f, 0x36,0xed,0xb1,0x85,0x33,0x1a);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("37e56907-2f10-41e8-b72f-36edb185331a")
IXNetworkingImpl : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE XNetworkingQueryPreferredLocalUdpMultiplayerPort(
        UINT16 *preferredLocalUdpMultiplayerPort) = 0;

    virtual HRESULT STDMETHODCALLTYPE XNetworkingQueryPreferredLocalUdpMultiplayerPortAsync(
        XAsyncBlock *asyncBlock) = 0;

    virtual HRESULT STDMETHODCALLTYPE XNetworkingQueryPreferredLocalUdpMultiplayerPortAsyncResult(
        XAsyncBlock *asyncBlock,
        UINT16 *preferredLocalUdpMultiplayerPort) = 0;

    virtual HRESULT STDMETHODCALLTYPE XNetworkingRegisterPreferredLocalUdpMultiplayerPortChanged(
        XTaskQueueHandle queue,
        void *context,
        XNetworkingPreferredLocalUdpMultiplayerPortChangedCallback *callback,
        XTaskQueueRegistrationToken *token) = 0;

    virtual BOOLEAN STDMETHODCALLTYPE XNetworkingUnregisterPreferredLocalUdpMultiplayerPortChanged(
        XTaskQueueRegistrationToken token,
        BOOLEAN wait) = 0;

    virtual HRESULT STDMETHODCALLTYPE XNetworkingQuerySecurityInformationForUrlAsync(
        const char *url,
        XAsyncBlock *asyncBlock) = 0;

    virtual HRESULT STDMETHODCALLTYPE XNetworkingQuerySecurityInformationForUrlAsyncResultSize(
        XAsyncBlock *asyncBlock,
        SIZE_T *securityInformationBufferByteCount) = 0;

    virtual HRESULT STDMETHODCALLTYPE XNetworkingQuerySecurityInformationForUrlAsyncResult(
        XAsyncBlock *asyncBlock,
        SIZE_T securityInformationBufferByteCount,
        SIZE_T *securityInformationBufferByteCountUsed,
        UINT8 *securityInformationBuffer,
        XNetworkingSecurityInformation **securityInformation) = 0;

    virtual HRESULT STDMETHODCALLTYPE XNetworkingQuerySecurityInformationForUrlUtf16Async(
        const WCHAR *url,
        XAsyncBlock *asyncBlock) = 0;

    virtual HRESULT STDMETHODCALLTYPE XNetworkingQuerySecurityInformationForUrlUtf16AsyncResultSize(
        XAsyncBlock *asyncBlock,
        SIZE_T *securityInformationBufferByteCount) = 0;

    virtual HRESULT STDMETHODCALLTYPE XNetworkingQuerySecurityInformationForUrlUtf16AsyncResult(
        XAsyncBlock *asyncBlock,
        SIZE_T securityInformationBufferByteCount,
        SIZE_T *securityInformationBufferByteCountUsed,
        UINT8 *securityInformationBuffer,
        XNetworkingSecurityInformation **securityInformation) = 0;

    virtual HRESULT STDMETHODCALLTYPE XNetworkingVerifyServerCertificate(
        void *requestHandle,
        const XNetworkingSecurityInformation *securityInformation) = 0;

    virtual HRESULT STDMETHODCALLTYPE XNetworkingGetConnectivityHint(
        XNetworkingConnectivityHint *connectivityHint) = 0;

    virtual HRESULT STDMETHODCALLTYPE XNetworkingRegisterConnectivityHintChanged(
        XTaskQueueHandle queue,
        void *context,
        XNetworkingConnectivityHintChangedCallback *callback,
        XTaskQueueRegistrationToken *token) = 0;

    virtual BOOLEAN STDMETHODCALLTYPE XNetworkingUnregisterConnectivityHintChanged(
        XTaskQueueRegistrationToken token,
        BOOLEAN wait) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXNetworkingImpl, 0x37e56907, 0x2f10, 0x41e8, 0xb7,0x2f, 0x36,0xed,0xb1,0x85,0x33,0x1a)
#endif
#else
typedef struct IXNetworkingImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXNetworkingImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXNetworkingImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXNetworkingImpl *This);

    /*** IXNetworkingImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XNetworkingQueryPreferredLocalUdpMultiplayerPort)(
        IXNetworkingImpl *This,
        UINT16 *preferredLocalUdpMultiplayerPort);

    HRESULT (STDMETHODCALLTYPE *XNetworkingQueryPreferredLocalUdpMultiplayerPortAsync)(
        IXNetworkingImpl *This,
        XAsyncBlock *asyncBlock);

    HRESULT (STDMETHODCALLTYPE *XNetworkingQueryPreferredLocalUdpMultiplayerPortAsyncResult)(
        IXNetworkingImpl *This,
        XAsyncBlock *asyncBlock,
        UINT16 *preferredLocalUdpMultiplayerPort);

    HRESULT (STDMETHODCALLTYPE *XNetworkingRegisterPreferredLocalUdpMultiplayerPortChanged)(
        IXNetworkingImpl *This,
        XTaskQueueHandle queue,
        void *context,
        XNetworkingPreferredLocalUdpMultiplayerPortChangedCallback *callback,
        XTaskQueueRegistrationToken *token);

    BOOLEAN (STDMETHODCALLTYPE *XNetworkingUnregisterPreferredLocalUdpMultiplayerPortChanged)(
        IXNetworkingImpl *This,
        XTaskQueueRegistrationToken token,
        BOOLEAN wait);

    HRESULT (STDMETHODCALLTYPE *XNetworkingQuerySecurityInformationForUrlAsync)(
        IXNetworkingImpl *This,
        const char *url,
        XAsyncBlock *asyncBlock);

    HRESULT (STDMETHODCALLTYPE *XNetworkingQuerySecurityInformationForUrlAsyncResultSize)(
        IXNetworkingImpl *This,
        XAsyncBlock *asyncBlock,
        SIZE_T *securityInformationBufferByteCount);

    HRESULT (STDMETHODCALLTYPE *XNetworkingQuerySecurityInformationForUrlAsyncResult)(
        IXNetworkingImpl *This,
        XAsyncBlock *asyncBlock,
        SIZE_T securityInformationBufferByteCount,
        SIZE_T *securityInformationBufferByteCountUsed,
        UINT8 *securityInformationBuffer,
        XNetworkingSecurityInformation **securityInformation);

    HRESULT (STDMETHODCALLTYPE *XNetworkingQuerySecurityInformationForUrlUtf16Async)(
        IXNetworkingImpl *This,
        const WCHAR *url,
        XAsyncBlock *asyncBlock);

    HRESULT (STDMETHODCALLTYPE *XNetworkingQuerySecurityInformationForUrlUtf16AsyncResultSize)(
        IXNetworkingImpl *This,
        XAsyncBlock *asyncBlock,
        SIZE_T *securityInformationBufferByteCount);

    HRESULT (STDMETHODCALLTYPE *XNetworkingQuerySecurityInformationForUrlUtf16AsyncResult)(
        IXNetworkingImpl *This,
        XAsyncBlock *asyncBlock,
        SIZE_T securityInformationBufferByteCount,
        SIZE_T *securityInformationBufferByteCountUsed,
        UINT8 *securityInformationBuffer,
        XNetworkingSecurityInformation **securityInformation);

    HRESULT (STDMETHODCALLTYPE *XNetworkingVerifyServerCertificate)(
        IXNetworkingImpl *This,
        void *requestHandle,
        const XNetworkingSecurityInformation *securityInformation);

    HRESULT (STDMETHODCALLTYPE *XNetworkingGetConnectivityHint)(
        IXNetworkingImpl *This,
        XNetworkingConnectivityHint *connectivityHint);

    HRESULT (STDMETHODCALLTYPE *XNetworkingRegisterConnectivityHintChanged)(
        IXNetworkingImpl *This,
        XTaskQueueHandle queue,
        void *context,
        XNetworkingConnectivityHintChangedCallback *callback,
        XTaskQueueRegistrationToken *token);

    BOOLEAN (STDMETHODCALLTYPE *XNetworkingUnregisterConnectivityHintChanged)(
        IXNetworkingImpl *This,
        XTaskQueueRegistrationToken token,
        BOOLEAN wait);

    END_INTERFACE
} IXNetworkingImplVtbl;

interface IXNetworkingImpl {
    CONST_VTBL IXNetworkingImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXNetworkingImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXNetworkingImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXNetworkingImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IXNetworkingImpl methods ***/
#define IXNetworkingImpl_XNetworkingQueryPreferredLocalUdpMultiplayerPort(This,preferredLocalUdpMultiplayerPort) (This)->lpVtbl->XNetworkingQueryPreferredLocalUdpMultiplayerPort(This,preferredLocalUdpMultiplayerPort)
#define IXNetworkingImpl_XNetworkingQueryPreferredLocalUdpMultiplayerPortAsync(This,asyncBlock) (This)->lpVtbl->XNetworkingQueryPreferredLocalUdpMultiplayerPortAsync(This,asyncBlock)
#define IXNetworkingImpl_XNetworkingQueryPreferredLocalUdpMultiplayerPortAsyncResult(This,asyncBlock,preferredLocalUdpMultiplayerPort) (This)->lpVtbl->XNetworkingQueryPreferredLocalUdpMultiplayerPortAsyncResult(This,asyncBlock,preferredLocalUdpMultiplayerPort)
#define IXNetworkingImpl_XNetworkingRegisterPreferredLocalUdpMultiplayerPortChanged(This,queue,context,callback,token) (This)->lpVtbl->XNetworkingRegisterPreferredLocalUdpMultiplayerPortChanged(This,queue,context,callback,token)
#define IXNetworkingImpl_XNetworkingUnregisterPreferredLocalUdpMultiplayerPortChanged(This,token,wait) (This)->lpVtbl->XNetworkingUnregisterPreferredLocalUdpMultiplayerPortChanged(This,token,wait)
#define IXNetworkingImpl_XNetworkingQuerySecurityInformationForUrlAsync(This,url,asyncBlock) (This)->lpVtbl->XNetworkingQuerySecurityInformationForUrlAsync(This,url,asyncBlock)
#define IXNetworkingImpl_XNetworkingQuerySecurityInformationForUrlAsyncResultSize(This,asyncBlock,securityInformationBufferByteCount) (This)->lpVtbl->XNetworkingQuerySecurityInformationForUrlAsyncResultSize(This,asyncBlock,securityInformationBufferByteCount)
#define IXNetworkingImpl_XNetworkingQuerySecurityInformationForUrlAsyncResult(This,asyncBlock,securityInformationBufferByteCount,securityInformationBufferByteCountUsed,securityInformationBuffer,securityInformation) (This)->lpVtbl->XNetworkingQuerySecurityInformationForUrlAsyncResult(This,asyncBlock,securityInformationBufferByteCount,securityInformationBufferByteCountUsed,securityInformationBuffer,securityInformation)
#define IXNetworkingImpl_XNetworkingQuerySecurityInformationForUrlUtf16Async(This,url,asyncBlock) (This)->lpVtbl->XNetworkingQuerySecurityInformationForUrlUtf16Async(This,url,asyncBlock)
#define IXNetworkingImpl_XNetworkingQuerySecurityInformationForUrlUtf16AsyncResultSize(This,asyncBlock,securityInformationBufferByteCount) (This)->lpVtbl->XNetworkingQuerySecurityInformationForUrlUtf16AsyncResultSize(This,asyncBlock,securityInformationBufferByteCount)
#define IXNetworkingImpl_XNetworkingQuerySecurityInformationForUrlUtf16AsyncResult(This,asyncBlock,securityInformationBufferByteCount,securityInformationBufferByteCountUsed,securityInformationBuffer,securityInformation) (This)->lpVtbl->XNetworkingQuerySecurityInformationForUrlUtf16AsyncResult(This,asyncBlock,securityInformationBufferByteCount,securityInformationBufferByteCountUsed,securityInformationBuffer,securityInformation)
#define IXNetworkingImpl_XNetworkingVerifyServerCertificate(This,requestHandle,securityInformation) (This)->lpVtbl->XNetworkingVerifyServerCertificate(This,requestHandle,securityInformation)
#define IXNetworkingImpl_XNetworkingGetConnectivityHint(This,connectivityHint) (This)->lpVtbl->XNetworkingGetConnectivityHint(This,connectivityHint)
#define IXNetworkingImpl_XNetworkingRegisterConnectivityHintChanged(This,queue,context,callback,token) (This)->lpVtbl->XNetworkingRegisterConnectivityHintChanged(This,queue,context,callback,token)
#define IXNetworkingImpl_XNetworkingUnregisterConnectivityHintChanged(This,token,wait) (This)->lpVtbl->XNetworkingUnregisterConnectivityHintChanged(This,token,wait)
#else
/*** IUnknown methods ***/
static inline HRESULT IXNetworkingImpl_QueryInterface(IXNetworkingImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXNetworkingImpl_AddRef(IXNetworkingImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXNetworkingImpl_Release(IXNetworkingImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IXNetworkingImpl methods ***/
static inline HRESULT IXNetworkingImpl_XNetworkingQueryPreferredLocalUdpMultiplayerPort(IXNetworkingImpl* This,UINT16 *preferredLocalUdpMultiplayerPort) {
    return This->lpVtbl->XNetworkingQueryPreferredLocalUdpMultiplayerPort(This,preferredLocalUdpMultiplayerPort);
}
static inline HRESULT IXNetworkingImpl_XNetworkingQueryPreferredLocalUdpMultiplayerPortAsync(IXNetworkingImpl* This,XAsyncBlock *asyncBlock) {
    return This->lpVtbl->XNetworkingQueryPreferredLocalUdpMultiplayerPortAsync(This,asyncBlock);
}
static inline HRESULT IXNetworkingImpl_XNetworkingQueryPreferredLocalUdpMultiplayerPortAsyncResult(IXNetworkingImpl* This,XAsyncBlock *asyncBlock,UINT16 *preferredLocalUdpMultiplayerPort) {
    return This->lpVtbl->XNetworkingQueryPreferredLocalUdpMultiplayerPortAsyncResult(This,asyncBlock,preferredLocalUdpMultiplayerPort);
}
static inline HRESULT IXNetworkingImpl_XNetworkingRegisterPreferredLocalUdpMultiplayerPortChanged(IXNetworkingImpl* This,XTaskQueueHandle queue,void *context,XNetworkingPreferredLocalUdpMultiplayerPortChangedCallback *callback,XTaskQueueRegistrationToken *token) {
    return This->lpVtbl->XNetworkingRegisterPreferredLocalUdpMultiplayerPortChanged(This,queue,context,callback,token);
}
static inline BOOLEAN IXNetworkingImpl_XNetworkingUnregisterPreferredLocalUdpMultiplayerPortChanged(IXNetworkingImpl* This,XTaskQueueRegistrationToken token,BOOLEAN wait) {
    return This->lpVtbl->XNetworkingUnregisterPreferredLocalUdpMultiplayerPortChanged(This,token,wait);
}
static inline HRESULT IXNetworkingImpl_XNetworkingQuerySecurityInformationForUrlAsync(IXNetworkingImpl* This,const char *url,XAsyncBlock *asyncBlock) {
    return This->lpVtbl->XNetworkingQuerySecurityInformationForUrlAsync(This,url,asyncBlock);
}
static inline HRESULT IXNetworkingImpl_XNetworkingQuerySecurityInformationForUrlAsyncResultSize(IXNetworkingImpl* This,XAsyncBlock *asyncBlock,SIZE_T *securityInformationBufferByteCount) {
    return This->lpVtbl->XNetworkingQuerySecurityInformationForUrlAsyncResultSize(This,asyncBlock,securityInformationBufferByteCount);
}
static inline HRESULT IXNetworkingImpl_XNetworkingQuerySecurityInformationForUrlAsyncResult(IXNetworkingImpl* This,XAsyncBlock *asyncBlock,SIZE_T securityInformationBufferByteCount,SIZE_T *securityInformationBufferByteCountUsed,UINT8 *securityInformationBuffer,XNetworkingSecurityInformation **securityInformation) {
    return This->lpVtbl->XNetworkingQuerySecurityInformationForUrlAsyncResult(This,asyncBlock,securityInformationBufferByteCount,securityInformationBufferByteCountUsed,securityInformationBuffer,securityInformation);
}
static inline HRESULT IXNetworkingImpl_XNetworkingQuerySecurityInformationForUrlUtf16Async(IXNetworkingImpl* This,const WCHAR *url,XAsyncBlock *asyncBlock) {
    return This->lpVtbl->XNetworkingQuerySecurityInformationForUrlUtf16Async(This,url,asyncBlock);
}
static inline HRESULT IXNetworkingImpl_XNetworkingQuerySecurityInformationForUrlUtf16AsyncResultSize(IXNetworkingImpl* This,XAsyncBlock *asyncBlock,SIZE_T *securityInformationBufferByteCount) {
    return This->lpVtbl->XNetworkingQuerySecurityInformationForUrlUtf16AsyncResultSize(This,asyncBlock,securityInformationBufferByteCount);
}
static inline HRESULT IXNetworkingImpl_XNetworkingQuerySecurityInformationForUrlUtf16AsyncResult(IXNetworkingImpl* This,XAsyncBlock *asyncBlock,SIZE_T securityInformationBufferByteCount,SIZE_T *securityInformationBufferByteCountUsed,UINT8 *securityInformationBuffer,XNetworkingSecurityInformation **securityInformation) {
    return This->lpVtbl->XNetworkingQuerySecurityInformationForUrlUtf16AsyncResult(This,asyncBlock,securityInformationBufferByteCount,securityInformationBufferByteCountUsed,securityInformationBuffer,securityInformation);
}
static inline HRESULT IXNetworkingImpl_XNetworkingVerifyServerCertificate(IXNetworkingImpl* This,void *requestHandle,const XNetworkingSecurityInformation *securityInformation) {
    return This->lpVtbl->XNetworkingVerifyServerCertificate(This,requestHandle,securityInformation);
}
static inline HRESULT IXNetworkingImpl_XNetworkingGetConnectivityHint(IXNetworkingImpl* This,XNetworkingConnectivityHint *connectivityHint) {
    return This->lpVtbl->XNetworkingGetConnectivityHint(This,connectivityHint);
}
static inline HRESULT IXNetworkingImpl_XNetworkingRegisterConnectivityHintChanged(IXNetworkingImpl* This,XTaskQueueHandle queue,void *context,XNetworkingConnectivityHintChangedCallback *callback,XTaskQueueRegistrationToken *token) {
    return This->lpVtbl->XNetworkingRegisterConnectivityHintChanged(This,queue,context,callback,token);
}
static inline BOOLEAN IXNetworkingImpl_XNetworkingUnregisterConnectivityHintChanged(IXNetworkingImpl* This,XTaskQueueRegistrationToken token,BOOLEAN wait) {
    return This->lpVtbl->XNetworkingUnregisterConnectivityHintChanged(This,token,wait);
}
#endif
#endif

#endif


#endif  /* __IXNetworkingImpl_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IXNetworkingImpl2 interface
 */
#ifndef __IXNetworkingImpl2_INTERFACE_DEFINED__
#define __IXNetworkingImpl2_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXNetworkingImpl2, 0xbf2346b2, 0x39af, 0x4658, 0xb5,0xea, 0x44,0x71,0x3c,0x7e,0x83,0xb3);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("bf2346b2-39af-4658-b5ea-44713c7e83b3")
IXNetworkingImpl2 : public IXNetworkingImpl
{
    virtual HRESULT STDMETHODCALLTYPE XNetworkingQueryConfigurationSetting(
        XNetworkingConfigurationSetting configurationSetting,
        UINT64 *value) = 0;

    virtual HRESULT STDMETHODCALLTYPE XNetworkingSetConfigurationSetting(
        XNetworkingConfigurationSetting configurationParameter,
        UINT64 value) = 0;

    virtual HRESULT STDMETHODCALLTYPE XNetworkingQueryStatistics(
        XNetworkingStatisticsType statisticsType,
        XNetworkingStatisticsBuffer *statisticsBuffer) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXNetworkingImpl2, 0xbf2346b2, 0x39af, 0x4658, 0xb5,0xea, 0x44,0x71,0x3c,0x7e,0x83,0xb3)
#endif
#else
typedef struct IXNetworkingImpl2Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXNetworkingImpl2 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXNetworkingImpl2 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXNetworkingImpl2 *This);

    /*** IXNetworkingImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XNetworkingQueryPreferredLocalUdpMultiplayerPort)(
        IXNetworkingImpl2 *This,
        UINT16 *preferredLocalUdpMultiplayerPort);

    HRESULT (STDMETHODCALLTYPE *XNetworkingQueryPreferredLocalUdpMultiplayerPortAsync)(
        IXNetworkingImpl2 *This,
        XAsyncBlock *asyncBlock);

    HRESULT (STDMETHODCALLTYPE *XNetworkingQueryPreferredLocalUdpMultiplayerPortAsyncResult)(
        IXNetworkingImpl2 *This,
        XAsyncBlock *asyncBlock,
        UINT16 *preferredLocalUdpMultiplayerPort);

    HRESULT (STDMETHODCALLTYPE *XNetworkingRegisterPreferredLocalUdpMultiplayerPortChanged)(
        IXNetworkingImpl2 *This,
        XTaskQueueHandle queue,
        void *context,
        XNetworkingPreferredLocalUdpMultiplayerPortChangedCallback *callback,
        XTaskQueueRegistrationToken *token);

    BOOLEAN (STDMETHODCALLTYPE *XNetworkingUnregisterPreferredLocalUdpMultiplayerPortChanged)(
        IXNetworkingImpl2 *This,
        XTaskQueueRegistrationToken token,
        BOOLEAN wait);

    HRESULT (STDMETHODCALLTYPE *XNetworkingQuerySecurityInformationForUrlAsync)(
        IXNetworkingImpl2 *This,
        const char *url,
        XAsyncBlock *asyncBlock);

    HRESULT (STDMETHODCALLTYPE *XNetworkingQuerySecurityInformationForUrlAsyncResultSize)(
        IXNetworkingImpl2 *This,
        XAsyncBlock *asyncBlock,
        SIZE_T *securityInformationBufferByteCount);

    HRESULT (STDMETHODCALLTYPE *XNetworkingQuerySecurityInformationForUrlAsyncResult)(
        IXNetworkingImpl2 *This,
        XAsyncBlock *asyncBlock,
        SIZE_T securityInformationBufferByteCount,
        SIZE_T *securityInformationBufferByteCountUsed,
        UINT8 *securityInformationBuffer,
        XNetworkingSecurityInformation **securityInformation);

    HRESULT (STDMETHODCALLTYPE *XNetworkingQuerySecurityInformationForUrlUtf16Async)(
        IXNetworkingImpl2 *This,
        const WCHAR *url,
        XAsyncBlock *asyncBlock);

    HRESULT (STDMETHODCALLTYPE *XNetworkingQuerySecurityInformationForUrlUtf16AsyncResultSize)(
        IXNetworkingImpl2 *This,
        XAsyncBlock *asyncBlock,
        SIZE_T *securityInformationBufferByteCount);

    HRESULT (STDMETHODCALLTYPE *XNetworkingQuerySecurityInformationForUrlUtf16AsyncResult)(
        IXNetworkingImpl2 *This,
        XAsyncBlock *asyncBlock,
        SIZE_T securityInformationBufferByteCount,
        SIZE_T *securityInformationBufferByteCountUsed,
        UINT8 *securityInformationBuffer,
        XNetworkingSecurityInformation **securityInformation);

    HRESULT (STDMETHODCALLTYPE *XNetworkingVerifyServerCertificate)(
        IXNetworkingImpl2 *This,
        void *requestHandle,
        const XNetworkingSecurityInformation *securityInformation);

    HRESULT (STDMETHODCALLTYPE *XNetworkingGetConnectivityHint)(
        IXNetworkingImpl2 *This,
        XNetworkingConnectivityHint *connectivityHint);

    HRESULT (STDMETHODCALLTYPE *XNetworkingRegisterConnectivityHintChanged)(
        IXNetworkingImpl2 *This,
        XTaskQueueHandle queue,
        void *context,
        XNetworkingConnectivityHintChangedCallback *callback,
        XTaskQueueRegistrationToken *token);

    BOOLEAN (STDMETHODCALLTYPE *XNetworkingUnregisterConnectivityHintChanged)(
        IXNetworkingImpl2 *This,
        XTaskQueueRegistrationToken token,
        BOOLEAN wait);

    /*** IXNetworkingImpl2 methods ***/
    HRESULT (STDMETHODCALLTYPE *XNetworkingQueryConfigurationSetting)(
        IXNetworkingImpl2 *This,
        XNetworkingConfigurationSetting configurationSetting,
        UINT64 *value);

    HRESULT (STDMETHODCALLTYPE *XNetworkingSetConfigurationSetting)(
        IXNetworkingImpl2 *This,
        XNetworkingConfigurationSetting configurationParameter,
        UINT64 value);

    HRESULT (STDMETHODCALLTYPE *XNetworkingQueryStatistics)(
        IXNetworkingImpl2 *This,
        XNetworkingStatisticsType statisticsType,
        XNetworkingStatisticsBuffer *statisticsBuffer);

    END_INTERFACE
} IXNetworkingImpl2Vtbl;

interface IXNetworkingImpl2 {
    CONST_VTBL IXNetworkingImpl2Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXNetworkingImpl2_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXNetworkingImpl2_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXNetworkingImpl2_Release(This) (This)->lpVtbl->Release(This)
/*** IXNetworkingImpl methods ***/
#define IXNetworkingImpl2_XNetworkingQueryPreferredLocalUdpMultiplayerPort(This,preferredLocalUdpMultiplayerPort) (This)->lpVtbl->XNetworkingQueryPreferredLocalUdpMultiplayerPort(This,preferredLocalUdpMultiplayerPort)
#define IXNetworkingImpl2_XNetworkingQueryPreferredLocalUdpMultiplayerPortAsync(This,asyncBlock) (This)->lpVtbl->XNetworkingQueryPreferredLocalUdpMultiplayerPortAsync(This,asyncBlock)
#define IXNetworkingImpl2_XNetworkingQueryPreferredLocalUdpMultiplayerPortAsyncResult(This,asyncBlock,preferredLocalUdpMultiplayerPort) (This)->lpVtbl->XNetworkingQueryPreferredLocalUdpMultiplayerPortAsyncResult(This,asyncBlock,preferredLocalUdpMultiplayerPort)
#define IXNetworkingImpl2_XNetworkingRegisterPreferredLocalUdpMultiplayerPortChanged(This,queue,context,callback,token) (This)->lpVtbl->XNetworkingRegisterPreferredLocalUdpMultiplayerPortChanged(This,queue,context,callback,token)
#define IXNetworkingImpl2_XNetworkingUnregisterPreferredLocalUdpMultiplayerPortChanged(This,token,wait) (This)->lpVtbl->XNetworkingUnregisterPreferredLocalUdpMultiplayerPortChanged(This,token,wait)
#define IXNetworkingImpl2_XNetworkingQuerySecurityInformationForUrlAsync(This,url,asyncBlock) (This)->lpVtbl->XNetworkingQuerySecurityInformationForUrlAsync(This,url,asyncBlock)
#define IXNetworkingImpl2_XNetworkingQuerySecurityInformationForUrlAsyncResultSize(This,asyncBlock,securityInformationBufferByteCount) (This)->lpVtbl->XNetworkingQuerySecurityInformationForUrlAsyncResultSize(This,asyncBlock,securityInformationBufferByteCount)
#define IXNetworkingImpl2_XNetworkingQuerySecurityInformationForUrlAsyncResult(This,asyncBlock,securityInformationBufferByteCount,securityInformationBufferByteCountUsed,securityInformationBuffer,securityInformation) (This)->lpVtbl->XNetworkingQuerySecurityInformationForUrlAsyncResult(This,asyncBlock,securityInformationBufferByteCount,securityInformationBufferByteCountUsed,securityInformationBuffer,securityInformation)
#define IXNetworkingImpl2_XNetworkingQuerySecurityInformationForUrlUtf16Async(This,url,asyncBlock) (This)->lpVtbl->XNetworkingQuerySecurityInformationForUrlUtf16Async(This,url,asyncBlock)
#define IXNetworkingImpl2_XNetworkingQuerySecurityInformationForUrlUtf16AsyncResultSize(This,asyncBlock,securityInformationBufferByteCount) (This)->lpVtbl->XNetworkingQuerySecurityInformationForUrlUtf16AsyncResultSize(This,asyncBlock,securityInformationBufferByteCount)
#define IXNetworkingImpl2_XNetworkingQuerySecurityInformationForUrlUtf16AsyncResult(This,asyncBlock,securityInformationBufferByteCount,securityInformationBufferByteCountUsed,securityInformationBuffer,securityInformation) (This)->lpVtbl->XNetworkingQuerySecurityInformationForUrlUtf16AsyncResult(This,asyncBlock,securityInformationBufferByteCount,securityInformationBufferByteCountUsed,securityInformationBuffer,securityInformation)
#define IXNetworkingImpl2_XNetworkingVerifyServerCertificate(This,requestHandle,securityInformation) (This)->lpVtbl->XNetworkingVerifyServerCertificate(This,requestHandle,securityInformation)
#define IXNetworkingImpl2_XNetworkingGetConnectivityHint(This,connectivityHint) (This)->lpVtbl->XNetworkingGetConnectivityHint(This,connectivityHint)
#define IXNetworkingImpl2_XNetworkingRegisterConnectivityHintChanged(This,queue,context,callback,token) (This)->lpVtbl->XNetworkingRegisterConnectivityHintChanged(This,queue,context,callback,token)
#define IXNetworkingImpl2_XNetworkingUnregisterConnectivityHintChanged(This,token,wait) (This)->lpVtbl->XNetworkingUnregisterConnectivityHintChanged(This,token,wait)
/*** IXNetworkingImpl2 methods ***/
#define IXNetworkingImpl2_XNetworkingQueryConfigurationSetting(This,configurationSetting,value) (This)->lpVtbl->XNetworkingQueryConfigurationSetting(This,configurationSetting,value)
#define IXNetworkingImpl2_XNetworkingSetConfigurationSetting(This,configurationParameter,value) (This)->lpVtbl->XNetworkingSetConfigurationSetting(This,configurationParameter,value)
#define IXNetworkingImpl2_XNetworkingQueryStatistics(This,statisticsType,statisticsBuffer) (This)->lpVtbl->XNetworkingQueryStatistics(This,statisticsType,statisticsBuffer)
#else
/*** IUnknown methods ***/
static inline HRESULT IXNetworkingImpl2_QueryInterface(IXNetworkingImpl2* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXNetworkingImpl2_AddRef(IXNetworkingImpl2* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXNetworkingImpl2_Release(IXNetworkingImpl2* This) {
    return This->lpVtbl->Release(This);
}
/*** IXNetworkingImpl methods ***/
static inline HRESULT IXNetworkingImpl2_XNetworkingQueryPreferredLocalUdpMultiplayerPort(IXNetworkingImpl2* This,UINT16 *preferredLocalUdpMultiplayerPort) {
    return This->lpVtbl->XNetworkingQueryPreferredLocalUdpMultiplayerPort(This,preferredLocalUdpMultiplayerPort);
}
static inline HRESULT IXNetworkingImpl2_XNetworkingQueryPreferredLocalUdpMultiplayerPortAsync(IXNetworkingImpl2* This,XAsyncBlock *asyncBlock) {
    return This->lpVtbl->XNetworkingQueryPreferredLocalUdpMultiplayerPortAsync(This,asyncBlock);
}
static inline HRESULT IXNetworkingImpl2_XNetworkingQueryPreferredLocalUdpMultiplayerPortAsyncResult(IXNetworkingImpl2* This,XAsyncBlock *asyncBlock,UINT16 *preferredLocalUdpMultiplayerPort) {
    return This->lpVtbl->XNetworkingQueryPreferredLocalUdpMultiplayerPortAsyncResult(This,asyncBlock,preferredLocalUdpMultiplayerPort);
}
static inline HRESULT IXNetworkingImpl2_XNetworkingRegisterPreferredLocalUdpMultiplayerPortChanged(IXNetworkingImpl2* This,XTaskQueueHandle queue,void *context,XNetworkingPreferredLocalUdpMultiplayerPortChangedCallback *callback,XTaskQueueRegistrationToken *token) {
    return This->lpVtbl->XNetworkingRegisterPreferredLocalUdpMultiplayerPortChanged(This,queue,context,callback,token);
}
static inline BOOLEAN IXNetworkingImpl2_XNetworkingUnregisterPreferredLocalUdpMultiplayerPortChanged(IXNetworkingImpl2* This,XTaskQueueRegistrationToken token,BOOLEAN wait) {
    return This->lpVtbl->XNetworkingUnregisterPreferredLocalUdpMultiplayerPortChanged(This,token,wait);
}
static inline HRESULT IXNetworkingImpl2_XNetworkingQuerySecurityInformationForUrlAsync(IXNetworkingImpl2* This,const char *url,XAsyncBlock *asyncBlock) {
    return This->lpVtbl->XNetworkingQuerySecurityInformationForUrlAsync(This,url,asyncBlock);
}
static inline HRESULT IXNetworkingImpl2_XNetworkingQuerySecurityInformationForUrlAsyncResultSize(IXNetworkingImpl2* This,XAsyncBlock *asyncBlock,SIZE_T *securityInformationBufferByteCount) {
    return This->lpVtbl->XNetworkingQuerySecurityInformationForUrlAsyncResultSize(This,asyncBlock,securityInformationBufferByteCount);
}
static inline HRESULT IXNetworkingImpl2_XNetworkingQuerySecurityInformationForUrlAsyncResult(IXNetworkingImpl2* This,XAsyncBlock *asyncBlock,SIZE_T securityInformationBufferByteCount,SIZE_T *securityInformationBufferByteCountUsed,UINT8 *securityInformationBuffer,XNetworkingSecurityInformation **securityInformation) {
    return This->lpVtbl->XNetworkingQuerySecurityInformationForUrlAsyncResult(This,asyncBlock,securityInformationBufferByteCount,securityInformationBufferByteCountUsed,securityInformationBuffer,securityInformation);
}
static inline HRESULT IXNetworkingImpl2_XNetworkingQuerySecurityInformationForUrlUtf16Async(IXNetworkingImpl2* This,const WCHAR *url,XAsyncBlock *asyncBlock) {
    return This->lpVtbl->XNetworkingQuerySecurityInformationForUrlUtf16Async(This,url,asyncBlock);
}
static inline HRESULT IXNetworkingImpl2_XNetworkingQuerySecurityInformationForUrlUtf16AsyncResultSize(IXNetworkingImpl2* This,XAsyncBlock *asyncBlock,SIZE_T *securityInformationBufferByteCount) {
    return This->lpVtbl->XNetworkingQuerySecurityInformationForUrlUtf16AsyncResultSize(This,asyncBlock,securityInformationBufferByteCount);
}
static inline HRESULT IXNetworkingImpl2_XNetworkingQuerySecurityInformationForUrlUtf16AsyncResult(IXNetworkingImpl2* This,XAsyncBlock *asyncBlock,SIZE_T securityInformationBufferByteCount,SIZE_T *securityInformationBufferByteCountUsed,UINT8 *securityInformationBuffer,XNetworkingSecurityInformation **securityInformation) {
    return This->lpVtbl->XNetworkingQuerySecurityInformationForUrlUtf16AsyncResult(This,asyncBlock,securityInformationBufferByteCount,securityInformationBufferByteCountUsed,securityInformationBuffer,securityInformation);
}
static inline HRESULT IXNetworkingImpl2_XNetworkingVerifyServerCertificate(IXNetworkingImpl2* This,void *requestHandle,const XNetworkingSecurityInformation *securityInformation) {
    return This->lpVtbl->XNetworkingVerifyServerCertificate(This,requestHandle,securityInformation);
}
static inline HRESULT IXNetworkingImpl2_XNetworkingGetConnectivityHint(IXNetworkingImpl2* This,XNetworkingConnectivityHint *connectivityHint) {
    return This->lpVtbl->XNetworkingGetConnectivityHint(This,connectivityHint);
}
static inline HRESULT IXNetworkingImpl2_XNetworkingRegisterConnectivityHintChanged(IXNetworkingImpl2* This,XTaskQueueHandle queue,void *context,XNetworkingConnectivityHintChangedCallback *callback,XTaskQueueRegistrationToken *token) {
    return This->lpVtbl->XNetworkingRegisterConnectivityHintChanged(This,queue,context,callback,token);
}
static inline BOOLEAN IXNetworkingImpl2_XNetworkingUnregisterConnectivityHintChanged(IXNetworkingImpl2* This,XTaskQueueRegistrationToken token,BOOLEAN wait) {
    return This->lpVtbl->XNetworkingUnregisterConnectivityHintChanged(This,token,wait);
}
/*** IXNetworkingImpl2 methods ***/
static inline HRESULT IXNetworkingImpl2_XNetworkingQueryConfigurationSetting(IXNetworkingImpl2* This,XNetworkingConfigurationSetting configurationSetting,UINT64 *value) {
    return This->lpVtbl->XNetworkingQueryConfigurationSetting(This,configurationSetting,value);
}
static inline HRESULT IXNetworkingImpl2_XNetworkingSetConfigurationSetting(IXNetworkingImpl2* This,XNetworkingConfigurationSetting configurationParameter,UINT64 value) {
    return This->lpVtbl->XNetworkingSetConfigurationSetting(This,configurationParameter,value);
}
static inline HRESULT IXNetworkingImpl2_XNetworkingQueryStatistics(IXNetworkingImpl2* This,XNetworkingStatisticsType statisticsType,XNetworkingStatisticsBuffer *statisticsBuffer) {
    return This->lpVtbl->XNetworkingQueryStatistics(This,statisticsType,statisticsBuffer);
}
#endif
#endif

#endif


#endif  /* __IXNetworkingImpl2_INTERFACE_DEFINED__ */

/*****************************************************************************
 * XNetworkingImpl coclass
 */

DEFINE_GUID(CLSID_XNetworkingImpl, 0x37e56907, 0x2f10, 0x41e8, 0xb7,0x2f, 0x36,0xed,0xb1,0x85,0x33,0x1a);

#ifdef __cplusplus
class DECLSPEC_UUID("37e56907-2f10-41e8-b72f-36edb185331a") XNetworkingImpl;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(XNetworkingImpl, 0x37e56907, 0x2f10, 0x41e8, 0xb7,0x2f, 0x36,0xed,0xb1,0x85,0x33,0x1a)
#endif
#endif

#endif
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __xnetworking_h__ */
