/*** Autogenerated by WIDL 11.15 from xpersistentlocalstorage.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __xpersistentlocalstorage_h__
#define __xpersistentlocalstorage_h__

/* Forward declarations */

#ifndef __IXPersistentLocalStorageImpl_FWD_DEFINED__
#define __IXPersistentLocalStorageImpl_FWD_DEFINED__
typedef interface IXPersistentLocalStorageImpl IXPersistentLocalStorageImpl;
#ifdef __cplusplus
interface IXPersistentLocalStorageImpl;
#endif /* __cplusplus */
#endif

#ifndef __IXPersistentLocalStorageImpl2_FWD_DEFINED__
#define __IXPersistentLocalStorageImpl2_FWD_DEFINED__
typedef interface IXPersistentLocalStorageImpl2 IXPersistentLocalStorageImpl2;
#ifdef __cplusplus
interface IXPersistentLocalStorageImpl2;
#endif /* __cplusplus */
#endif

#ifndef __IXPersistentLocalStorageImpl3_FWD_DEFINED__
#define __IXPersistentLocalStorageImpl3_FWD_DEFINED__
typedef interface IXPersistentLocalStorageImpl3 IXPersistentLocalStorageImpl3;
#ifdef __cplusplus
interface IXPersistentLocalStorageImpl3;
#endif /* __cplusplus */
#endif

#ifndef __XPersistentLocalStorageImpl_FWD_DEFINED__
#define __XPersistentLocalStorageImpl_FWD_DEFINED__
#ifdef __cplusplus
typedef class XPersistentLocalStorageImpl XPersistentLocalStorageImpl;
#else
typedef struct XPersistentLocalStorageImpl XPersistentLocalStorageImpl;
#endif /* defined __cplusplus */
#endif /* defined __XPersistentLocalStorageImpl_FWD_DEFINED__ */

/* Headers for imported files */

#include <unknwn.h>
#include <xasync.h>
#include <xpackage.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct XPersistentLocalStorageSpaceInfo XPersistentLocalStorageSpaceInfo;
struct XPersistentLocalStorageSpaceInfo {
    UINT64 availableFreeBytes;
    UINT64 totalFreeBytes;
    UINT64 usedBytes;
    UINT64 totalBytes;
};
#ifdef __WINESRC__
/*****************************************************************************
 * IXPersistentLocalStorageImpl interface
 */
#ifndef __IXPersistentLocalStorageImpl_INTERFACE_DEFINED__
#define __IXPersistentLocalStorageImpl_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXPersistentLocalStorageImpl, 0xf4faf4d4, 0x2d04, 0x4fce, 0xb3,0xe0, 0x47,0x4a,0x71,0x3a,0x3e,0x84);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("f4faf4d4-2d04-4fce-b3e0-474a713a3e84")
IXPersistentLocalStorageImpl : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE XPersistentLocalStorageGetPathSize(
        SIZE_T *pathSize) = 0;

    virtual HRESULT STDMETHODCALLTYPE XPersistentLocalStorageGetPath(
        SIZE_T pathSize,
        char *path,
        SIZE_T *pathUsed) = 0;

    virtual HRESULT STDMETHODCALLTYPE XPersistentLocalStorageGetSpaceInfo(
        XPersistentLocalStorageSpaceInfo *info) = 0;

    virtual HRESULT STDMETHODCALLTYPE XPersistentLocalStoragePromptUserForSpaceAsync(
        UINT64 requestedBytes,
        XAsyncBlock *asyncBlock) = 0;

    virtual HRESULT STDMETHODCALLTYPE XPersistentLocalStoragePromptUserForSpaceResult(
        XAsyncBlock *asyncBlock) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXPersistentLocalStorageImpl, 0xf4faf4d4, 0x2d04, 0x4fce, 0xb3,0xe0, 0x47,0x4a,0x71,0x3a,0x3e,0x84)
#endif
#else
typedef struct IXPersistentLocalStorageImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXPersistentLocalStorageImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXPersistentLocalStorageImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXPersistentLocalStorageImpl *This);

    /*** IXPersistentLocalStorageImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XPersistentLocalStorageGetPathSize)(
        IXPersistentLocalStorageImpl *This,
        SIZE_T *pathSize);

    HRESULT (STDMETHODCALLTYPE *XPersistentLocalStorageGetPath)(
        IXPersistentLocalStorageImpl *This,
        SIZE_T pathSize,
        char *path,
        SIZE_T *pathUsed);

    HRESULT (STDMETHODCALLTYPE *XPersistentLocalStorageGetSpaceInfo)(
        IXPersistentLocalStorageImpl *This,
        XPersistentLocalStorageSpaceInfo *info);

    HRESULT (STDMETHODCALLTYPE *XPersistentLocalStoragePromptUserForSpaceAsync)(
        IXPersistentLocalStorageImpl *This,
        UINT64 requestedBytes,
        XAsyncBlock *asyncBlock);

    HRESULT (STDMETHODCALLTYPE *XPersistentLocalStoragePromptUserForSpaceResult)(
        IXPersistentLocalStorageImpl *This,
        XAsyncBlock *asyncBlock);

    END_INTERFACE
} IXPersistentLocalStorageImplVtbl;

interface IXPersistentLocalStorageImpl {
    CONST_VTBL IXPersistentLocalStorageImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXPersistentLocalStorageImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXPersistentLocalStorageImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXPersistentLocalStorageImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IXPersistentLocalStorageImpl methods ***/
#define IXPersistentLocalStorageImpl_XPersistentLocalStorageGetPathSize(This,pathSize) (This)->lpVtbl->XPersistentLocalStorageGetPathSize(This,pathSize)
#define IXPersistentLocalStorageImpl_XPersistentLocalStorageGetPath(This,pathSize,path,pathUsed) (This)->lpVtbl->XPersistentLocalStorageGetPath(This,pathSize,path,pathUsed)
#define IXPersistentLocalStorageImpl_XPersistentLocalStorageGetSpaceInfo(This,info) (This)->lpVtbl->XPersistentLocalStorageGetSpaceInfo(This,info)
#define IXPersistentLocalStorageImpl_XPersistentLocalStoragePromptUserForSpaceAsync(This,requestedBytes,asyncBlock) (This)->lpVtbl->XPersistentLocalStoragePromptUserForSpaceAsync(This,requestedBytes,asyncBlock)
#define IXPersistentLocalStorageImpl_XPersistentLocalStoragePromptUserForSpaceResult(This,asyncBlock) (This)->lpVtbl->XPersistentLocalStoragePromptUserForSpaceResult(This,asyncBlock)
#else
/*** IUnknown methods ***/
static inline HRESULT IXPersistentLocalStorageImpl_QueryInterface(IXPersistentLocalStorageImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXPersistentLocalStorageImpl_AddRef(IXPersistentLocalStorageImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXPersistentLocalStorageImpl_Release(IXPersistentLocalStorageImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IXPersistentLocalStorageImpl methods ***/
static inline HRESULT IXPersistentLocalStorageImpl_XPersistentLocalStorageGetPathSize(IXPersistentLocalStorageImpl* This,SIZE_T *pathSize) {
    return This->lpVtbl->XPersistentLocalStorageGetPathSize(This,pathSize);
}
static inline HRESULT IXPersistentLocalStorageImpl_XPersistentLocalStorageGetPath(IXPersistentLocalStorageImpl* This,SIZE_T pathSize,char *path,SIZE_T *pathUsed) {
    return This->lpVtbl->XPersistentLocalStorageGetPath(This,pathSize,path,pathUsed);
}
static inline HRESULT IXPersistentLocalStorageImpl_XPersistentLocalStorageGetSpaceInfo(IXPersistentLocalStorageImpl* This,XPersistentLocalStorageSpaceInfo *info) {
    return This->lpVtbl->XPersistentLocalStorageGetSpaceInfo(This,info);
}
static inline HRESULT IXPersistentLocalStorageImpl_XPersistentLocalStoragePromptUserForSpaceAsync(IXPersistentLocalStorageImpl* This,UINT64 requestedBytes,XAsyncBlock *asyncBlock) {
    return This->lpVtbl->XPersistentLocalStoragePromptUserForSpaceAsync(This,requestedBytes,asyncBlock);
}
static inline HRESULT IXPersistentLocalStorageImpl_XPersistentLocalStoragePromptUserForSpaceResult(IXPersistentLocalStorageImpl* This,XAsyncBlock *asyncBlock) {
    return This->lpVtbl->XPersistentLocalStoragePromptUserForSpaceResult(This,asyncBlock);
}
#endif
#endif

#endif


#endif  /* __IXPersistentLocalStorageImpl_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IXPersistentLocalStorageImpl2 interface
 */
#ifndef __IXPersistentLocalStorageImpl2_INTERFACE_DEFINED__
#define __IXPersistentLocalStorageImpl2_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXPersistentLocalStorageImpl2, 0xd29411df, 0x0794, 0x4553, 0x8b,0x27, 0x95,0xfc,0x02,0xd0,0xf7,0x5d);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("d29411df-0794-4553-8b27-95fc02d0f75d")
IXPersistentLocalStorageImpl2 : public IXPersistentLocalStorageImpl
{
};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXPersistentLocalStorageImpl2, 0xd29411df, 0x0794, 0x4553, 0x8b,0x27, 0x95,0xfc,0x02,0xd0,0xf7,0x5d)
#endif
#else
typedef struct IXPersistentLocalStorageImpl2Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXPersistentLocalStorageImpl2 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXPersistentLocalStorageImpl2 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXPersistentLocalStorageImpl2 *This);

    /*** IXPersistentLocalStorageImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XPersistentLocalStorageGetPathSize)(
        IXPersistentLocalStorageImpl2 *This,
        SIZE_T *pathSize);

    HRESULT (STDMETHODCALLTYPE *XPersistentLocalStorageGetPath)(
        IXPersistentLocalStorageImpl2 *This,
        SIZE_T pathSize,
        char *path,
        SIZE_T *pathUsed);

    HRESULT (STDMETHODCALLTYPE *XPersistentLocalStorageGetSpaceInfo)(
        IXPersistentLocalStorageImpl2 *This,
        XPersistentLocalStorageSpaceInfo *info);

    HRESULT (STDMETHODCALLTYPE *XPersistentLocalStoragePromptUserForSpaceAsync)(
        IXPersistentLocalStorageImpl2 *This,
        UINT64 requestedBytes,
        XAsyncBlock *asyncBlock);

    HRESULT (STDMETHODCALLTYPE *XPersistentLocalStoragePromptUserForSpaceResult)(
        IXPersistentLocalStorageImpl2 *This,
        XAsyncBlock *asyncBlock);

    END_INTERFACE
} IXPersistentLocalStorageImpl2Vtbl;

interface IXPersistentLocalStorageImpl2 {
    CONST_VTBL IXPersistentLocalStorageImpl2Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXPersistentLocalStorageImpl2_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXPersistentLocalStorageImpl2_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXPersistentLocalStorageImpl2_Release(This) (This)->lpVtbl->Release(This)
/*** IXPersistentLocalStorageImpl methods ***/
#define IXPersistentLocalStorageImpl2_XPersistentLocalStorageGetPathSize(This,pathSize) (This)->lpVtbl->XPersistentLocalStorageGetPathSize(This,pathSize)
#define IXPersistentLocalStorageImpl2_XPersistentLocalStorageGetPath(This,pathSize,path,pathUsed) (This)->lpVtbl->XPersistentLocalStorageGetPath(This,pathSize,path,pathUsed)
#define IXPersistentLocalStorageImpl2_XPersistentLocalStorageGetSpaceInfo(This,info) (This)->lpVtbl->XPersistentLocalStorageGetSpaceInfo(This,info)
#define IXPersistentLocalStorageImpl2_XPersistentLocalStoragePromptUserForSpaceAsync(This,requestedBytes,asyncBlock) (This)->lpVtbl->XPersistentLocalStoragePromptUserForSpaceAsync(This,requestedBytes,asyncBlock)
#define IXPersistentLocalStorageImpl2_XPersistentLocalStoragePromptUserForSpaceResult(This,asyncBlock) (This)->lpVtbl->XPersistentLocalStoragePromptUserForSpaceResult(This,asyncBlock)
#else
/*** IUnknown methods ***/
static inline HRESULT IXPersistentLocalStorageImpl2_QueryInterface(IXPersistentLocalStorageImpl2* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXPersistentLocalStorageImpl2_AddRef(IXPersistentLocalStorageImpl2* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXPersistentLocalStorageImpl2_Release(IXPersistentLocalStorageImpl2* This) {
    return This->lpVtbl->Release(This);
}
/*** IXPersistentLocalStorageImpl methods ***/
static inline HRESULT IXPersistentLocalStorageImpl2_XPersistentLocalStorageGetPathSize(IXPersistentLocalStorageImpl2* This,SIZE_T *pathSize) {
    return This->lpVtbl->XPersistentLocalStorageGetPathSize(This,pathSize);
}
static inline HRESULT IXPersistentLocalStorageImpl2_XPersistentLocalStorageGetPath(IXPersistentLocalStorageImpl2* This,SIZE_T pathSize,char *path,SIZE_T *pathUsed) {
    return This->lpVtbl->XPersistentLocalStorageGetPath(This,pathSize,path,pathUsed);
}
static inline HRESULT IXPersistentLocalStorageImpl2_XPersistentLocalStorageGetSpaceInfo(IXPersistentLocalStorageImpl2* This,XPersistentLocalStorageSpaceInfo *info) {
    return This->lpVtbl->XPersistentLocalStorageGetSpaceInfo(This,info);
}
static inline HRESULT IXPersistentLocalStorageImpl2_XPersistentLocalStoragePromptUserForSpaceAsync(IXPersistentLocalStorageImpl2* This,UINT64 requestedBytes,XAsyncBlock *asyncBlock) {
    return This->lpVtbl->XPersistentLocalStoragePromptUserForSpaceAsync(This,requestedBytes,asyncBlock);
}
static inline HRESULT IXPersistentLocalStorageImpl2_XPersistentLocalStoragePromptUserForSpaceResult(IXPersistentLocalStorageImpl2* This,XAsyncBlock *asyncBlock) {
    return This->lpVtbl->XPersistentLocalStoragePromptUserForSpaceResult(This,asyncBlock);
}
#endif
#endif

#endif


#endif  /* __IXPersistentLocalStorageImpl2_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IXPersistentLocalStorageImpl3 interface
 */
#ifndef __IXPersistentLocalStorageImpl3_INTERFACE_DEFINED__
#define __IXPersistentLocalStorageImpl3_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXPersistentLocalStorageImpl3, 0x41a4e10c, 0x5a7e, 0x41d9, 0x8c,0x37, 0x37,0xbd,0xe6,0x2a,0x07,0xd6);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("41a4e10c-5a7e-41d9-8c37-37bde62a07d6")
IXPersistentLocalStorageImpl3 : public IXPersistentLocalStorageImpl2
{
    virtual HRESULT STDMETHODCALLTYPE XPersistentLocalStorageMountForPackage(
        const char *packageIdentifier,
        XPackageMountHandle *mountHandle) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXPersistentLocalStorageImpl3, 0x41a4e10c, 0x5a7e, 0x41d9, 0x8c,0x37, 0x37,0xbd,0xe6,0x2a,0x07,0xd6)
#endif
#else
typedef struct IXPersistentLocalStorageImpl3Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXPersistentLocalStorageImpl3 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXPersistentLocalStorageImpl3 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXPersistentLocalStorageImpl3 *This);

    /*** IXPersistentLocalStorageImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XPersistentLocalStorageGetPathSize)(
        IXPersistentLocalStorageImpl3 *This,
        SIZE_T *pathSize);

    HRESULT (STDMETHODCALLTYPE *XPersistentLocalStorageGetPath)(
        IXPersistentLocalStorageImpl3 *This,
        SIZE_T pathSize,
        char *path,
        SIZE_T *pathUsed);

    HRESULT (STDMETHODCALLTYPE *XPersistentLocalStorageGetSpaceInfo)(
        IXPersistentLocalStorageImpl3 *This,
        XPersistentLocalStorageSpaceInfo *info);

    HRESULT (STDMETHODCALLTYPE *XPersistentLocalStoragePromptUserForSpaceAsync)(
        IXPersistentLocalStorageImpl3 *This,
        UINT64 requestedBytes,
        XAsyncBlock *asyncBlock);

    HRESULT (STDMETHODCALLTYPE *XPersistentLocalStoragePromptUserForSpaceResult)(
        IXPersistentLocalStorageImpl3 *This,
        XAsyncBlock *asyncBlock);

    /*** IXPersistentLocalStorageImpl3 methods ***/
    HRESULT (STDMETHODCALLTYPE *XPersistentLocalStorageMountForPackage)(
        IXPersistentLocalStorageImpl3 *This,
        const char *packageIdentifier,
        XPackageMountHandle *mountHandle);

    END_INTERFACE
} IXPersistentLocalStorageImpl3Vtbl;

interface IXPersistentLocalStorageImpl3 {
    CONST_VTBL IXPersistentLocalStorageImpl3Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXPersistentLocalStorageImpl3_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXPersistentLocalStorageImpl3_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXPersistentLocalStorageImpl3_Release(This) (This)->lpVtbl->Release(This)
/*** IXPersistentLocalStorageImpl methods ***/
#define IXPersistentLocalStorageImpl3_XPersistentLocalStorageGetPathSize(This,pathSize) (This)->lpVtbl->XPersistentLocalStorageGetPathSize(This,pathSize)
#define IXPersistentLocalStorageImpl3_XPersistentLocalStorageGetPath(This,pathSize,path,pathUsed) (This)->lpVtbl->XPersistentLocalStorageGetPath(This,pathSize,path,pathUsed)
#define IXPersistentLocalStorageImpl3_XPersistentLocalStorageGetSpaceInfo(This,info) (This)->lpVtbl->XPersistentLocalStorageGetSpaceInfo(This,info)
#define IXPersistentLocalStorageImpl3_XPersistentLocalStoragePromptUserForSpaceAsync(This,requestedBytes,asyncBlock) (This)->lpVtbl->XPersistentLocalStoragePromptUserForSpaceAsync(This,requestedBytes,asyncBlock)
#define IXPersistentLocalStorageImpl3_XPersistentLocalStoragePromptUserForSpaceResult(This,asyncBlock) (This)->lpVtbl->XPersistentLocalStoragePromptUserForSpaceResult(This,asyncBlock)
/*** IXPersistentLocalStorageImpl3 methods ***/
#define IXPersistentLocalStorageImpl3_XPersistentLocalStorageMountForPackage(This,packageIdentifier,mountHandle) (This)->lpVtbl->XPersistentLocalStorageMountForPackage(This,packageIdentifier,mountHandle)
#else
/*** IUnknown methods ***/
static inline HRESULT IXPersistentLocalStorageImpl3_QueryInterface(IXPersistentLocalStorageImpl3* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXPersistentLocalStorageImpl3_AddRef(IXPersistentLocalStorageImpl3* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXPersistentLocalStorageImpl3_Release(IXPersistentLocalStorageImpl3* This) {
    return This->lpVtbl->Release(This);
}
/*** IXPersistentLocalStorageImpl methods ***/
static inline HRESULT IXPersistentLocalStorageImpl3_XPersistentLocalStorageGetPathSize(IXPersistentLocalStorageImpl3* This,SIZE_T *pathSize) {
    return This->lpVtbl->XPersistentLocalStorageGetPathSize(This,pathSize);
}
static inline HRESULT IXPersistentLocalStorageImpl3_XPersistentLocalStorageGetPath(IXPersistentLocalStorageImpl3* This,SIZE_T pathSize,char *path,SIZE_T *pathUsed) {
    return This->lpVtbl->XPersistentLocalStorageGetPath(This,pathSize,path,pathUsed);
}
static inline HRESULT IXPersistentLocalStorageImpl3_XPersistentLocalStorageGetSpaceInfo(IXPersistentLocalStorageImpl3* This,XPersistentLocalStorageSpaceInfo *info) {
    return This->lpVtbl->XPersistentLocalStorageGetSpaceInfo(This,info);
}
static inline HRESULT IXPersistentLocalStorageImpl3_XPersistentLocalStoragePromptUserForSpaceAsync(IXPersistentLocalStorageImpl3* This,UINT64 requestedBytes,XAsyncBlock *asyncBlock) {
    return This->lpVtbl->XPersistentLocalStoragePromptUserForSpaceAsync(This,requestedBytes,asyncBlock);
}
static inline HRESULT IXPersistentLocalStorageImpl3_XPersistentLocalStoragePromptUserForSpaceResult(IXPersistentLocalStorageImpl3* This,XAsyncBlock *asyncBlock) {
    return This->lpVtbl->XPersistentLocalStoragePromptUserForSpaceResult(This,asyncBlock);
}
/*** IXPersistentLocalStorageImpl3 methods ***/
static inline HRESULT IXPersistentLocalStorageImpl3_XPersistentLocalStorageMountForPackage(IXPersistentLocalStorageImpl3* This,const char *packageIdentifier,XPackageMountHandle *mountHandle) {
    return This->lpVtbl->XPersistentLocalStorageMountForPackage(This,packageIdentifier,mountHandle);
}
#endif
#endif

#endif


#endif  /* __IXPersistentLocalStorageImpl3_INTERFACE_DEFINED__ */

/*****************************************************************************
 * XPersistentLocalStorageImpl coclass
 */

DEFINE_GUID(CLSID_XPersistentLocalStorageImpl, 0xf4faf4d4, 0x2d04, 0x4fce, 0xb3,0xe0, 0x47,0x4a,0x71,0x3a,0x3e,0x84);

#ifdef __cplusplus
class DECLSPEC_UUID("f4faf4d4-2d04-4fce-b3e0-474a713a3e84") XPersistentLocalStorageImpl;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(XPersistentLocalStorageImpl, 0xf4faf4d4, 0x2d04, 0x4fce, 0xb3,0xe0, 0x47,0x4a,0x71,0x3a,0x3e,0x84)
#endif
#endif

#endif
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __xpersistentlocalstorage_h__ */
