/*** Autogenerated by WIDL 11.15 from xsystem.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __xsystem_h__
#define __xsystem_h__

/* Forward declarations */

#ifndef __IXSystemImpl_FWD_DEFINED__
#define __IXSystemImpl_FWD_DEFINED__
typedef interface IXSystemImpl IXSystemImpl;
#ifdef __cplusplus
interface IXSystemImpl;
#endif /* __cplusplus */
#endif

#ifndef __IXSystemImpl2_FWD_DEFINED__
#define __IXSystemImpl2_FWD_DEFINED__
typedef interface IXSystemImpl2 IXSystemImpl2;
#ifdef __cplusplus
interface IXSystemImpl2;
#endif /* __cplusplus */
#endif

#ifndef __IXSystemImpl3_FWD_DEFINED__
#define __IXSystemImpl3_FWD_DEFINED__
typedef interface IXSystemImpl3 IXSystemImpl3;
#ifdef __cplusplus
interface IXSystemImpl3;
#endif /* __cplusplus */
#endif

#ifndef __IXSystemImpl4_FWD_DEFINED__
#define __IXSystemImpl4_FWD_DEFINED__
typedef interface IXSystemImpl4 IXSystemImpl4;
#ifdef __cplusplus
interface IXSystemImpl4;
#endif /* __cplusplus */
#endif

#ifndef __IXSystemImpl5_FWD_DEFINED__
#define __IXSystemImpl5_FWD_DEFINED__
typedef interface IXSystemImpl5 IXSystemImpl5;
#ifdef __cplusplus
interface IXSystemImpl5;
#endif /* __cplusplus */
#endif

#ifndef __IXSystemAnalyticsImpl_FWD_DEFINED__
#define __IXSystemAnalyticsImpl_FWD_DEFINED__
typedef interface IXSystemAnalyticsImpl IXSystemAnalyticsImpl;
#ifdef __cplusplus
interface IXSystemAnalyticsImpl;
#endif /* __cplusplus */
#endif

#ifndef __XSystemImpl_FWD_DEFINED__
#define __XSystemImpl_FWD_DEFINED__
#ifdef __cplusplus
typedef class XSystemImpl XSystemImpl;
#else
typedef struct XSystemImpl XSystemImpl;
#endif /* defined __cplusplus */
#endif /* defined __XSystemImpl_FWD_DEFINED__ */

#ifndef __XSystemAnalyticsImpl_FWD_DEFINED__
#define __XSystemAnalyticsImpl_FWD_DEFINED__
#ifdef __cplusplus
typedef class XSystemAnalyticsImpl XSystemAnalyticsImpl;
#else
typedef struct XSystemAnalyticsImpl XSystemAnalyticsImpl;
#endif /* defined __cplusplus */
#endif /* defined __XSystemAnalyticsImpl_FWD_DEFINED__ */

/* Headers for imported files */

#include <unknwn.h>
#include <xgameruntimetypes.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
enum class XSystemDeviceType : UINT32
{                                    
    Unknown,                         
    Pc,                              
    XboxOne,                         
    XboxOneS,                        
    XboxOneX,                        
    XboxOneXDevkit,                  
    XboxScarlettLockhart,            
    XboxScarlettAnaconda,            
    XboxScarlettDevkit,              
};                                   
enum class XSystemHandleCallbackReason : UINT32
{                                              
    Created,                                   
    Destroyed,                                 
};                                             
enum class XSystemHandleType : UINT32
{                                    
    AppCaptureScreenshotStream,      
    DisplayTimeoutDeferral,          
    GameSaveContainer,               
    GameSaveProvider,                
    GameSaveUpdate,                  
    PackageInstallationMonitor,      
    PackageMount,                    
    SpeechSynthesizer,               
    SpeechSynthesizerStream,         
    StoreContext,                    
    StoreLicense,                    
    StoreProductQuery,               
    TaskQueue,                       
    User,                            
    UserSignOutDeferral,             
    GameUiTextEntry,                 
};                                   
#elif defined(__WINESRC__)
typedef enum XSystemDeviceType {
    XSystemDeviceType_Unknown = 0,
    XSystemDeviceType_Pc = 1,
    XSystemDeviceType_XboxOne = 2,
    XSystemDeviceType_XboxOneS = 3,
    XSystemDeviceType_XboxOneX = 4,
    XSystemDeviceType_XboxOneXDevkit = 5,
    XSystemDeviceType_XboxScarlettLockhart = 6,
    XSystemDeviceType_XboxScarlettAnaconda = 7,
    XSystemDeviceType_XboxScarlettDevkit = 8
} XSystemDeviceType;
typedef enum XSystemHandleCallbackReason {
    XSystemHandleCallbackReason_Created = 0,
    XSystemHandleCallbackReason_Destroyed = 1
} XSystemHandleCallbackReason;
typedef enum XSystemHandleType {
    XSystemHandleType_AppCaptureScreenshotStream = 0,
    XSystemHandleType_DisplayTimeoutDeferral = 1,
    XSystemHandleType_GameSaveContainer = 2,
    XSystemHandleType_GameSaveProvider = 3,
    XSystemHandleType_GameSaveUpdate = 4,
    XSystemHandleType_PackageInstallationMonitor = 5,
    XSystemHandleType_PackageMount = 6,
    XSystemHandleType_SpeechSynthesizer = 7,
    XSystemHandleType_SpeechSynthesizerStream = 8,
    XSystemHandleType_StoreContext = 9,
    XSystemHandleType_StoreLicense = 10,
    XSystemHandleType_StoreProductQuery = 11,
    XSystemHandleType_TaskQueue = 12,
    XSystemHandleType_User = 13,
    XSystemHandleType_UserSignOutDeferral = 14,
    XSystemHandleType_GameUiTextEntry = 15
} XSystemHandleType;
#endif
typedef void *XSystemHandle;
typedef struct XSystemAnalyticsInfo XSystemAnalyticsInfo;
typedef struct XSystemRuntimeInfo XSystemRuntimeInfo;
typedef void __stdcall  XSystemHandleCallback(XSystemHandle handle,XSystemHandleType type,XSystemHandleCallbackReason reason,void *context);
struct XSystemAnalyticsInfo {
    XVersion osVersion;
    XVersion hostingOsVersion;
    char family[64];
    char form[64];
};
struct XSystemRuntimeInfo {
    XVersion runtimeVersion;
    XVersion availableVersion;
};
#ifdef __WINESRC__
/*****************************************************************************
 * IXSystemImpl interface
 */
#ifndef __IXSystemImpl_INTERFACE_DEFINED__
#define __IXSystemImpl_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXSystemImpl, 0xe349bd1a, 0xfc20, 0x4e40, 0xb9,0x9c, 0x41,0x78,0xcc,0x6b,0x40,0x9f);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("e349bd1a-fc20-4e40-b99c-4178cc6b409f")
IXSystemImpl : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE XSystemGetConsoleId(
        INT32 consoleIdSize,
        char *consoleId,
        SIZE_T *consoleIdUsed) = 0;

    virtual HRESULT STDMETHODCALLTYPE XSystemGetXboxLiveSandboxId(
        INT32 sandboxIdSize,
        char *sandboxId,
        SIZE_T *sandboxIdUsed) = 0;

    virtual HRESULT STDMETHODCALLTYPE XSystemGetAppSpecificDeviceId(
        INT32 appSpecificDeviceIdSize,
        char *appSpecificDeviceId,
        SIZE_T *appSpecificDeviceIdUsed) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXSystemImpl, 0xe349bd1a, 0xfc20, 0x4e40, 0xb9,0x9c, 0x41,0x78,0xcc,0x6b,0x40,0x9f)
#endif
#else
typedef struct IXSystemImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXSystemImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXSystemImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXSystemImpl *This);

    /*** IXSystemImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XSystemGetConsoleId)(
        IXSystemImpl *This,
        INT32 consoleIdSize,
        char *consoleId,
        SIZE_T *consoleIdUsed);

    HRESULT (STDMETHODCALLTYPE *XSystemGetXboxLiveSandboxId)(
        IXSystemImpl *This,
        INT32 sandboxIdSize,
        char *sandboxId,
        SIZE_T *sandboxIdUsed);

    HRESULT (STDMETHODCALLTYPE *XSystemGetAppSpecificDeviceId)(
        IXSystemImpl *This,
        INT32 appSpecificDeviceIdSize,
        char *appSpecificDeviceId,
        SIZE_T *appSpecificDeviceIdUsed);

    END_INTERFACE
} IXSystemImplVtbl;

interface IXSystemImpl {
    CONST_VTBL IXSystemImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXSystemImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXSystemImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXSystemImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IXSystemImpl methods ***/
#define IXSystemImpl_XSystemGetConsoleId(This,consoleIdSize,consoleId,consoleIdUsed) (This)->lpVtbl->XSystemGetConsoleId(This,consoleIdSize,consoleId,consoleIdUsed)
#define IXSystemImpl_XSystemGetXboxLiveSandboxId(This,sandboxIdSize,sandboxId,sandboxIdUsed) (This)->lpVtbl->XSystemGetXboxLiveSandboxId(This,sandboxIdSize,sandboxId,sandboxIdUsed)
#define IXSystemImpl_XSystemGetAppSpecificDeviceId(This,appSpecificDeviceIdSize,appSpecificDeviceId,appSpecificDeviceIdUsed) (This)->lpVtbl->XSystemGetAppSpecificDeviceId(This,appSpecificDeviceIdSize,appSpecificDeviceId,appSpecificDeviceIdUsed)
#else
/*** IUnknown methods ***/
static inline HRESULT IXSystemImpl_QueryInterface(IXSystemImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXSystemImpl_AddRef(IXSystemImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXSystemImpl_Release(IXSystemImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IXSystemImpl methods ***/
static inline HRESULT IXSystemImpl_XSystemGetConsoleId(IXSystemImpl* This,INT32 consoleIdSize,char *consoleId,SIZE_T *consoleIdUsed) {
    return This->lpVtbl->XSystemGetConsoleId(This,consoleIdSize,consoleId,consoleIdUsed);
}
static inline HRESULT IXSystemImpl_XSystemGetXboxLiveSandboxId(IXSystemImpl* This,INT32 sandboxIdSize,char *sandboxId,SIZE_T *sandboxIdUsed) {
    return This->lpVtbl->XSystemGetXboxLiveSandboxId(This,sandboxIdSize,sandboxId,sandboxIdUsed);
}
static inline HRESULT IXSystemImpl_XSystemGetAppSpecificDeviceId(IXSystemImpl* This,INT32 appSpecificDeviceIdSize,char *appSpecificDeviceId,SIZE_T *appSpecificDeviceIdUsed) {
    return This->lpVtbl->XSystemGetAppSpecificDeviceId(This,appSpecificDeviceIdSize,appSpecificDeviceId,appSpecificDeviceIdUsed);
}
#endif
#endif

#endif


#endif  /* __IXSystemImpl_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IXSystemImpl2 interface
 */
#ifndef __IXSystemImpl2_INTERFACE_DEFINED__
#define __IXSystemImpl2_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXSystemImpl2, 0x6fd71f09, 0x7513, 0x49f0, 0x89,0xbc, 0xbf,0xaf,0x5d,0xf6,0xf8,0x52);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("6fd71f09-7513-49f0-89bc-bfaf5df6f852")
IXSystemImpl2 : public IXSystemImpl
{
};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXSystemImpl2, 0x6fd71f09, 0x7513, 0x49f0, 0x89,0xbc, 0xbf,0xaf,0x5d,0xf6,0xf8,0x52)
#endif
#else
typedef struct IXSystemImpl2Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXSystemImpl2 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXSystemImpl2 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXSystemImpl2 *This);

    /*** IXSystemImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XSystemGetConsoleId)(
        IXSystemImpl2 *This,
        INT32 consoleIdSize,
        char *consoleId,
        SIZE_T *consoleIdUsed);

    HRESULT (STDMETHODCALLTYPE *XSystemGetXboxLiveSandboxId)(
        IXSystemImpl2 *This,
        INT32 sandboxIdSize,
        char *sandboxId,
        SIZE_T *sandboxIdUsed);

    HRESULT (STDMETHODCALLTYPE *XSystemGetAppSpecificDeviceId)(
        IXSystemImpl2 *This,
        INT32 appSpecificDeviceIdSize,
        char *appSpecificDeviceId,
        SIZE_T *appSpecificDeviceIdUsed);

    END_INTERFACE
} IXSystemImpl2Vtbl;

interface IXSystemImpl2 {
    CONST_VTBL IXSystemImpl2Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXSystemImpl2_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXSystemImpl2_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXSystemImpl2_Release(This) (This)->lpVtbl->Release(This)
/*** IXSystemImpl methods ***/
#define IXSystemImpl2_XSystemGetConsoleId(This,consoleIdSize,consoleId,consoleIdUsed) (This)->lpVtbl->XSystemGetConsoleId(This,consoleIdSize,consoleId,consoleIdUsed)
#define IXSystemImpl2_XSystemGetXboxLiveSandboxId(This,sandboxIdSize,sandboxId,sandboxIdUsed) (This)->lpVtbl->XSystemGetXboxLiveSandboxId(This,sandboxIdSize,sandboxId,sandboxIdUsed)
#define IXSystemImpl2_XSystemGetAppSpecificDeviceId(This,appSpecificDeviceIdSize,appSpecificDeviceId,appSpecificDeviceIdUsed) (This)->lpVtbl->XSystemGetAppSpecificDeviceId(This,appSpecificDeviceIdSize,appSpecificDeviceId,appSpecificDeviceIdUsed)
#else
/*** IUnknown methods ***/
static inline HRESULT IXSystemImpl2_QueryInterface(IXSystemImpl2* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXSystemImpl2_AddRef(IXSystemImpl2* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXSystemImpl2_Release(IXSystemImpl2* This) {
    return This->lpVtbl->Release(This);
}
/*** IXSystemImpl methods ***/
static inline HRESULT IXSystemImpl2_XSystemGetConsoleId(IXSystemImpl2* This,INT32 consoleIdSize,char *consoleId,SIZE_T *consoleIdUsed) {
    return This->lpVtbl->XSystemGetConsoleId(This,consoleIdSize,consoleId,consoleIdUsed);
}
static inline HRESULT IXSystemImpl2_XSystemGetXboxLiveSandboxId(IXSystemImpl2* This,INT32 sandboxIdSize,char *sandboxId,SIZE_T *sandboxIdUsed) {
    return This->lpVtbl->XSystemGetXboxLiveSandboxId(This,sandboxIdSize,sandboxId,sandboxIdUsed);
}
static inline HRESULT IXSystemImpl2_XSystemGetAppSpecificDeviceId(IXSystemImpl2* This,INT32 appSpecificDeviceIdSize,char *appSpecificDeviceId,SIZE_T *appSpecificDeviceIdUsed) {
    return This->lpVtbl->XSystemGetAppSpecificDeviceId(This,appSpecificDeviceIdSize,appSpecificDeviceId,appSpecificDeviceIdUsed);
}
#endif
#endif

#endif


#endif  /* __IXSystemImpl2_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IXSystemImpl3 interface
 */
#ifndef __IXSystemImpl3_INTERFACE_DEFINED__
#define __IXSystemImpl3_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXSystemImpl3, 0x67ce4bfc, 0xb1d1, 0x4ac7, 0xbc,0x3a, 0xcb,0x92,0x19,0xa9,0x7a,0x85);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("67ce4bfc-b1d1-4ac7-bc3a-cb9219a97a85")
IXSystemImpl3 : public IXSystemImpl2
{
    virtual HRESULT STDMETHODCALLTYPE XSystemHandleTrack(
        XSystemHandleCallback callback,
        void *context) = 0;

    virtual BOOLEAN STDMETHODCALLTYPE XSystemIsHandleValid(
        XSystemHandle handle) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXSystemImpl3, 0x67ce4bfc, 0xb1d1, 0x4ac7, 0xbc,0x3a, 0xcb,0x92,0x19,0xa9,0x7a,0x85)
#endif
#else
typedef struct IXSystemImpl3Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXSystemImpl3 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXSystemImpl3 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXSystemImpl3 *This);

    /*** IXSystemImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XSystemGetConsoleId)(
        IXSystemImpl3 *This,
        INT32 consoleIdSize,
        char *consoleId,
        SIZE_T *consoleIdUsed);

    HRESULT (STDMETHODCALLTYPE *XSystemGetXboxLiveSandboxId)(
        IXSystemImpl3 *This,
        INT32 sandboxIdSize,
        char *sandboxId,
        SIZE_T *sandboxIdUsed);

    HRESULT (STDMETHODCALLTYPE *XSystemGetAppSpecificDeviceId)(
        IXSystemImpl3 *This,
        INT32 appSpecificDeviceIdSize,
        char *appSpecificDeviceId,
        SIZE_T *appSpecificDeviceIdUsed);

    /*** IXSystemImpl3 methods ***/
    HRESULT (STDMETHODCALLTYPE *XSystemHandleTrack)(
        IXSystemImpl3 *This,
        XSystemHandleCallback callback,
        void *context);

    BOOLEAN (STDMETHODCALLTYPE *XSystemIsHandleValid)(
        IXSystemImpl3 *This,
        XSystemHandle handle);

    END_INTERFACE
} IXSystemImpl3Vtbl;

interface IXSystemImpl3 {
    CONST_VTBL IXSystemImpl3Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXSystemImpl3_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXSystemImpl3_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXSystemImpl3_Release(This) (This)->lpVtbl->Release(This)
/*** IXSystemImpl methods ***/
#define IXSystemImpl3_XSystemGetConsoleId(This,consoleIdSize,consoleId,consoleIdUsed) (This)->lpVtbl->XSystemGetConsoleId(This,consoleIdSize,consoleId,consoleIdUsed)
#define IXSystemImpl3_XSystemGetXboxLiveSandboxId(This,sandboxIdSize,sandboxId,sandboxIdUsed) (This)->lpVtbl->XSystemGetXboxLiveSandboxId(This,sandboxIdSize,sandboxId,sandboxIdUsed)
#define IXSystemImpl3_XSystemGetAppSpecificDeviceId(This,appSpecificDeviceIdSize,appSpecificDeviceId,appSpecificDeviceIdUsed) (This)->lpVtbl->XSystemGetAppSpecificDeviceId(This,appSpecificDeviceIdSize,appSpecificDeviceId,appSpecificDeviceIdUsed)
/*** IXSystemImpl3 methods ***/
#define IXSystemImpl3_XSystemHandleTrack(This,callback,context) (This)->lpVtbl->XSystemHandleTrack(This,callback,context)
#define IXSystemImpl3_XSystemIsHandleValid(This,handle) (This)->lpVtbl->XSystemIsHandleValid(This,handle)
#else
/*** IUnknown methods ***/
static inline HRESULT IXSystemImpl3_QueryInterface(IXSystemImpl3* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXSystemImpl3_AddRef(IXSystemImpl3* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXSystemImpl3_Release(IXSystemImpl3* This) {
    return This->lpVtbl->Release(This);
}
/*** IXSystemImpl methods ***/
static inline HRESULT IXSystemImpl3_XSystemGetConsoleId(IXSystemImpl3* This,INT32 consoleIdSize,char *consoleId,SIZE_T *consoleIdUsed) {
    return This->lpVtbl->XSystemGetConsoleId(This,consoleIdSize,consoleId,consoleIdUsed);
}
static inline HRESULT IXSystemImpl3_XSystemGetXboxLiveSandboxId(IXSystemImpl3* This,INT32 sandboxIdSize,char *sandboxId,SIZE_T *sandboxIdUsed) {
    return This->lpVtbl->XSystemGetXboxLiveSandboxId(This,sandboxIdSize,sandboxId,sandboxIdUsed);
}
static inline HRESULT IXSystemImpl3_XSystemGetAppSpecificDeviceId(IXSystemImpl3* This,INT32 appSpecificDeviceIdSize,char *appSpecificDeviceId,SIZE_T *appSpecificDeviceIdUsed) {
    return This->lpVtbl->XSystemGetAppSpecificDeviceId(This,appSpecificDeviceIdSize,appSpecificDeviceId,appSpecificDeviceIdUsed);
}
/*** IXSystemImpl3 methods ***/
static inline HRESULT IXSystemImpl3_XSystemHandleTrack(IXSystemImpl3* This,XSystemHandleCallback callback,void *context) {
    return This->lpVtbl->XSystemHandleTrack(This,callback,context);
}
static inline BOOLEAN IXSystemImpl3_XSystemIsHandleValid(IXSystemImpl3* This,XSystemHandle handle) {
    return This->lpVtbl->XSystemIsHandleValid(This,handle);
}
#endif
#endif

#endif


#endif  /* __IXSystemImpl3_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IXSystemImpl4 interface
 */
#ifndef __IXSystemImpl4_INTERFACE_DEFINED__
#define __IXSystemImpl4_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXSystemImpl4, 0xdadc2895, 0x34b0, 0x4ef5, 0xa8,0x3e, 0x45,0x11,0x4d,0x62,0x9b,0x80);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("dadc2895-34b0-4ef5-a83e-45114d629b80")
IXSystemImpl4 : public IXSystemImpl3
{
    virtual void STDMETHODCALLTYPE XSystemAllowFullDownloadBandwidth(
        BOOLEAN enable) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXSystemImpl4, 0xdadc2895, 0x34b0, 0x4ef5, 0xa8,0x3e, 0x45,0x11,0x4d,0x62,0x9b,0x80)
#endif
#else
typedef struct IXSystemImpl4Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXSystemImpl4 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXSystemImpl4 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXSystemImpl4 *This);

    /*** IXSystemImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XSystemGetConsoleId)(
        IXSystemImpl4 *This,
        INT32 consoleIdSize,
        char *consoleId,
        SIZE_T *consoleIdUsed);

    HRESULT (STDMETHODCALLTYPE *XSystemGetXboxLiveSandboxId)(
        IXSystemImpl4 *This,
        INT32 sandboxIdSize,
        char *sandboxId,
        SIZE_T *sandboxIdUsed);

    HRESULT (STDMETHODCALLTYPE *XSystemGetAppSpecificDeviceId)(
        IXSystemImpl4 *This,
        INT32 appSpecificDeviceIdSize,
        char *appSpecificDeviceId,
        SIZE_T *appSpecificDeviceIdUsed);

    /*** IXSystemImpl3 methods ***/
    HRESULT (STDMETHODCALLTYPE *XSystemHandleTrack)(
        IXSystemImpl4 *This,
        XSystemHandleCallback callback,
        void *context);

    BOOLEAN (STDMETHODCALLTYPE *XSystemIsHandleValid)(
        IXSystemImpl4 *This,
        XSystemHandle handle);

    /*** IXSystemImpl4 methods ***/
    void (STDMETHODCALLTYPE *XSystemAllowFullDownloadBandwidth)(
        IXSystemImpl4 *This,
        BOOLEAN enable);

    END_INTERFACE
} IXSystemImpl4Vtbl;

interface IXSystemImpl4 {
    CONST_VTBL IXSystemImpl4Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXSystemImpl4_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXSystemImpl4_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXSystemImpl4_Release(This) (This)->lpVtbl->Release(This)
/*** IXSystemImpl methods ***/
#define IXSystemImpl4_XSystemGetConsoleId(This,consoleIdSize,consoleId,consoleIdUsed) (This)->lpVtbl->XSystemGetConsoleId(This,consoleIdSize,consoleId,consoleIdUsed)
#define IXSystemImpl4_XSystemGetXboxLiveSandboxId(This,sandboxIdSize,sandboxId,sandboxIdUsed) (This)->lpVtbl->XSystemGetXboxLiveSandboxId(This,sandboxIdSize,sandboxId,sandboxIdUsed)
#define IXSystemImpl4_XSystemGetAppSpecificDeviceId(This,appSpecificDeviceIdSize,appSpecificDeviceId,appSpecificDeviceIdUsed) (This)->lpVtbl->XSystemGetAppSpecificDeviceId(This,appSpecificDeviceIdSize,appSpecificDeviceId,appSpecificDeviceIdUsed)
/*** IXSystemImpl3 methods ***/
#define IXSystemImpl4_XSystemHandleTrack(This,callback,context) (This)->lpVtbl->XSystemHandleTrack(This,callback,context)
#define IXSystemImpl4_XSystemIsHandleValid(This,handle) (This)->lpVtbl->XSystemIsHandleValid(This,handle)
/*** IXSystemImpl4 methods ***/
#define IXSystemImpl4_XSystemAllowFullDownloadBandwidth(This,enable) (This)->lpVtbl->XSystemAllowFullDownloadBandwidth(This,enable)
#else
/*** IUnknown methods ***/
static inline HRESULT IXSystemImpl4_QueryInterface(IXSystemImpl4* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXSystemImpl4_AddRef(IXSystemImpl4* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXSystemImpl4_Release(IXSystemImpl4* This) {
    return This->lpVtbl->Release(This);
}
/*** IXSystemImpl methods ***/
static inline HRESULT IXSystemImpl4_XSystemGetConsoleId(IXSystemImpl4* This,INT32 consoleIdSize,char *consoleId,SIZE_T *consoleIdUsed) {
    return This->lpVtbl->XSystemGetConsoleId(This,consoleIdSize,consoleId,consoleIdUsed);
}
static inline HRESULT IXSystemImpl4_XSystemGetXboxLiveSandboxId(IXSystemImpl4* This,INT32 sandboxIdSize,char *sandboxId,SIZE_T *sandboxIdUsed) {
    return This->lpVtbl->XSystemGetXboxLiveSandboxId(This,sandboxIdSize,sandboxId,sandboxIdUsed);
}
static inline HRESULT IXSystemImpl4_XSystemGetAppSpecificDeviceId(IXSystemImpl4* This,INT32 appSpecificDeviceIdSize,char *appSpecificDeviceId,SIZE_T *appSpecificDeviceIdUsed) {
    return This->lpVtbl->XSystemGetAppSpecificDeviceId(This,appSpecificDeviceIdSize,appSpecificDeviceId,appSpecificDeviceIdUsed);
}
/*** IXSystemImpl3 methods ***/
static inline HRESULT IXSystemImpl4_XSystemHandleTrack(IXSystemImpl4* This,XSystemHandleCallback callback,void *context) {
    return This->lpVtbl->XSystemHandleTrack(This,callback,context);
}
static inline BOOLEAN IXSystemImpl4_XSystemIsHandleValid(IXSystemImpl4* This,XSystemHandle handle) {
    return This->lpVtbl->XSystemIsHandleValid(This,handle);
}
/*** IXSystemImpl4 methods ***/
static inline void IXSystemImpl4_XSystemAllowFullDownloadBandwidth(IXSystemImpl4* This,BOOLEAN enable) {
    This->lpVtbl->XSystemAllowFullDownloadBandwidth(This,enable);
}
#endif
#endif

#endif


#endif  /* __IXSystemImpl4_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IXSystemImpl5 interface
 */
#ifndef __IXSystemImpl5_INTERFACE_DEFINED__
#define __IXSystemImpl5_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXSystemImpl5, 0x1861cf2e, 0xe18b, 0x4834, 0xa9,0xf5, 0xb4,0xa4,0xe6,0xef,0xb4,0xcf);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("1861cf2e-e18b-4834-a9f5-b4a4e6efb4cf")
IXSystemImpl5 : public IXSystemImpl4
{
};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXSystemImpl5, 0x1861cf2e, 0xe18b, 0x4834, 0xa9,0xf5, 0xb4,0xa4,0xe6,0xef,0xb4,0xcf)
#endif
#else
typedef struct IXSystemImpl5Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXSystemImpl5 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXSystemImpl5 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXSystemImpl5 *This);

    /*** IXSystemImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XSystemGetConsoleId)(
        IXSystemImpl5 *This,
        INT32 consoleIdSize,
        char *consoleId,
        SIZE_T *consoleIdUsed);

    HRESULT (STDMETHODCALLTYPE *XSystemGetXboxLiveSandboxId)(
        IXSystemImpl5 *This,
        INT32 sandboxIdSize,
        char *sandboxId,
        SIZE_T *sandboxIdUsed);

    HRESULT (STDMETHODCALLTYPE *XSystemGetAppSpecificDeviceId)(
        IXSystemImpl5 *This,
        INT32 appSpecificDeviceIdSize,
        char *appSpecificDeviceId,
        SIZE_T *appSpecificDeviceIdUsed);

    /*** IXSystemImpl3 methods ***/
    HRESULT (STDMETHODCALLTYPE *XSystemHandleTrack)(
        IXSystemImpl5 *This,
        XSystemHandleCallback callback,
        void *context);

    BOOLEAN (STDMETHODCALLTYPE *XSystemIsHandleValid)(
        IXSystemImpl5 *This,
        XSystemHandle handle);

    /*** IXSystemImpl4 methods ***/
    void (STDMETHODCALLTYPE *XSystemAllowFullDownloadBandwidth)(
        IXSystemImpl5 *This,
        BOOLEAN enable);

    END_INTERFACE
} IXSystemImpl5Vtbl;

interface IXSystemImpl5 {
    CONST_VTBL IXSystemImpl5Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXSystemImpl5_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXSystemImpl5_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXSystemImpl5_Release(This) (This)->lpVtbl->Release(This)
/*** IXSystemImpl methods ***/
#define IXSystemImpl5_XSystemGetConsoleId(This,consoleIdSize,consoleId,consoleIdUsed) (This)->lpVtbl->XSystemGetConsoleId(This,consoleIdSize,consoleId,consoleIdUsed)
#define IXSystemImpl5_XSystemGetXboxLiveSandboxId(This,sandboxIdSize,sandboxId,sandboxIdUsed) (This)->lpVtbl->XSystemGetXboxLiveSandboxId(This,sandboxIdSize,sandboxId,sandboxIdUsed)
#define IXSystemImpl5_XSystemGetAppSpecificDeviceId(This,appSpecificDeviceIdSize,appSpecificDeviceId,appSpecificDeviceIdUsed) (This)->lpVtbl->XSystemGetAppSpecificDeviceId(This,appSpecificDeviceIdSize,appSpecificDeviceId,appSpecificDeviceIdUsed)
/*** IXSystemImpl3 methods ***/
#define IXSystemImpl5_XSystemHandleTrack(This,callback,context) (This)->lpVtbl->XSystemHandleTrack(This,callback,context)
#define IXSystemImpl5_XSystemIsHandleValid(This,handle) (This)->lpVtbl->XSystemIsHandleValid(This,handle)
/*** IXSystemImpl4 methods ***/
#define IXSystemImpl5_XSystemAllowFullDownloadBandwidth(This,enable) (This)->lpVtbl->XSystemAllowFullDownloadBandwidth(This,enable)
#else
/*** IUnknown methods ***/
static inline HRESULT IXSystemImpl5_QueryInterface(IXSystemImpl5* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXSystemImpl5_AddRef(IXSystemImpl5* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXSystemImpl5_Release(IXSystemImpl5* This) {
    return This->lpVtbl->Release(This);
}
/*** IXSystemImpl methods ***/
static inline HRESULT IXSystemImpl5_XSystemGetConsoleId(IXSystemImpl5* This,INT32 consoleIdSize,char *consoleId,SIZE_T *consoleIdUsed) {
    return This->lpVtbl->XSystemGetConsoleId(This,consoleIdSize,consoleId,consoleIdUsed);
}
static inline HRESULT IXSystemImpl5_XSystemGetXboxLiveSandboxId(IXSystemImpl5* This,INT32 sandboxIdSize,char *sandboxId,SIZE_T *sandboxIdUsed) {
    return This->lpVtbl->XSystemGetXboxLiveSandboxId(This,sandboxIdSize,sandboxId,sandboxIdUsed);
}
static inline HRESULT IXSystemImpl5_XSystemGetAppSpecificDeviceId(IXSystemImpl5* This,INT32 appSpecificDeviceIdSize,char *appSpecificDeviceId,SIZE_T *appSpecificDeviceIdUsed) {
    return This->lpVtbl->XSystemGetAppSpecificDeviceId(This,appSpecificDeviceIdSize,appSpecificDeviceId,appSpecificDeviceIdUsed);
}
/*** IXSystemImpl3 methods ***/
static inline HRESULT IXSystemImpl5_XSystemHandleTrack(IXSystemImpl5* This,XSystemHandleCallback callback,void *context) {
    return This->lpVtbl->XSystemHandleTrack(This,callback,context);
}
static inline BOOLEAN IXSystemImpl5_XSystemIsHandleValid(IXSystemImpl5* This,XSystemHandle handle) {
    return This->lpVtbl->XSystemIsHandleValid(This,handle);
}
/*** IXSystemImpl4 methods ***/
static inline void IXSystemImpl5_XSystemAllowFullDownloadBandwidth(IXSystemImpl5* This,BOOLEAN enable) {
    This->lpVtbl->XSystemAllowFullDownloadBandwidth(This,enable);
}
#endif
#endif

#endif


#endif  /* __IXSystemImpl5_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IXSystemAnalyticsImpl interface
 */
#ifndef __IXSystemAnalyticsImpl_INTERFACE_DEFINED__
#define __IXSystemAnalyticsImpl_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXSystemAnalyticsImpl, 0xb884675d, 0xb738, 0x4a9c, 0x81,0x5d, 0x9a,0x9a,0x1e,0x0c,0x6c,0x9b);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("b884675d-b738-4a9c-815d-9a9a1e0c6c9b")
IXSystemAnalyticsImpl : public IUnknown
{
#ifdef WIDL_EXPLICIT_AGGREGATE_RETURNS
    virtual XSystemAnalyticsInfo* STDMETHODCALLTYPE XSystemGetAnalyticsInfo(
        XSystemAnalyticsInfo *__ret) = 0;
    XSystemAnalyticsInfo STDMETHODCALLTYPE XSystemGetAnalyticsInfo(
        )
    {
        XSystemAnalyticsInfo __ret;
        return *XSystemGetAnalyticsInfo(&__ret);
    }
#else
    virtual XSystemAnalyticsInfo STDMETHODCALLTYPE XSystemGetAnalyticsInfo(
        ) = 0;
#endif

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXSystemAnalyticsImpl, 0xb884675d, 0xb738, 0x4a9c, 0x81,0x5d, 0x9a,0x9a,0x1e,0x0c,0x6c,0x9b)
#endif
#else
typedef struct IXSystemAnalyticsImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXSystemAnalyticsImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXSystemAnalyticsImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXSystemAnalyticsImpl *This);

    /*** IXSystemAnalyticsImpl methods ***/
    XSystemAnalyticsInfo * (STDMETHODCALLTYPE *XSystemGetAnalyticsInfo)(
        IXSystemAnalyticsImpl *This,
        XSystemAnalyticsInfo *__ret);

    END_INTERFACE
} IXSystemAnalyticsImplVtbl;

interface IXSystemAnalyticsImpl {
    CONST_VTBL IXSystemAnalyticsImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXSystemAnalyticsImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXSystemAnalyticsImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXSystemAnalyticsImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IXSystemAnalyticsImpl methods ***/
#define IXSystemAnalyticsImpl_XSystemGetAnalyticsInfo(This) IXSystemAnalyticsImpl_XSystemGetAnalyticsInfo_define_WIDL_C_INLINE_WRAPPERS_for_aggregate_return_support
#else
/*** IUnknown methods ***/
static inline HRESULT IXSystemAnalyticsImpl_QueryInterface(IXSystemAnalyticsImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXSystemAnalyticsImpl_AddRef(IXSystemAnalyticsImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXSystemAnalyticsImpl_Release(IXSystemAnalyticsImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IXSystemAnalyticsImpl methods ***/
static inline XSystemAnalyticsInfo IXSystemAnalyticsImpl_XSystemGetAnalyticsInfo(IXSystemAnalyticsImpl* This) {
    XSystemAnalyticsInfo __ret;
    return *This->lpVtbl->XSystemGetAnalyticsInfo(This,&__ret);
}
#endif
#endif

#endif


#endif  /* __IXSystemAnalyticsImpl_INTERFACE_DEFINED__ */

/*****************************************************************************
 * XSystemImpl coclass
 */

DEFINE_GUID(CLSID_XSystemImpl, 0xe349bd1a, 0xfc20, 0x4e40, 0xb9,0x9c, 0x41,0x78,0xcc,0x6b,0x40,0x9f);

#ifdef __cplusplus
class DECLSPEC_UUID("e349bd1a-fc20-4e40-b99c-4178cc6b409f") XSystemImpl;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(XSystemImpl, 0xe349bd1a, 0xfc20, 0x4e40, 0xb9,0x9c, 0x41,0x78,0xcc,0x6b,0x40,0x9f)
#endif
#endif

/*****************************************************************************
 * XSystemAnalyticsImpl coclass
 */

DEFINE_GUID(CLSID_XSystemAnalyticsImpl, 0xb884675d, 0xb738, 0x4a9c, 0x81,0x5d, 0x9a,0x9a,0x1e,0x0c,0x6c,0x9b);

#ifdef __cplusplus
class DECLSPEC_UUID("b884675d-b738-4a9c-815d-9a9a1e0c6c9b") XSystemAnalyticsImpl;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(XSystemAnalyticsImpl, 0xb884675d, 0xb738, 0x4a9c, 0x81,0x5d, 0x9a,0x9a,0x1e,0x0c,0x6c,0x9b)
#endif
#endif

#endif
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __xsystem_h__ */
